diff --git a/scripts/Makefile b/scripts/Makefile
index 70044de4..776ce73c 100644
--- a/scripts/Makefile
+++ b/scripts/Makefile
@@ -64,12 +64,12 @@ clean:
 install: build
 	-$(PIP) uninstall -y interpret
 	-$(PIP) uninstall -y interpret-core
-	cd $(ROOTDIR)/python/interpret-core && $(PIP) install -e .
-	cd $(ROOTDIR)/python/interpret && $(PIP) install -e .
+	cd $(ROOTDIR)/python/interpret-core && $(PIP) install --no-deps -e .
+	cd $(ROOTDIR)/python/interpret && $(PIP) install --no-deps -e .
 install-core: build
 	-$(PIP) uninstall -y interpret
 	-$(PIP) uninstall -y interpret-core
-	cd $(ROOTDIR)/python/interpret-core && $(PIP) install -e .
+	cd $(ROOTDIR)/python/interpret-core && $(PIP) install --no-deps -e .
 
 
 build: build-wheel
