load("@rules_java//java:defs.bzl", "java_library")
java_library(
    name = "core",
    runtime_deps = ["@maven_protobuf//:com_google_protobuf_protobuf_java"],
    visibility = ["//visibility:public"],
)

