schema_version: 1

context:
  version: "2.7.4"
  buildnum: 0

package:
  name: xpmem
  version: ${{ version }}

source:
  url: https://github.com/openucx/xpmem/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 738c70041ce09dcc66b64d80aebc1479e779efe12a9c02217fba610e2ae61f18

build:
  number:  ${{ buildnum }}
  script: build.sh
  skip:
    - osx
    - win

requirements:
  build:
    - ${{ compiler('c') }}
#   - ${{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config

tests:
  - script:
      - test -f $PREFIX/lib/libxpmem.so
      - test -f $PREFIX/include/xpmem.h
      - grep -q "xpmem_make" $PREFIX/include/xpmem.h
      - nm -D $PREFIX/lib/libxpmem.so | grep -q "xpmem_init"

about:
  homepage: https://github.com/openucx/xpmem
  license: LGPL-2.1-only
  license_file: COPYING
  summary: >-
    XPMEM userspace library (libxpmem) enables UCX zero-copy intra-node shared memory transport
  description: |
    XPMEM (Cross-Process Memory) is a Linux kernel module that allows a process to map the memory of another process directly into its virtual address space, without an extra copy. This enables true zero-copy intra-node MPI communication.

extra:
  recipe-maintainers:
    - j34ni
