#!/usr/bin/env bash

# https://github.com/mitchellh/vouch/blob/8c4f29bb7f2ddfa0b8dbc1bb6575e3f27c95d10a/action/setup-vouch/action.yml#L28-L41
cmd=''
for a in "$@"; do cmd="$cmd $(printf '%q' "$a")"; done
if [ $# -eq 0 ]; then cmd='vouch main'; fi
exec nu --no-config-file -c "use 'REPLACE_ME/share/nushell/lib/vouch' *; $cmd"
