{% set version = "0.10.8.post10" %}

package:
  name: uv-ffi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/uv-ffi/uv_ffi-{{ version }}.tar.gz
  sha256: 785c2d2cfee44012d34b47f962321469122f144a497252aa818c64457017399e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - rust
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - uv_ffi
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/1minds3t/uv-ffi
  summary: Persistent in-process execution engine for uv — internal dependency of omnipkg
  license: Apache-2.0 AND BSD-2-Clause AND MIT
  license_file:
    - LICENSE-MIT
    - NOTICE
    - crates/uv-ffi/LICENSE-MIT
    - crates/uv-ffi/NOTICE
    - crates/uv-pep508/License-Apache
    - crates/uv-pep508/License-BSD
    - crates/uv-python/python/packaging/LICENSE.APACHE
    - crates/uv-python/python/packaging/LICENSE.BSD
    - crates/uv-extract/src/vendor/LICENSE
    - crates/uv-build-frontend/src/pipreqs/LICENSE
    - crates/uv-pep440/License-Apache
    - crates/uv-pep440/License-BSD

extra:
  recipe-maintainers:
    - 1minds3t
