schema_version: 1

context:
  name: zsh-jupyter-kernel
  version: "3.5.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:   https://files.pythonhosted.org/packages/bb/ef/a5e15b09aed56e983cd8ba0bd1f4e4a924a2eaab81812e20c80828e7d955/zsh_jupyter_kernel-${{ version }}.tar.gz
  sha256: e60454e6e6ffe1297b0d038b3cca7767529811376472cfaf7957eb2615f42479

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - jupyter_client
    - setuptools >=61
    - pip
  run:
    - python >=${{ python_min }}
    - ipykernel
    - pexpect
  run_constraints:
    - zsh >=5.1

tests:
  - python:
      imports:
        - zsh_jupyter_kernel
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - python -m zsh_jupyter_kernel.install --prefix ${{ PREFIX }}
      - jupyter kernelspec list | grep zsh
      - jupyter run --kernel=zsh test.sh
    files:
      recipe:
        - test.sh

about:
  homepage: https://dan-oak.github.io/zsh-jupyter-kernel
  repository: https://github.com/dan-oak/zsh-jupyter-kernel
  documentation: https://dan-oak.github.io/zsh-jupyter-kernel
  license: GPL-3.0-only
  license_file: LICENSE.md
  summary: Z shell kernel for Project Jupyter
  description: A simple Z Shell Jupyter kernel powered by Python, IPyKernel, Pexpect, and enthusiasm — turn your scripts into notebooks!

extra:
  recipe-maintainers:
    - eunos-1128
