{% set name = "ttta" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ttta-{{ version }}.tar.gz
  sha256: db9cb42eeb89f234d576e911d460d2253f665caf6213e13daac56b8359e6fed4

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - nltk
    - cython
    - pandas
    - scipy
    - tqdm
    - scikit-learn
    - hanta
    - pyldavis >=3.4.0
    - matplotlib-base
    - seaborn

test:
  imports:
    - ttta
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'Tools for temporal text analysis: A Python package providing diachronic tools for text analysis.'
  home: https://github.com/K-RLange/ttta
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
