schema_version: 1

context:
  version: "0.7.0"
  python_min: "3.11"

package:
  name: dau-build
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dau-build/dau_build-${{ version }}.tar.gz
  sha256: e22c9f86a0b46ae1d3026685c989eaf1f824e28c937a8f7a62214774dbe3bdfb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dau-build = dau_build.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - amaranth
    - artlink
    - ccflow >=0.8.5
    - dau-sim >=0.2.0
    - dau-utils
    - hydra-core
    - pydantic
    - pyslang
    - pyyaml
    - typing-extensions

tests:
  - python:
      imports:
        - dau_build
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - dau-build --help

about:
  summary: Build tools for dau
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/dau-dev/dau-build
  repository: https://github.com/dau-dev/dau-build

extra:
  recipe-maintainers:
    - timkpaine
