schema_version: 1

context:
  version: "0.2.2"

package:
  name: reflink
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/reflink/reflink-${{ version }}.tar.gz
  sha256: 882375ee7319275ae5f6a6a1287406365dac1e9643b91ad10e5187d3f84253bd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - cffi
    - pytest-runner
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cffi

tests:
  - python:
      imports:
        - reflink
      pip_check: true

about:
  summary: Python reflink wraps around platform specific reflink implementations
  license: MIT
  license_file: LICENSE
  homepage: https://gitlab.com/rubdos/pyreflink

extra:
  recipe-maintainers:
    - HeavyTony2
