context:
  version: "2.3.2"

package:
  name: fairlogger
  version: ${{ version }}

source:
  url: https://github.com/FairRootGroup/FairLogger/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 17878988b220ab6e06944d0d91d4cc82f0e0c5dc3b16ddade2db72abf7c28add
  patches:
    - fix-version.patch

build:
  skip:
    - win
  number: 0
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
  host:
    - fmt
  run:
    - fmt

tests:
  - package_contents:
      strict: true
      lib:
        - FairLogger
      include:
        - fairlogger/*
      files:
        - lib/cmake/FairLogger-${{ version }}/FairLogger*.cmake

about:
  homepage: https://github.com/FairRootGroup/FairLogger
  summary: Lightweight and fast C++ Logging Library
  description: |
    FairLogger is a lightweight and fast C++ logging library developed by
    GSI Helmholtzzentrum fuer Schwerionenforschung. It provides a simple
    interface for logging with multiple severity levels, custom sinks,
    and color support.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  repository: https://github.com/FairRootGroup/FairLogger

extra:
  recipe-maintainers:
    - olantwin
