#!/bin/bash

acc-lda --help
acc-tree-stats --help
add-deltas --help
add-deltas-sdc --help
add-self-loops --help
ali-to-pdf --help
ali-to-phones --help
ali-to-post --help
align-compiled-mapped --help
align-equal --help
align-equal-compiled --help
align-mapped --help
align-text --help
am-info --help
analyze-counts --help
append-post-to-feats --help
append-vector-to-feats --help
apply-cmvn --help
apply-cmvn-sliding --help
arpa-to-const-arpa --help
arpa2fst --help
build-pfile-from-ali --help
build-tree --help
build-tree-two-level --help
chain-est-phone-lm --help
chain-get-supervision --help
chain-make-den-fst --help
cluster-phones --help
cmvn-to-nnet --help
compare-feats --help
compile-questions --help
compile-train-graphs --help
compile-train-graphs-fsts --help
compose-transforms --help
compute-and-process-kaldi-pitch-feats --help
compute-atwv --help
compute-cmvn-stats --help
compute-cmvn-stats-two-channel --help
compute-eer --help
compute-fbank-feats --help
compute-kaldi-pitch-feats --help
compute-mce-scale --help
compute-mfcc-feats --help
compute-plp-feats --help
compute-spectrogram-feats --help
compute-vad --help
compute-vad-from-frame-likes --help
compute-wer --help
compute-wer-bootci --help
concat-feats --help
convert-ali --help
copy-feats --help
copy-feats-to-htk --help
copy-feats-to-sphinx --help
copy-gselect --help
copy-int-vector --help
copy-int-vector-vector --help
copy-matrix --help
copy-post --help
copy-transition-model --help
copy-tree --help
copy-vector --help
create-split-from-vad --help
decode-faster --help
decode-faster-mapped --help
dot-weights --help
draw-tree --help
duplicate-matrix --help
est-lda --help
est-mllt --help
est-pca --help
extend-transform-dim --help
extract-ctx --help
extract-feature-segments --help
extract-rows --help
extract-segments --help
feat-to-dim --help
feat-to-len --help
feat-to-post --help
fgmm-global-acc-stats --help
fgmm-global-acc-stats-post --help
fgmm-global-acc-stats-twofeats --help
fgmm-global-copy --help
fgmm-global-est --help
fgmm-global-get-frame-likes --help
fgmm-global-gselect-to-post --help
fgmm-global-info --help
fgmm-global-init-from-accs --help
fgmm-global-merge --help
fgmm-global-mixdown --help
fgmm-global-sum-accs --help
fgmm-global-to-gmm --help
fgmm-gselect --help
fmpe-acc-stats --help
fmpe-apply-transform --help
fmpe-copy --help
fmpe-est --help
fmpe-init --help
fmpe-sum-accs --help
fstaddselfloops --help
fstaddsubsequentialloop --help
fstcomposecontext --help
fstcopy --help
fstdeterminizelog --help
fstdeterminizestar --help
fstfactor --help
fstisstochastic --help
fstmakecontextfst --help
fstmakecontextsyms --help
fstminimizeencoded --help
fstphicompose --help
fstpropfinal --help
fstpushspecial --help
fstrand --help
fstrhocompose --help
fstrmepslocal --help
fstrmsymbols --help
fsts-project --help
fsts-to-transcripts --help
fsts-union --help
fsttablecompose --help
generate-proxy-keywords --help
get-full-lda-mat --help
get-post-on-ali --help
get-silence-probs --help
global-gmm-adapt-map --help
gmm-acc-hlda --help
gmm-acc-mllt --help
gmm-acc-mllt-global --help
gmm-acc-stats --help
gmm-acc-stats-ali --help
gmm-acc-stats-twofeats --help
gmm-acc-stats2 --help
gmm-adapt-map --help
gmm-align --help
gmm-align-compiled --help
gmm-basis-fmllr-accs --help
gmm-basis-fmllr-accs-gpost --help
gmm-basis-fmllr-training --help
gmm-boost-silence --help
gmm-compute-likes --help
gmm-compute-likes-gmmubm --help
gmm-copy --help
gmm-decode-biglm-faster --help
gmm-decode-faster --help
gmm-decode-faster-regtree-fmllr --help
gmm-decode-faster-regtree-mllr --help
gmm-decode-nbest --help
gmm-decode-simple --help
gmm-diff-accs --help
gmm-est --help
gmm-est-basis-fmllr --help
gmm-est-basis-fmllr-gpost --help
gmm-est-fmllr --help
gmm-est-fmllr-global --help
gmm-est-fmllr-gpost --help
gmm-est-fmllr-raw --help
gmm-est-fmllr-raw-gpost --help
gmm-est-gaussians-ebw --help
gmm-est-hlda --help
gmm-est-lvtln-trans --help
gmm-est-map --help
gmm-est-regtree-fmllr --help
gmm-est-regtree-fmllr-ali --help
gmm-est-regtree-mllr --help
gmm-est-rescale --help
gmm-est-weights-ebw --help
gmm-fmpe-acc-stats --help
gmm-get-feat-deriv --help
gmm-get-stats-deriv --help
gmm-global-acc-stats --help
gmm-global-acc-stats-twofeats --help
gmm-global-copy --help
gmm-global-est --help
gmm-global-est-fmllr --help
gmm-global-est-lvtln-trans --help
gmm-global-get-frame-likes --help
gmm-global-get-post --help
gmm-global-gselect-to-post --help
gmm-global-info --help
gmm-global-init-from-feats --help
gmm-global-sum-accs --help
gmm-global-to-fgmm --help
gmm-gselect --help
gmm-info --help
gmm-init-lvtln --help
gmm-init-model --help
gmm-init-model-flat --help
gmm-init-mono --help
gmm-init-trans --help
gmm-ismooth-stats --help
gmm-latgen-biglm-faster --help
gmm-latgen-faster --help
gmm-latgen-faster-parallel --help
gmm-latgen-faster-regtree-fmllr --help
gmm-latgen-map --help
gmm-latgen-simple --help
gmm-make-regtree --help
gmm-mixup --help
gmm-post-to-gpost --help
gmm-rescore-lattice --help
gmm-scale-accs --help
gmm-sum-accs --help
gmm-train-lvtln-special --help
gmm-transform-means --help
gmm-transform-means-global --help
hmm-info --help
init-ubm --help
interpolate-pitch --help
ivector-adapt-plda --help
ivector-compute-dot-products --help
ivector-compute-lda --help
ivector-compute-plda --help
ivector-copy-plda --help
ivector-extract --help
ivector-extract-online --help
ivector-extractor-acc-stats --help
ivector-extractor-est --help
ivector-extractor-init --help
ivector-extractor-sum-accs --help
ivector-mean --help
ivector-normalize-length --help
ivector-plda-scoring --help
ivector-subtract-global-mean --help
ivector-transform --help
kws-index-union --help
kws-search --help
latgen-faster-mapped --help
latgen-faster-mapped-parallel --help
lattice-1best --help
lattice-add-penalty --help
lattice-add-trans-probs --help
lattice-align-phones --help
lattice-align-words --help
lattice-align-words-lexicon --help
lattice-arc-post --help
lattice-best-path --help
lattice-boost-ali --help
lattice-combine --help
lattice-compose --help
lattice-confidence --help
lattice-copy --help
lattice-copy-backoff --help
lattice-depth --help
lattice-depth-per-frame --help
lattice-determinize --help
lattice-determinize-non-compact --help
lattice-determinize-phone-pruned --help
lattice-determinize-phone-pruned-parallel --help
lattice-determinize-pruned --help
lattice-determinize-pruned-parallel --help
lattice-difference --help
lattice-equivalent --help
lattice-expand-ngram --help
lattice-interp --help
lattice-limit-depth --help
lattice-lmrescore --help
lattice-lmrescore-const-arpa --help
lattice-lmrescore-rnnlm --help
lattice-mbr-decode --help
lattice-minimize --help
lattice-oracle --help
lattice-project --help
lattice-prune --help
lattice-push --help
lattice-rescore-mapped --help
lattice-rmali --help
lattice-scale --help
lattice-to-ctm-conf --help
lattice-to-fst --help
lattice-to-kws-index --help
lattice-to-mpe-post --help
lattice-to-nbest --help
lattice-to-phone-lattice --help
lattice-to-post --help
lattice-to-smbr-post --help
lattice-union --help
lattice-word-align --help
linear-to-nbest --help
logistic-regression-copy --help
logistic-regression-eval --help
logistic-regression-train --help
logprob-to-post --help
make-h-transducer --help
make-ilabel-transducer --help
make-pdf-to-tid-transducer --help
matrix-dim --help
matrix-logprob --help
matrix-sum --help
matrix-sum-rows --help
merge-vads --help
modify-cmvn-stats --help
nbest-to-ctm --help
nbest-to-lattice --help
nbest-to-linear --help
nbest-to-prons --help
nnet-adjust-priors --help
nnet-align-compiled --help
nnet-am-average --help
nnet-am-combine --help
nnet-am-compute --help
nnet-am-copy --help
nnet-am-fix --help
nnet-am-info --help
nnet-am-init --help
nnet-am-limit-rank --help
nnet-am-limit-rank-final --help
nnet-am-mixup --help
nnet-am-reinitialize --help
nnet-am-rescale --help
nnet-am-shrink --help
nnet-am-stats --help
nnet-am-switch-preconditioning --help
nnet-am-widen --help
nnet-combine --help
nnet-combine-a --help
nnet-combine-egs-discriminative --help
nnet-combine-fast --help
nnet-compare-hash-discriminative --help
nnet-compute --help
nnet-compute-from-egs --help
nnet-compute-prob --help
nnet-concat --help
nnet-copy --help
nnet-copy-egs --help
nnet-copy-egs-discriminative --help
nnet-forward --help
nnet-get-egs --help
nnet-get-egs-discriminative --help
nnet-get-feature-transform --help
nnet-get-feature-transform-multi --help
nnet-get-weighted-egs --help
nnet-gradient --help
nnet-info --help
nnet-init --help
nnet-initialize --help
nnet-insert --help
nnet-kl-hmm-acc --help
nnet-kl-hmm-mat-to-component --help
nnet-latgen-faster --help
nnet-latgen-faster-parallel --help
nnet-limit-degradation --help
nnet-logprob --help
nnet-logprob-parallel --help
nnet-logprob2 --help
nnet-logprob2-parallel --help
nnet-modify-learning-rates --help
nnet-normalize-stddev --help
nnet-perturb-egs --help
nnet-perturb-egs-fmllr --help
nnet-relabel-egs --help
nnet-replace-last-layers --help
nnet-select-egs --help
nnet-set-learnrate --help
nnet-show-progress --help
nnet-shrink --help
nnet-shuffle-egs --help
nnet-shuffle-egs-discriminative --help
nnet-subset-egs --help
nnet-to-raw-nnet --help
nnet-train-discriminative-parallel --help
nnet-train-discriminative-simple --help
nnet-train-ensemble --help
nnet-train-frmshuff --help
nnet-train-mmi-sequential --help
nnet-train-mpe-sequential --help
nnet-train-multistream --help
nnet-train-multistream-perutt --help
nnet-train-parallel --help
nnet-train-perutt --help
nnet-train-simple --help
nnet-train-transitions --help
nnet1-to-raw-nnet --help
nnet2-boost-silence --help
paste-feats --help
paste-post --help
pdf-to-counts --help
phones-to-prons --help
post-to-feats --help
post-to-pdf-post --help
post-to-phone-post --help
post-to-tacc --help
post-to-weights --help
print-proxy-keywords --help
prob-to-post --help
process-kaldi-pitch-feats --help
process-pitch-feats --help
prons-to-wordali --help
rand-prune-post --help
raw-nnet-concat --help
raw-nnet-copy --help
raw-nnet-info --help
rbm-convert-to-nnet --help
rbm-train-cd1-frmshuff --help
remove-mean --help
reverse-feats --help
reverse-weights --help
scale-post --help
select-feats --help
select-voiced-frames --help
sgmm2-acc-stats --help
sgmm2-acc-stats-gpost --help
sgmm2-acc-stats2 --help
sgmm2-align-compiled --help
sgmm2-comp-prexform --help
sgmm2-copy --help
sgmm2-est --help
sgmm2-est-ebw --help
sgmm2-est-fmllr --help
sgmm2-est-spkvecs --help
sgmm2-est-spkvecs-gpost --help
sgmm2-gselect --help
sgmm2-info --help
sgmm2-init --help
sgmm2-latgen-faster --help
sgmm2-latgen-faster-parallel --help
sgmm2-post-to-gpost --help
sgmm2-project --help
sgmm2-rescore-lattice --help
sgmm2-sum-accs --help
shift-feats --help
show-alignments --help
show-transitions --help
splice-feats --help
subsample-feats --help
subset-feats --help
sum-lda-accs --help
sum-matrices --help
sum-mllt-accs --help
sum-post --help
sum-tree-stats --help
thresh-post --help
train-transitions --help
transcripts-to-fsts --help
transf-to-nnet --help
transform-feats --help
transform-vec --help
tree-info --help
vector-scale --help
vector-sum --help
wav-copy --help
wav-reverberate --help
wav-to-duration --help
weight-post --help
weight-silence-post --help
