if [ "${JAVA_HOME_CONDA_BACKUP+x}" ] ; then
  export JAVA_HOME=$JAVA_HOME_CONDA_BACKUP
  unset JAVA_HOME_CONDA_BACKUP
else
  unset JAVA_HOME
fi

if [ "${JAVA_LD_LIBRARY_PATH_BACKUP+x}" ] ; then
  export JAVA_LD_LIBRARY_PATH=$JAVA_LD_LIBRARY_PATH_BACKUP
  unset JAVA_LD_LIBRARY_PATH_BACKUP
else
  unset JAVA_LD_LIBRARY_PATH
fi
