context:
  name: perl-module-scandeps
  version: "1.37"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RS/RSCHUPP/Module-ScanDeps-${{ version }}.tar.gz
  sha256: 1f5e119cade1466c39c71e5bc35a8d4f4e672635db03d79a5a0dcf08c4e2b5a3

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-version >=0.77
  run:
    - perl
    - perl-version >=0.77

tests:
  - script: perl -e 'use Module::ScanDeps; print "ok\n"'

about:
  homepage: https://metacpan.org/dist/Module-ScanDeps
  summary: Recursively scan Perl code for dependencies
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file: LICENSE

extra:
  recipe-maintainers:
    - baszalmstra
