schema_version: 1

context:
  version: "0.0.6"

package:
  name: deepagents-acp
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/d/deepagents-acp/deepagents_acp-${{ version }}.tar.gz
    sha256: 42f7c324281893563496741579db0818ec8bfd7bfc2e03d0f18cacd5a7b27dbb
  - url: https://raw.githubusercontent.com/langchain-ai/deepagents/refs/tags/deepagents-acp%3D%3D${{ version }}/LICENSE
    sha256: 4ec67e4ca6e6721dba849b2ca82261597c86a61ee214bbf21416006b7b2d0478
    file_name: LICENSE

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - agent-client-protocol >=0.8.0
    - deepagents
    - python-dotenv >=1.2.1

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - deepagents_acp
      pip_check: true

about:
  summary: Agent Client Protocol integration for Deep Agents
  repository: https://github.com/langchain-ai/deepagents
  license: MIT
  license_file: LICENSE
  homepage: https://docs.langchain.com/oss/python/deepagents/overview
  documentation: https://reference.langchain.com/python/deepagents/

extra:
  recipe-maintainers:
    - xhochy
