context:
  version: "0.6.0"

package:
  name: chunkah
  version: ${{ version }}

source:
  url: https://github.com/coreos/chunkah/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7b5a103451a714d65e2a75c5b1331545b39689f31901ef3eb8da46045eddccc7

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    content:
      - cargo auditable install --path=. --root="$PREFIX" --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=./THIRDPARTY.yml
  skip: not linux

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - chunkah --help
      - chunkah help build
  - package_contents:
      files:
        - bin/chunkah
      strict: true

about:
  summary: An OCI building tool for content-based layers
  description: |
    chunkah takes a flat rootfs and outputs layered OCI images using
    content-based layers, improving layer reuse and cache efficiency.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  homepage: https://github.com/coreos/chunkah
  repository: https://github.com/coreos/chunkah

extra:
  recipe-maintainers:
    - salim-b
