--- DIVA-4.7.2.orig/DIVA3D/src/Fortran/Makefile	2018-08-31 04:29:22.000000000 -0300
+++ DIVA-4.7.2/DIVA3D/src/Fortran/Makefile	2019-08-09 16:58:33.208526856 -0300
@@ -4,7 +4,7 @@
 
 DIVA_PARALLEL=1
 
-export compiler=gfortran
+export compiler=${GFORTRAN}
 
 export flags=-O3 -frecord-marker=4 -cpp -DDIVAITERATIVE
 ifeq ($(DIVA_PARALLEL), 1)
@@ -14,11 +14,11 @@
 endif
 
 
-export nclib=$(shell nf-config --flibs)
-export ncinc=$(shell nf-config --fflags)
+# export nclib=$(shell ${PREFIX}/nf-config --flibs)
+# export ncinc=$(shell ${PREFIX}/nf-config --fflags)
 
-#export ncinc=-I/usr/local/include
-#export nclib=-L/usr/local/lib -lnetcdff -L/usr/local/lib -lnetcdf -lnetcdf
+export ncinc=-I$(PREFIX)/include
+export nclib=-L$(PREFIX)/lib -lnetcdff -L$(PREFIX)/lib -lnetcdf -lnetcdf
 
 # For ifort (adapt path to ifort compiled netCDF library)
 #export compiler=ifort
@@ -29,8 +29,8 @@
 # export nocyg=...
 # export noglobals=...
 
-export SRCDIR=$(PWD)
-export BINDIR=$(SRCDIR)/../../bin/
+export SRCDIR=$(SRC_DIR)
+export BINDIR=$(PREFIX)/bin/
 export DIVA2DDIR=$(SRCDIR)/../../divastripped
 export DIVAWORKDIR=$(DIVA2DDIR)/divawork/
 export DIVAMESHDIR=$(DIVA2DDIR)/meshgenwork/
