{% set name = "lsdb-rubin" %}
{% set version = "0.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lsdb_rubin-{{ version }}.tar.gz
  sha256: 6f2e4742fd419b2a4d7077a73de52808ba1cfeee3e369e8e122133f307e807e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - lsdb >=0.9.2
    - skymap-convert >=0.1.1

test:
  imports:
    - lsdb_rubin
  commands:
    - pip check
    - pytest tests/lsdb_rubin
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/lincc-frameworks/lsdb-rubin
  summary: Suite of utilities for interacting with Rubin LSST data within LSDB.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - delucchi-cmu
    - camposandro
