load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "utility",
    linkopts = [
        "-labsl_base",
        "-pthread",
    ],
)
