schema_version: 1

context:
  version: 3.2.0

package:
  name: throttled-py
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/throttled-py/throttled_py-${{ version }}.tar.gz
  sha256: a168ad3c0b77efd3cef10120b2e4e52100018e6c02f9d5e1f064bb84c7b39d74

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - throttled_py
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: 🔧 High-performance Python rate limiting library with multiple algorithms (Fixed Window, Sliding Window, Token Bucket, Leaky Bucket & GCRA) and storage backends (Redis, In-Memory).
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ZhuoZhuoCrayon/throttled-py
  documentation: https://throttled-py.readthedocs.io

extra:
  recipe-maintainers:
    - thewchan