diff --git a/src/Makefile b/src/Makefile
index 315db85..59ea4f3 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -35,12 +35,12 @@
 
 ### gfortran/MacOS settings:
 ###-------------------------
-FC     = gfortran
+#FC     = gfortran
 USE_C_FILES = yes
-CC = gcc
-CFLAGS =
-LIB           = -L/Users/jbehler/Daten-Goettingen/Codes/LAPACK/lapack-3.8.0 -llapack -lblas
-FFLAGS        = -O3
+#CC = gcc
+#CFLAGS =
+LIB           = -L${PREFIX}/lib -lblas -llapack
+#FFLAGS        = -O3
 
 ### GWDG
 ###-----
