diff --git a/src/Makefile b/src/Makefile
index 315db85..627a3d0 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -35,11 +35,11 @@

 ### gfortran/MacOS settings:
 ###-------------------------
-FC     = gfortran
+#FC     = gfortran
 USE_C_FILES = yes
-CC = gcc
+#CC = gcc
- CFLAGS =
+# CFLAGS =
-LIB           = -L/Users/jbehler/Daten-Goettingen/Codes/LAPACK/lapack-3.8.0 -llapack -lblas
+LIB           = -L${PREFIX}/lib -lblas -llapack
- FFLAGS        = -O3
+# FFLAGS =

 ### GWDG
