# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.0.0"

package:
  name: dj-control-room-base
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dj-control-room-base/dj_control_room_base-${{ version }}.tar.gz
  sha256: a137f9aee8cd1b43ac8b286a04d00fe515f372d62f584ba18c0a9c92da73ab0a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2

tests:
  - python:
      imports:
        - dist
        - dj_control_room_base
        - docs
        - images
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Core framework for Django Control Room panels
  license: MIT
  license_file: LICENSE
  homepage: https://yassi.github.io/dj-control-room-base/
  repository: https://yassi.github.io/dj-control-room-base/
  documentation: https://yassi.github.io/dj-control-room-base/

extra:
  recipe-maintainers:
    - rxm7706
