mkdir build
cd build


cmake ^
    -G "%CMAKE_GENERATOR%" ^
    -DCMAKE_PREFIX_PATH=$PREFIX ^
    -DCMAKE_3RDPARTY_DIR="%LIBRARY_LIB%" ^
    -D3RDPARTY_TK_DIR="%LIBRARY_PREFIX%" ^
    -D3RDPARTY_TCL_DIR="%LIBRARY_PREFIX%" ^
    -D3RDPARTY_TK_LIBRARY_DIR="%LIBRARY_PREFIX%\lib" ^
    -D3RDPARTY_TCL_LIBRARY_DIR="%LIBRARY_PREFIX% \lib" ^
    -DCMAKE_INSTALL_PREFIX:PATH="%LIBRARY_PREFIX%" ..

msbuild /m