mkdir build
cd build

cmake .. -G "Ninja" ^
    -DCMAKE_PREFIX_PATH:FILEPATH="%PREFIX%" ^
    -DCMAKE_INSTALL_PREFIX:FILEPATH="%LIBRARY_PREFIX%" ^
    -D3DPARTY_TCL_DIR:FILEPATH="%LIBRARY_PREFIX%" ^
    -D3DPARTY_TCL_DLL_DIR:FILEPATH="%LIBRARY_BIN%" ^
    -D3DPARTY_TCL_INCLUDE_DIR:FILEPATH="%LIBRARY_INC%" ^
    -D3DPARTY_TCL_LIBRARY_DIR:FILEPATH="%LIBRARY_LIB%" ^
    -D3DPARTY_TK_DIR:FILEPATH="%LIBRARY_PREFIX%" ^
    -D3DPARTY_TK_DLL_DIR:FILEPATH="%LIBRARY_BIN%" ^
    -D3DPARTY_TK_INCLUDE_DIR:FILEPATH="%LIBRARY_INC%" ^
    -D3DPARTY_TK_LIBRARY_DIR:FILEPATH="%LIBRARY_LIB%" ^
    -DTK_LIBRARY_PATH:FILEPATH="%LIBRARY_PREFIX%"

if errorlevel 1 exit 1

ninja install
if errorlevel 1 exit 1
