mkdir build && cd build

cmake -G "Ninja" \
 -D CMAKE_BUILD_TYPE:STRING=Release \
 -D CMAKE_INSTALL_PREFIX:FILEPATH=$PREFIX \
 -D CMAKE_PREFIX_PATH:FILEPATH=$PREFIX \
 -D CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=$PREFIX \
 -D OCC_INCLUDE_DIR:FILEPATH=$PREFIX/include/opencasade \
 -D OCC_LIBRARY_DIR:FILEPATH=$PREFIX/lib \
 -D PYTHON_EXECUTABLE:FILEPATH=$PYTHON \
 -D COLLADA_SUPPORT:BOOL=OFF \
 -D BUILD_EXAMPLES:BOOL=OFF \
 -D BUILD_GEOMSERVER:BOOL=OFF \
 -D BUILD_CONVERT:BOOL=OFF \
 ../cmake

ninja install
