schema_version: 1

context:
  version: "0.2.3"

package:
  name: pytest-accept
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-accept/pytest_accept-${{ version }}.tar.gz
  sha256: c747d92ef0bcac0dc20e46f3dfb73b8e9aee970de11b98985868560ca508d06e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.7.19,<0.8.0
    - pip
  run:
    - python >=${{ python_min }}
    - astor >=0.8.1
    - pytest >=7

tests:
  - python:
      imports:
        - pytest_accept
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  summary: A pytest plugin for automatically updating doctest outputs
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/pytest-accept/

extra:
  recipe-maintainers:
    - isuruf
