package:
  name: pqdump
  version: "0.1.0"

source:
  url: https://github.com/charles-turner-1/pqdump/archive/refs/tags/v0.1.0.tar.gz
  sha256: 3931909f9b5e3120125ba1fab29d378981048163cc61730675b8cdfc37886c26

build:
  number: 0
  script: cargo build --release --locked

requirements:
  build:
    - rust
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host: []
  run: []

test:
  commands:
    - pqdump --help
    - pqdump --version
    - pqdump tests/data/GLODAPv2.2023_head.pq

about:
  home: https://github.com/charles-turner-1/pqdump
  summary: CLI tool for inspecting parquet files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - charles-turner-1
