#!/usr/bin/env bash

if [ -n "${_OLD_OCL_ICD_FILENAMES_INTEL_GPU_OCL_ICD_SYSTEM+x}" ]; then
  if [ -n "${_OLD_OCL_ICD_FILENAMES_INTEL_GPU_OCL_ICD_SYSTEM}" ]; then
    export OCL_ICD_FILENAMES="${_OLD_OCL_ICD_FILENAMES_INTEL_GPU_OCL_ICD_SYSTEM}"
  else
    unset OCL_ICD_FILENAMES
  fi
  unset _OLD_OCL_ICD_FILENAMES_INTEL_GPU_OCL_ICD_SYSTEM
fi
