schema_version: 1

context:
  name: gaphas
  version: 5.1.2
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gaphas-${{ version }}.tar.gz
  sha256: 5dd6b05931f3856a96b623269b50187231b4abf7b9849f48f7eec52898563696

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pygobject >=3.50
    - pycairo >=1.20.0

tests:
  - python:
      imports:
        - gaphas
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/gaphor/gaphas
  summary: Gaphas is a GTK diagramming widget
  documentation: https://gaphas.readthedocs.io/
  repository: https://github.com/gaphor/gaphas
  license: Apache-2.0
  license_file: LICENSES/Apache-2.0.txt

extra:
  recipe-maintainers:
    - danyeaw
