context:
  version: "6.10.2"

package:
  name: qt6-positioning
  version: ${{ version }}

source:
  url: https://github.com/qt/qtpositioning/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d7cc67a09f60f33328cb5e94818149d3eb2ccdbcd3cd38a1dc537e3ff79b739b

build:
  number: 0
  script:
    - if: win
      then:
        - cmake -S . -B build -G Ninja %CMAKE_ARGS%
          -DQt6_DIR=%PREFIX%\\Library\\lib\\cmake\\Qt6
      else:
        - cmake -S . -B build -G Ninja ${CMAKE_ARGS}
          -DQt6_DIR=${{ PREFIX }}/lib/cmake/Qt6
    - cmake --build build --parallel ${{ CPU_COUNT }}
    - ctest --test-dir build --output-on-failure 
    - cmake --install build
    - if: win
      then:
        - copy %PREFIX%\Library\lib\qt6\bin\Qt6Positioning.dll %PREFIX%\Library\bin\Qt6Positioning.dll

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - pkg-config
    - if: build_platform != target_platform
      then: qt6-main ${{ version }}.*
  host:
    - qt6-main ${{ version }}.*
  run:
    - qt6-main ${{ version }}.*
  run_exports:
    - ${{ pin_subpackage('qt6-positioning', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - qt6/QtPositioning/qgeopositioninfo.h
      lib:
        - Qt6Positioning

about:
  homepage: https://doc.qt.io/qt-6/qtpositioning-index.html
  summary: Qt Positioning support
  description: |
    The Qt Positioning API provides positioning information via QML and C++ interfaces.
  license: LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
  license_file: LICENSES/
  repository: https://github.com/qt/qtpositioning
  documentation: https://doc.qt.io/qt-6/qtpositioning-index.html

extra:
  feedstock-name: qt-positioning
  recipe-maintainers:
    - hxbb00
