{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mycor
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/mycor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mycor/mycor_{{ version }}.tar.gz
  sha256: 2f8f73cc0d76ee79d49f652d9187cf8b1e3f8f2627e931d0207b09a1deae1802

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-lattice
  run:
    - r-base
    - r-lattice

test:
  commands:
    - $R -e "library('mycor')"           # [not win]
    - "\"%R%\" -e \"library('mycor')\""  # [win]

about:
  home: https://github.com/cardiomoon/mycor
  license: CC0-1.0
  summary: Perform correlation and linear regression test among the numeric fields in a data.frame
    automatically and make plots using pairs or lattice::parallelplot.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mycor
# Title: Automatic Correlation and Regression Test in a 'data.frame'
# Version: 0.1.1
# Authors@R: person("Keon-Woong","Moon", email="cardiomoon@gmail.com", role=c("aut","cre"))
# Description: Perform correlation and linear regression test among the numeric fields in a data.frame automatically and make plots using pairs or lattice::parallelplot.
# Depends: R (>= 3.1.1)
# License: CC0
# URL: https://github.com/cardiomoon/mycor
# LazyData: true
# Imports: lattice
# Suggests: knitr, testthat
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-04-10 12:50:03 UTC; cardiomoon
# Author: Keon-Woong Moon [aut, cre]
# Maintainer: Keon-Woong Moon <cardiomoon@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-04-10 13:16:31 UTC
