# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  version: "1.9.0"

package:
  name: agent-framework-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/agent-framework-core/agent_framework_core-${{ version }}.tar.gz
  sha256: 09c5f18a43209f6db53dfe0da25d3dfbf1e5176a930a8ec3859091687d8f80a2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core >=3.11,<4.0
  run:
    - python >=${{ python_min }}
    - typing-extensions >=4.15.0,<5
    - pydantic >=2,<3
    - python-dotenv >=1,<2
    - opentelemetry-api >=1.39.0,<2

tests:
  - python:
      imports:
        - agent_framework
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://aka.ms/agent-framework
  repository: https://github.com/microsoft/agent-framework
  summary: Microsoft Agent Framework core package with the core abstractions and implementations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
