{% set name = "tsui" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src
    url: https://github.com/neuralinkcorp/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: bc1c170b9ca2f335aa9710d84b95486dc34542ee00eb4f629834ef2be52a12ad

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/tsui  # [not win]
    - go build -v -o %LIBRARY_BIN%\tsui.exe  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - tsui --version
    - tsui --help

about:
  home: https://github.com/neuralinkcorp/tsui
  license: MIT
  license_file:
    - src/LICENSE.md
    - library_licenses/
  summary: An (experimental) elegant TUI for configuring Tailscale.
  dev_url: https://github.com/neuralinkcorp/tsui

extra:
  recipe-maintainers:
    - pavelzw
