--- Makefile.bak	2019-03-07 11:14:06.155077049 -0500
+++ Makefile	2019-03-07 11:14:24.787076792 -0500
@@ -9,7 +9,7 @@
 
 all: $(all)
 
-install: all
+install:
 	install -d $(DESTDIR)$(PREFIX)/bin
 	install -m 0755 $(self) $(DESTDIR)$(PREFIX)/bin
 	install -d $(DESTDIR)$(PREFIX)/share/man/man1
