--- xgboost/Makefile
+++ xgboost/Makefile
@@ -43,8 +43,9 @@
 # it is useful for pip install compiling-on-the-fly
 OS := $(shell uname)
 ifeq ($(OS), Darwin)
-export CC = $(if $(shell which gcc-5),gcc-5,clang-omp)
-export CXX = $(if $(shell which g++-5),g++-5,clang-omp++)
+export CC = $(if $(shell which gcc),gcc,clang)
+export CXX = $(if $(shell which g++),g++,clang++)
+export ADD_LDFLAGS = -lgcc_eh
 endif
 
 export LDFLAGS= -pthread -lm $(ADD_LDFLAGS) $(DMLC_LDFLAGS) $(PLUGIN_LDFLAGS)
