--- xgboost-0.6a2/xgboost/Makefile	2016-08-09 04:32:24.000000000 -0500
+++ xgboost-0.6a2/xgboost/Makefile	2017-03-10 15:15:39.000000000 -0600
@@ -43,8 +43,8 @@
 # it is useful for pip install compiling-on-the-fly
 OS := $(shell uname)
 ifeq ($(OS), Darwin)
-export CC = $(if $(shell which gcc-5),gcc-5,clang-omp)
-export CXX = $(if $(shell which g++-5),g++-5,clang-omp++)
+export CC = $(if $(shell which gcc),gcc,clang)
+export CXX = $(if $(shell which g++),g++,clang++)
 endif
 
 export LDFLAGS= -pthread -lm $(ADD_LDFLAGS) $(DMLC_LDFLAGS) $(PLUGIN_LDFLAGS)
