#!/bin/bash

set -ex

cmake ${CMAKE_ARGS} \
  -S "$SRC_DIR/client/src/c++" \
  -B build-cpp \
  -GNinja \
  -DBUILD_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_INSTALL_BINDIR=bin \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DFETCHCONTENT_FULLY_DISCONNECTED=ON \
  -DFETCHCONTENT_SOURCE_DIR_REPO-COMMON="$SRC_DIR/common" \
  -DTRITON_COMMON_ENABLE_PROTOBUF_PYTHON=OFF \
  -DTRITON_ENABLE_CC_GRPC=ON \
  -DTRITON_ENABLE_CC_HTTP=ON \
  -DTRITON_ENABLE_EXAMPLES=OFF \
  -DTRITON_ENABLE_GPU=OFF \
  -DTRITON_ENABLE_TESTS=OFF \
  -DTRITON_KEEP_TYPEINFO=ON \
  -DTRITON_USE_THIRD_PARTY=OFF
cmake --build build-cpp --parallel "$CPU_COUNT"
cmake --install build-cpp
