schema_version: 1

context:
  name: s3-log-extraction
  pypi_name: s3_log_extraction
  version: "1.3.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ pypi_name[0] }}/${{ pypi_name }}/${{ pypi_name }}-${{ version }}.tar.gz
  sha256: 2047d666e8f0aeb78adc61a381bcad7863fb1c179bab42d82fd7264b011daeba

build:
  number: 0
  skip:
    - not linux
    - match(python, "<3.14")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - s3logextraction = s3_log_extraction._command_line_interface._cli:_s3logextraction_cli

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - pandas
    - tqdm
    - pyyaml
    - rich-click
    - natsort
    - psutil
    - cryptography
    - pydantic

tests:
  - python:
      imports:
        - s3_log_extraction
      pip_check: true
  - script:
      - pytest -m "not remote"
    requirements:
      run:
        - pytest
        - pytest-cov
    files:
      source:
        - tests/

about:
  homepage: https://github.com/dandi/s3-log-extraction
  repository: https://github.com/dandi/s3-log-extraction
  documentation: https://github.com/dandi/s3-log-extraction/blob/main/README.md
  summary: Fast extraction of access summary data from S3 logs.
  description: |
    Creates summary file reports of bytes downloaded with coarse geolocations.
    Aggregates over top-level 'datasets', as well as the entire bucket.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CodyCBakerPhD
    - yarikoptic
    - candleindark
    - asmacdo
