package:
  name: spring2
  version: 1.0.0

source:
  url: https://github.com/thisisamirv/SPRING2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c900abaa5cff98eebf3a5be034dc1a1beafbd645202e33a5186f478782c5e0a9

build:
  number: 0

outputs:
  - name: spring2
    build:
      ignore_run_exports:
        - vc14_runtime  # [win]
        - libcxx  # [osx]
      script:
        - bash "${RECIPE_DIR}/build.sh"  # [unix]
        - call "%RECIPE_DIR%\\bld.bat"  # [win]
    requirements:
      build:
        - "{{ compiler('c') }}"
        - "{{ compiler('cxx') }}"
        - "{{ stdlib('c') }}"
        - cmake >=3.31
        - ninja
        - nasm
        - make  # [unix]
      host:
        - _openmp_mutex * *_gnu  # [linux]
        - llvm-openmp  # [osx]
      run:
        - _openmp_mutex * *_gnu  # [linux]
        - llvm-openmp  # [osx]
        - llvm-openmp  # [win]
    test:
      commands:
        - spring2 --version
        - spring2 --help

about:
  home: https://spring2.readthedocs.io/
  summary: Cross-platform FASTQ/FASTA compressor and decompressor
  description: |
    SPRING2 is a modernized derivative of SPRING for compressing and
    decompressing FASTQ/FASTA genomic read data across Linux, macOS, and Windows.
  license: LicenseRef-SPRING
  license_file: LICENSE
  dev_url: https://github.com/thisisamirv/SPRING2

extra:
  recipe-maintainers:
    - thisisamirv
