context:
  version: "1.0.2"

package:
  name: spring2
  version: ${{ version }}

source:
  url: https://github.com/thisisamirv/SPRING2/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2582bb71eeff875ff0afdc7da86f9c13a66e527627de579ff1fd33f4ce6e10a1

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake >=3.31
    - ninja
    - nasm
    - if: unix
      then: make
  host:
    - if: linux
      then: _openmp_mutex * *_gnu
    - if: osx
      then: llvm-openmp
  run:
    - if: linux
      then: _openmp_mutex * *_gnu
    - if: osx or win
      then: llvm-openmp

tests:
  - script:
      - spring2 --version
      - spring2 --help

about:
  homepage: https://spring2.readthedocs.io/
  summary: Cross-platform FASTQ/FASTA compressor and decompressor
  description: |
    SPRING2 is a modernized derivative of SPRING for compressing and
    decompressing FASTQ/FASTA genomic read data across Linux, macOS, and Windows.
  license: LicenseRef-SPRING
  license_file:
    - LICENSE
    - REDISTRIBUTION_PERMISSION.md
  repository: https://github.com/thisisamirv/SPRING2

extra:
  recipe-maintainers:
    - thisisamirv
