schema_version: 1

context:
  version: "1.7.1"

package:
  name: gkx
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gkx/gkx-${{ version }}.tar.gz
  sha256: eb020e42bda81ea3222a6b21d8c5bd5b48c0ff79e6890a1de6e49a980edc3700

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - gkx = gkx.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - jax
    - jaxlib
    - matplotlib-base
    - scipy
    - netcdf4
    - diffrax
    - equinox
    - solvax
    # python < 3.11
    - tomli
    - tqdm

tests:
  - python:
      imports:
        - gkx
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - gkx --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Gyrokinetic Spectral Solver of Plasma Turbulence
  description: |
    GKX is a JAX-native gyrokinetic solver designed for differentiability,
    high-performance accelerator execution, and advanced stellarator
    optimization.
    The code employs a Hermite-Laguerre velocity space, Fourier perpendicular
    coordinates, and field-aligned flux-tube geometry to simulate linear and
    nonlinear electrostatic and electromagnetic turbulence in magnetized
    plasmas.
  license: MIT
  license_file: LICENSE
  homepage: https://gkx.readthedocs.io/
  repository: https://github.com/uwplasma/GKX
  documentation: https://gkx.readthedocs.io/

extra:
  recipe-maintainers:
    - matthewfeickert
    - RKHashmani
