--- Makefile.am	2012-10-12 10:05:48.000000000 -0400
+++ Makefile.am	2017-10-15 00:31:46.663828612 -0400
@@ -63,11 +63,6 @@
 else
 JAV =
 endif
-if MACOSX
-INSTALLOSX = install-exec-local-osx
-else 
-INSTALLOSX = 
-endif
 
 SUBDIRS=include sasldb lib plugins utils doc man $(PWC) $(SAM) $(JAV) $(SAD)
 EXTRA_DIST=config cmulocal win32 mac dlcompat-20010505 NTMakefile INSTALL.TXT \
@@ -81,8 +76,7 @@
 	@find $(distdir) -name CVS -print | xargs -t rm -rf
 	(cd $(distdir)/plugins && sh makeinit.sh)
 
-framedir = /Library/Frameworks/SASL2.framework
-install-exec-local: $(INSTALLOSX)
+install-exec-local:
 	@if test "$(plugindir)" != "$(prefix)/lib/sasl2"; then \
 	  echo "********************************************************"; \
 	  echo "* WARNING:"; \
@@ -100,11 +94,4 @@
 	  echo "* the library should use."; \
 	  echo "********************************************************"; \
 	fi
-install-exec-local-osx:
-	$(mkinstalldirs) $(framedir)/Versions/A/Headers
-	$(mkinstalldirs) $(framedir)/Versions/A/Resources
-	cd $(framedir)/Versions ; ln -fs A Current
-	cd $(framedir) ; ln -fs Versions/A/Headers .
-	cd $(framedir) ; ln -fs Versions/A/Resources .
-	$(INSTALL_DATA) $(srcdir)/config/Info.plist $(framedir)/Versions/A/Resources
 
