{% set version = "0.1.0a4" %}
{% set python_min = "3.11" %}

package:
  name: sklearn-wrap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sklearn-wrap/sklearn_wrap-{{ version }}.tar.gz
  sha256: 008445fe2c0a2229e5a948c628e53ac6b9b30295cbc313f5b0b1621a16a12c71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn >=1.6.0
    - joblib >=1.2.0

test:
  imports:
    - sklearn_wrap
  commands:
    - pip check
    - pytest --help
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/stateful-y/sklearn-wrap
  summary: A Package for wrapping Python classes into Scikit-Learn estimators
  doc_url: https://sklearn-wrap.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gtauzin
