context:
  version: "0.8.0"

package:
  name: libnanoarrow
  version: ${{ version }}

source:
  url: https://github.com/apache/arrow-nanoarrow/releases/download/apache-arrow-nanoarrow-${{ version }}/apache-arrow-nanoarrow-${{ version }}.tar.gz
  sha256: 6e61e2819c9138e9092ba32b568ed6f4594928b306171937251eaaafa7dc2b8c

build:
  number: 0
  script: build

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    # needed for testing
    - gtest
    - nlohmann_json
  run_exports:
    - ${{ pin_subpackage("libnanoarrow", upper_bound="x.x") }}
  ignore_run_exports:
    from_package:
      - gtest
      - nlohmann_json

tests:
  - package_contents:
      include:
        - nanoarrow/nanoarrow.h
        - nanoarrow/common/inline_array.h
        - nanoarrow/hpp/array_stream.hpp
      lib:
        - nanoarrow

about:
  homepage: https://github.com/apache/arrow-nanoarrow
  summary: 'Helpers for Arrow C Data & Arrow C Stream interfaces'
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/apache/arrow-nanoarrow

extra:
  recipe-maintainers:
    - h-vetinari
