{% set name = "rpscore" %}
{% set version = "6.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rpscore/archive/refs/tags/{{ version }}.tar.gz
  sha256: a590dba589fa1bf7d9b701caf8c1c4807ee7d7162fab6854de98d296f5e9cf8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas <=2.0.3
    - rdkit
    - h5py
    - tqdm
    - scikit-learn
    - xgboost =3.0.2
    - brs_utils >=1.26.0
    - rplibs >=6.9.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - rpscore
  commands:
    - python -m rpscore --help

about:
  home: https://github.com/brsynth/rpscore/tree/main
  summary: "Computes a global score for a heterologous pathway."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
