schema_version: 1

context:
  version: "0.15.2"
  python_min: "3.10"

package:
  name: kernels
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/kernels/kernels-${{ version }}.tar.gz
  sha256: 5af4fab4a2d4eb67f01522dffabfdc3a4bcfc167ce68f7549c0d2828a73cbc19

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - kernels=kernels.cli:main
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - huggingface_hub >=1.10.0
    - kernels-data >=0.14.0
    - packaging >=20.0
    - pyyaml >=6
    - sigstore >=4,<5
    - tomli >=2.0
    - tomlkit >=0.13.3
    - typing_extensions >=4.0

tests:
  - python:
      imports:
        - kernels
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - kernels --help

about:
  homepage: https://github.com/huggingface/kernels
  repository: https://github.com/huggingface/kernels
  summary: Download compute kernels from Hugging Face Hub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - baszalmstra
