{% set name = "cgsmiles" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gruenewald-lab/CGsmiles/archive/{{ version }}.tar.gz
  sha256: 425adc24ce089be08663d10872c4631d65b024c1414b395dec66b7d326e00682

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=2.0
    - networkx >=2.0
    - python >={{ python_min }},<=3.13
    - setuptools
    - importlib_resources
    - pysmiles

test:
  requires:
    - python {{ python_min }}
  imports:
    - cgsmiles 

about:
  home: https://github.com/gruenewald-lab/CGsmiles
  license: Apache-2.0
  license_file: LICENSE
  summary: A Versatile Line Notation for Molecular Representations Across Multiple Resolutions

  description: |
    The CGSmiles line notation encodes arbitrary resolutions of molecules and defines the conversion between these resolutions unambiguously.
    For example, in coarse-grained (CG) simulations multiple atoms are represented as one large pseudo-atom often called bead.
    The conversion from the atomic resolution to the CG resolution can be described using the CGSmiles notation.
  doc_url: https://cgsmiles.readthedocs.io/en/latest/
  dev_url: https://github.com/gruenewald-lab/CGsmiles

extra:
  recipe-maintainers:
    - fgrunewald 
    - pckroon
    - ricalessandri 
    - chrisjonesBSU
