diff --git i/src/Makefile.INCLUDE w/src/Makefile.INCLUDE
index d165447..3321b70 100644
--- i/src/Makefile.INCLUDE
+++ w/src/Makefile.INCLUDE
@@ -15,7 +15,7 @@ LLIBS_X11 ?= $(LLIBS)
 # netpbm is stored in varying locations under homebrew, allow for that
 NETPBMDIR ?= /usr/include/netpbm
 
-LDFLAGS = $(LFLAGS)
+#LDFLAGS = $(LFLAGS)
 
 # for compiling with OpenMP, if available
 
diff --git i/src/other_builds/Makefile.linux_universal w/src/other_builds/Makefile.linux_universal
index 6725962..a0b4411 100644
--- i/src/other_builds/Makefile.linux_universal
+++ w/src/other_builds/Makefile.linux_universal
@@ -31,7 +31,7 @@ CEXTRA = -Wcomment -Wformat -DUSE_TRACING -DHAVE_XDBE -D_GNU_SOURCE \
          -DREPLACE_XT $(CPROF)
 
 #use gcc by default unless user demands clang or gcc not found
-CEXE = /usr/bin/gcc
+CEXE ?= /usr/bin/gcc
 CLANGEXE = /usr/bin/clang
 #run "useClang=1 make all" to give clang precedence over gcc
 ifeq "$(useClang)" "1"
@@ -57,9 +57,9 @@ CCOLD  = $(CC)
 OMPFLAG = -fopenmp -DUSE_OMP  # for OpenMP
 CCMIN  = $(CEXE) -fPIC $(CPROF)
 CCD    = $(CC) $(CCDEBS)
-IFLAGS = -I. -I/usr/X11R6/include $(I_USE_ACML)
+IFLAGS = #-I. -I/usr/X11R6/include $(I_USE_ACML)
 #-I/usr/src/linux-headers-3.0.0-17/include/linux -I/usr/src/linux-headers-3.0.0-17/include $(I_USE_ACML)
-LFLAGS = -L. -L/usr/X11R6/lib64 $(L_USE_ACML)
+LFLAGS = #-L. -L/usr/X11R6/lib64 $(L_USE_ACML)
 
 # maybe 
 
@@ -69,12 +69,12 @@ PLUGIN_SUFFIX = so
 PLUGIN_LFLAGS = -shared -fPIC
 PLUGIN_CC     = $(CC)
 # PLFLAGS       = -rdynamic -L. -L/usr/X11R6/lib
-PLFLAGS       = -rdynamic -L. -L/usr/X11R6/lib64
+PLFLAGS       = #-rdynamic -L. # -L/usr/X11R6/lib64
 
 # possibly modify from above
 ifdef MRI_SHARED
-LFLAGS  = -L. -L/usr/lib64 $(L_USE_ACML) -Wl,-rpath='$$ORIGIN'
-PLFLAGS = -rdynamic $(LFLAGS)
+LFLAGS  = #-L. $(L_USE_ACML) -Wl,-rpath='$$ORIGIN'
+PLFLAGS = #-rdynamic $(LFLAGS)
 endif
 
 SHOWOFF = -DSHOWOFF=$(SYSTEM_NAME)
@@ -108,9 +108,9 @@ EXPROGS = $(GSLPROGS)   # 3dQwarp gifti_tool $(GSLPROGS)
 # for static linking to Motif, dynamic to all else
 
 # separate X11 libs from non-X11 ones
-LLIBS  = -lmri -lf2c $(LZLIB) $(LGIFTI) -lm  -ldl -lc
+LLIBS  = -lmri -lf2c $(LZLIB) $(LGIFTI) -lm  -ldl -lc $(LDFLAGS)
 LLIBS_X11 = -lmri -lf2c -lXm -lXpm -lXext -lXmu -lXt -lSM -lICE -lX11 \
-            $(LZLIB) $(LGIFTI) -lm  -ldl -lc
+            $(LZLIB) $(LGIFTI) -lm  -ldl -lc $(LDFLAGS)
 
 #LLIBS  = -lmri -lf2c /usr/X11R6/lib64/libXm.a -lXpm -lXext -lXmu -lXt -lSM -lICE -lX11 $(LZLIB) $(LGIFTI) -lm  -ldl -lc
 
@@ -131,8 +131,8 @@ LLIBS_X11 = -lmri -lf2c -lXm -lXpm -lXext -lXmu -lXt -lSM -lICE -lX11 \
 # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
 # For suma (NO STATIC LINKING OF GL libs)
 SUMA_GLIB_VER = -2.0
-SUMA_INCLUDE_PATH = -I/usr/X11R6/include -I./ -I../ -I../niml/ -Igts/src -I/usr/include/glib-1.2 -I/usr/include/glib-2.0 -I/usr/lib64/glib/include -I/usr/lib64/ -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/aarch64-linux-gnu/glib-2.0/include
-SUMA_LINK_PATH = -L/usr/lib64 -L/usr/X11R6/lib64 -L../
+SUMA_INCLUDE_PATH = -I./ -I../ -I../niml/ -Igts/src -I${PREFIX}/include
+SUMA_LINK_PATH = -L${PREFIX}/lib -L../
 #use -lGLw if you have libGLw.a or libGLw.so* or 
 #  -lMesaGLw if you have Mesa's version (libMesaGLw*) of libGLw
 #
