#!/usr/bin/env bash
set -e

BUILD_DIR="build"

mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

cmake .. -DCMAKE_INSTALL_PREFIX=${PREFIX} ${CMAKE_ARGS} \
         -DSECP256K1_ENABLE_MODULE_ECDH=${SECP256K1_ENABLE_MODULE_ECDH:-ON} \
         -DSECP256K1_ENABLE_MODULE_RECOVERY=${SECP256K1_ENABLE_MODULE_RECOVERY:-ON} \
         -DSECP256K1_ENABLE_MODULE_EXTRAKEYS=${SECP256K1_ENABLE_MODULE_EXTRAKEYS:-ON} \
         -DSECP256K1_ENABLE_MODULE_SCHNORRSIG=${SECP256K1_ENABLE_MODULE_SCHNORRSIG:-ON}

cmake --build . --target install ${CMAKE_BUILD_OPTIONS}

make check
