{% set name = "substrait-extensions" %}
{% set version = "0.85.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/substrait_extensions-{{ version }}.tar.gz
  sha256: 6b5403b5e7d9cf5f9dbe86f276c6485c9155bec78fab080310202c99b177ca8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=80
  run:
    - python >={{ python_min }}

test:
  imports:
    - substrait_extensions.extensions.simple_extensions
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://substrait.io
  summary: Packaged Substrait Extension Files
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/substrait-io/substrait-packaging

extra:
  recipe-maintainers:
    - nielspardon
