{% set name = "iso639-lang" %}
{% set version = "2.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/iso639_lang-{{ version }}.tar.gz
  sha256: 078ddb7cd0182dcc04367691acc8022ddf7158b6cb09f08f798af823fa864265

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9

test:
  imports:
    - iso639
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A fast, comprehensive, ISO 639 library.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bgruening
