{% set version = '1.15.4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-wrmisc
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/wrMisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wrMisc/wrMisc_{{ version }}.tar.gz
  sha256: 2c1c816e022664091c1e02fc1d8d43d1d0cbc47a2db40dd4801f91b3f45e801c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('wrMisc')"           # [not win]
    - "\"%R%\" -e \"library('wrMisc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=wrMisc
  license: GPL-3.0-only
  summary: The efficient treatment and convenient analysis of experimental high-throughput (omics)
    data gets facilitated through this collection of diverse functions. Several functions
    address advanced object-conversions, like manipulating lists of lists or lists of
    arrays, reorganizing lists to arrays or into separate vectors, merging of multiple
    entries, etc. Another set of functions provides speed-optimized calculation of standard
    deviation (sd), coefficient of variance (CV) or standard error of the mean (SEM)
    for data in matrixes or means per line with respect to additional grouping (eg n
    groups of replicates). A group of functions facilitate dealing with non-redundant
    information, by indexing unique, adding counters to redundant or eliminating lines
    with respect redundancy in a given reference-column, etc. Help is provided to identify
    very closely matching numeric values to generate (partial) distance matrixes for
    very big data in a memory efficient manner or to reduce the complexity of large
    data-sets by combining very close values. Other functions help aligning a matrix
    or data.frame to a reference using partial matching or to mine an experimental setup
    to extract patterns of replicate samples. Many times large experimental datasets
    need some additional filtering, adequate functions are provided. Convenient data
    normalization is supported in various different modes, parameter estimation via
    permutations or boot-strap as well as flexible testing of multiple pair-wise combinations
    using the framework of 'limma' is provided, too. Batch reading (or writing) of sets
    of files and combining data to arrays is supported, too.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: wrMisc
# Version: 1.15.4
# Title: Analyze Experimental High-Throughput (Omics) Data
# Authors@R: person("Wolfgang", "Raffelsberger", email = "w.raffelsberger@gmail.com", role = c("aut", "cre"))
# Author: Wolfgang Raffelsberger [aut, cre]
# Maintainer: Wolfgang Raffelsberger <w.raffelsberger@gmail.com>
# Description: The efficient treatment and convenient analysis of experimental high-throughput (omics) data gets facilitated through this collection of diverse functions. Several functions address advanced object-conversions, like manipulating lists of lists or lists of arrays, reorganizing lists to arrays or into separate vectors, merging of multiple entries, etc. Another set of functions provides speed-optimized calculation of standard deviation (sd), coefficient of variance (CV) or standard error of the mean (SEM) for data in matrixes or means per line with respect to additional grouping (eg n groups of replicates). A group of functions facilitate dealing with non-redundant information, by indexing unique, adding counters to redundant or eliminating lines with respect redundancy in a given reference-column, etc. Help is provided to identify very closely matching numeric values to generate (partial) distance matrixes for very big data in a memory efficient manner or to reduce the complexity of large data-sets by combining very close values. Other functions help aligning a matrix or data.frame to a reference using partial matching or to mine an experimental setup to extract patterns of replicate samples. Many times large experimental datasets need some additional filtering, adequate functions are provided. Convenient data normalization is supported in various different modes, parameter estimation via permutations or boot-strap as well as flexible testing of multiple pair-wise combinations using the framework of 'limma' is provided, too. Batch reading (or writing) of sets of files and combining data to arrays is supported, too.
# VignetteBuilder: knitr
# Depends: R (>= 3.1.0)
# Imports: grDevices, graphics, MASS, stats, utils
# Suggests: BBmisc, boot, coin, data.table, data.tree, fdrtool, flexclust, knitr, limma, markdown, mixdist, NbClust, preprocessCore, qvalue, Rcpp, RColorBrewer, readxl, rmarkdown, som, stringi, VGAM, vsn, wrGraph
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# NeedsCompilation: no
# Packaged: 2025-06-17 15:14:38 UTC; wraff
# Repository: CRAN
# Date/Publication: 2025-06-18 08:00:02 UTC
