echo CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH
echo PREFIX: $PREFIX
ls -la $PREFIX
ls -la $PREFIX/lib
ls -la $PREFIX/lib/cmake/fftw3
echo conda-forge CMAKE_ARGS: ${CMAKE_ARGS}
cmake -S . -B _build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$PREFIX" -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON ${CMAKE_ARGS} -DUSE_OPENMP:BOOL=ON -DUSE_FFTW:BOOL=ON -DUSE_MKL:BOOL=OFF -DUSE_MKL_FFT:BOOL=OFF -DUSE_VSL:BOOL=OFF -DCMAKE_Fortran_FLAGS="-I${PREFIX}/include"
cmake --build _build
cmake --install _build --prefix $PREFIX

