# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1
context:
  name: culsans
  version: "0.11.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/culsans-${{ version }}.tar.gz
  sha256: 0b43d0d05dce6106293d114c86e3fb4bfc63088cfe8ff08ed3fe36891447fe33

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - aiologic >=0.16.0,<0.18.0
    - typing_extensions >=4.10.0

tests:
  - python:
      imports:
        - culsans
      pip_check: true
      python_version:
      - ${{ python_min }}.*
      - "*"

about:
  homepage: https://github.com/x42005e1f/culsans
  summary: Thread-safe async-aware queue for Python
  license: ISC
  license_file: ISC.txt
  documentation: https://culsans.readthedocs.io/
  repository: https://github.com/x42005e1f/culsans

extra:
  recipe-maintainers:
    - rxm7706
    - x42005e1f
