schema_version: 1

context:
  name: tinkr
  version: "0.2.0"

package:
  name: r-${{ name|lower }}
  version: ${{ version }}

source:
  url: https://cran.r-project.org/src/contrib/tinkr_${{ version }}.tar.gz
  sha256: f8b7823e4b97822b576660c2535fdf753e249120067f8394695ef10714a91e19

build:
  number: 0
  merge_build_and_host_envs: true
  script: ${{ R }} CMD INSTALL --build .
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  host:
    - r-R6
    - r-base
    - r-commonmark >=1.6
    - r-glue
    - r-magrittr
    - r-purrr
    - r-xml2
    - r-xslt
    - r-yaml
  run:
    - r-R6
    - r-base
    - r-commonmark >=1.6
    - r-glue
    - r-magrittr
    - r-purrr
    - r-xml2
    - r-xslt
    - r-yaml

tests:
  - script:
      - if: win
        then: R -e \"library('tinkr')\""
        else: R -e "library('tinkr')"

about:
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: conversion from Markdown to XML and back again
  description: |
    Parsing '(R)Markdown' files with numerous regular expressions can be
    fraught with peril, but it does not have to be this way. Converting
    '(R)Markdown' files to 'XML' using the 'commonmark' package allows
    in-memory editing via of 'markdown' elements via 'XPath' through the
    extensible 'R6' class called 'yarn'. These modified 'XML' representations
    can be written to '(R)Markdown' documents via an 'xslt' stylesheet which
    implements an extended version of 'GitHub'-flavoured 'markdown' so that
    you can tinker to your hearts content.
  homepage: https://github.com/ropensci/tinkr/
  repository: https://github.com/ropensci/tinkr
  documentation: https://docs.ropensci.org/tinkr/

extra:
  recipe-maintainers:
    - matthewfeickert
    - zkamvar
