#!/usr/bin/env bash

# Expected to be run in a TravisCI context.

set -e

# Install Miniconda.
echo ""
echo "Installing a fresh version of Miniconda."
curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > ~/miniconda.sh
bash ~/miniconda.sh -b -p ~/miniconda
source ~/miniconda/bin/activate root

# Configure conda.
echo ""
echo "Configuring conda."
conda config --set show_channel_urls true
conda config --add channels conda-forge
conda install --yes --quiet conda-smithy github

if [ -n "$GH_TOKEN" ]; then
    mkdir -p ~/.conda-smithy && echo $GH_TOKEN > ~/.conda-smithy/github.token
    mkdir feedstocks && cd feedstocks
    python ../travis_scripts/update_all_tokens.py
fi

