schema_version: 1

context:
  version: 0.1.6

package:
  name: pynter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pynter/pynter-${{ version }}.tar.gz
  sha256: 5779e4352f74eeb7e3502406039be96e81e4986f44af6682e7968e9e6ea88f1e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - pillow

tests:
  - python:
      imports:
        - pynter
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Minimal utility for generating images with textual caption
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/GabrielePicco/pynter

extra:
  recipe-maintainers:
    - jan-janssen
