schema_version: 1

context:
  version: "1.99.0"
  python_min: "3.10"

package:
  name: nominal
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nominal/nominal-${{ version }}.tar.gz
  sha256: 114c51c7543acdf605c70c6153ab9eb36988ef71e61ebf949b5cce5ec18bab7b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - nom = nominal.cli:nom
      - nominal = nominal.cli:nom

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4
    - cachetools >=6.1.0
    - click >=8,<9
    - conjure-python-client >=3.1.0,<4
    - ffmpeg-python >=0.2.0
    - nominal-api ==0.1019.0
    - nominal-streaming ==0.5.8
    - openpyxl
    - pandas
    - polars
    - python-dateutil
    - pyyaml
    - requests
    - rich >=14.1.0
    - tabulate >=0.9.0,<0.10
    - types-cachetools >=6.0.0.20250525
    - typing_extensions >=4,<5

tests:
  - python:
      imports:
        - nominal
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - nominal --help
      - nom --help

about:
  summary: Automate Nominal workflows in Python
  license: MIT
  license_file: LICENSE
  homepage: https://nominal.io
  documentation: https://docs.nominal.io
  repository: https://github.com/nominal-io/nominal-client

extra:
  recipe-maintainers:
    - wolfv
