cmake -G "NMake Makefiles" ^
  -D CMAKE_BUILD_TYPE=Release ^
  -D CMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
  -D CMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
  -D SFML_DEPENDENCIES_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
  -D SFML_BUILD_EXAMPLES=OFF ^
  -D SFML_BUILD_DOC=OFF ^
  -D SFML_BUILD_AUDIO=ON ^
  -D SFML_BUILD_GRAPHICS=ON ^
  -D SFML_BUILD_WINDOW=ON ^
  -D SFML_BUILD_NETWORK=ON ^
  -D SFML_USE_SYSTEM_DEPS=ON ^
  %SRC_DIR%
if errorlevel 1 exit 1

nmake
if errorlevel 1 exit 1

nmake install
if errorlevel 1 exit 1
