# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: sema4ai-action-server
  version: "3.1.1"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sema4ai_action_server-${{ version }}.tar.gz
  sha256: 3927e8e99f16439563443e89c12a235f6efac17b71de0665c1f1a1ca20c9e3be

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - action-server = sema4ai.action_server.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<4
    - aiohttp >=3.13.2,<4.0.0
    - fastapi-slim >=0.121.1,<0.122.0
    - starlette >=0.40.0,<0.50.0
    - jsonschema >=4.23.0,<5.0.0
    - jsonschema-specifications >=2024.10.1,<2025.0.0
    - msgspec >=0.19.0,<0.20.0
    - psutil >=5.0,<8.0
    - pydantic >=2.12.4,<3.0.0
    - pyyaml >=6.0.3,<7.0.0
    - requests >=2.0.0,<3.0.0
    - sema4ai-actions >=1.6.4,<2.0.0
    - termcolor >=3.2.0,<4.0.0
    - uvicorn >=0.38.0,<0.39.0
    - websockets >=15.0.1,<16.0.0
    - cryptography >=46.0.3,<47.0.0
    - requests-oauthlib >=2.0.0,<3.0.0
    - watchfiles >=1.1.1,<2.0.0
    - sema4ai-common >=0.2.1,<0.3.0
    - mcp >=1.21.0,<2.0.0

tests:
  - python:
      imports:
        - sema4ai.action_server
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - action-server --help

about:
  summary: Sema4AI Action Server
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/sema4ai/actions/

extra:
  recipe-maintainers:
    - rxm7706
