{% set version = '1.2-0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-poolr
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/poolr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poolr/poolr_{{ version }}.tar.gz
  sha256: 8a0e5e5a99043be358a2bacb42d84633ccede3c15fa92f540898a154a6da0828

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mathjaxr
  run:
    - r-base
    - r-mathjaxr

test:
  commands:
    - $R -e "library('poolr')"           # [not win]
    - "\"%R%\" -e \"library('poolr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=poolr
  license: GPL-2.0-only
  summary: Functions for pooling/combining the results (i.e., p-values) from (dependent) hypothesis
    tests. Included are Fisher's method, Stouffer's method, the inverse chi-square method,
    the Bonferroni method, Tippett's method, and the binomial test. Each method can
    be adjusted based on an estimate of the effective number of tests or using empirically
    derived null distribution using pseudo replicates. For Fisher's, Stouffer's, and
    the inverse chi-square method, direct generalizations based on multivariate theory
    are also available (leading to Brown's method, Strube's method, and the generalized
    inverse chi-square method). An introduction can be found in Cinar and Viechtbauer
    (2022) <doi:10.18637/jss.v101.i01>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: poolr
# Version: 1.2-0
# Date: 2025-05-01
# Title: Methods for Pooling P-Values from (Dependent) Tests
# Authors@R: c(person("Ozan", "Cinar", email = "ozancinar86@gmail.com", role = c("aut","cre"), comment = c(ORCID = "0000-0003-0329-1977")), person("Wolfgang", "Viechtbauer", email = "wvb@wvbauer.com", role = "aut", comment = c(ORCID = "0000-0003-3463-4063")))
# Depends: R (>= 3.5.0)
# Imports: methods, stats, utils, mathjaxr
# Suggests: testthat
# RdMacros: mathjaxr
# Description: Functions for pooling/combining the results (i.e., p-values) from (dependent) hypothesis tests. Included are Fisher's method, Stouffer's method, the inverse chi-square method, the Bonferroni method, Tippett's method, and the binomial test. Each method can be adjusted based on an estimate of the effective number of tests or using empirically derived null distribution using pseudo replicates. For Fisher's, Stouffer's, and the inverse chi-square method, direct generalizations based on multivariate theory are also available (leading to Brown's method, Strube's method, and the generalized inverse chi-square method). An introduction can be found in Cinar and Viechtbauer (2022) <doi:10.18637/jss.v101.i01>.
# License: GPL (>= 2)
# ByteCompile: TRUE
# LazyData: TRUE
# Encoding: UTF-8
# BuildManual: TRUE
# NeedsCompilation: no
# Packaged: 2025-05-07 13:17:38 UTC; ozan
# Author: Ozan Cinar [aut, cre] (ORCID: <https://orcid.org/0000-0003-0329-1977>), Wolfgang Viechtbauer [aut] (ORCID: <https://orcid.org/0000-0003-3463-4063>)
# Maintainer: Ozan Cinar <ozancinar86@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-05-07 16:50:01 UTC
