{% set name = "sickle" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Sickle-{{ version }}.tar.gz
  sha256: 8944bcda3db0109a361248ef71fef476dd1f11109cdd1a41135527b7992b958b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - requests >=1.1.0
    - lxml >=3.2.3

test:
  imports:
    - sickle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: http://github.com/mloesch/sickle
  summary: A lightweight OAI client library for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IvoLeist
