{% set version = "2023.12.21" %}

package:
  name: oldest-supported-numpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/oldest-supported-numpy/oldest-supported-numpy-{{ version }}.tar.gz
  sha256: 71d89c31bb567814e47e2e268eb2e92b6f99f5ce76f4c3db30833624e9ef29e0

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy ==1.16.0  # [py==37 and aix]
    - numpy ==1.23.3  # [py==39 and os400]
    - numpy ==1.14.5  # [py==37 and not aix]
    - numpy ==1.21.0  # [py==37 and osx]
    - numpy ==1.21.0  # [py==38 and osx]
    - numpy ==1.21.0  # [py==39 and osx]
    - numpy ==1.22.2  # [py>=38 and py<311]
    - numpy ==1.14.5  # [py==37 and win]
    - numpy ==1.17.3  # [py==38 and win]
    - numpy ==1.19.3  # [py==39 and win]
    - numpy ==1.25.0  # [py==39]

test:
  imports:
    - oldest_supported_numpy
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/scipy/oldest-supported-numpy
  summary: Meta-package that provides the oldest NumPy that supports a given Python version and platform. If wheels for the platform became available on PyPI only for a more recent NumPy version, then that NumPy version is specified.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tcompa
