schema_version: 1

context:
  version: "1.2.0"

package:
  name: pystac-ext-table
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pystac-ext-table/pystac.extensions.table-${{ version }}.tar.gz
  sha256: c7035db662272a84f1149e7d694c8409f85093cc056cdc655c06e9b9f5cefe37

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pystac-core

tests:
  - python:
      imports:
        - pystac.extensions.table
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Table extension for PySTAC
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/pystac-ext-table/
  documentation: https://pystac.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
