schema_version: 1

context:
  version: "0.2.2"

package:
  name: tadasets
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tadasets/tadasets-${{ version }}.tar.gz
  sha256: 0be975f49d0f1e36539730215dba2389c68ecabfe08cdf1fb87edc2f26f8e3dc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
  run:
    - python >=${{ python_min }}
    - numpy
    - matplotlib-base

tests:
  - python:
      imports:
        - tadasets
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true
  - script:
      - python -c "import tadasets; assert tadasets.dsphere(n=10, d=2, seed=0).shape == (10, 3)"

about:
  homepage: https://tadasets.scikit-tda.org
  summary: Great data sets for Topological Data Analysis.
  description: |
    tadasets provides utilities for generating synthetic data sets with
    topological features useful in Topological Data Analysis.
  license: MIT
  license_file: LICENSE.txt
  documentation: https://tadasets.scikit-tda.org
  repository: https://github.com/scikit-tda/tadasets

extra:
  recipe-maintainers:
    - jmchilton
