{% set name = "skore-mlflow-project" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore_mlflow_project-{{ version }}.tar.gz
  sha256: e97aa781f405f5b1fe0517f9492969b4a15464311f4f123762ca7745187c4455

build:
  entry_points:
    - skore.plugins.project.mlflow = skore_mlflow_project:Project
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - joblib
    - mlflow
    - numpy
    - pandas
    - rich[jupyter] >=14.2
    - scikit-learn
    - matplotlib-base

test:
  imports:
    - skore_mlflow_project
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - rouk1
    - thomass-dev
    - tuscland
    - cakedev0
