schema_version: 1

context:
  python_min: "3.9"
  version: "0.1.9"

package:
  name: iterative-stratification
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/iterative-stratification/iterative_stratification-${{ version }}.tar.gz
  sha256: e7e299a3b28909fd0867d50ae6fc512def3bd482f71666ebaf0a3480b84cec42

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy
    - scikit-learn

tests:
  - python:
      imports:
        - iterstrat
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Package that provides scikit-learn compatible cross validators with stratification for multilabel data
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/trent-b/iterative-stratification

extra:
  recipe-maintainers:
    - guillaume-gricourt
