{% set name = "cpnest-bilby" %}
{% set version = "0.1.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cpnest_bilby-{{ version }}.tar.gz
  sha256: 0f2775f38fab16bb053b3f0e8921316d362f0c76ac0f2c41187e4ef8c2671a9f

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - bilby >=2.3.0
    - cpnest >=0.9.4
    - numpy >=1.18.0

test:
  imports:
    - cpnest_bilby
  commands:
    - pip check
    - python -m pytest tests/
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/bilby-dev/cpnest-bilby
  summary: Plugin for using cpnest with bilby.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mj-will
    - johnveitch
    - ColmTalbot
