#!/bin/bash
set -euxo pipefail

MODULE_NAME=calc
INSTALL_LOCATION="${PREFIX}/epics/modules/${MODULE_NAME}"

# Upstream gates swait (SSCAN) and editSseq (SNCSEQ) on configure/RELEASE; leave
# both undefined so this package depends only on epics-base.
cat > configure/CONFIG_SITE.local <<EOF
INSTALL_LOCATION=${INSTALL_LOCATION}
EOF

cat > configure/RELEASE <<EOF
# Generated by the calc conda build.
EPICS_BASE=${EPICS_BASE}
EOF

make -j"${CPU_COUNT:-2}" build
make runtests
make install

# Shared library only; static archives are not part of the conda-forge
# distribution (CFEP-18).
find "${INSTALL_LOCATION}/lib" -name '*.a' -delete
