schema_version: 1

context:
  version: "3.7.5"

package:
  name: calc
  version: ${{ version }}

source:
  url: https://github.com/epics-modules/calc/archive/refs/tags/R3-7-5.tar.gz
  sha256: 5cf1a7b3d444e763eb96ca5b9cdbcb9c29f5a6f9ac2b8d9cdb17a007d3fa8347

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - perl
  host:
    - epics-base
  run_exports:
    - ${{ pin_subpackage('calc', upper_bound='x.x.x') }}

tests:
  - script:
      - test -f ${PREFIX}/epics/modules/calc/dbd/calcSupport.dbd
      - test -f ${PREFIX}/epics/modules/calc/dbd/transformRecord.dbd
      - test -f ${PREFIX}/epics/modules/calc/dbd/sCalcoutRecord.dbd
      - test -f ${PREFIX}/epics/modules/calc/dbd/aCalcoutRecord.dbd
      - test -f ${PREFIX}/epics/modules/calc/dbd/sseqRecord.dbd
      - test -f ${PREFIX}/epics/modules/calc/include/sCalcPostfix.h
      - test -n "$(find ${PREFIX}/epics/modules/calc/lib -name 'libcalc.*')"
      - test ! -f ${PREFIX}/epics/modules/calc/dbd/swaitRecord.dbd
      - test ! -f ${PREFIX}/epics/modules/calc/dbd/editSseq.dbd

about:
  homepage: https://github.com/epics-modules/calc
  license: EPICS
  license_file: LICENSE
  summary: EPICS module for calculation records (calcout, transform, sseq)
  documentation: https://epics-modules.github.io/calc
  repository: https://github.com/epics-modules/calc

extra:
  recipe-maintainers:
    - anderslindho
