schema_version: 1

context:
  version: "3.0.0"

package:
  name: tango-takeoff
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tango-takeoff/tango_takeoff-${{ version }}.tar.gz
  sha256: f770b15fce376fc0dd706e0a4a3ecc84ef3b77a840d0b9777de8bccf0e2eb938

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - takeoff = takeoff.runner:run

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - pytango

tests:
  - python:
      imports:
        - takeoff
        - takeoff.runner
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - takeoff --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: A script that can find, start and stop Tango Device Server(s)
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/MaxIV/tools/tango-takeoff
  repository: https://gitlab.com/MaxIV/tools/tango-takeoff

extra:
  recipe-maintainers:
    - beenje
