context:
  version: "0.8.14"

package:
  name: toybox
  version: ${{ version }}

source:
  url: https://github.com/landley/toybox/archive/${{ version }}.tar.gz
  sha256: 082df8cfd76135ce3c4820c8cf4c0081d61491e0990aff2da48e21fc9bbb24d1

build:
  number: 0
  skip: win
  script:
    content:
      - if: osx
        then:
          - make macos_defconfig toybox HOSTCC="${CC}"
        else:
          - make defconfig toybox HOSTCC="${CC}"
      - install -D -m755 toybox "${PREFIX}/bin/toybox"

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - make
    - sed
    - uutils-coreutils
  host:
    - if: linux
      then: libxcrypt

tests:
  - script:
      - toybox --version
      - toybox --help
  - package_contents:
      strict: true
      bin:
        - toybox

about:
  homepage: https://landley.net/toybox/
  summary: all-in-one Linux command line.
  description: |
    all-in-one Linux command line.
  license: 0BSD
  license_file:
    - LICENSE
  repository: https://github.com/landley/toybox

extra:
  recipe-maintainers:
    - XhstormR
