schema_version: 1

context:
  version: "2026.3.3"

package:
  name: openeo-pg-parser-networkx
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/openeo-pg-parser-networkx/openeo_pg_parser_networkx-${{ version }}.tar.gz
  sha256: 16ef4c2691c3bdaa7aacbd6d9a519164231888e578813fd7962363baaffa5c17

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10,<3.15
    - poetry-core
    - pip
  run:
    - python >=3.10,<3.15
    - pydantic >=2.4.0,<3.0.0
    - pyproj >=3.4.0,<4.0
    - networkx >=3.0.0
    - geojson-pydantic >=1.0.0,<2.0.0
    - numpy >=1.20.3
    - pendulum >=3.0.0
    - traitlets <=5.14.4
    - yprov4wfs >=0.0.8
    - xarray >=2022.11.0
    - dask-core >=2023.4.0
  run_constraints:
    - matplotlib-base >=3.7.1,<4.0.0

tests:
  - python:
      imports:
        - openeo_pg_parser_networkx
      pip_check: true

about:
  summary: Parse OpenEO process graphs from JSON to traversible Python objects.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Open-EO/openeo-pg-parser-networkx

extra:
  recipe-maintainers:
    - martinRenou
