schema_version: 1

context:
  version: "0.1.5"

package:
  name: pyfcs
  version: ${{ version }}

source:
  url: https://github.com/OpenSMFS/pyFCS/archive/${{ version }}.tar.gz
  sha256: 847de6c0becfe8b82603a0fc5297d0089be8925891fa38c4ef88baf7acc82419

build:
  number: 0
  skip: match(python, "<3.10")
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy
  host:
    - python
    - setuptools >=77
    - setuptools-scm >=8.0
    - numpy
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - pyFCS
      pip_check: true

about:
  summary: Functions for performing auto and cross-correlations of single photon data with and without weights
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/OpenSMFS/pyFCS

extra:
  recipe-maintainers:
    - harripd
