context:
  version: "0.1.1"
  python_min: "3.12"

package:
  name: conda-pyproject-toml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/conda-pyproject-toml/conda_pyproject_toml-${{ version }}.tar.gz
  sha256: 02d3875ac666a72da3fe4423aa2817996133df01aff303072152591b1324d52d

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling >=1.26
    - pip
    - python ${{ python_min }}.*
  run:
    - conda >=26.9.1
    - grayskull >=3.2.0
    - python >=${{ python_min }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - conda_pyproject_toml
      pip_check: true
  - script:
      - conda plugins list | grep -q "conda-pyproject-toml"

about:
  homepage: https://github.com/m-rossi/conda-pyproject-toml
  summary: 'Conda plugin that installs dependencies from a pyproject.toml file.'
  license: MIT
  license_file: LICENSE
  repository: https://github.com/m-rossi/conda-pyproject-toml

extra:
  recipe-maintainers:
    - m-rossi
