schema_version: 1

context:
  version: "0.0.2"

package:
  name: microbenchmark
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/microbenchmark/microbenchmark-${{ version }}.tar.gz
  sha256: 93d9b8ce52090c2f4ab29dbe44f2f2f3fad4583440b8c81d333e9ef31ab75c49

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools ==68.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - printo >=0.0.22

tests:
  - python:
      imports:
        - microbenchmark
      pip_check: true
      python_version: 
        - ${{ python_min }}.*
        - "*"

about:
  summary: A minimal Python library for writing and running benchmarks.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mutating/microbenchmark

extra:
  recipe-maintainers:
    - thewchan
