context:
  name: ckmseed
  version: "1.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://gitlab.com/earthscope/public/epic/passoft/ckMseed/-/archive/v${{ version }}/ckMseed-v${{ version }}.tar.gz
  sha256: aaf6f3366cb0ab27657a3cfb31a514acab9702cd1f3fb186ba3958845312eb60

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  python:
    entry_points:
      - ckmseed = ckMseed.ckMseed:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pyside6

tests:
  - python:
      imports:
        - ckMseed
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - ckmseed -h
  - script:
      - python -m unittest discover -s tests
    requirements:
      run:
        - python ${{ python_min }}.*
    files:
      source:
        - tests/

about:
  homepage: https://epic.earthscope.org/content/software-resources
  summary: Find and review MSEED files
  description: |
    Find and review MSEED files with a graphical interface.
  license: GPL-3.0-or-later
  license_file: LICENSE
  repository: https://gitlab.com/earthscope/public/epic/passoft/ckMseed

extra:
  recipe-maintainers:
    - omid-earthscope
