context:
  version: "0.0.11"

package:
  name: iamb
  version: ${{ version }}

source:
  url: https://github.com/ulyssa/iamb/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a5cf4f248e0893b5657c5ad1234207c09968018c5462d4063c096f0db459dd7c

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: iamb --help
  - package_contents:
      bin:
        - iamb
      strict: true

about:
  homepage: https://iamb.chat/
  summary: 'A Matrix client for Vim addicts'
  description: |
      iamb is a terminal-based client for Matrix for the Vim addict.
      You can edit messages, navigate windows and manage tabs
      in the same ways that your fingers are used to from your favorite text editor!
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://iamb.chat/
  repository: https://github.com/ulyssa/iamb

extra:
  recipe-maintainers:
    - phreed
