schema_version: 1

context:
  python_min: "3.11"
  version: "0.16.0"

package:
  name: oac
  version: ${{ version }}

source:
  url: https://github.com/dlr-pa/oac/archive/v${{ version }}.tar.gz
  sha256: 7f6845fcd24ba22b0f90016b315b9146c6d5ea0f802a45577a65260fc26e0caf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools
    - joblib
    - numpy
    - pandas
    - toml
    - matplotlib-base
    - cf-units
    - xarray
    - netcdf4
    - scipy
    - deepmerge
    - ambiance

tests:
  - python:
      imports:
        - openairclim
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: OpenAirClim is a model for simplified evaluation of the approximate chemistry-climate impact of air traffic emissions.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/dlr-pa/oac

extra:
  recipe-maintainers:
    - ocefpaf
