context:
  version: "0.0.1"
  python_min: "3.11"

package:
  name: easyimaging
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/easyimaging/easyimaging-${{ version }}.tar.gz
  sha256: a0542a37a922ae6131cb2cd9dcc7ad7d2650e22f1b5e5d3bab768d96d536ef73 

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling <=1.21.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - easyscience >=2.2.0
    - scitiff
    - essimaging
    - plopp
    - ncrystal

tests:
  - python:
      imports:
        - easyimaging
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python package for bragg-edge analysis
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/easyscience/imaging-lib/

extra:
  recipe-maintainers:
    - MridulS
