#!/usr/bin/env bash
set -euxo pipefail

# Generate a simple spherical Fermi surface with a known 1 kT frequency
printf '%s\n' \
    4.0 \
    20 \
    1.0 \
    1.0 \
    0.0 \
    | simbxsf_sphere

test -s simulated.bxsf
grep -q "BEGIN_BLOCK_BANDGRID_3D" simulated.bxsf
grep -q "END_BLOCK_BANDGRID_3D" simulated.bxsf

# Read the Fermi energy generated by simbxsf_sphere
fermi_energy=$(awk '/Fermi Energy:/ {print $3}' simulated.bxsf)

cat > config.in <<EOF
simulated.bxsf
${fermi_energy}
50
0.0
0.0
c
0.0
0.01
0.05
n
0.0
0.0
0.0
0.0
1
EOF

# Run an actual SKEAF extremal-area calculation
# Skip DOS to keep the test focused and reasonably quick
export OMP_NUM_THREADS=2
skeaf -rdcfg -nodos

test -s results_short.out
test -s results_long.out

# Check that the calculated dHvA frequency is within 5% of the expected value of 1 kT
freq=$(awk '/Freq\. =/ {
    split($3, value, "+/-")
    print value[1]
    exit
}' results_short.out)

awk -v freq="$freq" 'BEGIN {
    if (freq < 0.95 || freq > 1.05) {
        print "Unexpected dHvA frequency:", freq, "kT"
        exit 1
    }
    print "Calculated dHvA frequency:", freq, "kT"
}'
