--- makefile    2020-06-03 13:15:56.267331987 +0100
+++ makefile    2020-06-03 13:15:37.639335523 +0100
@@ -1,6 +1,4 @@
 INCLUDES= -I ./rilib/ -I ./include/
-CC=g++
-CFLAGS=-c -O3

 SOURCES= ri3.cpp
 OBJECTS=$(SOURCES:.cpp=.o)
@@ -10,7 +8,7 @@
 all:	$(SOURCES) $(EXECUTABLE)

 $(EXECUTABLE): $(OBJECTS)
-	$(CC) $(OBJECTS) -o $@
+	$(CXX) $(LDFLAGS) $(OBJECTS) -o $@

 .cpp.o:
-	$(CC) $(CFLAGS) $< $(INCLUDES) -o $@  
+	$(CXX) -c $(CFLAGS) $< $(INCLUDES) -o $@
