schema_version: 1

context:
  version: 0.3.7

package:
  name: pyfvs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyfvs/pyfvs-${{ version }}.tar.gz
  sha256: 43afe8edd712a5e76c261a047c8329ebc554dffa60b3de568beee068f485c639

build:
  number: 0
  skip: match(python, "<3.10")
  script:
    env:
      variants: "pn,wc,so,op,oc,ec,ca,nc,bm,ie,ci,ak,ws"
      mode: "release"
  python:
    entry_points:
      - pyfvs = pyfvs.__main__:cli

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
  host:
    - python >=3.10
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
    - meson
    - meson-python >=0.20.0
    - numpy
    - ninja
    - if: linux
      then: patchelf
    - python-build
    - pip
  run:
    - python >=3.10
    - confuse
    - click
    - pandas
    - numpy
    - typing_extensions

tests:
  - python:
      imports:
        - pyfvs
      pip_check: true
  - requirements:
      run:
        - pip
        - python
    script:
      - pyfvs --help

about:
  summary: Python wrappers and utilities for using the Forest Vegetation Simulator
  license: MIT AND ISO-permission
  license_file:
    - LICENSE
    - fvs/license.txt
  homepage: https://pypi.org/project/pyfvs/

extra:
  recipe-maintainers:
    - tharen