context:
  version: "0.10.5"

package:
  name: libraqm
  version: ${{ version }}

source:
  url: https://github.com/HOST-Oman/libraqm/releases/download/v${{ version }}/raqm-${{ version }}.tar.xz
  sha256: 563053e724892a7b037913110ea2daef50ad575d4fa9f7c368ae1e4515f5e856

build:
  number: 0
  script: build

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - meson
    - ninja
  host:
    - freetype
    - fribidi
    - harfbuzz
  run_exports:
    - ${{ pin_subpackage("libraqm", upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - raqm.h
      lib:
        - raqm

about:
  homepage: https://github.com/HOST-Oman/libraqm
  summary: 'A library for complex text layout'
  license: MIT
  license_file: COPYING
  repository: https://github.com/HOST-Oman/libraqm

extra:
  recipe-maintainers:
    - h-vetinari
