{% set version = "2026.5.20" %}
{% set python_min = "3.10" %}

package:
  name: radclss
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/radclss/radclss-{{ version }}.tar.gz
  sha256: dfda9ecfc842eb108864444a0f879eb789a5b1b66521774e534d1968a55d37b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python
    - pip
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numpy <2.4.0
  run:
    - python >={{ python_min }}
    - act-atmos
    - arm_pyart
    - numpy <2.4.0
    - xarray
    - pandas
    - matplotlib-base
    - pip
    - boto3
    - xradar
    - dask
    
test:
  requires:
    - python {{ python_min }}
    - pytest
    - arm_pyart
    - pip
  source_files:
    - tests/
  imports:
    - radclss
  commands:
    - pytest tests/test_column_utils.py tests/test_config.py

about:
  home: https://github.com/ARM-Development/radclss
  summary: 'Radar Columns and In Situ Sensors'
  description: |
    RADclss is a utility for developing vertical columns from CF/Radial compliant radar scans, co-located with ARM ground based instruments. 
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcjackson
