# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.8.0"

package:
  name: django-ai-boost
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/django-ai-boost/django_ai_boost-${{ version }}.tar.gz
  sha256: 881c073edf0ae4ee6eca6ed961ce6c54f020eb4662ca7bc2a5638a1edb727b5d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - django-ai-boost = django_ai_boost:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2
    - fastmcp >=2.14.5
    - joserfc

tests:
  - python:
      imports:
        - django_ai_boost
      pip_check: true
      python_version:
      - ${{ python_min }}
      - "*"
  - requirements:
      run:
        - pip
        - python
    script:
      - django-ai-boost --help

about:
  summary: A Model Context Protocol (MCP) server for Django applications, inspired by Laravel Boost
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vintasoftware/django-ai-boost

extra:
  recipe-maintainers:
    - rxm7706
