context:
  version: "0.8.2"

package:
  name: veccore
  version: ${{ version }}

source:
  url: https://github.com/root-project/veccore/archive/v${{ version }}.tar.gz
  sha256: 1268bca92acf00acd9775f1e79a2da7b1d902733d17e283e0dd5e02c41ac9666

build:
  script:
    - cmake -S . -B build -G Ninja -DVC=ON -DUMESIMD=OFF -DCUDA=OFF -DBUILD_TESTING=ON -DBUILD_BENCHMARKS=OFF -DBUILD_VC=OFF -DBUILD_UMESIMD=OFF ${CXX_STANDARD_CMAKE_FLAG} ${CMAKE_ARGS}
    - ninja -C build -j${CPU_COUNT} && ctest --test-dir build --output-on-failure
    - ninja -C build install
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - gtest
    - ninja
  host:
    - vector-classes

tests:
  - package_contents:
      include:
        - VecCore/*
      files:
        - lib/cmake/VecCore/*
      strict: true

about:
  homepage: https://github.com/root-project/veccore
  summary: 'An abstraction layer on top of other vectorization libraries - VecCore'
  description: |
    VecCore is a simple abstraction layer on top of other vectorization libraries. It provides an
    architecture-independent API for expressing vector operations on data. Code written with this API can
    then be dispatched to one of several backends implemented using libraries like Vc, UME::SIMD, or a
    scalar implementation.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://root-project.github.io/veccore/docs/latest/index.html
  repository: https://github.com/root-project/veccore

extra:
  recipe-maintainers:
    - utk4r-sh
    - GiacomoXT
    - vvsagar
    - AlexanderHeidelbach
