{% set version = "1.7.5" %}

package:
  name: openmeteo_requests
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openmeteo_requests/openmeteo_requests-{{ version }}.tar.gz
  sha256: 5557b5df957aa00f5e673d85ddc47f8b5bcadde6c72a98c0ec1999b538db39f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - niquests >=3.15.2
    - openmeteo-sdk >=1.22.0

test:
  imports:
    - openmeteo_requests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/openmeteo-requests/
  summary: Open-Meteo Python Library
  doc_url: https://github.com/open-meteo/python-requests/tree/main
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - akrherz
