#!/bin/bash
set -ex

export CC=mpicc
export CXX=mpicxx
export FC=mpifort

cd ${SRC_DIR}/nektar

mkdir build && cd build

cmake ${CMAKE_ARGS} .. \
  -DNEKTAR_BUILD_LIBRARY=ON \
  -DNEKTAR_BUILD_SOLVERS=ON \
  -DNEKTAR_BUILD_UTILITIES=ON \
  -DNEKTAR_BUILD_TESTS=OFF \
  -DNEKTAR_BUILD_UNIT_TESTS=OFF \
  -DNEKTAR_USE_MPI=ON \
  -DNEKTAR_USE_FFTW=ON \
  -DNEKTAR_USE_SCOTCH=ON \
  -DNEKTAR_USE_ARPACK=ON \
  -DNEKTAR_USE_HDF5=ON \
  -DTHIRDPARTY_BUILD_GSMPI=ON \
  -DTHIRDPARTY_BUILD_XXT=ON \
  -DTHIRDPARTY_BUILD_FFTW=OFF \
  -DTHIRDPARTY_BUILD_SCOTCH=ON \
  -DTHIRDPARTY_BUILD_ARPACK=OFF \
  -DTHIRDPARTY_BUILD_HDF5=ON \
  -DTHIRDPARTY_BUILD_TINYXML=OFF \
  -DNEKTAR_USE_SYSTEM_BLAS_LAPACK=ON

make -j${CPU_COUNT}
make install
