schema_version: 1

context:
  name: cosma
  version: "2.8.4"
  mpi_prefix: "mpi_${{ mpi }}"

package:
  name: ${{ name|lower }}-scalapack
  version: ${{ version }}

source:
  - url: https://github.com/eth-cscs/${{ name | upper }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: b478cc239a99baf6fdf889d123308a6b01a4521330bdb3f4def457feb0f7dfa0

build:
  number: 0
  script: build.sh
  string: mpi_${{ mpi }}_h${{ hash }}_${{ build_number }}
  skip:
    - win64

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("fortran") }}
    - ${{ mpi }}
    - cmake >=3.24
    - ninja >=1.13
    - pkg-config
  host:
    - ${{ mpi }}
    - "costa-scalapack * *${{ mpi_prefix }}_*"
    - "openblas * *openmp_*"
    - scalapack
  run:
    - ${{ mpi }}
    - "costa-scalapack * *${{ mpi_prefix }}_*"
    - "openblas * *openmp_*"
    - scalapack

tests:
  - package_contents:
      lib:
        - cosma
        - cosma_prefixed_pxgemm
        - cosma_pxgemm
        - cosma_pxgemm_cpp

about:
  homepage: https://github.com/eth-cscs/COSMA
  license: BSD-3-Clause
  license_family: BSD 
  license_file: LICENSE
  summary: Communication-Optimal Matrix-Multiplication (COSMA)
  description: |
    COSMA is a parallel, high-performance, GPU-accelerated, matrix-matrix multiplication algorithm
    that is communication-optimal for all combinations of matrix dimensions, number of processors
    and memory sizes, without the need for any parameter tuning. The key idea behind COSMA is to
    first derive a tight optimal sequential schedule and only then parallelize it, preserving I/O
    optimality between processes. This stands in contrast with the 2D and 3D algorithms, which fix
    process domain decomposition upfront and then map it to the matrix dimensions, which may result
    in asymptotically more communication. The final design of COSMA facilitates the overlap of
    computation and communication, ensuring speedups and applicability of modern mechanisms such as
    RDMA. COSMA allows to not utilize some processors in order to optimize the processor grid, which
    reduces the communication volume even further and increases the computation volume per processor.
  documentation: https://github.com/eth-cscs/COSMA
  repository: hhttps://github.com/eth-cscs/COSMA

extra:
  recipe-maintainers:
    - mkrack
