context:
  version: "0.4.3"

package:
  name: python-graphql-client
  version: ${{ version }}

source:
  # url: https://pypi.org/packages/source/p/python-graphql-client/python_graphql_client-${{ version }}.tar.gz
  url: https://github.com/prodigyeducation/python-graphql-client/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ba8a83f6ee6ae1d6e0b5f5d3a839d4271a7d50cbca0b9fd994d66096e4d30851

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=${{ python_min }}
    - setuptools
  run:
    - aiohttp >=3,<4
    - requests >=2,<3
    - python ${{ python_min }}.*
    - websockets >=5

tests:
  - python:
      imports:
      - python_graphql_client
      pip_check: true

about:
  homepage: https://github.com/prodigyeducation/python-graphql-client
  summary: 'Simple module for making requests to a graphQL server in python.'
  description: |
    Simple module for making requests to a graphQL server in python.
  license: MIT
  license_file: LICENSE
  documentation: https://pypi.org/project/python-graphql-client/
  repository: https://github.com/prodigyeducation/python-graphql-client

extra:
  recipe-maintainers:
    - MementoRC
