#!/bin/bash
pkg=$1
# Get the current versions of a package's installed dependencies
# get dist_name for the package so we can find it's json file
pkg_dist_name=$(conda list --json | jq -r '.[] | select(.name=="'${pkg}'") | .dist_name')
# get dependencies in the form of a regex
name_regex=$(jq -r '.depends | map(. | split(" ")[0]) | join("$|")' ${CONDA_PREFIX}/conda-meta/${pkg_dist_name}.json)
# print list of dependency=version for installed dependencies
conda list --json | jq -r '.[] | select(.name | match("'${name_regex}'")) | "\(.name)=\(.version)"'

