context:
  name: spaceprime
  version: "0.0.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 959c2385fa13fce8e24e712aab8d61db55beea1ee5cea2691b1a324be7935eeb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling >=1.12.0
  run:
    - python >=3.10
    - numpy
    - msprime
    - rasterio >=1.0.0
    - scipy
    - shapely
    - geopandas
    - scikit-allel
    - contextily
    - matplotlib-base
    - folium
    - mapclassify
    - esda >=2.5.1
    - libpysal >=4.10
    - scikit-learn
    - pandas

tests:
  - python:
      imports:
        - spaceprime
      pip_check: true

about:
  homepage: https://github.com/connor-french/spaceprime
  summary: A python package to facilitate spatially explicit coalescent modeling in msprime
  license: MIT
  license_file: LICENSE
  documentation: https://connor-french.github.io/spaceprime
  repository: https://github.com/connor-french/spaceprime

extra:
  recipe-maintainers:
    - connor-french
