context:
  version: "0.20.0"
  python_min: "3.10"

package:
  name: pylangacq
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pylangacq/pylangacq-${{ version }}.tar.gz
  sha256: 1325db9b32b6ae55ffa189dd12cbb2f414bdd9a95e80af6206873ac65a4177fa

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python >= ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >= ${{ python_min }}
    - rustling >= 0.5.0

tests:
  - python:
      imports:
        - pylangacq
      pip_check: true

about:
  homepage: https://pylangacq.org
  summary: Language Acquisition Research in Python
  license: MIT
  license_file: LICENSE.txt
  documentation: https://pylangacq.org
  repository: https://github.com/jacksonllee/pylangacq

extra:
  recipe-maintainers:
    - jacksonllee
