schema_version: 1

context:
  version: "1.1.0"

package:
  name: tree-sitter-kotlin
  version: ${{ version }}

source:
  url: https://github.com/tree-sitter-grammars/tree-sitter-kotlin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3c36bd5627fff38e4323ebead1f7e86e6d1727f0353618d1c976fea88260ba90

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("c") }}
  host:
    - python
    - pip
    - setuptools >=42
  run:
    - python

tests:
  - python:
      imports:
        - tree_sitter_kotlin

about:
  homepage: https://github.com/tree-sitter-grammars/tree-sitter-kotlin
  summary: Kotlin grammar for tree-sitter
  license: MIT
  license_file: LICENSE
  repository: https://github.com/tree-sitter-grammars/tree-sitter-kotlin

extra:
  recipe-maintainers:
    - killua156
    - mgorny
