{% set version = "3.5.0" %}

package:
  name: stac-pydantic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/stac-pydantic/stac_pydantic-{{ version }}.tar.gz
  sha256: 0d70f4e9d0754842a0bfd04c06e41a41af04f313de94b6dfe06c98b6c5eea4fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - stac-pydantic = stac_pydantic.scripts.cli:app

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - click >=8.1.7
    - pydantic >=2.4.1
    - geojson-pydantic >=1.0.0
test:
  imports:
    - stac_pydantic
  commands:
    - pip check
    - stac-pydantic --help
  requires:
    - pip
    - python {{ python_min }}
    - requests

about:
  home: https://github.com/CS-SI/stac-pydantic
  summary: Pydantic data models for the STAC spec
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gadomski
    - sbrunato
