# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: torchcodec
  version: "0.2.1"
  build_number: 0
  torch_proc_type: ${{ "cuda" ~ cuda_compiler_version | version_to_buildstring if cuda_compiler_version != "None" else "cpu" }}
  string_prefix: ${{ cuda_build_string if cuda ==  "true" else "cpu_" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/pytorch/torchcodec/archive/refs/tags/v${{ version }}.tar.gz
    sha256: b142ef4fef1e9ddb6dde70dda6ac4d12a02a010065230468eadbf37478621927

build:
  number: ${{ build_number }}
  skip: cuda_compiler_version == "11.8"
  string: ${{ torch_proc_type }}_py${{ python | version_to_buildstring }}_h${{ hash }}_${{ build_number }}
  script:
    file: build

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pytorch
        - if: cuda_compiler_version != "None"
          then:
            - cuda-driver-dev
            - cuda-cudart-dev
            - cuda-nvrtc-dev
            - cuda-nvtx-dev
            - cuda-nvml-dev
            - cuda-profiler-api
            - libcublas-dev
            - libcufft-dev
            - libcurand-dev
            - libcusolver-dev
            - libcusparse-dev
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: cuda_compiler_version != "None"
      then:
        - ${{ compiler('cuda') }}
    - cmake
    - ninja


  host:
    - python
    - pip
    - setuptools
    - ffmpeg
    - libtorch
    - libtorch * [build=${{ torch_proc_type }}*]
    - pytorch
    - pytorch * [build=${{ torch_proc_type }}*]

    - if: cuda_compiler_version != "None"
      then:
        # These are transitive dependency of the libtorch cuda package
        - cuda-driver-dev
        - cuda-cudart-dev
        - cuda-nvrtc-dev
        - cuda-nvtx-dev
        - cuda-nvml-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcufft-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        - magma
        - nccl
        - nvtx-c
        - zlib
        # These are actual torchcodec deps
        - libnpp-dev
  run:
    - python
    - pytorch * [build=${{ torch_proc_type }}*]


tests:
  - python:
      imports:
        - torchcodec
      pip_check: true

  - requirements:
      run:
        - pytest
        - numpy
        - pillow
        - torchvision
    files:
      source:
        - test/
    script:
      - pytest test

about:
  homepage: https://github.com/pytorch/torchcodec
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: TorchCodec is a Python library for decoding videos into PyTorch tensors, on CPU and CUDA GPU. 

extra:
  recipe-maintainers:
    - traversaro
