= node-red
:version: 4.1.0


// GENERATED CONTENT START

Low-code programming for event-driven applications

== Description

Node-RED's goal is to enable anyone to build applications that collect, transform and visualize their data; building flows that can automate their world. Its low-code nature makes it accessible to users of any background, whether for home automation, industrial control systems or anything in between.

== Links

* Homepage: https://nodered.org
* Repository: https://github.com/node-red/node-red
* Documentation: https://nodered.org/docs/

== Package Information

* **License**: Apache-2.0
* **Version**: 4.1.0

== Requirements

=== Host Requirements

* nodejs
* grunt

=== Run Requirements

* nodejs

=== Build Requirements

* nushell
* nodejs

== Installation

This package is built using rattler-build and can be installed using mamba or conda:

[source,bash]
----
pixi global install -c meso-forge node-red
----

== Maintainers

* phreed

---

_This portion of the README was generated from the recipe.yaml file._

_Last updated: 2025-06-11_

// GENERATED CONTENT END

`node-red` is an nodejs package.

https://nodered.org/docs/getting-started/development

https://github.com/conda-forge/grunt-feedstock
https://docs.npmjs.com/about-the-public-npm-registry

== V1 recipe format

https://github.com/prefix-dev/recipe-format
