{% set version = "1.0.2" %}
{% set python_min = "3.9" %}

package:
  name: fracsim
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fracsim/fracsim-{{ version }}.tar.gz
  sha256: 9b44d02819095e6e5cf781072b8915f9f373a2d495412d7f57dfe83e4636ba85

build:
  entry_points:
    - fracsim=fracsim.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
  run:
    - python >={{ python_min }}
    - mmh3 >=4.0.0
    - numpy >=1.21.0
    - pytest >=7.0.0
    - pytest-cov >=4.0.0

test:
  imports:
    - fracsim
  commands:
    - pip check
    - fracsim --help
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/zhuyu534/FracSim.git
  summary: a FracMinHash-based genome similarity estimator for bacteria
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
