schema_version: 1

context:
  version: "1.0.2"
  python_min: "3.8"

package:
  name: fracsim
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fracsim/fracsim-${{ version }}.tar.gz
  sha256: 9b44d02819095e6e5cf781072b8915f9f373a2d495412d7f57dfe83e4636ba85

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - fracsim = fracsim.main:main
  run_exports:
    - ${{ pin_subpackage('fracsim', max_pin='x.x') }}

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - mmh3 >=4.0.0
  run:
    - python >=${{ python_min }}
    - mmh3 >=4.0.0

test:
  imports:
    - fracsim
  commands:
    - fracsim --help
  requires:
    - pip

about:
  summary: a FracMinHash-based genome similarity estimator for bacteria
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/zhuyu534/FracSim

extra:
  recipe-maintainers:
    - zhuyu534