{% set name = "pyozwald" %}
{% set version = "0.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyozwald/pyozwald-{{ version }}.tar.gz
  sha256: 6ea218765bc94064e7ad4a13c87bfc024bbb6c8a66de91291a59a0b97364db00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
    - wheel
  run:
    - python >={{ python_min }}
    - troi-core
    - attrs
    - typing_extensions
    - pandas
    - xarray
    - netcdf4

test:
  imports:
    - pyozwald
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thestochasticman/pyozwald
  summary: Machine-wide cache of OzWALD meteorology and 8-day biophysical series
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thestochasticman
    - johnburley3000
