context:
  version: "3.0.9"

package:
  name: xmake
  version: ${{ version }}

source:
  git: https://github.com/xmake-io/xmake.git
  tag: v${{ version }}
  patches:
    - 0001-use-system-lua-lz4-and-tbox.patch
    - 0002-support-conda-clang-on-windows.patch
    - 0003-detect-conda-libraries-on-windows.patch
    - 0004-use-msvc-names-for-internal-libraries.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - if: unix
      then:
        - ninja
    - if: win
      then:
        - autotools_clang_conda
        - m2-sed
  host:
    - lua 5.4.*
    - lz4-c
    - tbox ==1.8.0 *_2
    - if: unix
      then:
        - ncurses
        - readline
  run:
    - lua >=5.4,<5.5.0a0
    - tbox ==1.8.0 *_2

tests:
  - script:
      - xmake --version
      - xrepo --version

about:
  homepage: https://xmake.io
  summary: A cross-platform build utility based on Lua
  description: |
    XMake is a lightweight, cross-platform build utility based on Lua. It uses
    xmake.lua files to describe project builds and includes a built-in package
    manager for C and C++ dependencies.
  license: Apache-2.0 AND Unlicense AND BSD-2-Clause
  license_file:
    - LICENSE.md
    - NOTICE.md
    - core/src/sv/sv/UNLICENSE
    - core/src/xxhash/xxhash/LICENSE
  documentation: https://xmake.io/guide/
  repository: https://github.com/xmake-io/xmake

extra:
  recipe-maintainers:
    - luadebug
