{% set name = "tensorvid" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fa793438cf2581736b1e28cd81c056f625641677f5f0d34ef287c5bfe7f2dc9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - pkg-config
  host:
    - python
    - pip
    - maturin >=1.4.0
    - ffmpeg >=6.0
  run:
    - python
    - torch
    - numpy

test:
  imports:
    - tensorvid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chedetinaveen/tensorvid
  summary: Zero-copy hardware-accelerated video decoding to PyTorch tensors.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chedetinaveen
