#!/usr/bin/env bash
set -euxo pipefail

# XIOS is built by FCM through ./make_xios, which is configured entirely by an
# "arch" triplet: arch-<NAME>.env (shell setup), arch-<NAME>.path (library
# search paths) and arch-<NAME>.fcm (compilers and flags). We generate an
# arch-CONDA pointing at $PREFIX. This mirrors the arch-SPACK generated by the
# Spack recipe in ickc/lfric-env-isambard.
ARCH=CONDA

# Nothing to source: the conda build environment is already activated.
: > "arch/arch-${ARCH}.env"

# netCDF and HDF5 both live in $PREFIX. XIOS wants the *parallel* netCDF, which
# is what the mpi_${mpi}_* host builds provide.
cat > "arch/arch-${ARCH}.path" <<EOF
NETCDF_INCDIR="-I ${PREFIX}/include"
NETCDF_LIBDIR="-L ${PREFIX}/lib"
NETCDF_LIB="-lnetcdff -lnetcdf"

MPI_INCDIR=""
MPI_LIBDIR=""
MPI_LIB=""

HDF5_INCDIR="-I ${PREFIX}/include"
HDF5_LIBDIR="-L ${PREFIX}/lib"
HDF5_LIB="-lhdf5_hl -lhdf5"

OASIS_INCDIR=""
OASIS_LIBDIR=""
OASIS_LIB=""
EOF

# The LINKER is mpif90 (gfortran), which does not auto-link the C++ runtime that
# XIOS's C++ objects and blitz need, so the arch file adds it explicitly. Which
# runtime depends on the platform's C++ toolchain: GNU libstdc++ on linux, LLVM
# libc++ on macOS (conda-forge's osx C/C++ compiler is clang). Forcing -lstdc++
# on osx would fail -- there is no libstdc++ in the clang toolchain there.
case "${target_platform:-$(uname -s)}" in
  osx-*|Darwin) CXX_RT_LIB="-lc++" ;;
  *)            CXX_RT_LIB="-lstdc++" ;;
esac

# Boost and Blitz++ headers are both under $PREFIX/include, so one -I covers the
# two -I flags the Spack recipe emits separately.
#
# NOTE: upstream's and Spack's arch files pass -D_GLIBCXX_USE_CXX11_ABI=0. That
# is deliberately NOT carried over: conda-forge builds libstdc++ and boost with
# the new C++11 string/list ABI, so forcing the old one here would produce
# undefined references against the very libraries we link.
cat > "arch/arch-${ARCH}.fcm" <<EOF
%CCOMPILER      mpic++
%FCOMPILER      mpif90
%LINKER         mpif90

%BASE_CFLAGS    -std=c++14 -w -I${PREFIX}/include
%PROD_CFLAGS    -O3 -DBOOST_DISABLE_ASSERTS
%DEV_CFLAGS     -g -O2
%DEBUG_CFLAGS   -g

%BASE_FFLAGS    -D__NONE__ -ffree-line-length-none
%PROD_FFLAGS    -O3
%DEV_FFLAGS     -g -O2
%DEBUG_FFLAGS   -g

%BASE_INC       -D__NONE__
%BASE_LD        -L${PREFIX}/lib -lblitz ${CXX_RT_LIB}

%CPP            mpicc -E
%FPP            mpicc -E -P -x c
%MAKE           make
EOF

# make_xios drives the compilers through these, so point them at the MPI wrappers.
export CC=mpicc
export CXX=mpic++
export FC=mpif90
export F77=mpif90

./make_xios \
  --full \
  --prod \
  --arch "${ARCH}" \
  --use_extern_boost \
  --use_extern_blitz \
  --netcdf_lib netcdf4_par \
  --job "${CPU_COUNT:-2}"

# XIOS has no install target; place the build products by hand.
#   bin  xios_server.exe and the test drivers
#   lib  libxios.a
#   inc  the Fortran .mod files LFRic compiles against
mkdir -p "${PREFIX}/bin" "${PREFIX}/lib" "${PREFIX}/include"
cp -a bin/. "${PREFIX}/bin/"
cp -a lib/. "${PREFIX}/lib/"
cp -a inc/. "${PREFIX}/include/"

# etc/ and cfg/ are XML configuration templates, not libraries or config that
# conda should own at the top of $PREFIX -- keep them under share/.
for d in etc cfg; do
  if [ -d "$d" ]; then
    mkdir -p "${PREFIX}/share/xios/${d}"
    cp -a "$d/." "${PREFIX}/share/xios/${d}/"
  fi
done
