diff --git a/Makefile b/Makefile
index aaae785..1af095b 100644
--- a/Makefile
+++ b/Makefile
@@ -12,10 +12,10 @@ BIN = $(SEEDALGN)/bin
 
 #compiler options
 #CPP = x86_64-w64-mingw32-g++-win32
-CPP = g++
-CPPFLAGS = -O3 -ffast-math -Wall -Wextra -DNDEBUG -m64
+#CPP = g++
+#CPPFLAGS = -O3 -ffast-math -Wall -Wextra -DNDEBUG -m64
 #CPPFLAGS=-O0 -ggdb
-LDFLAGS =  
+LDFLAGS =
 .cpp.o:
 	$(CPP) $(CPPFLAGS) -c -o $@ $<
 
