diff --git a/Makefile b/Makefile
index aaae785..418eaba 100644
--- a/Makefile
+++ b/Makefile
@@ -12,12 +12,12 @@ BIN = $(SEEDALGN)/bin
 
 #compiler options
 #CPP = x86_64-w64-mingw32-g++-win32
-CPP = g++
-CPPFLAGS = -O3 -ffast-math -Wall -Wextra -DNDEBUG -m64
+#CPP = g++
+#CPPFLAGS = -O3 -ffast-math -Wall -Wextra -DNDEBUG -m64
 #CPPFLAGS=-O0 -ggdb
-LDFLAGS =  
+LDFLAGS =
 .cpp.o:
-	$(CPP) $(CPPFLAGS) -c -o $@ $<
+	$(CXX) $(CXXFLAGS) -c -o $@ $<
 
 #macros
 OBJECTS =    $(OBJ)/cmdLineParser.o\
@@ -42,53 +42,53 @@ all: $(ALL)
 
 
 #------------------------------------------------------------------------------
-$(BIN)/mmligner: $(OBJECTS) 
-	$(CPP) $(CPPFLAGS)  $(LDFLAGS) -o $@ $(OBJECTS)
+$(BIN)/mmligner: $(OBJECTS)
+	$(CXX) $(CXXFLAGS)  $(LDFLAGS) -o $@ $(OBJECTS)
 
-$(OBJ)/cmdLineParser.o: $(SRC)/cmdLineParser.h $(SRC)/cmdLineParser.cpp 
-		$(CPP) $(CPPFLAGS) -c $(SRC)/cmdLineParser.cpp -o $(OBJ)/cmdLineParser.o
+$(OBJ)/cmdLineParser.o: $(SRC)/cmdLineParser.h $(SRC)/cmdLineParser.cpp
+		$(CXX) $(CXXFLAGS) -c $(SRC)/cmdLineParser.cpp -o $(OBJ)/cmdLineParser.o
 
-$(OBJ)/structureInformationClass.o: $(SRC)/structureInformationClass.h $(SRC)/structureInformationClass.cpp 
-		$(CPP) $(CPPFLAGS) -c $(SRC)/structureInformationClass.cpp -o $(OBJ)/structureInformationClass.o
+$(OBJ)/structureInformationClass.o: $(SRC)/structureInformationClass.h $(SRC)/structureInformationClass.cpp
+		$(CXX) $(CXXFLAGS) -c $(SRC)/structureInformationClass.cpp -o $(OBJ)/structureInformationClass.o
 
-$(OBJ)/fastautils.o: $(SRC)/fastautils.h $(SRC)/fastautils.cpp 
-		$(CPP) $(CPPFLAGS) -c $(SRC)/fastautils.cpp -o $(OBJ)/fastautils.o
+$(OBJ)/fastautils.o: $(SRC)/fastautils.h $(SRC)/fastautils.cpp
+		$(CXX) $(CXXFLAGS) -c $(SRC)/fastautils.cpp -o $(OBJ)/fastautils.o
 
-$(OBJ)/MFPClass.o: $(SRC)/MFPClass.h $(SRC)/MFPClass.cpp 
-		$(CPP) $(CPPFLAGS) -c $(SRC)/MFPClass.cpp -o $(OBJ)/MFPClass.o
+$(OBJ)/MFPClass.o: $(SRC)/MFPClass.h $(SRC)/MFPClass.cpp
+		$(CXX) $(CXXFLAGS) -c $(SRC)/MFPClass.cpp -o $(OBJ)/MFPClass.o
 
-$(OBJ)/AlignClass.o: $(SRC)/AlignClass.h $(SRC)/AlignClass.cpp 
-		$(CPP) $(CPPFLAGS) -c $(SRC)/AlignClass.cpp -o $(OBJ)/AlignClass.o
+$(OBJ)/AlignClass.o: $(SRC)/AlignClass.h $(SRC)/AlignClass.cpp
+		$(CXX) $(CXXFLAGS) -c $(SRC)/AlignClass.cpp -o $(OBJ)/AlignClass.o
 
 $(OBJ)/pdbClass.o: $(SRC)/pdbClass.h $(SRC)/pdbClass.cpp $(SRC)/geometry3D.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/pdbClass.cpp -o $(OBJ)/pdbClass.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/pdbClass.cpp -o $(OBJ)/pdbClass.o
 
 $(OBJ)/seedAlignmentUtils.o: $(SRC)/seedAlignmentUtils.h $(SRC)/seedAlignmentUtils.cpp $(SRC)/geometry3D.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/seedAlignmentUtils.cpp -o $(OBJ)/seedAlignmentUtils.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/seedAlignmentUtils.cpp -o $(OBJ)/seedAlignmentUtils.o
 
 $(OBJ)/geometry3D.o: $(SRC)/geometry3D.h $(SRC)/geometry3D.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/geometry3D.cpp -o $(OBJ)/geometry3D.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/geometry3D.cpp -o $(OBJ)/geometry3D.o
 
 $(OBJ)/superpose3D.o: $(SRC)/superpose3D.h $(SRC)/superpose3D.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/superpose3D.cpp -o $(OBJ)/superpose3D.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/superpose3D.cpp -o $(OBJ)/superpose3D.o
 
 $(OBJ)/misc.o: $(SRC)/misc.h $(SRC)/misc.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/misc.cpp -o $(OBJ)/misc.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/misc.cpp -o $(OBJ)/misc.o
 
 $(OBJ)/Kent.o: $(SRC)/Kent.h $(SRC)/Kent.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/Kent.cpp -o $(OBJ)/Kent.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/Kent.cpp -o $(OBJ)/Kent.o
 
 $(OBJ)/ivalue.o: $(SRC)/ivalue.h $(SRC)/ivalue.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/ivalue.cpp -o $(OBJ)/ivalue.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/ivalue.cpp -o $(OBJ)/ivalue.o
 
 $(OBJ)/dp.o: $(SRC)/dp.h $(SRC)/dp.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/dp.cpp -o $(OBJ)/dp.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/dp.cpp -o $(OBJ)/dp.o
 
 $(OBJ)/em.o: $(SRC)/em.h $(SRC)/em.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/em.cpp -o $(OBJ)/em.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/em.cpp -o $(OBJ)/em.o
 
 $(OBJ)/main.o: $(SRC)/main.cpp
-		$(CPP) $(CPPFLAGS) -c $(SRC)/main.cpp -o $(OBJ)/main.o
+		$(CXX) $(CXXFLAGS) -c $(SRC)/main.cpp -o $(OBJ)/main.o
 
 #------------------------------------------------------------------------------
 clean:
