schema_version: 1

context:
  version: "2.7"

package:
  name: r-qcc
  version: ${{ version }}

source:
  url:
    - ${{ cran_mirror }}/src/contrib/qcc_${{ version }}.tar.gz
    - ${{ cran_mirror }}/src/contrib/Archive/qcc/qcc_${{ version }}.tar.gz
  sha256: ff139a046e6b139ac25537b69be24e0ff32d6a39db6c941d1d02b4710f378251

build:
  number: 0
  noarch: generic
  script:
    - R CMD INSTALL --build .

requirements:
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

tests:
  - script:
      - Rscript -e "library('qcc')"

about:
  homepage: https://github.com/luca-scr/qcc
  repository: https://github.com/luca-scr/qcc
  summary: Quality Control Charts
  description: |
    Shewhart quality control charts for continuous, attribute and count data.
    Cusum and EWMA charts. Operating characteristic curves. Process capability
    analysis. Pareto chart and cause-and-effect chart. Multivariate control
    charts.
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file:
    - ${{ PREFIX }}/lib/R/share/licenses/GPL-2
    - ${{ PREFIX }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ewels
