context:
  name: lopt
  version: "1.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://gitlab.com/earthscope/public/epic/passoft/lopt/-/archive/v${{ version }}/lopt-v${{ version }}.tar.gz
  sha256: b74b9036b12b51634792765e3a26a62476bdd0dbb5ec54e86867bcb17fd9d77d

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  python:
    entry_points:
      - lopt = lopt.lopt:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pyside6
    - if: linux
      then:
        - __linux
    - if: osx
      then:
        - __osx

tests:
  - python:
      imports:
        - lopt
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - lopt -h
  - script:
      - python -m unittest discover -s tests
    requirements:
      run:
        - python ${{ python_min }}.*
    files:
      source:
        - tests/

about:
  homepage: https://epic.earthscope.org/content/software-resources
  summary: Display time in PASSCAL time format
  description: |
    A simple GUI clock that displays the current GMT time in PASSCAL
    (year:day:hour:minute:second) format.
  license: GPL-3.0-or-later
  license_file: LICENSE
  repository: https://gitlab.com/earthscope/public/epic/passoft/lopt

extra:
  recipe-maintainers:
    - omid-earthscope
