# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.6.0"

package:
  name: microsoft-agents-m365copilot
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/microsoft-agents-m365copilot/microsoft_agents_m365copilot-${{ version }}.tar.gz
    sha256: cc3ccc74d937c52c2690806004248d2adbe20b05ce2c7b0d0149318e0645bf6a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - microsoft-agents-m365copilot-core >=1.0.0
    - microsoft-kiota-authentication-azure >=1.8.0,<2.0.0
    - microsoft-kiota-bundle >=1.8.0,<2.0.0
    - httpx >=0.23.0

tests:
  - python:
      imports:
        - microsoft_agents_m365copilot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Microsoft Agents M365 Copilot Python SDK
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/microsoft/Agents-M365Copilot/tree/main/python
  repository: https://github.com/microsoft/Agents-M365Copilot
  documentation: https://github.com/microsoft/Agents-M365Copilot/tree/main/python/packages/microsoft_agents_m365copilot

extra:
  recipe-maintainers:
    - rxm7706
