schema_version: 1

context:
  python_min: "3.13"
  version: "0.1.2"

package:
  name: cf-job-logs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cf-job-logs/cf_job_logs-${{ version }}.tar.gz
  sha256: a518015b48047009d9e429d7c39830fa6c72209d3cba3ec418d3178d5d7be07f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cf-job-logs = cf_job_logs.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - click >=8.0.0,<9
    - httpx >=0.28.1,<0.29
    - pydantic >=2.12.5,<3

tests:
  - python:
      imports:
        - cf_job_logs
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - cf-job-logs --help

about:
  summary: A utility for fetching and structuring conda-forge Azure CI logs into clean, agent-readable artifacts.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/quantco/cf-job-logs
  repository: https://github.com/quantco/cf-job-logs

extra:
  recipe-maintainers:
    - ManuelLerchner
    - ytausch
