{% set name = "openpkflow" %}
{% set version = "2.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 923aa6b1e3b51460f9dbc497dae3f62a38181fc7bdc388f7ce97714f915855ee

build:
  number: 0
  noarch: python
  entry_points:
    - openpkflow = openpkflow.cli:app
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - pandas >=2.0
    - scipy >=1.10
    - matplotlib-base >=3.7
    - pydantic >=2.0
    - typer >=0.12
    - jinja2 >=3.1

test:
  imports:
    - openpkflow
    - openpkflow.nca
    - openpkflow.dissolution
    - openpkflow.sim
    - openpkflow.be
    - openpkflow.ivivc
    - openpkflow.report
    - openpkflow.validation
  commands:
    - pip check
    - openpkflow version
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/priyamthakar/openpkflow
  license: MIT
  license_file: LICENSE
  summary: >-
    A transparent, reproducible, open-source Python workflow for dissolution,
    NCA, PK/PD simulation, and pharmacometric reporting.
  doc_url: https://priyamthakar.github.io/openpkflow/
  dev_url: https://github.com/priyamthakar/openpkflow/

extra:
  recipe-maintainers:
    - priyamthakar
