schema_version: 1

context:
  python_min: "3.10"
  version: "0.1.2"

package:
  name: histserv
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/h/histserv/histserv-${{ version }}.tar.gz
  sha256: 2f284ebb0f7e38b848417df5d96ddf92698ea9921db81b107cba18ca674eab35

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - histserv = histserv.__main__:run

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - grpcio >=1.76.0
    - hist >=2.9.0
    - boost-histogram >=1.7.1
    - uhi >=1.0.0
    - numcodecs >=0.13.1
    - grpcio-tools >=1.78.0

tests:
  - python:
      imports:
        - histserv
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - histserv --help

about:
  summary: Histogramming as a Service
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pfackeldey/histserv
  repository: https://github.com/pfackeldey/histserv

extra:
  recipe-maintainers:
    - pfackeldey
