features=(
  AGL
  AVFAudio
  AVFoundation
  AVKit
  AVRouting
  Accelerate
  Accessibility
  Accounts
  AdServices
  AdSupport
  AddressBook
  AppIntents
  AppKit
  AppTrackingTransparency
  AppleScriptKit
  AppleScriptObjC
  ApplicationServices
  AudioToolbox
  AudioUnit
  AudioVideoBridging
  AuthenticationServices
  AutomaticAssessmentConfiguration
  Automator
  BackgroundAssets
  BackgroundTasks
  BusinessChat
  CFNetwork
  CalendarStore
  CallKit
  Carbon
  ClassKit
  CloudKit
  Cocoa
  Collaboration
  ColorSync
  Contacts
  ContactsUI
  CoreAudio
  CoreAudioKit
  CoreBluetooth
  CoreData
  CoreFoundation
  CoreGraphics
  CoreHaptics
  CoreImage
  CoreLocation
  CoreMIDI
  CoreML
  CoreMedia
  CoreMediaIO
  CoreMotion
  CoreServices
  CoreSpotlight
  CoreTelephony
  CoreText
  CoreTransferable
  CoreVideo
  CoreWLAN
  CryptoTokenKit
  DVDPlayback
  DataDetection
  DeviceCheck
  DirectoryService
  DiscRecording
  DiscRecordingUI
  DiskArbitration
  EventKit
  ExceptionHandling
  ExecutionPolicy
  ExposureNotification
  ExtensionFoundation
  ExtensionKit
  ExternalAccessory
  FileProvider
  FileProviderUI
  FinderSync
  ForceFeedback
  Foundation
  GLKit
  GLUT
  GSS
  GameController
  GameKit
  GameplayKit
  HealthKit
  Hypervisor
  ICADevices
  IMServicePlugIn
  IOBluetooth
  IOBluetoothUI
  IOKit
  IOSurface
  IOUSBHost
  IdentityLookup
  ImageCaptureCore
  ImageIO
  InputMethodKit
  InstallerPlugins
  InstantMessage
  Intents
  IntentsUI
  JavaNativeFoundation
  JavaRuntimeSupport
  JavaScriptCore
  Kerberos
  KernelManagement
  LDAP
  LatentSemanticMapping
  LinkPresentation
  LocalAuthentication
  LocalAuthenticationEmbeddedUI
  MLCompute
  MailKit
  MapKit
  Matter
  MediaAccessibility
  MediaLibrary
  MediaPlayer
  MediaToolbox
  Metal
  MetalFX
  MetalKit
  MetalPerformanceShaders
  MetalPerformanceShadersGraph
  MetricKit
  ModelIO
  MultipeerConnectivity
  NaturalLanguage
  NearbyInteraction
  NetFS
  Network
  NetworkExtension
  NotificationCenter
  OSAKit
  OSLog
  OpenAL
  OpenCL
  OpenDirectory
  OpenGL
  PCSC
  PDFKit
  PHASE
  ParavirtualizedGraphics
  PassKit
  PencilKit
  Photos
  PhotosUI
  PreferencePanes
  PushKit
  Quartz
  QuartzCore
  QuickLook
  QuickLookThumbnailing
  QuickLookUI
  ReplayKit
  SafariServices
  SafetyKit
  SceneKit
  ScreenCaptureKit
  ScreenSaver
  ScreenTime
  ScriptingBridge
  Security
  SecurityFoundation
  SecurityInterface
  SensorKit
  ServiceManagement
  SharedWithYou
  SharedWithYouCore
  ShazamKit
  Social
  SoundAnalysis
  Speech
  SpriteKit
  StoreKit
  SwiftUI
  SyncServices
  SystemConfiguration
  SystemExtensions
  TWAIN
  Tcl
  ThreadNetwork
  UniformTypeIdentifiers
  UserNotifications
  UserNotificationsUI
  VideoDecodeAcceleration
  VideoSubscriberAccount
  VideoToolbox
  Virtualization
  Vision
  VisionKit
  WebKit
  WidgetKit
  iTunesLibrary
  vmnet
)
