${PYTHON} -c "from django.conf import settings; settings.configure()"
${PYTHON} -c "import graphene_django"
# ${PYTHON} -c "graphene_django.debug"
# ${PYTHON} -c "graphene_django.debug.sql"
# ${PYTHON} -c "graphene_django.debug.tests"
# ${PYTHON} -c "graphene_django.filter"
# ${PYTHON} -c "graphene_django.filter.tests"
# ${PYTHON} -c "graphene_django.forms"
# ${PYTHON} -c "graphene_django.forms.tests"
# ${PYTHON} -c "graphene_django.management"
# ${PYTHON} -c "graphene_django.management.commands"
# ${PYTHON} -c "graphene_django.rest_framework"
# ${PYTHON} -c "graphene_django.rest_framework.tests"
# ${PYTHON} -c "graphene_django.tests"
# ${PYTHON} -c "graphene_django.tests.issues"
# ${PYTHON} -c "graphene_django.utils"