SET MYBINDIR="%LIBRARY_PREFIX%\bin"
SET MYINCLUDEDIR="%LIBRARY_PREFIX%\include"
SET MYPYTHONDIR="%LIBRARY_PREFIX%\python"

MKDIR "%MYBINDIR%"
MKDIR "%MYINCLUDEDIR%\cxxtest"
MKDIR "%MYPYTHONDIR%"

XCOPY ".\cxxtest\*" "%MYINCLUDEDIR%\cxxtest\" /E
XCOPY ".\bin\*" "%MYBINDIR%\" /E
XCOPY ".\python\*" "%MYPYTHONDIR%\" /E