#!/opt/anaconda1anaconda2anaconda3/bin/python
#
# The CxxTest driver script, which uses the cxxtest Python package.
#

import sys
import os.path
import sysconfig

LIBDIR = sysconfig.get_config_var('LIBDIR')
CXXBASE = os.path.join(LIBDIR, 'cxxtest-4.4')
pytail = 'python' if sys.version_info < (3, 0) else 'python/python3'
PYDIR = os.path.join(CXXBASE, pytail)

sys.path.insert(0, PYDIR)
sys.path.append(".")

import cxxtest

cxxtest.main(sys.argv)
