schema_version: 1

context:
  version: "1.0.0b260514"
  python_min: "3.10"

package:
  name: agent-framework-ollama
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/agent-framework-ollama/agent_framework_ollama-${{ version }}.tar.gz
  sha256: 7cbedc2e5ad03e60978c4533c8507da563a0b5a4ff4a8ee5057da88c4806a5f2

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - agent-framework-core <2,>=1.4.0
    - ollama-python <0.5.4,>=0.5.3

tests:
  - python:
      imports:
        - agent_framework.ollama
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: |
    Ollama integration for Microsoft Agent Framework.
  homepage: https://pypi.org/project/agent-framework-ollama/
  repository: https://github.com/microsoft/agent-framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
    - mgorny
