schema_version: 1

context:
  python_min: "3.11"
  version: "0.5.0"

package:
  name: gdalxarray
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gdalxarray/gdalxarray-${{ version }}.tar.gz
  sha256: eff6bcc192d653cf3a1a2a9c256bd91f66ccc9276ba135f763c3e77229bc12e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - packaging
    - affine
    - rasterix >=0.2,<0.3
    - xarray >=2025.6
    - numpy
    - xproj
    - gdal

tests:
  - python:
      imports:
        - gdalxarray
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: xarray extension for GDAL
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/hypertidy/gdalxarray

extra:
  recipe-maintainers:
    - ocefpaf
