context:
  version: "0.0.1"

package:
  name: numba-cfunc-compiler
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/numba-cfunc-compiler/numba_cfunc_compiler-${{ version }}.tar.gz
  sha256: 0b72b8a9eb1151248abcf10737916e068d2ccd70bf7539020c081bfc462d93c2

build:
  script: python -m pip install . -vv
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - hatchling
    - hatch-cpp
  run:
    - python
    - numba >=0.64
    - llvmlite >=0.46

tests:
  - python:
      imports:
      - numba_cfunc_compiler
      - numba_cfunc_compiler.numba_rt
      pip_check: true

about:
  homepage: https://github.com/Point72/numba-cfunc-compiler
  summary: 'Generic, framework-agnostic infrastructure for compiling Python functions to Numba @cfunc via AST transformation'
  description: |
    Generic, framework-agnostic infrastructure for compiling Python functions to Numba @cfunc via AST transformation
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://github.com/Point72/numba-cfunc-compiler/wiki
  repository: https://github.com/Point72/numba-cfunc-compiler

extra:
  recipe-maintainers:
    - timkpaine
