{% set version = '2.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-iq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/iq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/iq/iq_{{ version }}.tar.gz
  sha256: 423f03641e4ac15cab601cc8b13dc5f7abf742dea651393edf23917502c56d86

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ stdlib("c") }}
  host:
    - llvm-openmp  # [osx]
    - libgomp # [linux]
    - r-base
    - r-rcpp
    - r-rcppeigen
  run:
    - r-base
    - r-rcpp
    - r-rcppeigen

test:
  commands:
    - $R -e "library('iq')"           # [not win]
    - "\"%R%\" -e \"library('iq')\""  # [win]

about:
  home: https://github.com/tvpham/iq
  license: BSD-3-Clause
  summary: An implementation of the MaxLFQ algorithm by Cox et al. (2014) <doi:10.1074/mcp.M113.031591>
    in a comprehensive pipeline for processing proteomics data in data-independent acquisition
    mode (Pham et al. 2020 <doi:10.1093/bioinformatics/btz961>). It offers additional
    options for protein quantification using the N most intense fragment ions, using
    all fragment ions, the median polish algorithm by Tukey (1977, ISBN:0201076160),
    and a robust linear model. In general, the tool can be used to integrate multiple
    proportional observations into a single quantitative value.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - fgeier

# Package: iq
# Type: Package
# Title: Protein Quantification in Mass Spectrometry-Based Proteomics
# Version: 2.0.0
# Authors@R: c(person("Thang", "Pham", email = "t.pham@amsterdamumc.nl", role = c("aut", "cre", "cph", "ctb"), comment = c(ORCID = "0000-0003-0333-2492")), person("Alex", "Henneman", role = c("ctb"), comment = c(ORCID = "0000-0002-3746-4410")))
# Maintainer: Thang Pham <t.pham@amsterdamumc.nl>
# Description: An implementation of the MaxLFQ algorithm by Cox et al. (2014) <doi:10.1074/mcp.M113.031591> in a comprehensive pipeline for processing proteomics data in data-independent acquisition mode (Pham et al. 2020 <doi:10.1093/bioinformatics/btz961>). It offers additional options for protein quantification using the N most intense fragment ions, using all fragment ions, the median polish algorithm by Tukey (1977, ISBN:0201076160), and a robust linear model. In general, the tool can be used to integrate multiple proportional observations into a single quantitative value.
# Depends: R (>= 2.10)
# License: BSD_3_clause + file LICENSE
# LinkingTo: Rcpp, RcppEigen
# Encoding: UTF-8
# LazyData: true
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# URL: https://github.com/tvpham/iq
# BugReports: https://github.com/tvpham/iq/issues
# NeedsCompilation: yes
# Packaged: 2025-10-04 19:44:15 UTC; P032181
# Author: Thang Pham [aut, cre, cph, ctb] (ORCID: <https://orcid.org/0000-0003-0333-2492>), Alex Henneman [ctb] (ORCID: <https://orcid.org/0000-0002-3746-4410>)
# Repository: CRAN
# Date/Publication: 2025-10-06 07:30:02 UTC
