schema_version: 1

context:
  name: probsamplers
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/b4/33/e32412bb95576098939df074a5141c910a04fe261f2295345ec5782967d6/probsamplers-0.1.0.tar.gz
  sha256: ad6e72e107d50838d738de9a1104e8704097217ba97749f4eba78741cc2b6df5

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - scipy

tests:
  - python:
      imports:
        - probsamplers
      pip_check: true

about:
  homepage: https://github.com/HaoZeke/probsamplers
  summary: Probability samplers for MCMC methods
  license: MIT
  license_file: LICENSE
  repository: https://github.com/HaoZeke/probsamplers

extra:
  recipe-maintainers:
    - HaoZeke
