{% set version = '1.0.7' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-recommenderlab
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/recommenderlab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/recommenderlab/recommenderlab_{{ version }}.tar.gz
  sha256: 91b128288c8774414c84e9cf89bf1e8a055fde2d80ccc73051ee60ec17aa534d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.5
    - r-matrix
    - r-arules >=1.7_11
    - r-irlba
    - r-matrixstats
    - r-proxy >=0.4_26
    - r-recosystem
    - r-registry
  run:
    - r-base >=4.5
    - r-matrix
    - r-arules >=1.7_11
    - r-irlba
    - r-matrixstats
    - r-proxy >=0.4_26
    - r-recosystem
    - r-registry

test:
  commands:
    - $R -e "library('recommenderlab')"           # [not win]
    - "\"%R%\" -e \"library('recommenderlab')\""  # [win]

about:
  home: https://github.com/mhahsler/recommenderlab
  license: GPL-2.0-only
  summary: Provides a research infrastructure to develop and evaluate collaborative filtering
    recommender algorithms. This includes a sparse representation for user-item matrices,
    many popular algorithms, top-N recommendations, and cross-validation. Hahsler (2022)
    <doi:10.48550/arXiv.2205.12371>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: recommenderlab
# Version: 1.0.7
# Date: 2025-05-29
# Title: Lab for Developing and Testing Recommender Algorithms
# Authors@R: c(person("Michael", "Hahsler", role = c("aut", "cre", "cph"), email = "mhahsler@lyle.smu.edu", comment = c(ORCID = "0000-0003-2716-1405")), person("Bregt", "Vereet", role = c("ctb")))
# Description: Provides a research infrastructure to develop and evaluate collaborative filtering recommender algorithms. This includes a sparse representation for user-item matrices, many popular algorithms, top-N recommendations, and cross-validation. Hahsler (2022) <doi:10.48550/arXiv.2205.12371>.
# Classification/ACM: G.4, H.2.8
# Depends: R (>= 4.5.0), Matrix, arules (>= 1.7-11), proxy (>= 0.4-26)
# Imports: registry, methods, utils, stats, irlba, recosystem, matrixStats
# Suggests: testthat
# BugReports: https://github.com/mhahsler/recommenderlab/issues
# URL: https://github.com/mhahsler/recommenderlab
# License: GPL-2
# Copyright: (C) Michael Hahsler
# NeedsCompilation: no
# Packaged: 2025-05-29 20:14:47 UTC; mhahsler
# Author: Michael Hahsler [aut, cre, cph] (ORCID: <https://orcid.org/0000-0003-2716-1405>), Bregt Vereet [ctb]
# Maintainer: Michael Hahsler <mhahsler@lyle.smu.edu>
# Repository: CRAN
# Date/Publication: 2025-05-31 21:20:02 UTC
