{% set name = "rpextractsink" %}
{% set version = "6.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rpExtractSink/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9266de01073674bf6189f97c0247ffde918c440bcca6ad0be3b4693daf0cb331

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - rr_cache
    - brs_utils
    - rplibs

test:
  requires:
      - python {{ python_min }}
  imports:
    - rpextractsink
  commands:
    - pip check

about:
  home: https://github.com/brsynth/rpExtractSink/tree/main
  summary: "RetroPath2 sink generator"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
