schema_version: 1

context:
  version: "2.0.0"

package:
  name: dkx
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dkx/dkx-${{ version }}.tar.gz
  sha256: 662cc22d56539918fd67d0f706573d275619c7241024d1fe30bb4f5fdc743ee3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - dkx = dkx.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - jax
    - numpy
    - scipy
    - h5py
    - netcdf4
    - matplotlib-base
    - solvax

tests:
  - python:
      imports:
        - dkx
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - dkx --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Neoclassical transport solver with CPU/GPU and differentiable JAX workflows
  license: MIT
  license_file: LICENSE
  homepage: https://sfincs-jax.readthedocs.io/
  repository: https://github.com/uwplasma/DKX
  documentation: https://sfincs-jax.readthedocs.io/

extra:
  recipe-maintainers:
    - matthewfeickert
    - RKHashmani
