{% set python_min = "3.9" %}
{% set version = "0.2.9" %}

package:
  name: image-registration
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/image-registration/image_registration-{{ version }}.tar.gz
  sha256: 29d12e282a15da4af6d6cc17d86a2b405c42a900e2f1203f2ee128ee4756503f

build:
  entry_points:
    - astropy-package-template-example = packagename.example_mod:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - extension-helpers
    - numpy
    - vcs_versioning
    - pip
  run:
    - python >={{ python_min }}
    - astropy
    - matplotlib-base
    - pytest
    - numpy

test:
  imports:
    - image_registration
  commands:
    - pip check
    - astropy-package-template-example --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://image-registration.readthedocs.io/en/latest/
  summary: Package for registering images with extended emission
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tcompa
