{% set name = "excitingscripts" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/excitingscripts-{{ version }}.tar.gz
  sha256: 21e66bfbe05e230e37f456e0cc89bd37084f1dba267a20fd547b28fa2c12b589

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel >=0.35.0
    - excitingtools
    - numpy
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.14.5
    - matplotlib-base >=2.2.0
    - scipy >=1.7.0
    - excitingtools >=1.6.3
    - typing_extensions >=3.7
    - ase >=3.22.1
    - requests

test:
  imports:
    - excitingscripts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Executable command-line scripts for working with the exciting code.
  home: https://github.com/exciting/exciting
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
