context:
  name: mise
  version: 2026.3.1

package:
  name: mise
  version: ${{ version }}

source:
  url: https://github.com/jdx/mise/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7365f10ceeb5279de4b1cdec0fc4a02efc653f401c0619fde02f23842b1270cb

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - export LIBCLANG_PATH=$BUILD_PREFIX/lib
          - cargo auditable install --no-track --locked --bins --all-features --root ${{ PREFIX }} --path .
        else:
          - powershell -c "cp (gci $env:BUILD_PREFIX\Library\bin\libclang-*.dll)[0] $env:BUILD_PREFIX\Library\bin\libclang.dll"
          - set "LIBCLANG_PATH=%BUILD_PREFIX%\Library\bin"
          - cargo auditable install --no-track --locked --bins --all-features --root %LIBRARY_PREFIX% --path .
          - cargo auditable install --no-track --locked --bins --all-features --root %LIBRARY_PREFIX% --path crates/mise-shim
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib("c") }} 
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - clang
    - cmake
    - libclang
    - make
    - ninja
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - mise --version
      - mise --help
      - if: win
        then: if not exist %LIBRARY_BIN%\\mise-shim.exe exit 1

about:
  summary: mise manages dev tools, env vars, and runs tasks.
  description: |
    `mise` (mise-en-place) is a unified CLI tool designed to simplify and manage local development environments.
    It acts as a polyglot tool version manager, installing and seamlessly switching between versions of various
    development tools (replacing utilities like `asdf`, `nvm`, and `pyenv`). Additionally, it functions as an
    environment variable manager that dynamically loads project-specific env vars based on your current directory
    (replacing `direnv`), and serves as a built-in task runner to define and execute project workflows as a modern
    alternative to `make` or `npm` scripts.
  license: MIT
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://mise.jdx.dev/
  repository: https://github.com/jdx/mise

extra:
  recipe-maintainers:
    - salim-b
