{% set name = "amn" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/amn_library/archive/refs/tags/{{ version }}.tar.gz
  sha256: ee51ccb607848aee6eb54ff083181b8efce77df47f5931562d76bf26bfdbbf72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy =1.23.5
    - pandas
    - matplotlib
    - scikit-learn
    - xgboost 
    - keras
    - cobra
    - pydantic =1.10.11
    - typing_extensions =4.5.0
    - pip
    - ipykernel
    - tensorflow =2.4.1
    - tensorflow-probability
    - importlib-resources

test:
  source_files: 
    - tests/
  imports:
    - amn
  requires:
    - python {{ python_min }}
  commands:
    - python -m amn --help

about:
  home: https://github.com/brsynth/amn_library
  summary: "Build, Training & Prediction with Artificial Metabolic Networks (AMN)"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
