# export AMBERHOME=${PWD}
# cd $AMBERHOME
# echo 'N' | ./configure  -noX11 -openmp --prefix ${PREFIX} --with-python ${PREFIX}/bin/python --python-install local gnu
# bash amber.sh
# make install

# cp -rf $SRC_DIR/bin/FEW.pl $PREFIX/bin/
# cp -rf $SRC_DIR/bin/espgen.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/pymdpbsa $PREFIX/bin/
# cp -rf $SRC_DIR/bin/cpptraj $PREFIX/bin/
# cp -rf $SRC_DIR/bin/senergy $PREFIX/bin/
# cp -rf $SRC_DIR/bin/fix_new_inpcrd_vel $PREFIX/bin/
# cp -rf $SRC_DIR/bin/softcore_setup.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/cphstats $PREFIX/bin/
# cp -rf $SRC_DIR/bin/IPMach.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mm_pbsa_statistics.pl $PREFIX/bin/
# cp -rf $SRC_DIR/bin/respgen $PREFIX/bin/
# cp -rf $SRC_DIR/bin/molsurf $PREFIX/bin/
# cp -rf $SRC_DIR/bin/teLeap $PREFIX/bin/
# cp -rf $SRC_DIR/bin/paramfit $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ucpp $PREFIX/bin/
# cp -rf $SRC_DIR/bin/xaLeap $PREFIX/bin/
# cp -rf $SRC_DIR/bin/cpinutil.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/sgldwt.sh $PREFIX/bin/
# cp -rf $SRC_DIR/bin/charmmlipid2amber.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/cestats $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ChBox $PREFIX/bin/
# cp -rf $SRC_DIR/bin/minab $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ffgbsa $PREFIX/bin/
# cp -rf $SRC_DIR/bin/new_to_old_crd $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nc-config $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nccopy $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mmpbsa_py_energy $PREFIX/bin/
# cp -rf $SRC_DIR/bin/finddgref.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/process_minout.perl $PREFIX/bin/
# cp -rf $SRC_DIR/bin/rism3d.thermo $PREFIX/bin/
# cp -rf $SRC_DIR/bin/make_crd_hg $PREFIX/bin/
# cp -rf $SRC_DIR/bin/pytleap $PREFIX/bin/
# cp -rf $SRC_DIR/bin/residuegen $PREFIX/bin/
# cp -rf $SRC_DIR/bin/fantasian $PREFIX/bin/
# cp -rf $SRC_DIR/bin/gbnsr6 $PREFIX/bin/
# cp -rf $SRC_DIR/bin/elsize $PREFIX/bin/
# cp -rf $SRC_DIR/bin/sander.LES $PREFIX/bin/
# cp -rf $SRC_DIR/bin/sander $PREFIX/bin/
# cp -rf $SRC_DIR/bin/sqm $PREFIX/bin/
# cp -rf $SRC_DIR/bin/resp $PREFIX/bin/
# cp -rf $SRC_DIR/bin/parmchk2 $PREFIX/bin/
# cp -rf $SRC_DIR/bin/sviol $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mol2rtf.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/fftw-wisdom-to-conf $PREFIX/bin/
# cp -rf $SRC_DIR/bin/amb2gro_top_gro.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/MCPB.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/fitpkaeo.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/packmol $PREFIX/bin/
# cp -rf $SRC_DIR/bin/am1bcc $PREFIX/bin/
# cp -rf $SRC_DIR/bin/MMPBSA.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/volslice $PREFIX/bin/
# cp -rf $SRC_DIR/bin/pdb4amber $PREFIX/bin/
# cp -rf $SRC_DIR/bin/fftw-wisdom $PREFIX/bin/
# cp -rf $SRC_DIR/bin/amb2chm_par.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/antechamber $PREFIX/bin/
# cp -rf $SRC_DIR/bin/rism3d.snglpnt $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nmode $PREFIX/bin/
# cp -rf $SRC_DIR/bin/memembed $PREFIX/bin/
# cp -rf $SRC_DIR/bin/atomtype $PREFIX/bin/
# cp -rf $SRC_DIR/bin/amb2chm_psf_crd.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/tinker_to_amber $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ambpdb $PREFIX/bin/
# cp -rf $SRC_DIR/bin/OptC4.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/hcp_getpdb $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ncdump $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nfe-umbrella-slice $PREFIX/bin/
# cp -rf $SRC_DIR/bin/saxs_md $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mdout2pymbar.pl $PREFIX/bin/
# cp -rf $SRC_DIR/bin/tleap $PREFIX/bin/
# cp -rf $SRC_DIR/bin/makeDIST_RST $PREFIX/bin/
# cp -rf $SRC_DIR/bin/dacdif $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ncgen3 $PREFIX/bin/
# cp -rf $SRC_DIR/bin/new_crd_to_dyn $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ceinutil.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/UnitCell $PREFIX/bin/
# cp -rf $SRC_DIR/bin/AddToBox $PREFIX/bin/
# cp -rf $SRC_DIR/bin/rism1d $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mdnab $PREFIX/bin/
# cp -rf $SRC_DIR/bin/car_to_files.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mm_pbsa.pl $PREFIX/bin/
# cp -rf $SRC_DIR/bin/pbsa $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mmpbsa_py_nabnmode $PREFIX/bin/
# cp -rf $SRC_DIR/bin/sgldinfo.sh $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mdout_analyzer.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mdgx $PREFIX/bin/
# cp -rf $SRC_DIR/bin/makeANG_RST $PREFIX/bin/
# cp -rf $SRC_DIR/bin/saxs_rism $PREFIX/bin/
# cp -rf $SRC_DIR/bin/new2oldparm $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ante-MMPBSA.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/parmed $PREFIX/bin/
# cp -rf $SRC_DIR/bin/prepgen $PREFIX/bin/
# cp -rf $SRC_DIR/bin/sviol2 $PREFIX/bin/
# cp -rf $SRC_DIR/bin/PdbSearcher.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ProScrs.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/to_be_dispatched $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nab $PREFIX/bin/
# cp -rf $SRC_DIR/bin/mm_pbsa_nabnmode $PREFIX/bin/
# cp -rf $SRC_DIR/bin/makeCHIR_RST $PREFIX/bin/
# cp -rf $SRC_DIR/bin/rism3d.orave $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nab2c $PREFIX/bin/
# cp -rf $SRC_DIR/bin/CartHess2FC.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/cpeinutil.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/lmanal $PREFIX/bin/
# cp -rf $SRC_DIR/bin/genremdinputs.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nf-config $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ncgen $PREFIX/bin/
# cp -rf $SRC_DIR/bin/xparmed $PREFIX/bin/
# cp -rf $SRC_DIR/bin/CheckMD $PREFIX/bin/
# cp -rf $SRC_DIR/bin/espgen $PREFIX/bin/
# cp -rf $SRC_DIR/bin/nef_to_RST $PREFIX/bin/
# cp -rf $SRC_DIR/bin/packmol-memgen $PREFIX/bin/
# cp -rf $SRC_DIR/bin/fixremdcouts.py $PREFIX/bin/
# cp -rf $SRC_DIR/bin/ambmask $PREFIX/bin/
# cp -rf $SRC_DIR/bin/PropPDB $PREFIX/bin/
# cp -rf $SRC_DIR/bin/process_mdout.perl $PREFIX/bin/
# cp -rf $SRC_DIR/bin/bondtype $PREFIX/bin/
# cp -rf $SRC_DIR/bin/addles $PREFIX/bin/
# cp -rf $SRC_DIR/bin/reduce $PREFIX/bin/
# cp -rf $SRC_DIR/lib/libfftw3.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_thread.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libblas.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_filesystem.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libcpptraj.so $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libnetcdff.la $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libsaxs_md.so $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libsqm.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_system.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libcifparse.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/liblapack.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libarpack.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/perl $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_graph.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_iostreams.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libpbsa.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libsanderles.so $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libnetcdf.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libemil.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/pkgconfig $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libfftw3.la $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_regex.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libnetcdf.la $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libmdgx.so $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libnab.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/python2.7 $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_program_options.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libnetcdff.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libnetcdf.settings $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_timer.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/librism.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libxblas-amb.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libFpbsa.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libsff.a $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libsaxs_rism.so $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libsander.so $PREFIX/lib/
# cp -rf $SRC_DIR/lib/libboost_chrono.a $PREFIX/lib/
# cp -rf $SRC_DIR/include/fftw3.h $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf.inc $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf.h $PREFIX/include/
# cp -rf $SRC_DIR/include/defreal.h $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_mem.h $PREFIX/include/
# cp -rf $SRC_DIR/include/sff.h $PREFIX/include/
# cp -rf $SRC_DIR/include/sander.h $PREFIX/include/
# cp -rf $SRC_DIR/include/nab_netcdf.h $PREFIX/include/
# cp -rf $SRC_DIR/include/fftw3.f $PREFIX/include/
# cp -rf $SRC_DIR/include/nabtypes.h $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_nf_data.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_fortv2_c_interfaces.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_nc_data.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_nc_interfaces.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/nab.h $PREFIX/include/
# cp -rf $SRC_DIR/include/mdgx.h $PREFIX/include/
# cp -rf $SRC_DIR/include/CompatibilityMacros.h $PREFIX/include/
# cp -rf $SRC_DIR/include/xmin_opt.h $PREFIX/include/
# cp -rf $SRC_DIR/include/sander_api.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/nabcode.h $PREFIX/include/
# cp -rf $SRC_DIR/include/sanderles_api.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_nf_interfaces.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_f03.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/typesizes.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf.mod $PREFIX/include/
# cp -rf $SRC_DIR/include/boost $PREFIX/include/
# cp -rf $SRC_DIR/include/netcdf_meta.h $PREFIX/include/
# cp -rf $SRC_DIR/include/lmod_opt.h $PREFIX/include/
# cp -rf $SRC_DIR/include/AmberNetcdf.h $PREFIX/include/
# cp -rf $SRC_DIR/include/fftw3.f03 $PREFIX/include/
# cp -rf $SRC_DIR/dat/reslib $PREFIX/dat/
# cp -rf $SRC_DIR/dat/mmpbsa $PREFIX/dat/
# cp -rf $SRC_DIR/dat/pymsmt $PREFIX/dat/
# cp -rf $SRC_DIR/dat/slko $PREFIX/dat/
# cp -rf $SRC_DIR/dat/map.NEF-AMBER $PREFIX/dat/
# cp -rf $SRC_DIR/dat/reduce_wwPDB_het_dict.txt $PREFIX/dat/
# cp -rf $SRC_DIR/dat/PROTON_INFO $PREFIX/dat/
# cp -rf $SRC_DIR/dat/chamber $PREFIX/dat/
# cp -rf $SRC_DIR/dat/antechamber $PREFIX/dat/
# cp -rf $SRC_DIR/dat/Karplus.txt $PREFIX/dat/
# cp -rf $SRC_DIR/dat/CMakeLists.txt $PREFIX/dat/
# cp -rf $SRC_DIR/dat/dgdb $PREFIX/dat/
# cp -rf $SRC_DIR/dat/rism3d $PREFIX/dat/
# cp -rf $SRC_DIR/dat/contrib $PREFIX/dat/
# cp -rf $SRC_DIR/dat/pixmap $PREFIX/dat/
# cp -rf $SRC_DIR/dat/rism1d $PREFIX/dat/
# cp -rf $SRC_DIR/dat/charmmlipid2amber $PREFIX/dat/
# cp -rf $SRC_DIR/dat/map.DG-AMBER $PREFIX/dat/
# cp -rf $SRC_DIR/dat/leap $PREFIX/dat/
# cp -rf $SRC_DIR/dat/XaLeap_wcl $PREFIX/dat/
# cp -rf $SRC_DIR/dat/PROTON_INFO.pdbv2 $PREFIX/dat/

mkdir build
cd build
cmake  -DCMAKE_INSTALL_PREFIX=${PREFIX} -D CMAKE_C_COMPILER=${CC} -D CMAKE_CXX_COMPILER=${CXX} -DBUILD_GUI=FALSE -DOPENMP=TRUE -DPYTHON_EXECUTABLE=${PREFIX}/bin/python -DCOMPILER=GNU -DDOWNLOAD_MINICONDA=FALSE -DINSTALL_TESTS=TRUE "-DDISABLE_TOOLS=" ..
make
make install
