{% set name = "toe" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LiuShang-777/toe_for_conda/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4853bb31c696a26e22344f67be64daaeb2b1d7e8760bda027597900589ca436f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - toe = toe.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - scikit-learn

test:
  imports:
    - toe
  commands:
    - toe --help

about:
  home: https://github.com/LiuShang-777/toe_for_conda
  license: MIT
  license_file: LICENSE
  summary: Trade-off evaluation using convex hull and Pareto frontier analysis.

extra:
  recipe-maintainers:
    - LiuShang-777
