#!/bin/bash

unset CONDA_FORGE_EMSCRIPTEN_ACTIVATED
unset PY_SIDE_LD_FLAGV
unset OPTFLAGS_USED
unset DBGFLAGS_USED
unset LDFLAGS_BASE
unset CFLAGS_BASE
unset SIDE_MODULE_LDFLAGS
unset SIDE_MODULE_CFLAGS
