context:
  version: 2602.0.2

package:
  name: py-oidc-auth-client
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/py-oidc-auth-client/py_oidc_auth_client-${{ version }}.tar.gz
  sha256: 6b46384587197595ae1b83b0b0760e694bcaf16197c95bd584eb0c36e0cb913f

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . --no-deps -vv
  python:
    entry_points:
    - oidc-auth = py_oidc_auth_client.__main__:main
  noarch: python

requirements:
  host:
  - python ${{ python_min }}.*
  - flit-core
  - pip
  run:
  - python >=${{ python_min }}
  - httpx
  - platformdirs
  - rich
  - typing-extensions

tests:
- python:
    imports:
      - py_oidc_auth_client
    pip_check: true
    python_version:
      - ${{ python_min }}.*
      - "*"

about:
  summary: Client library for the OIDC Auth server.
  description: |+
    py-oidc-auth-client is the counterpart of the server-side library **py-oidc-auth**.

    While **py-oidc-auth** helps you add OpenID Connect login, token, and device endpoints to web frameworks,
    **py-oidc-auth-client** consumes those routes and gives you ready-to-use bearer tokens for calling protected APIs.
  documentation: https://py-oidc-auth-client.readthedocs.io
  homepage: https://github.com/freva-org/py-oidc-auth-client
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
