file(STRINGS ${PROCESSED_LIST} PROCESSED_FILES)

foreach(HEADER IN LISTS INPUT_HEADERS)
    get_filename_component(FILE_NAME ${HEADER} NAME)
    set(OUTPUT_FILE "${OUTPUT_DIR}/${FILE_NAME}")

    if(NOT "${OUTPUT_FILE}" IN_LIST PROCESSED_FILES)
        file(READ ${HEADER} HEADER_CONTENT)
        file(READ ${EXPORT_HEADER} EXPORT_CONTENT)
        file(WRITE ${OUTPUT_FILE} "${EXPORT_CONTENT}\n${HEADER_CONTENT}")
        file(APPEND ${PROCESSED_LIST} "${OUTPUT_FILE}\n")
    endif()
endforeach()
