# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.10"

package:
  name: python-cityhash
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cityhash/cityhash-${{ version }}.tar.gz
  sha256: 7e35da9aaf5fcf91da3fea23405874db55ffa58b1abc441d39cce0c8704a9c15

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}

    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - cython
    - py-cpuinfo
    - setuptools
    - wheel
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - cityhash
        - cityhashcrc
        - farmhash
      pip_check: true

about:
  summary: Python bindings for CityHash and FarmHash
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/escherba/python-cityhash

extra:
  recipe-maintainers:
    - rxm7706
