set -euxo pipefail

rm -rf build || true
mkdir build
cd build

cmake ${SRC_DIR} ${CMAKE_ARGS} \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_CUDA_MODULE=OFF \
    -DBUILD_COMMON_CUDA_ARCHS=OFF \
    -DBUILD_CACHED_CUDA_MANAGER=OFF \
    -DBUILD_ISPC_MODULE=OFF \
    -DBUILD_GUI=OFF \
    -DWITH_IPPICV=OFF \
    -DWITH_FAISS=OFF \
    -DBUILD_WEBRTC=OFF \
    -DBUILD_JUPYTER_EXTENSION=OFF \
    -DUSE_BLAS=ON \
    -DUSE_SYSTEM_EIGEN3=ON \
    -DUSE_SYSTEM_FMT=ON \
    -DUSE_SYSTEM_GLEW=ON \
    -DUSE_SYSTEM_GLFW=ON \
    -DUSE_SYSTEM_IMGUI=OFF \
    -DUSE_SYSTEM_JPEG=ON \
    -DUSE_SYSTEM_LIBLZF=OFF \
    -DUSE_SYSTEM_PNG=ON \
    -DUSE_SYSTEM_PYBIND11=ON \
    -DUSE_SYSTEM_QHULLCPP=ON \
    -DUSE_SYSTEM_TINYGLTF=ON \
    -DUSE_SYSTEM_TINYOBJLOADER=ON \
    -DBUILD_LIBREALSENSE=OFF \
    -DUSE_SYSTEM_LIBREALSENSE=OFF \
    -DBUILD_AZURE_KINECT=OFF \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUILD_PYTORCH_OPS=OFF

make
make install
