{% set version = "0.4.6" %}

package:
  name: pyafv
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyafv/pyafv-{{ version }}.tar.gz
  sha256: 35ce6801f8a80ead6487a0363f32a8d02284cd884bc2032261efe5b8cc195281

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - python-gil
    - hatchling
    - hatch-cython
    - cython
    - setuptools
    - numpy >=1.26.4
    - pip
  run:
    - python
    - python-gil
    - numpy >=1.26.4
    - scipy >=1.13.1
    - matplotlib-base >=3.8.4

test:
  imports:
    - pyafv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://wwang721.github.io/pyafv
  summary: Python implementation of the active-finite-Voronoi (AFV) model
  doc_url: https://pyafv.readthedocs.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wwang721
