# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.0.1"

package:
  name: abstract-singleton
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/abstract-singleton/abstract_singleton-${{ version }}.tar.gz
  sha256: d97d26ecbcb7422f78df1b0bca48a03df5ba04cf58844c6da033a7840beaae82

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - abstract_singleton
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: An abstract singleton class.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/BillSchumacher/Abstract-Singleton

extra:
  recipe-maintainers:
    - rxm7706
