schema_version: 1

context:
  version: "1.0.0b260514"
  python_min: "3.10"

package:
  name: agent-framework-anthropic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/agent-framework-anthropic/agent_framework_anthropic-${{ version }}.tar.gz
  sha256: 4093b0477355b9cbb6bc7976f5842931088900edd0b28c93dff43d10c74dca4f

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core <4.0,>=3.11
  run:
    - python >=${{ python_min }}
    - agent-framework-core <2,>=1.4.0
    - anthropic <0.80.1,>=0.80.0

tests:
  - python:
      imports:
        - agent_framework.anthropic
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: |
    Anthropic integration for Microsoft Agent Framework.
  homepage: https://pypi.org/project/agent-framework-anthropic/
  repository: https://github.com/microsoft/agent-framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
    - mgorny
