#!/usr/bin/env bash


# Set the numpy variable. This isn't used, but conda-build complains if we haven't set it already.
export CONDA_NPY=19

wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root
conda config --set show_channel_urls True
conda config --add channels conda-forge
conda install --yes --quiet conda-build-all
conda install --yes --quiet conda-build jinja2 anaconda-client setuptools
# Workaround latest conda-build.
conda install --yes conda-build=1.18.2

# We just want to build all of the recipes.
conda-build-all ./recipes --matrix-condition "numpy >=1.8" "python >=2.7,<3|>=3.4"
