#!/usr/bin/env bash


# Set the numpy variable. This isn't used, but conda-build complains if we haven't set it already.
export CONDA_NPY=19
# Needed because conda-build-all does not set CONDA_R due to a bug (see SciTools/conda-build-all#73).
export CONDA_R=3.3.2

# Remove homebrew.
brew remove --force --ignore-dependencies $(brew list)
brew cleanup -s
rm -rf $(brew --cache)

# Install and configure conda environment.
curl -L -O https://raw.githubusercontent.com/conda-forge/conda-smithy/e976c7e84bb3c4846e7562afd1a42c4b535b51f5/bootstrap-obvious-ci-and-miniconda.py
python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 3 --without-obvci && source ~/miniconda/bin/activate root
conda config --add channels conda-forge
conda config --set show_channel_urls true
conda install --yes --quiet conda-build-all=1.0.0
conda install --yes --quiet conda-forge-build-setup
source run_conda_forge_build_setup

# Find the recipes from master in this PR and remove them.
pushd ./recipes > /dev/null
echo "Finding recipes merged in master and removing them from the build."
git ls-tree --name-only master -- . | xargs -I {} sh -c "rm -rf {} && echo Removing recipe: {}"
popd > /dev/null

# We just want to build all of the recipes.
conda-build-all ./recipes --matrix-condition "numpy >=1.11" "python >=2.7,<3|>=3.5" "r-base >=3.3.2"
