#!/usr/bin/env bash

set -e

# Ensure we are on the latest commit
# of the branch where we are converting
# recipes from. Currently this is `master`.
git checkout "${TRAVIS_BRANCH}"

# Download and setup Miniconda
mkdir -p ~/miniconda_staging
pushd ~/miniconda_staging
curl -L -O https://raw.githubusercontent.com/conda-forge/conda-smithy/e976c7e84bb3c4846e7562afd1a42c4b535b51f5/bootstrap-obvious-ci-and-miniconda.py
python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 3 --without-obvci && source ~/miniconda/bin/activate root
popd
rm -rf ~/miniconda_staging

# Temporarily pin `conda` to 4.1.x for `conda-smithy`.
touch ~/miniconda/conda-meta/pinned
echo "conda 4.1.*" >> ~/miniconda/conda-meta/pinned

conda config --set show_channel_urls true
conda config --add channels conda-forge
conda install --yes --quiet git
conda install --yes --quiet conda-smithy
conda install --yes --quiet conda-forge-build-setup
source run_conda_forge_build_setup

mkdir -p ~/.conda-smithy
echo $TRAVIS_TOKEN > ~/.conda-smithy/travis.token

python .CI/create_feedstocks.py
