#!/usr/bin/env bash

set -e


if [ -n "$GH_TOKEN" ]; then
    wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
    python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 3 --without-obvci && source ~/miniconda/bin/activate root
    conda config --set show_channel_urls true
    conda config --add channels conda-forge
    conda install --yes --quiet conda-smithy

    python .CI/create_feedstocks.py

    # If we have got this far and we have a GH_TOKEN, trigger the conda-forge.github.io
    # travis suite to run (this builds docs etc.)
    python .CI/trigger_travis_conda-forge.github.io.py
fi
