#!/usr/bin/env bash

# Expected to be run in a TravisCI context.

set -e

if [ -n "$GH_TOKEN" ]; then
    # Install Miniconda.
    echo ""
    echo "Installing a fresh version of Miniconda."
    curl -L https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh > ~/miniconda.sh
    bash ~/miniconda.sh -b -p ~/miniconda
    source ~/miniconda/bin/activate root

    # Configure conda.
    echo ""
    echo "Configuring conda."
    conda config --set show_channel_urls true
    conda config --add channels conda-forge
    conda install --yes --quiet git=2.12.2
    conda install --yes --quiet conda-smithy conda-execute
    conda install --yes --quiet conda-forge-build-setup
    source run_conda_forge_build_setup

    mkdir -p ~/.conda-smithy

    git clone https://${GH_TOKEN}@github.com/conda-forge/feedstocks.git feedstocks_repo
    curl -L -O https://raw.githubusercontent.com/conda-forge/conda-forge.github.io/master/scripts/update_feedstocks_submodules.py
    conda execute -v update_feedstocks_submodules.py ./feedstocks_repo
    cd ./feedstocks_repo

    # Update to avoid race-conditions.
    git fetch origin 2> /dev/null && git rebase origin/master
    git push origin master 2> /dev/null

    cd feedstocks
    for dir in ./*; do
        [ -d "${dir}" ] || continue
        (cd $dir && python ../../.CI/update_token.py)
    done

fi

