#!/usr/bin/env bash

# Expected to be run in a TravisCI context.

set -e

if [ -n "$GH_TOKEN" ]; then
    # Install Miniconda.
    echo ""
    echo "Installing a fresh version of Miniconda."
    curl -L https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh > ~/miniconda.sh
    bash ~/miniconda.sh -b -p ~/miniconda
    source ~/miniconda/bin/activate root

    # Configure conda.
    echo ""
    echo "Configuring conda."
    conda config --set show_channel_urls true
    conda config --add channels conda-forge
    conda install --yes --quiet git=2.12.2
    conda install --yes --quiet conda-smithy conda-execute gitpython
    conda install --yes --quiet conda-forge-build-setup
    source run_conda_forge_build_setup

    mkdir -p ~/.conda-smithy && echo $GH_TOKEN > ~/.conda-smithy/github.token

    mkdir feedstocks && cd feedstocks
    python ../.CI/update_token.py

fi

