context:
  version: "1.8.1"

package:
  name: sbb-tui
  version: ${{ version }}

source:
  - url: https://github.com/Necrom4/sbb-tui/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 602067ce869d1f492c9e88f127de9e9a3ba8fe6ee28550d59ced09c81eafdab6
    target_directory: src
  - if: win
    then:
      url: https://raw.githubusercontent.com/mattn/go-localereader/refs/heads/master/LICENSE
      sha256: dceede03550621e65ec7b79fcba87cf6dbb9d31132a8ae71a8fe8ceec0af7da3
      file_name: LICENSE-go-localereader

build:
  number: 0
  script:
    - cd src
    - if: unix
      then:
        - go-licenses save . --save_path ../library_licenses
        - go build -v -o $PREFIX/bin/sbb-tui -ldflags="-s -w -X main.version=${{ version }}"
      else:
        - go-licenses save . --save_path ../library_licenses --ignore github.com/mattn/go-localereader
        - go build -v -o %LIBRARY_BIN%\sbb-tui.exe -ldflags="-s -X main.version=${{ version }}"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: sbb-tui --version
  - package_contents:
      bin:
        - sbb-tui
      strict: true

about:
  homepage: https://github.com/Necrom4/sbb-tui
  summary: TUI client for Switzerland's public transport timetables
  description: |
    A terminal user interface client for Switzerland's public transport
    timetables (SBB/CFF/FFS), inspired by the official SBB app.
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
    - if: win
      then:
        - LICENSE-go-localereader
  repository: https://github.com/Necrom4/sbb-tui

extra:
  recipe-maintainers:
    - pavelzw
