schema_version: 1

context:
  name: newton
  version: v1.0.0rc2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/newton-physics/newton/archive/refs/tags/${{ version }}.zip
  sha256: 59c46e186d679a8978694be36efdcd904545fe6832708d2ef69f2b1791503dd2

build:
  number: 0
  skip: osx
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    # https://github.com/newton-physics/newton/blob/main/pyproject.toml
    - python >=${{ python_min }}
    - warp-lang >=1.11.0
    - newton-actuators
    # [sim]
    - mujoco-warp >=3.5.0
    - mujoco >=3.5.0
    # [importers]
    - requests >=2.25.0
    - scipy
    - fast-simplification >=0.1.11
    - alphashape >=1.3.1
    # - coacd >=1.0.7
    - trimesh >=4.6.8
    - meshio >=5.3.0
    - pycollada >=0.9
    - resolve-robotics-uri-py >=0.4.0
    - openusd >=25.5
    - newton-usd-schemas >=0.1.0rc3
    # [remesh]
    - open3d >=0.18.0
    - pyfqmr >=0.5.0
    # [examples]
    - pyglet >=2.1.6
    - gitpython >=3.1.44
    - imgui-bundle >=1.92.0
    - pyyaml >=6.0.2
    - cbor2 >=5.7.0
    # Other dependencies
    - importlib_resources
  run_constraints:
    - pytorch >=2.7.0

tests:
  - python:
      imports:
        - newton
      pip_check: false
      python_version: ${{ python_min }}.*
  - script:
      - pip check
    requirements:
      run:
        - pip
        - python 3.11.*
        # Fix missing open3d-cpu dependencies.
        - configargparse
        - nbformat

about:
  homepage: https://newton-physics.github.io/newton/
  license: Apache-2.0
  license_file: LICENSE.md
  repository: https://github.com/newton-physics/newton
  summary: An open-source, GPU-accelerated physics simulation engine built upon NVIDIA Warp, specifically targeting roboticists and simulation researchers.

extra:
  recipe-maintainers:
    - adenzler-nvidia
    - diegoferigo
    - eric-heiden
    - preist-nvidia
