context:
  name: opencode
  version: "1.0.146"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/anomalyco/opencode/archive/refs/tags/v${{ version }}.tar.gz
    sha256: f7bcdfbcf07bd0b1de105f7d5faa0898af2e0afb8f94ad01ef149d116880bc5b

build:
  script: |
    sed -i.bak 's/if (!semver.satisfies(process.versions.bun/if (false \&\& !semver.satisfies(process.versions.bun/' \
    packages/script/src/index.ts
    mv package.json package.json.bak
    jq 'del(.devDependencies)' package.json.bak > package.json
    bun install --ignore-scripts
    bunx license-checker --production --plainTextOutput third-party-licenses.txt
    mv package.json.bak package.json
    rm -rf node_modules
    bun install --ignore-scripts
    cd packages/opencode
    bun run build --single
    bun pm pack
    npm install --global --prefix ${{ PREFIX }} --build-from-source ${{ name }}-${{ version }}.tgz
  number: 0

requirements:
  build:
    - bun
    - jq
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - opencode --help
      - opencode --version

about:
  homepage: https://opencode.ai
  summary: The open source coding agent.
  license: MIT
  license_file:
    - LICENSE
    - package/third-party-licenses.txt
  documentation: https://opencode.ai/docs
  repository: https://github.com/sst/opencode

extra:
  recipe-maintainers:
    - pavelzw
    - moritzwilksch
