context:
  version: "0.9.0"

package:
  name: kompute
  version: ${{ version }}

source:
  url: https://github.com/KomputeProject/kompute/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 901f609029033f1b97de8189228229d25508408c9f7f1dda0e75b2fa632f3521
  patches:
    - patches/0001-fmt-ranges.patch
    - patches/0002-logging-macros-debug.patch
    - patches/0003-remove-python-build-cond.patch
    - patches/0004-fmt-format.patch
    - patches/0005-python-module-build-dep.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then: make
    - if: win
      then: jom
  host:
    - fmt
    - pybind11
    - python
    - vulkan-headers
    - libvulkan-loader
  run:
    - numpy
    - python
  run_exports:
    - ${{ pin_subpackage("kompute", upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - kompute/Kompute.hpp
      lib:
        - kompute
  - python:
      imports:
        - kp
      pip_check: true
      python_version: ${{ python }}
  - script:
      - make test_python
    requirements:
      run:
        - glslang
        - make
        - pyshader
        - pytest
    files:
      source:
        - python/test/
        - Makefile

about:
  homepage: https://kompute.cc
  repository: https://github.com/KomputeProject/kompute
  documentation: https://kompute.cc
  license: Apache-2.0
  license_file: LICENSE
  summary: The general purpose GPU compute framework for cross vendor graphics cards (AMD, Qualcomm, NVIDIA & friends)
  description: |
    General purpose GPU compute framework built on Vulkan to support 1000s of cross vendor graphics cards (AMD, Qualcomm, NVIDIA & friends).
    Blazing fast, mobile-enabled, asynchronous and optimized for advanced GPU data processing usecases.
    Backed by the Linux Foundation.

extra:
  recipe-maintainers:
    - eunos-1128
