context:
  name: rapidminer-ai-runtime
  version: "2.0"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://maven.rapidminer.com/repository/pypi-snapshot/packages/rapidminer-ai-runtime/${{ version }}/rapidminer_ai_runtime-${{ version }}.tar.gz
  sha256: 327bf935388ccbd5576122991dd884eb816cfe735128444dd4193a5fff91d5ec

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.24.4
    - packaging >=24.1
    - pandas >=2.0.3
    - pydantic >=2.0.3,<3.0
    - rapidminer-ai-core >=2.0
    - websockets >=16.0
    - pyarrow >=19.0.1

tests:
  - python:
      imports:
      - rapidminer
#      - rapidminer.core
#      - rapidminer.ai
#      - rapidminer.ai.ext
      pip_check: true

about:
  homepage: https://www.siemens.com/en-us/products/rapidminer/
  summary: 'rapidminer-ai-runtime is a comprehensive Python package for running Rapidminer AI extensions in Python.'
  description: |
    rapidminer-ai-runtime is a comprehensive Python package for running Rapidminer
    AI extensions in Python, developed for Rapidminer AI Studio, Rapidminer AI Hub
    and Rapidminer AI Cloud.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skontar-altair
    - tjarvas-altair
    - mboeck-siemens
