schema_version: 1

context:
  name: gaphor
  version: 3.2.0
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gaphor-${{ version }}.tar.gz
  sha256: b2dcc1b1c67ec4094c92c0929b3c8156a53d7ad9acdb05ce7c11840482474412

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  python:
    entry_points:
      - gaphor = gaphor.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pycairo >=1.22.0
    - pygobject >=3.52
    - gaphas >=5.0
    - python-generic >=1.0.0
    - tinycss2 >=1.0.2
    - babel >=2.10.3
    - jedi >=0.18.1,<0.20.0
    - better-exceptions >=0.3.3
    - pydot >=1.4.2,<4.0.0
    - pillow >=10.0.0
    - defusedxml >=0.7.1
    - dulwich >=0.21.7,<0.23.0
    - gtk4
    - libadwaita
    - adwaita-icon-theme
    - gtksourceview
    - if: osx
      then:
        - __osx
        - pyobjc-framework-cocoa >=9.0.1,<11.0.0

tests:
  - python:
      imports:
        - gaphor
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - gtk4
        - libadwaita
        - gtksourceview
    script:
      - gaphor --help

about:
  summary: Gaphor is the simple modeling tool written in Python.
  license: Apache-2.0
  license_file:
    - LICENSES/Apache-2.0.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-or-later.txt
  homepage: https://gaphor.org
  repository: https://github.com/gaphor/gaphor
  documentation: https://docs.gaphor.org

extra:
  recipe-maintainers:
    - danyeaw
