"""Type stubs for the gm2calc ctypes interface.

Generated to match the bindings in gm2calc.py so editors and type checkers
can see the methods that are attached dynamically at import time.
"""

from typing import Any, Sequence, Union, overload

Matrix = Sequence[Sequence[float]]

__all__ = [
    "GM2CalcError",
    "MSSMNoFV",
    "SM",
    "THDM",
    "THDMConfig",
    "THDMGaugeBasis",
    "THDMMassBasis",
    "YukawaType",
    "error_str",
]

def error_str(code: int) -> str: ...

class GM2CalcError(Exception): ...

class YukawaType:
    type_1: int
    type_2: int
    type_X: int
    type_Y: int
    aligned: int
    general: int

class MSSMNoFV:
    def __init__(self) -> None: ...
    def set_verbose_output(self, enable: bool) -> None: ...
    def calculate_masses(self) -> None: ...
    def convert_to_onshell(self) -> None: ...
    def have_problem(self) -> bool: ...
    def have_warning(self) -> bool: ...
    def get_problems(self) -> str: ...
    def get_warnings(self) -> str: ...
    def set_alpha_MZ(self, value: float) -> None: ...
    def set_alpha_thompson(self, value: float) -> None: ...
    def set_g3(self, value: float) -> None: ...
    def set_MassB(self, value: float) -> None: ...
    def set_MassWB(self, value: float) -> None: ...
    def set_MassG(self, value: float) -> None: ...
    def set_Mu(self, value: float) -> None: ...
    def set_TB(self, value: float) -> None: ...
    def set_scale(self, value: float) -> None: ...
    def set_MAh_pole(self, value: float) -> None: ...
    def set_MZ_pole(self, value: float) -> None: ...
    def set_MW_pole(self, value: float) -> None: ...
    def set_MT_pole(self, value: float) -> None: ...
    def set_MB_running(self, value: float) -> None: ...
    def set_ML_pole(self, value: float) -> None: ...
    def set_MM_pole(self, value: float) -> None: ...
    def set_MSvmL_pole(self, value: float) -> None: ...
    def set_MSm_pole(self, i: int, value: float) -> None: ...
    def set_MCha_pole(self, i: int, value: float) -> None: ...
    def set_MChi_pole(self, i: int, value: float) -> None: ...
    @overload
    def set_Ae(self, matrix: Matrix) -> None: ...
    @overload
    def set_Ae(self, i: int, j: int, value: float) -> None: ...
    @overload
    def set_Au(self, matrix: Matrix) -> None: ...
    @overload
    def set_Au(self, i: int, j: int, value: float) -> None: ...
    @overload
    def set_Ad(self, matrix: Matrix) -> None: ...
    @overload
    def set_Ad(self, i: int, j: int, value: float) -> None: ...
    @overload
    def set_mq2(self, matrix: Matrix) -> None: ...
    @overload
    def set_mq2(self, i: int, j: int, value: float) -> None: ...
    @overload
    def set_mu2(self, matrix: Matrix) -> None: ...
    @overload
    def set_mu2(self, i: int, j: int, value: float) -> None: ...
    @overload
    def set_md2(self, matrix: Matrix) -> None: ...
    @overload
    def set_md2(self, i: int, j: int, value: float) -> None: ...
    @overload
    def set_ml2(self, matrix: Matrix) -> None: ...
    @overload
    def set_ml2(self, i: int, j: int, value: float) -> None: ...
    @overload
    def set_me2(self, matrix: Matrix) -> None: ...
    @overload
    def set_me2(self, i: int, j: int, value: float) -> None: ...
    def get_EL(self) -> float: ...
    def get_EL0(self) -> float: ...
    def get_gY(self) -> float: ...
    def get_g1(self) -> float: ...
    def get_g2(self) -> float: ...
    def get_g3(self) -> float: ...
    def get_TB(self) -> float: ...
    def get_MassB(self) -> float: ...
    def get_MassWB(self) -> float: ...
    def get_MassG(self) -> float: ...
    def get_Mu(self) -> float: ...
    def get_vev(self) -> float: ...
    def get_scale(self) -> float: ...
    def get_MW(self) -> float: ...
    def get_MZ(self) -> float: ...
    def get_ME(self) -> float: ...
    def get_MM(self) -> float: ...
    def get_ML(self) -> float: ...
    def get_MU(self) -> float: ...
    def get_MC(self) -> float: ...
    def get_MT(self) -> float: ...
    def get_MD(self) -> float: ...
    def get_MS(self) -> float: ...
    def get_MB(self) -> float: ...
    def get_MBMB(self) -> float: ...
    def get_MAh(self) -> float: ...
    def get_MSveL(self) -> float: ...
    def get_MSvmL(self) -> float: ...
    def get_MSvtL(self) -> float: ...
    def get_Mhh(self, i: int) -> float: ...
    def get_MCha(self, i: int) -> float: ...
    def get_MChi(self, i: int) -> float: ...
    def get_MSe(self, i: int) -> float: ...
    def get_MSm(self, i: int) -> float: ...
    def get_MStau(self, i: int) -> float: ...
    def get_MSu(self, i: int) -> float: ...
    def get_MSd(self, i: int) -> float: ...
    def get_MSc(self, i: int) -> float: ...
    def get_MSs(self, i: int) -> float: ...
    def get_MSt(self, i: int) -> float: ...
    def get_MSb(self, i: int) -> float: ...
    def get_Ae(self, i: int, j: int) -> float: ...
    def get_Ad(self, i: int, j: int) -> float: ...
    def get_Au(self, i: int, j: int) -> float: ...
    def get_mq2(self, i: int, j: int) -> float: ...
    def get_md2(self, i: int, j: int) -> float: ...
    def get_mu2(self, i: int, j: int) -> float: ...
    def get_ml2(self, i: int, j: int) -> float: ...
    def get_me2(self, i: int, j: int) -> float: ...
    def get_USe(self, i: int, j: int) -> float: ...
    def get_USm(self, i: int, j: int) -> float: ...
    def get_UStau(self, i: int, j: int) -> float: ...
    def get_USu(self, i: int, j: int) -> float: ...
    def get_USd(self, i: int, j: int) -> float: ...
    def get_USc(self, i: int, j: int) -> float: ...
    def get_USs(self, i: int, j: int) -> float: ...
    def get_USt(self, i: int, j: int) -> float: ...
    def get_USb(self, i: int, j: int) -> float: ...
    def get_Ye(self, i: int, j: int) -> float: ...
    def get_Yd(self, i: int, j: int) -> float: ...
    def get_Yu(self, i: int, j: int) -> float: ...
    def calculate_amu_1loop(self) -> float: ...
    def calculate_amu_1loop_non_tan_beta_resummed(self) -> float: ...
    def calculate_amu_2loop(self) -> float: ...
    def calculate_amu_2loop_non_tan_beta_resummed(self) -> float: ...
    def calculate_uncertainty_amu_0loop(self) -> float: ...
    def calculate_uncertainty_amu_1loop(self) -> float: ...
    def calculate_uncertainty_amu_2loop(self) -> float: ...
    def amu1LChi0(self) -> float: ...
    def amu1LChipm(self) -> float: ...
    def amu2LFSfapprox(self) -> float: ...
    def amu2LFSfapprox_non_tan_beta_resummed(self) -> float: ...
    def amu2LChipmPhotonic(self) -> float: ...
    def amu2LChi0Photonic(self) -> float: ...
    def amu2LaSferm(self) -> float: ...
    def amu2LaCha(self) -> float: ...

class SM:
    alpha_em_0: float
    alpha_em_mz: float
    alpha_s_mz: float
    mh: float
    mw: float
    mz: float
    mu: Any
    md: Any
    mv: Any
    ml: Any
    ckm_real: Any
    ckm_imag: Any
    def __init__(self) -> None: ...
    def set_alpha_em_0(self, value: float) -> None: ...
    def set_alpha_em_mz(self, value: float) -> None: ...
    def set_alpha_s_mz(self, value: float) -> None: ...
    def set_mh(self, value: float) -> None: ...
    def set_mw(self, value: float) -> None: ...
    def set_mz(self, value: float) -> None: ...
    def set_mu(self, i: int, value: float) -> None: ...
    def set_md(self, i: int, value: float) -> None: ...
    def set_mv(self, i: int, value: float) -> None: ...
    def set_ml(self, i: int, value: float) -> None: ...

class THDMConfig:
    force_output: int
    running_couplings: int
    def __init__(self) -> None: ...

class THDMMassBasis:
    yukawa_type: int
    mh: float
    mH: float
    mA: float
    mHp: float
    sin_beta_minus_alpha: float
    lambda_6: float
    lambda_7: float
    tan_beta: float
    m122: float
    zeta_u: float
    zeta_d: float
    zeta_l: float
    Delta_u: Any
    Delta_d: Any
    Delta_l: Any
    Pi_u: Any
    Pi_d: Any
    Pi_l: Any
    def __init__(self) -> None: ...

class THDMGaugeBasis:
    yukawa_type: int
    lambda_: Any
    tan_beta: float
    m122: float
    zeta_u: float
    zeta_d: float
    zeta_l: float
    Delta_u: Any
    Delta_d: Any
    Delta_l: Any
    Pi_u: Any
    Pi_d: Any
    Pi_l: Any
    def __init__(self) -> None: ...

class THDM:
    def __init__(
        self,
        basis: Union[THDMMassBasis, THDMGaugeBasis],
        sm: SM,
        config: THDMConfig | None = ...,
    ) -> None: ...
    def calculate_amu_1loop(self) -> float: ...
    def calculate_amu_2loop(self) -> float: ...
    def calculate_amu_2loop_bosonic(self) -> float: ...
    def calculate_amu_2loop_fermionic(self) -> float: ...
    def calculate_uncertainty_amu_0loop(self) -> float: ...
    def calculate_uncertainty_amu_1loop(self) -> float: ...
    def calculate_uncertainty_amu_2loop(self) -> float: ...
