context:
  version: 0.0.10
  build_number: "0"
  python_min: "3.10"

package:
  name: format-currency
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/format-currency/format_currency-${{ version }}.tar.gz
    sha256: 15f01e5aaecf7c636815911cf0cbab0b117c8a6bd992d61a666f5e038cce32d9

build:
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - format_currency
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A no-frill currency formatting python library.
  homepage: https://github.com/arifwn/format-currency
  repository: https://github.com/arifwn/format-currency
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - davidbrochart
