schema_version: 1

context:
  name: glim
  version: "1.2.0"

recipe:
  name: ${{ name|lower }}-split
  version: ${{ version }}

source:
  - url: https://github.com/koide3/glim/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 8e0f5f20b5fe03cf5c9f91cd08458bf468324a7532bcb1957e5db70971daa037
    patches:
      - 0001-fix-fmt-ptr-shared-ptr.patch

outputs:
  - package:
      name: ${{ name|lower }}
    build:
      script:
        - cmake -S . -B build -GNinja
          ${CMAKE_ARGS}
          ${{ "${CMAKE_ARGS}" if not win else "%CMAKE_ARGS%" }}
          -DBUILD_WITH_CUDA=${{ "ON" if cuda_compiler_version != "None" else "OFF" }}
          -DCMAKE_CUDA_ARCHITECTURES="${{ '86' if cuda_compiler_version != "None" else '' }}"
          -DCMAKE_CUDA_FLAGS="-Wno-deprecated-gpu-targets"
          -DBUILD_WITH_VIEWER=OFF
          -DBUILD_WITH_MARCH_NATIVE=OFF
          -DBUILD_WITH_OPENCV=ON
        - cmake --build build --config Release
        - cmake --install build/ --config Release
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }} 
        - ${{ stdlib("c") }}
        - if: cuda_compiler_version != "None"
          then: ${{ compiler('cuda') }}
        - cmake
        - ninja
        - pkg-config
      host:
        - gtsam
        - gtsam-points
        - eigen-abi-devel <4.0
        - libboost-devel
        - tbb-devel
        - spdlog
        - fmt
        - nlohmann_json
        - if: target_platform == "linux-aarch64"
          then: libopencv <4.12
          else: libopencv
        - if: cuda_compiler_version != "None"
          then:
            - cuda-version ${{ cuda_compiler_version }}.*
            - cuda-cudart-dev
            - libcublas-dev
            - libcurand-dev
            - libcusparse-dev
            - libcusolver-dev
      run:
      run_exports:
        - ${{ pin_subpackage('glim', upper_bound='x.x.x') }}
    tests:
      - package_contents:
          include:
            - glim/util/config.hpp
          lib:
            - glim
  - package:
      name: ${{ name|lower }}-devel
    requirements:
      run:
        - ${{ pin_subpackage('glim', exact=True) }}
        - eigen <4.0
        - libboost-devel
    tests:
      - script:
          - cmake-package-check glim --targets glim
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('cxx') }}
            - cmake
            - ninja
            - if: cuda_compiler_version != "None"
              then: ${{ compiler('cuda') }}

about:
  homepage: https://koide3.github.io/glim/
  license: MIT
  license_file: LICENSE
  repository: https://github.com/koide3/glim
  summary: GLIM: versatile and extensible point cloud-based 3D localization and mapping framework.

extra:
  feedstock-name: glim
  recipe-maintainers:
    - diegoferigo
