@echo on

cmake %CMAKE_ARGS% -S . -B build-conda -G Ninja ^
  -DCMAKE_BUILD_TYPE=Release ^
  -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
  -DCMAKE_INSTALL_LIBDIR=lib ^
  -DANDROID_PREBUILD=OFF ^
  -DBUILD_SHARED_LIBS=ON ^
  -DBUILD_AS_BUNDLE=OFF ^
  -DBUILD_APP=ON ^
  -DBUILD_TOOLS=ON ^
  -DBUILD_EXAMPLES=ON ^
  -DBUILD_OPENGV=OFF ^
  -DBUILD_WITH_RPATH_NOT_RUNPATH=OFF ^
  -DFLANN_KDTREE_MEM_OPT=OFF ^
  -DMULTI_ARCH=OFF ^
  -DPCL_OMP=ON ^
  -DRTABMAP_QT_VERSION=6 ^
  -DWITH_ALICE_VISION=OFF ^
  -DWITH_APRILTAG=ON ^
  -DWITH_CCCORELIB=OFF ^
  -DWITH_CERES=ON ^
  -DWITH_CPUTSDF=OFF ^
  -DWITH_CUDASIFT=OFF ^
  -DWITH_CUVSLAM=OFF ^
  -DWITH_CVSBA=OFF ^
  -DWITH_DC1394=OFF ^
  -DWITH_DEPTHAI=OFF ^
  -DWITH_DVO=OFF ^
  -DWITH_FASTCV=OFF ^
  -DWITH_FLOAM=OFF ^
  -DWITH_FOVIS=OFF ^
  -DWITH_FREENECT=OFF ^
  -DWITH_FREENECT2=OFF ^
  -DWITH_FLYCAPTURE2=OFF ^
  -DWITH_G2O=OFF ^
  -DWITH_GRIDMAP=OFF ^
  -DWITH_GTSAM=OFF ^
  -DWITH_K4A=OFF ^
  -DWITH_K4W2=OFF ^
  -DWITH_LIBLAS=OFF ^
  -DWITH_LIOSAM=OFF ^
  -DWITH_LOAM=OFF ^
  -DWITH_MADGWICK=OFF ^
  -DWITH_MRPT=OFF ^
  -DWITH_MSCKF_VIO=OFF ^
  -DWITH_MYNTEYE=OFF ^
  -DWITH_OCTOMAP=ON ^
  -DWITH_OKVIS=OFF ^
  -DWITH_OPEN3D=OFF ^
  -DWITH_OPENCHISEL=OFF ^
  -DWITH_OPENGV=OFF ^
  -DWITH_OPENMP=ON ^
  -DWITH_OPENNI=OFF ^
  -DWITH_OPENNI2=OFF ^
  -DWITH_OPENVINS=OFF ^
  -DWITH_ORBBEC_SDK=OFF ^
  -DWITH_ORB_OCTREE=OFF ^
  -DWITH_ORB_SLAM=OFF ^
  -DWITH_PDAL=ON ^
  -DWITH_POINTMATCHER=OFF ^
  -DWITH_PYTHON=OFF ^
  -DWITH_PYTHON_THREADING=OFF ^
  -DWITH_QT=ON ^
  -DWITH_REALSENSE=OFF ^
  -DWITH_REALSENSE2=ON ^
  -DWITH_REALSENSE_SLAM=OFF ^
  -DWITH_TORCH=OFF ^
  -DWITH_TORO=OFF ^
  -DWITH_VERTIGO=OFF ^
  -DVTK_GLOBAL_WARNING_DISPLAY=OFF ^
  -DWITH_VINS_FUSION=OFF ^
  -DWITH_VISO2=OFF ^
  -DWITH_XVSDK=OFF ^
  -DWITH_ZED=OFF ^
  -DWITH_ZEDOC=OFF
if errorlevel 1 exit /b 1

cmake --build build-conda --parallel 2
if errorlevel 1 exit /b 1

cmake --install build-conda
if errorlevel 1 exit /b 1
