context:
  version: "0.26.5"

package:
  name: taskwarrior-tui
  version: ${{ version }}

source:
  url: https://github.com/kdheepak/taskwarrior-tui/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9eebb2f736693cbb64b3a79b88d3e5bbae8603ef9206d47e555c9a9cf9077708

build:
  number: 0
  skip:
    # Support windows in the future when Taskwarrior supports windows
    - win

requirements:
  build:
    - ${{ compiler("rust") }}
    - cargo-auditable
    - cargo-bundle-licenses
  run:
    - taskwarrior

tests:
  - script:
      - taskwarrior-tui --version
      - taskwarrior-tui --report 2>&1 | grep -q "value is required" || exit 1

about:
  homepage: https://kdheepak.com/taskwarrior-tui
  repository: https://github.com/kdheepak/taskwarrior-tui
  documentation: https://kdheepak.com/taskwarrior-tui
  license: MIT
  license_file:
   - LICENSE
   - THIRDPARTY.yml
  summary: A terminal user interface for taskwarrior
  description: |
    A Terminal User Interface (TUI) for [Taskwarrior](https://taskwarrior.org) that you didn't know you wanted.

    ## Features
    - vim-like navigation
    - live filter updates
    - add, delete, complete, log tasks
    - multiple selection
    - tab completion
    - colors based on taskwarrior

extra:
  recipe-maintainers:
    - eunos-1128
