package:
  name: r-parsec_batch_correction
  version: "1.1.0"

source:
  url: https://forge.inrae.fr/api/v4/projects/23034/packages/generic/PARSEC/1.1.0/PARSEC_1.1.0.tar.gz
  sha256: 18ea4051d66a050970dd8543ea1e6aa833ca12891254029268abd642360a8303

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --build .

requirements:
  host:
    - r-base
    - r-lme4
    - r-ggplot2
    - r-patchwork
    - r-rlang
  run:
    - r-base
    - r-lme4
    - r-ggplot2
    - r-patchwork
    - r-rlang

test:
  commands:
    - Rscript -e "library('PARSEC')"

about:
  home: https://parsec-1d46f0.pages-forge.inrae.fr/docs/index.html
  dev_url: https://forge.inrae.fr/pfem/dev/libs/PARSEC
  license: CC-BY-SA-4.0
  license_file: "LICENSE"
  summary: "Provides an algorithm that perform batch effect and cohort effect
   correction on intensity data using a statistical modeling approach based on
   linear mixed models (LMM). This tool is especially suited for omics or
   high-throughput datasets, where batch or injection order can introduce
   unwanted variability."

extra:
  recipe-maintainers:
    - etiennejls
    - conda-forge/r
