# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.0.8"

package:
  name: dydantic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dydantic/dydantic-${{ version }}.tar.gz
  sha256: 14a31d4cdfce314ce3e69e8f8c7c46cbc26ce3ce4485de0832260386c612942f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.0.0,<3.0.0
  run_constraints:
    - email-validator >=2.1.0,<3.0.0

tests:
  - python:
      imports:
        - dydantic
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pypi.org/project/dydantic/
  license: MIT
  license_file: LICENSE
  summary: Dynamically generate pydantic models from JSON schema.
  repository: https://github.com/hinthornw/dydantic
  documentation: https://hinthornw.github.io/dydantic/
  description: |
    Dydantic dynamically creates pydantic models from JSON Schema
    definitions, supporting nested objects, custom configurations, and
    a range of JSON Schema types.

extra:
  recipe-maintainers:
    - rxm7706
