{% set name = "mgzip" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3acc22203e571f83e5764923ea534c0a9638b938ff6a4b4687a575fd0f2f15c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.8

test:
  imports:
    - mgzip
  commands:
    - pip check
    - mgzip --help
  requires:
    - pip

about:
  home: https://github.com/vinlyx/mgzip
  summary: A multi-threading implementation of Python gzip module
  description: |
    mgzip is a multiprocessing solution for gzip compression/decompression.
    It provides a simple replacement of Python internal gzip module to
    provide a multiprocessing solution for gzip compression/decompression.
  license: MIT
  license_file: LICENSE

extra:
  maintainers:
    - Vincent Li (@vinlyx)
  recipe-maintainers:
    - vinlyx
