= mediamtx
:version: 1.11.3


// GENERATED CONTENT START

MediaMTX is a live media server

== Description

MediaMTX is a ready-to-use and zero-dependency real-time media server and media proxy that allows to publish, read, proxy, record and playback video and audio streams. It has been conceived as a "media router" that routes media streams from one end to the other.

== Links

* Homepage: https://github.com/bluenviron/mediamtx/blob/main/README.md
* Repository: https://github.com/bluenviron/mediamtx

== Package Information

* **License**: Apache-2.0
* **Version**: 1.11.3

== Requirements

=== Build Requirements

* cmake
* Go compiler
* go-licenses

== Installation

This package is built using rattler-build and can be installed using mamba or conda:

[source,bash]
----
pixi global install -c meso-forge mediamtx
----

== Maintainers

* phreed

---

_This portion of the README was generated from the recipe.yaml file._

_Last updated: 2025-06-11_

// GENERATED CONTENT END

`mediamtx` is an go package.

* https://github.com/bluenviron/mediamtx

== V1 recipe format

https://github.com/prefix-dev/recipe-format


== Inspiration

* https://github.com/conda-forge/carapace-feedstock/blob/main/recipe/recipe.yaml
* https://github.com/conda-forge/minio-client-feedstock/blob/main/recipe/recipe.yaml
