schema_version: 1

context:
  version: "1.6.1"
  python_min: "3.9"

package:
  name: pytest-durations
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-durations/pytest_durations-${{ version }}.tar.gz
  sha256: bc43fbabb1fef6bb75766d35a6bf142c1e153fef01677ccd4705cc376bf2be34

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pytest >=4.6

tests:
  - python:
      imports:
        - pytest_durations
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Pytest plugin reporting fixtures and test functions execution time.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/blake-r/pytest-durations

extra:
  recipe-maintainers:
    - baszalmstra
