{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcolorconesa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RColorConesa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RColorConesa/RColorConesa_{{ version }}.tar.gz
  sha256: 46f1ac3a18fcb4764aa1e0d5acb71652cc5616959c6c9fbceaaae179e15e822c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('RColorConesa')"           # [not win]
    - "\"%R%\" -e \"library('RColorConesa')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RColorConesa
  license: MIT
  summary: Provides a collection of palettes designed to integrate with 'ggplot', reflecting
    the color schemes associated with 'ConesaLab'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
    - paboati

# Package: RColorConesa
# Title: Conesa Colors Palette
# Version: 1.0.0
# Authors@R: person("Pedro", "Salguero Garcia", , "pedrosalguerog@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1879-3374"))
# Maintainer: Pedro Salguero Garcia <pedrosalguerog@gmail.com>
# Description: Provides a collection of palettes designed to integrate with 'ggplot', reflecting the color schemes associated with 'ConesaLab'.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: ggplot2
# Suggests: testthat (>= 3.0.0)
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2023-09-12 08:37:20 UTC; Ps
# Author: Pedro Salguero Garcia [aut, cre] (<https://orcid.org/0000-0002-1879-3374>)
# Repository: CRAN
# Date/Publication: 2023-09-12 20:30:09 UTC
