# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.1.1"

package:
  name: langchain-sambanova
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/langchain-sambanova/langchain_sambanova-${{ version }}.tar.gz
  sha256: 1801b9b1c945de7b6e97e3b98082d5e3bf133e27aebc6fa801d0b115ac8fad93

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - langchain-core >0.3.0,<2.0.0
    - types-requests
    - sambanova >=1.9.1,<2.0.0

tests:
  - python:
      imports:
        - langchain_sambanova
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/sambanova/langchain-sambanova
  license: MIT
  license_file: LICENSE
  summary: An integration package connecting SambaNova and LangChain
  repository: https://github.com/sambanova/langchain-sambanova
  documentation: https://github.com/sambanova/langchain-sambanova
  description: |
    This package contains the LangChain integration with SambaNova,
    providing LangChain-compatible chat models and embeddings backed by
    the SambaNova Cloud and SambaStack APIs.

extra:
  recipe-maintainers:
    - rxm7706
