schema_version: 1

context:
  name: lazyslide-models
  version: 0.0.0.post7.dev0
  python_min: "3.11"
  github_owner: rendeirolab
  github_name: lazyslide-models
  github_rev: ae00e6d6089978f8f63fa34e49b241930d66fc57

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/${{ github_owner }}/${{ github_name }}/archive/${{ github_rev }}.tar.gz
  sha256: 4315c7327fd19e9dcd65524b1bef8db025d3fd491b98699b0da01b730cbcbe71

build:
  number: 0
  noarch: python
  script: UV_DYNAMIC_VERSIONING_BYPASS=${{ version }} ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.0.0
    - timm >=1.0.3
    - pytorch >=2.1.0
    - transformers >=4.0.0
    - pandas
    - opencv
    - scipy
    - scikit-image
    - platformdirs

tests:
  - python:
      imports:
        - lazyslide_models
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The model zoo for LazySlide
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/${{ github_owner }}/${{ github_name }}
  repository: https://github.com/${{ github_owner }}/${{ github_name }}

extra:
  recipe-maintainers:
    - SamirMoustafa
