{% set name = "sacroviewer" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AI-SDC/SACRO-Viewer/archive/v{{ version }}.tar.gz
  sha256: 7f0d50f69c464471eeb5d955fe30d76d6e161d6e1bf4c7f24d434c46be3b06cd

build:
  number: 0
  noarch: python
  script: bash {{ RECIPE_DIR }}/build.sh
  entry_points:
    - sacroviewer = sacro.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - nodejs
    - hatchling
    - hatch-nodejs-version
    - hatch-requirements-txt
    # Requirements for collectstatic
    - django <4.2
    - django-extensions
    - django-htmx
    - django-vite
    - environs
    - requests
    - slippers
    - structlog
    - uvicorn
    - whitenoise
    - brotli-python
  run:
    - python >={{ python_min }}
    - django <4.2
    - django-extensions
    - django-htmx
    - django-vite
    - environs
    - requests
    - slippers
    - structlog
    - uvicorn
    - whitenoise
    - brotli-python

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - sacro
  env:
    DJANGO_SETTINGS_MODULE: "sacro.settings"
    SECRET_KEY: "dummy"
    SACRO_APP_TOKEN: "dummy"
  commands:
    - pip check
    - timeout 5 sacroviewer --help || true  # [unix]
    - start /b sacroviewer --help & timeout /t 5 & taskkill /f /im sacroviewer.exe || true  # [win]

about:
  home: https://github.com/AI-SDC/SACRO-Viewer
  license: MIT
  license_file: LICENSE
  summary: A viewer for research outputs produced using the ACRO tools
  dev_url: https://github.com/AI-SDC/SACRO-Viewer

extra:
  recipe-maintainers:
    - JessUwe
