context:
  version: "0.0.7"

package:
  name: jupyter-ai-acp-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-ai-acp-client/jupyter_ai_acp_client-${{ version }}.tar.gz
  sha256: 5b16bc2b431f814417ad63a3439ccb7fffa0e29c5152ce822faa26e781dc1e70

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
  run:
    - python >=${{ python_min }}
    - agent-client-protocol
    - jupyter-ai-persona-manager >=0.0.6
    - jupyter_server >=2.4.0,<3
    - jupyterlab-chat >=0.20.0
    - pydantic >=2,<3

tests:
  - python:
      imports:
        - jupyter_ai_acp_client
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-ai-acp-client
  summary: "The ACP client implementation in Jupyter AI"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-ai-acp-client

extra:
  recipe-maintainers:
    - dlqqq
    - andrii-i
