{% set name = "pydlr" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydlr-{{ version }}.tar.gz
  sha256: 6876ac6cc93b99df309bc4c0ed70e560b80c522ba21b4b3b26ad415dcbaea402

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - pydlr
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jasonkaye/libdlr
  summary: Imaginary time calculations using the Discrete Lehmann Representation (DLR)
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/jasonkaye/libdlr

extra:
  recipe-maintainers:
    - Mo-Seong-Jun
