# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: sema4ai-mcp
  version: "0.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sema4ai_mcp-${{ version }}.tar.gz
  sha256: 0491c4b6d36791fe4f45fc5b617b0346bc69bfe57b71eba42b2eea5e7c0d9983

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4
    - sema4ai-actions >=1.6.0,<2.0.0

tests:
  - python:
      imports:
        - sema4ai.mcp
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Sema4AI Model Context Protocol (MCP)
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Sema4AI/actions/

extra:
  recipe-maintainers:
    - rxm7706
