context:
  name: NLR-rex
  version: "0.6.1"
  build_number: '0'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0]|lower }}/${{ name|lower|replace('-', '_') }}/${{ name|lower|replace('-', '_') }}-${{ version }}.tar.gz
  sha256: eee1a3184eca5e1abd35d4ead4815653d29a52428b1fcaddd74a82ee3f2a4804

build:
  noarch: python
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
    - rex = rex.resource_extraction.resource_cli:main
    - NSRDBX = rex.resource_extraction.nsrdb_cli:main
    - WINDX = rex.resource_extraction.wind_cli:main
    - WaveX = rex.resource_extraction.wave_cli:main
    - MultiYearX = rex.resource_extraction.multi_year_resource_cli:main
    - US-wave = rex.resource_extraction.US_wave_cli:main
    - rechunk = rex.rechunk_h5.rechunk_cli:main
    - combine-h5 = rex.rechunk_h5.combine_h5_cli:main
    - temporal-stats = rex.temporal_stats.temporal_stats_cli:main
    - wind-rose = rex.joint_pd.wind_rose_cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click >=8.1.8
    - fsspec >=2021.09.0
    - dask >=2026.8.0
    - h5py >=3.13.0
    - h5pyd >=0.18.0,<1
    - numpy >=2.0.2,<3
    - pandas >=3.0.5,<4
    - packaging >=24.2
    - psutil >=7.0.0
    - PyYAML >=6.0.2
    - s3fs >=2023.6.0
    - scikit-learn >=1.6.1
    - scipy >=1.3
    - toml >=0.10.2
    - xarray >=2026.07.0

tests:
  - python:
      imports:
        - rex
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  homepage: https://www.nlr.gov/research/software/rex-resource-extraction-tool
  summary: 'REsource eXtraction Tool (rex)'
  description: |
    rex stands for **REsource eXtraciton** tool. rex enables the efficient and scalable extraction, manipulation, and
    computation with NLRs flagship renewable resource datasets such as: the Wind Integration National Dataset (WIND Toolkit),
    the National Solar Radiation Database (NSRDB), the Ocean Surface Wave Hindcast (US Wave) Data, and the
    High-resolution downscaled climate change data (Sup3rCC).
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://simplejson.readthedocs.io/
  repository: https://natlabrockies.github.io/rex/

extra:
  recipe-maintainers:
    - ppinchuk
    - grantbuster
    - bnb32
