c_stdlib:
  - sysroot  # [linux]
  - macosx_deployment_target  # [osx]
c_stdlib_version:
  - "2.17"  # [linux]
  - "11.0"  # [osx]
blas_impl:
  - mkl  # [linux64]
  - openblas  # [linux and aarch64]
  - accelerate  # [osx]
nrgljubljana_build_tests:
  - "OFF"
nrgljubljana_test_long:
  - "OFF"
nrgljubljana_enable_mathematica:
  - "OFF"
nrgljubljana_strict_floating_point:
  - "OFF"
nrgljubljana_build_jobs:
  - "0"
nrgljubljana_test_jobs:
  - "0"
nrgljubljana_test_timeout:
  - "7200"
nrgljubljana_test_regex:
  - ""
