context:
  version: "0.5"

package:
  name: ccache-storage-http-cpp
  version: ${{ version }}

source:
  url: https://github.com/ccache/ccache-storage-http-cpp/archive/refs/tags/v${{ version }}.tar.gz
  sha256: bfcefccb6969bf0700717b52d6c315fa1294cdcab57212136a2a6796f11c09b4
  patches:
    - windows-install-copy.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - zlib
    - libcurl
    - libuv

tests:
  - package_contents:
      bin:
        - ccache-storage-http
        - ccache-storage-https

about:
  homepage: https://github.com/ccache/ccache-storage-http-cpp
  summary: ccache HTTP(S) storage helper (C++)
  description: |
    ccache-storage-http-cpp is a ccache remote storage helper for HTTP/HTTPS,
    implemented in C++.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/ccache/ccache-storage-http-cpp

extra:
  recipe-maintainers:
    - traversaro
