context:
  version: "1.0.3"

package:
  name: ahocorasick-rs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ahocorasick-rs/ahocorasick_rs-${{ version }}.tar.gz
  sha256: 579d37070a7c21da9cd9988b9fb471297273b60cb4126586d6dcd99faafc5ca5

build:
  number: 0
  skip: match(python, "<3.10")
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python
    - if: match(python, "<3.12")
      then: typing_extensions >=4.6

tests:
  - python:
      imports:
        - ahocorasick_rs
      pip_check: true
  - requirements:
      run:
        - pytest
        - hypothesis
    files:
      source:
        - tests/
    script: python -m pytest tests/ -q

about:
  homepage: https://github.com/G-Research/ahocorasick_rs
  summary: Fast multi-pattern search for strings and bytes using Aho-Corasick
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/G-Research/ahocorasick_rs

extra:
  recipe-maintainers:
    - iskandr
