diff --git a/Makefile b/Makefile
index 1dec9b3..b28f2ad 100644
--- a/Makefile
+++ b/Makefile
@@ -1,16 +1,11 @@
-CFLAGS=-arch x86_64 -arch arm64 -mmacosx-version-min=10.6
-
 .PHONY: package
 
-macher: append_data.o macher.h macher.c
-	gcc ${CFLAGS} -o macher append_data.o macher.c
+macher: append_data.o macher.o
+	${CC} ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o $@ $^
 
 macher.h:
 	/usr/bin/env python3 make_header.py > macher.h
 
-append_data.o: append_data.c
-	gcc ${CFLAGS} -c append_data.c
-
 package: macher
 	cd package; bash build_package.sh
 
