export C_INCLUDE_PATH="$BUILD_PREFIX/include":$C_INCLUDE_PATH
export INCLUDE_PATH="$BUILD_PREFIX/include":$INCLUDE_PATH
export CPLUS_INCLUDE_PATH="$BUILD_PREFIX/include":$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH="$BUILD_PREFIX/lib":$LD_LIBRARY_PATH
make condainstall PREFIX=$PREFIX CC=$CC CXX=$CXX
