{% set version = '2.6.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-missranger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/missRanger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/missRanger/missRanger_{{ version }}.tar.gz
  sha256: 35dab1b9a0bb9135efb86377e4ad909fb1f6a7aac4da289576983f7eeb8e685a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fnn
    - r-ranger >=0.16.0
  run:
    - r-base
    - r-fnn
    - r-ranger >=0.16.0

test:
  commands:
    - $R -e "library('missRanger')"           # [not win]
    - "\"%R%\" -e \"library('missRanger')\""  # [win]

about:
  home: https://mayer79.github.io/missRanger/
  dev_url: https://github.com/mayer79/missRanger
  license: GPL-2.0-or-later
  summary: Alternative implementation of the beautiful 'MissForest' algorithm used to impute
    mixed-type data sets by chaining random forests, introduced by Stekhoven, D.J. and
    Buehlmann, P. (2012) <doi:10.1093/bioinformatics/btr597>. Under the hood, it uses
    the lightning fast random forest package 'ranger'. Between the iterative model fitting,
    we offer the option of using predictive mean matching. This firstly avoids imputation
    with values not already present in the original data (like a value 0.3334 in 0-1
    coded variable).  Secondly, predictive mean matching tries to raise the variance
    in the resulting conditional distributions to a realistic level. This would allow,
    e.g., to do multiple imputation when repeating the call to missRanger(). Out-of-sample
    application is supported as well.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: missRanger
# Title: Fast Imputation of Missing Values
# Version: 2.6.1
# Authors@R: person("Michael", "Mayer", , "mayermichael79@gmail.com", role = c("aut", "cre"))
# Description: Alternative implementation of the beautiful 'MissForest' algorithm used to impute mixed-type data sets by chaining random forests, introduced by Stekhoven, D.J. and Buehlmann, P. (2012) <doi:10.1093/bioinformatics/btr597>. Under the hood, it uses the lightning fast random forest package 'ranger'. Between the iterative model fitting, we offer the option of using predictive mean matching. This firstly avoids imputation with values not already present in the original data (like a value 0.3334 in 0-1 coded variable).  Secondly, predictive mean matching tries to raise the variance in the resulting conditional distributions to a realistic level. This would allow, e.g., to do multiple imputation when repeating the call to missRanger(). Out-of-sample application is supported as well.
# License: GPL (>= 2)
# Depends: R (>= 3.5.0)
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# Imports: FNN, ranger (>= 0.16.0), stats, utils
# URL: https://github.com/mayer79/missRanger, https://mayer79.github.io/missRanger/
# BugReports: https://github.com/mayer79/missRanger/issues
# Suggests: knitr, rmarkdown, testthat (>= 3.0.0)
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2024-12-07 08:49:20 UTC; mayer
# Author: Michael Mayer [aut, cre]
# Maintainer: Michael Mayer <mayermichael79@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-12-07 09:20:02 UTC
