context:
  version: "0.2.5"
  python_min: "3.9"

package:
  name: marmot-agents
  version: ${{ version }}

source:
  url: https://github.com/JakeNunemaker/marmot/archive/refs/tags/${{ version }}.tar.gz
  sha256: 6e2d9da211ed4382c3996987ef45cd7cf8b8c8510eb0a35cd4dff4f011ac7f89

build:
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - versioneer
    - pip
  run:
    - python >=${{ python_min }}
    - numpy

tests:
  - script:
      - pytest -vvv
    requirements:
      run:
        - pytest >=5.1
        - python ${{ python_min }}.*
    files:
      source:
        - .
  - python:
      imports:
        - marmot
      pip_check: true

about:
  homepage: https://github.com/JakeNunemaker/marmot
  summary: Agent based process modeling.
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE
    - LICENSES/SIMPY

extra:
  recipe-maintainers:
    - julian-belina
