{% set version = "0.0.1" %}

package:
  name: eventcv
  version: {{ version }}

source:
  url: https://github.com/EventLAB-Team/eventcv/archive/v{{ version }}.tar.gz
  sha256: 9c6593458e8ff5f842ddbc27901479e25569eda046deb4193118dec0337e87b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9

test:
  imports:
    - eventcv
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  summary: Open source event-based computer vision library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdamDHines
