context:
  name: kombine-bilby
  version: "0.1.0"
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/kombine_bilby-${{ version }}.tar.gz
  sha256: fd71f0034edabb8485cea5b2447da33ca39e4c28e0632d6785a20dea170ede34

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - python >=${{ python_min }}
    - bilby >=2.3.0
    - kombine

tests:
  - python:
      imports:
        - kombine_bilby
      # kombine has incorrect wheel metadata in conda-forge.
      pip_check: false
      python_version: ${{ python_min }}.*

  - script:
      - python -m pytest tests/ -k "not test_interrupt_sampler"
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
    files:
      source:
        - tests/
        - pyproject.toml

about:
  homepage: https://github.com/bilby-dev/kombine-bilby
  summary: Plugin for using kombine with bilby.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
    - mj-will
