{% set name = "metaflow-functions" %}
{% set version = "0.2.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3651c549a580a1711c2b6e58a495e5e617ce653fa9ff4bd846656a32d1c1c8b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - metaflow >=2.16.0
    - psutil >=5.8.0
    - cffi
    - fastavro
    - ray-default

test:
  imports:
    - metaflow_extensions.nflx.plugins.functions
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Metaflow Functions
  home: https://github.com/Netflix/metaflow-nflx-extensions
  dev_url: https://github.com/Netflix/metaflow-nflx-extensions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - npow
    - romain-intel
