c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 2.17                       # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
  - 11.0                       # [osx]
zig_compiler:
  - zig
zig_compiler_version:
  - 0.15.2
  
# Only tg_ varies - other values computed in recipe via Jinja
tg_:
  - "aarch64"
  - "ppc64le"
  - "s390x"
  - "riscv64"
