conda_build_tool: rattler-build
conda_install_tool: pixi
noarch_platforms:
- linux_64
- win_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
  inspection: update-grayskull
  check_solvable: true
  run_deps_from_wheel: true
