mkdir build-debug
cd build-debug
cmake .. \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_BUILD_TYPE=Debug \
	-DOGDF_USE_ASSERT_EXCEPTIONS=ON \
	-DOGDF_USE_ASSERT_EXCEPTIONS_WITH_STACK_TRACE=ON_LIBUNWIND \
	-DDOC_INSTALL=OFF
make -j 8