{% set version = "0.0.0a4" %}

package:
  name: pypowder
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/P/PyPowder/pypowder-{{ version }}.tar.gz
  sha256: 665a2f43c45ac78d962d5a2eb865263a63594abce3d9538600cebf2d77e79075

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=77.0.3
    - setuptools-scm >=9.2
    - pip
  run:
    - python >=3.9
    - pandas
    - numpy
    - xmltodict
    - matplotlib-base

test:
  imports:
    - PyPOW
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/MaxPelly/PyPOW
  summary: Attempt at constructing a set of tools to convert XRDML files to a more usable format.
  license: GPL-3.0-or-later
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - MaxPelly
