context:
  version: "3.36.0"

package:
  name: azurite
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/azurite/-/azurite-3.36.0.tgz
  sha256: b33f3373449b0b9cc716cafe293a4d1ba6adfdad37ff2c816a3fafbdcbf50f9f

build:
  number: 0

requirements:
  build:
    - nodejs >=18
    - pnpm
    - pnpm-licenses
    - jq
  host:
    - nodejs >=18
  run:
    - nodejs >=18

tests:
  - script:
      - azurite --version
      - azurite-blob --version
      - azurite-queue --version
      - azurite-table --version

about:
  homepage: https://github.com/Azure/Azurite
  summary: 'A lightweight server clone of Azure Storage that simulates most of the commands supported by it with minimal dependencies'
  description: |
    A lightweight server clone of Azure Storage that simulates most of the commands supported by it with minimal dependencies
  license: MIT
  license_file: [LICENSE, ThirdPartyLicenses.txt]
  documentation: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite
  repository: https://github.com/Azure/Azurite

extra:
  recipe-maintainers:
    - EllaBootQC
