# SPDX-License-Identifier: Apache-2.0

{% set name = "chiltepin" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chiltepin-{{ version }}.tar.gz
  sha256: 14a9c25e2df256edeacc251a8694f2317269ccef66be7cf34ca8f46d141610ab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - chiltepin = chiltepin.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
  run:
    - python >=3.10
    - globus-compute-sdk >=4.3.0,<4.7.0
    - globus-compute-endpoint >=4.3.0,<4.7.0
    - parsl >=2025.12.1

test:
  imports:
    - chiltepin
    - chiltepin.cli
    - chiltepin.configure
    - chiltepin.endpoint
    - chiltepin.tasks
    - chiltepin.data
  commands:
    - chiltepin --help

about:
  home: https://github.com/NOAA-GSL/chiltepin
  license: Apache-2.0
  license_file: LICENSE
  summary: Federated NWP Workflow Tools
  description: |
    Chiltepin is a Python library for exploring federated workflow capabilities
    using Parsl and Globus Compute. It provides tools and demonstrations for
    implementing distributed scientific workflows on HPC systems.
  doc_url: https://chiltepin.readthedocs.io
  dev_url: https://github.com/NOAA-GSL/chiltepin

extra:
  recipe-maintainers:
    - christopherwharrop-noaa
