diff --git a/external/spglib/makefile b/external/spglib/makefile
index 8236c57..79bb088 100644
--- a/external/spglib/makefile
+++ b/external/spglib/makefile
@@ -1,6 +1,6 @@
 .DEFAULT:
 
-all: get libsymspg.a
+all:
 
 SPGLIB=spglib-$(SPG_VERSION)
 
diff --git a/external/symmol/makefile b/external/symmol/makefile
index c913c9f..b415b20 100644
--- a/external/symmol/makefile
+++ b/external/symmol/makefile
@@ -2,8 +2,6 @@
 	-touch $@
 all: symmol
 symmol: symmol.f 
-	-wget -c --timeout=10 --tries=1 -nv https://www.mtg.msm.cam.ac.uk/files/symmol.zip
-	-unzip -o symmol.zip symmol.f
 	-patch symmol.f symmol.patch
 	-$(FC) -w -o symmol symmol.f
 clean:
diff --git a/makefile b/makefile
index 707133e..20211a0 100644
--- a/makefile
+++ b/makefile
@@ -7,7 +7,7 @@ CC=gcc # GCC family only
 CFLAGS=
 
 # Define the version of spglib to be used
-export SPG_VERSION=1.14.1
+export SPG_VERSION=1.16.5
 
 PREFIX=$(PWD)
 
diff --git a/src/cabal/src/makefile b/src/cabal/src/makefile
index 04978a7..fbf11e5 100644
--- a/src/cabal/src/makefile
+++ b/src/cabal/src/makefile
@@ -4,14 +4,14 @@ all: cabal
 cabal.o: cabal.f90 spglib_f08.o niggli_reduce.o constants.o
 	$(FC) $(FFLAGS) -c cabal.f90
 spglib_f08.o: spglib_f08.f90
-	$(FC) $(FFLAGS) -c ../../../external/spglib/spglib-$(SPG_VERSION)/example/spglib_f08.f90
+	$(FC) $(FFLAGS) -c ../../../external/spglib/spglib-$(SPG_VERSION)/fortran/spglib_f08.f90
 niggli_reduce.o: ../../common/niggli_reduce.f90 constants.o
 	$(FC) $(FFLAGS) -c ../../common/niggli_reduce.f90
 constants.o: ../../common/constants.f90
 constants.o: ../../common/constants.f90
 	$(FC) $(FFLAGS) -c ../../common/constants.f90
 
-SRC = cabal.f90 ../../../external/spglib/spglib-master/example/spglib_f08.f90 ../../common/niggli_reduce.f90 ../../common/constants.f90
+SRC = cabal.f90 ../../../external/spglib/spglib-master/fortran/spglib_f08.f90 ../../common/niggli_reduce.f90 ../../common/constants.f90
 OBJ = cabal.o spglib_f08.o niggli_reduce.o constants.o
 clean: neat
 	-rm -f cabal
