--- GNUmakefile.orig	2017-03-04 10:22:30.107184773 +0530
+++ GNUmakefile	2017-03-04 10:24:48.671634507 +0530
@@ -15,9 +15,9 @@
 MORI_OBJ= $(MORI_SRC:.c=.o)
 
 
-CC=gcc
+CC?=gcc
 
-CFLAGS=-O3 -g -W -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
+override CFLAGS := -O3 -g -W -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE $(CFLAGS)
 # CFLAGS=-O3 -g				      # add -g for GNU debugger gdb
 # CFLAGS=-Ofast -O3 -mips4 -n32		      # SGI / 32 bit
 # CFLAGS=-Ofast -O3 -mips4 -64                # SGI / 64 bit
