mkdir build
cd build
cmake ^
    -G "Ninja" ^
    -D CMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -D CMAKE_BUILD_TYPE=Release ^
    -D OGRE_BUILD_RENDERSYSTEM_D3D9=FALSE ^
    -D OGRE_BUILD_RENDERSYSTEM_GL=TRUE ^
    -D OGRE_BUILD_RENDERSYSTEM_GL3PLUS=TRUE ^
    -D OGRE_BUILD_SAMPLES=FALSE ^
    -D CMAKE_CXX_FLAGS=-EHsc ^
    -D OGRE_BUILD_DEPENDENCIES=FALSE ^
    -D OGRE_INSTALL_PDB=FALSE ^
    -D OGRE_RESOURCEMANAGER_STRICT=0 ^
    -D OGRE_THREAD_SUPPORT=2 ^
    -D OGRE_THREAD_PROVIDER=1 ^
    %SRC_DIR%
if errorlevel 1 exit 1
ninja install
if errorlevel 1 exit 1