{% set version = "1.0.5" %}

package:
  name: hptt
  version: {{ version }}

source:
  url: https://github.com/springer13/hptt/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 29f8de960f0d8825d3ae82a1bafbcf2c03793e46abbdfac0685ee9d27e2830b1

build:
  number: 0
  skip: true  # [not linux]

  run_exports:
    - {{ pin_subpackage('hptt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - libgomp

test:
  commands:
    - test -f ${PREFIX}/lib/libhptt$SHLIB_EXT

about:
  home: https://github.com/springer13/hptt
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  summary: High-Performance Tensor Transpose library

extra:
  recipe-maintainers:
    - awvwgk
