# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.2.1"

package:
  name: astrapy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/astrapy/astrapy-${{ version }}.tar.gz
  sha256: b1ed99df345adf0adc10a94106346584b7b16550cb515e52b7fb5f8b48c28336

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - astrapy-repl = astrapy.repl:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - deprecation >=2.1.0,<2.2.dev0
    - httpx >=0.25.2,<1
    - h2 >=3,<5
    - h11 >=0.16.0
    - ipython >=8.0.0
    - pymongo >=3
    - toml >=0.10.2,<1.0.0
    - typing_extensions >=4.0
    - uuid6 >=2024.1.12

tests:
  - python:
      imports:
        - astrapy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - astrapy-repl --help

about:
  homepage: https://pypi.org/project/astrapy/
  license: Apache-2.0
  license_file: LICENSE.md
  summary: A Python client for the Data API on DataStax Astra DB
  repository: https://github.com/datastax/astrapy
  documentation: https://docs.datastax.com/en/astra-db-serverless/api-reference/dataapiclient.html
  description: |
    AstraPy is a Pythonic client for the Data API on DataStax Astra DB,
    providing both synchronous and asynchronous interfaces to work with
    databases, collections, tables, documents, and vector search.

extra:
  recipe-maintainers:
    - rxm7706
