schema_version: 1

context:
  python_min: "3.11"
  version: "0.1.0"

package:
  name: sen4cap-client
  version: ${{ version }}

source:
  url: https://github.com/Sen4CAP/sen4cap-client/archive/v${{ version }}.tar.gz
  sha256: a3af2b3692938068c0b112058d7d44fb7494bb617c329d579e83a61360aec286

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sen4cap-client = sen4cap_client.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click
    - pydantic
    - pyyaml
    - typer
    - uri-template
    - httpx
    - cuiman >=0.1.0
    - gavicore >=0.1.0

tests:
  - python:
      imports:
        - sen4cap_client
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - sen4cap-client --help

about:
  summary: Python client for the ESA Sen4CAP project
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Sen4CAP/sen4cap-client

extra:
  recipe-maintainers:
    - pont-us
