schema_version: 1

context:
  version: "1.601"

package:
  name: rename
  version: ${{ version }}

source:
  - url: https://github.com/ap/rename/archive/v${{ version }}.tar.gz
    sha256: e8fd67b662b9deddfb6a19853652306f8694d7959dfac15538a9b67339c87af4
  - url: https://raw.githubusercontent.com/ap/rename/refs/heads/master/LICENSE
    sha256: 93eb4e250a6deef628df1bbef91de51572f80d8f1b2560b0b451b3fe5b4ae22d

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/bin
    - install -m 755 ${SRC_DIR}/rename ${PREFIX}/bin/rename

requirements:
  run:
    - perl

tests:
  - script:
      - touch foo.txt && rename -s .txt .rtf *.txt && test -e foo.rtf

about:
  homepage: http://plasmasturm.org/code/rename
  repository: https://github.com/ap/rename
  documentation: http://plasmasturm.org/code/rename
  license: GPL-1.0-or-later OR Artistic-1.0
  license_file: LICENSE
  summary: Perl-powered file rename script with many helpful built-ins
  description: |
    This program renames files according to modification rules specified on the command line.
    If no filenames are given on the command line, a list of filenames will be expected on standard input.

    The documentation contains a ["TUTORIAL"](http://plasmasturm.org/code/rename/#TUTORIAL).

extra:
  recipe-maintainers:
    - eunos-1128
