context:
  version: "0.3.9"

package:
  name: cargo-wix
  version: ${{ version }}

source:
  url: https://github.com/volks73/cargo-wix/archive/refs/tags/${{ version }}.tar.gz
  sha256: b3d8d915a6759bb28b4c2a57303efbd271fc57b605455807e1c8bab7bc89eb3a

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: cargo-wix --help
  - package_contents:
      bin:
        - cargo-wix
      strict: true

about:
  homepage: https://github.com/volks73/cargo-wix
  summary: Build Windows installers using the WiX Toolset
  description: |
    A subcommand for Cargo that builds a Windows installer (MSI) using the
    WiX Toolset from the contents of a Cargo project. It can optionally sign
    the installer if a code signing certificate is available.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://volks73.github.io/cargo-wix
  repository: https://github.com/volks73/cargo-wix

extra:
  recipe-maintainers:
    - Hofer-Julian
    - baszalmstra
