--- samples/Makefile        2022-06-24 00:23:23.000000000 +0000
+++ samples/Makefile.new    2022-06-27 15:04:32.235125647 +0000
@@ -35,8 +35,8 @@
 
 # Common includes and paths for CUDA
-CUDA_PATH   := /usr/local/cuda
-CUFILE_PATH ?= /usr/local/cuda/targets/x86_64-linux/lib/
-CUFILE_INCLUDE_PATH ?= /usr/local/cuda/targets/x86_64-linux/include/
+CUDA_PATH   := ${PREFIX}
+CUFILE_PATH ?= $(CUDA_PATH)/targets/x86_64-linux/lib/
+CUFILE_INCLUDE_PATH ?= $(CUDA_PATH)/targets/x86_64-linux/include/
 CXXFLAGS    := -Wall
 CXXFLAGS    += -I $(CUDA_PATH)/include/ 
 CXXFLAGS    += -I $(CUFILE_INCLUDE_PATH)

