schema_version: 1

context:
  version: 0.1.2

package:
  name: cbaseline
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cbaseline/cbaseline-${{ version }}.tar.gz
  sha256: f4d17e48adef0fcf99942d9ab2ef1982ec2adb85266417fde3f314f0f9f85581

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy >=1.24
    - scipy >=1.10
    - numba >=0.58

tests:
  - python:
      imports:
        - cbaseline
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  homepage: https://github.com/lhentschel/cbaseline
  repository: https://github.com/lhentschel/cbaseline
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Canonical baselines for Shapley and integrated gradient attribution.
  description: |
    CBaseline constructs prediction-neutral background distributions for
    feature attribution methods such as SHAP and Integrated Gradients.

extra:
  recipe-maintainers:
    - LudgerHentschel
