{% set version = "0.1.1" %}

package:
  name: rooftex
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/rooftex/rooftex-{{ version }}.tar.gz
  sha256: 6e7da94b616ba60e0baca7f8ebf0c4df3c87d575ee4a748894429ddd648b086d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - wheel
    - pip
  run:
    - python >=3.9
    - numpy >=1.22

test:
  imports:
    - rooftex
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/rooftex-dev/rooftex
  summary: 'RoofteX - Rooftop Solar eXchange: rooftop PV potential, adoption dynamics, and profile generation'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msotocalvo
