#!/usr/bin/env bash

export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"

export OCCA_INSTALL_DIR=${PREFIX}
export OCCA_BUILD_DIR=`pwd`/build
export OCCA_BUILD_TYPE="RelWithDebInfo"

export OCCA_ENABLE_DPCPP="ON"
export OCCA_ENABLE_OPENCL="ON"
export OCCA_ENABLE_CUDA="ON"
export OCCA_ENABLE_HIP="ON"
export OCCA_ENABLE_OPENMP="ON"
export OCCA_ENABLE_METAL="OFF"
export OCCA_ENABLE_FORTRAN="OFF"
export OCCA_ENABLE_TESTS="ON"
export OCCA_ENABLE_EXAMPLES="ON"

cmake -S . -B ${OCCA_BUILD_DIR} \
  -DCMAKE_BUILD_TYPE=${OCCA_BUILD_TYPE} \
  -DCMAKE_INSTALL_PREFIX=${OCCA_INSTALL_DIR} \
  -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
  -DCMAKE_C_FLAGS="${CFLAGS}" \
  -DOCCA_ENABLE_OPENMP=${OCCA_ENABLE_OPENMP} \
  -DOCCA_ENABLE_OPENCL=${OCCA_ENABLE_OPENCL} \
  -DOCCA_ENABLE_DPCPP=${OCCA_ENABLE_DPCPP} \
  -DOCCA_ENABLE_CUDA=${OCCA_ENABLE_CUDA} \
  -DOCCA_ENABLE_HIP=${OCCA_ENABLE_HIP} \
  -DOCCA_ENABLE_METAL=${OCCA_ENABLE_METAL} \
  -DOCCA_ENABLE_FORTRAN=${OCCA_ENABLE_FORTRAN} \
  -DOCCA_ENABLE_TESTS=${OCCA_ENABLE_TESTS} \
  -DOCCA_ENABLE_EXAMPLES=${OCCA_ENABLE_EXAMPLES} \
  ${CMAKE_ARGS}

cmake --build build -- -j${CPU_COUNT}
cmake --build build --target install
