{% set version = "0.1.3" %}

package:
  name: bsrn
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/bsrn/bsrn-{{ version }}.tar.gz
  sha256: bd2a53077756e6b23e9f9850f41b7f6cea1dc9348cc57f5dc10e5d4183c0bd28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - pandas
    - numpy
    - requests
    - huggingface_hub
    - pyarrow
    - plotnine
    - matplotlib
    - scipy

test:
  imports:
    - bsrn
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/dazhiyang/bsrn
  summary: A Python package for quality control (QC) checks on BSRN station-to-archive files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dazhiyang
