schema_version: 1

context:
  name: crcpp-cpp
  version: 1.2.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/d-bahr/CRCpp/archive/refs/tags/release-${{ version }}.tar.gz
  sha256: e2019ed95300f865fe0c1ea326e5502e1ba538bfbc2e31d175a5ee313b31510d

build:
  noarch: generic
  number: 0
  script:
    - if: unix
      then:
        - cmake -G Ninja -S . -B build ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DBUILD_TEST=OFF
        - cmake --install build
    - if: win
      then:
        - cmake -G Ninja -S . -B build %CMAKE_ARGS% -DCMAKE_INSTALL_PREFIX="%PREFIX%" -DBUILD_TEST=OFF
        - cmake --install build

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - cmake
    - ninja

tests:
  - if: unix
    then:
      - script:
          - cmake -G Ninja -S . -B build ${CMAKE_ARGS} -DBUILD_TEST=ON
          - cmake --build build
          - ctest --test-dir build --output-on-failure
          - ${CXX} -std=c++11 -I"${PREFIX}/include" test.cpp -o crcpp-test
          - ./crcpp-test
        files:
          source:
            - CMakeLists.txt
            - inc/
            - test/
          recipe:
            - test.cpp
        requirements:
          build:
            - ${{ compiler('cxx') }}
            - ${{ stdlib('c') }}
            - cmake
            - ninja
  - if: win
    then:
      - script:
          - cmake -G Ninja -S . -B build %CMAKE_ARGS% -DBUILD_TEST=ON
          - cmake --build build
          - ctest --test-dir build --output-on-failure
          - '%CXX% /std:c++14 /I"%PREFIX%\include" test.cpp /Fe:crcpp-test.exe'
          - crcpp-test.exe
        files:
          source:
            - CMakeLists.txt
            - inc/
            - test/
          recipe:
            - test.cpp
        requirements:
          build:
            - ${{ compiler('cxx') }}
            - ${{ stdlib('c') }}
            - cmake
            - ninja

about:
  homepage: https://github.com/d-bahr/CRCpp
  repository: https://github.com/d-bahr/CRCpp
  summary: Header-only C++ library for CRC calculations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swahtz
