schema_version: 1

context:
  name: exorcist
  version: 0.0.1
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OpenFreeEnergy/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f
  # you can get the sha256 checksum with:  `openssl sha256 <file name>`,
  # or, in one go without keeping the file with: `curl -L <url> | sha256`
  # (you may need the packages or openssl and/or curl)

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - networkx
    - sqlalchemy

tests:
  # Some packages might need a `test/commands` key to check CLI.
  - python:
      imports:
      - exorcist
      pip_check: true  # run `pip check` to verify the integrity
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
  - script:
      - python -c "import ${{ name }}; print(${{ name }}.__version__)"
      - python -c "import ${{ name }}; assert(${{ name }}.__version__ == '${{ version }}')"
      - pytest -v --pyargs ${{ name }}

about:
  homepage: https://github.com/openFreeEnergy/exorcist
  summary: exorcist
  description: |
    Daemonless campaign-scale simulation orchestration.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/openFreeEnergy/exorcist
  documentation: https://exorcist.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - atravitz
    - dwhswenson
    - ethanholz
