schema_version: 1

context:
  version: "2.1.0"

package:
  name: httpx2-kerberos
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/h/httpx2-kerberos/httpx2_kerberos-${{ version }}.tar.gz
  sha256: c47551b2787259379c3f350de309c538a160a76f74d7a88dd51ae940bf56ae82

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools >=61
    - pip
  run:
    - python
    - cryptography >=46.0.0
    - httpx2 >=2.2.0,<3.0.0
    - pyspnego >=0.12.1

tests:
  - python:
      imports:
        - httpx2_kerberos
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Kerberos authentication for HTTPX2 (forked from HTTPX-Kerberos)
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/achapkowski/httpx_kerberos
  repository: https://github.com/achapkowski/httpx_kerberos

extra:
  recipe-maintainers:
    - achapkowski
