schema_version: 1

context:
  version: "0.10.0"
  python_min: "3.12"

package:
  name: easydynamics
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/E/EasyDynamics/easydynamics-${{ version }}.tar.gz
  sha256: fd01ab1fa80a50da5634efb0e9d0f625a948240fca9653a50482d2ee18b90501

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - easyscience >=2.5.1
    - numpy
    - scipy
    - scipp
    - h5py
    - matplotlib-base
    - pooch
    - darkdetect
    - plopp
    - ipywidgets
    - ipympl
    - sympy
    - jupyterlab
    - ipykernel
    - pixi-kernel
tests:
  - python:
      imports:
        - easydynamics
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: QENS data analysis
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/easyscience/dynamics-lib
  documentation: https://easyscience.github.io/dynamics-lib

extra:
  recipe-maintainers:
    - MridulS
