{% set version = '3.1.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sigora
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/sigora_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sigora/sigora_{{ version }}.tar.gz
  sha256: 1aa9355a782591ed6a30c3666b1045b2fb11d68e7335fb8f3f6b416ffd5e4b85

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-slam
  run:
    - r-base
    - r-slam

test:
  commands:
    - $R -e "library('sigora')"           # [not win]
    - "\"%R%\" -e \"library('sigora')\""  # [win]

about:
  home: https://github.com/wolski/sigora
  license: GPL-3.0-only
  summary: Pathway Analysis is statistically linking observations on the molecular level to biological
    processes or pathways on the systems(i.e., organism, organ, tissue, cell) level.
    Traditionally, pathway analysis methods regard pathways as collections of single
    genes and treat all genes in a pathway as equally informative. However, this can
    lead to identifying spurious pathways as statistically significant since components
    are often shared amongst pathways. SIGORA seeks to avoid this pitfall by focusing
    on genes or gene pairs that are (as a combination) specific to a single pathway.
    In relying on such pathway gene-pair signatures (Pathway-GPS), SIGORA inherently
    uses the status of other genes in the experimental context to identify the most
    relevant pathways. The current version allows for pathway analysis of human and
    mouse datasets. In addition, it contains pre-computed Pathway-GPS data for pathways
    in the KEGG and  Reactome pathway repositories and mechanisms for extracting GPS
    for user-supplied repositories.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sigora
# Type: Package
# biocViews: GeneSetEnrichment, GO, Software, Pathways, KEGG
# Title: Signature Overrepresentation Analysis
# Version: 3.1.1
# Date: 2021-11-29
# Authors@R: c( person("Amir", "Foroushani", email = c("sigora.dev@gmail.com"), role = c("aut"), comment = c(ORCID = "0000-0003-2748-3009")), person("Fiona", "Brinkman", email = c("sigora.dev@gmail.com"), role = c("aut")), person("David", "Lynn", email = c("sigora.dev@gmail.com"), role = c("aut")), person("Witold", "Wolski", email = c("wew@fgcz.ethz.ch"), role = c("cre"), comment = c(ORCID = "0000-0002-6468-120X")) )
# Depends: R (>= 3.0.0)
# URL: https://github.com/wolski/sigora
# BugReports: https://github.com/wolski/sigora/issues
# Imports: stats, slam
# Suggests: knitr
# Description: Pathway Analysis is statistically linking observations on the molecular level to biological processes or pathways on the systems(i.e., organism, organ, tissue, cell) level. Traditionally, pathway analysis methods regard pathways as collections of single genes and treat all genes in a pathway as equally informative. However, this can lead to identifying spurious pathways as statistically significant since components are often shared amongst pathways. SIGORA seeks to avoid this pitfall by focusing on genes or gene pairs that are (as a combination) specific to a single pathway. In relying on such pathway gene-pair signatures (Pathway-GPS), SIGORA inherently uses the status of other genes in the experimental context to identify the most relevant pathways. The current version allows for pathway analysis of human and mouse datasets. In addition, it contains pre-computed Pathway-GPS data for pathways in the KEGG and  Reactome pathway repositories and mechanisms for extracting GPS for user-supplied repositories.
# License: GPL-3
# NeedsCompilation: no
# RoxygenNote: 7.1.2
# VignetteBuilder: knitr
# Packaged: 2021-11-29 12:47:12 UTC; wolski
# Author: Amir Foroushani [aut] (<https://orcid.org/0000-0003-2748-3009>), Fiona Brinkman [aut], David Lynn [aut], Witold Wolski [cre] (<https://orcid.org/0000-0002-6468-120X>)
# Maintainer: Witold Wolski <wew@fgcz.ethz.ch>
# Repository: CRAN
# Date/Publication: 2021-11-30 07:50:02 UTC
