{% set version = "0.13.1" %}
{% set python_min = "3.11" %}

package:
  name: anemoi-models
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/anemoi-models/anemoi_models-{{ version }}.tar.gz
  sha256: d2b578d7288d452af2bfe8db69f0aae7b460ddb7c3c16b8da2afcc82e9fa3b75

build:
  entry_points:
    - anemoi-models = anemoi.models.__main__:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=61
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - anemoi-utils >=0.1.9
    - einops >=0.6.1
    - hydra-core >=1.3
    - pytorch >=2.3,<2.11
    - pytorch_geometric >=2.3

test:
  imports:
    - anemoi
  commands:
    - pip check
    - anemoi-models --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ecmwf/anemoi-models/
  summary: A package to hold various functions to support training of ML models.
  doc_url: https://anemoi-models.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tjtg
    - jasonjunweilyu
    - HCookie
