{% set version = "2026.9.16.post2" %}       

package:
  name: s1ifr
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/s1ifr/s1ifr-{{ version }}.tar.gz
  sha256: ce3c8bc614e0575a4228875bd0eea991d25989dcb60d03a8da3bf81d6124dd98

build:
  entry_points:
    - syncsafe = s1ifr.move_safe_from_ifr_to_ifr:main
    - syncsafebatch = s1ifr.scripts.move_safe_from_ifr_to_ifr_prun:main
    - archivesafe = s1ifr.sentinel1_pieuvre:main
    - get-s1-full-path-safe = s1ifr.scripts.get_full_path_SAFE:entrypoint
    - familyprod = s1ifr.paths_safe_product_family:entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}           
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}         
    - numpy
    - xarray
    - lxml
    - tqdm
    - pandas
    - pyyaml

test:
  imports:
    - s1ifr
  commands:
    - pip check
    - syncsafe --help
    - syncsafebatch --help
    - archivesafe --help
    - get-s1-full-path-safe --help
    - familyprod --help
  requires:
    - pip
    - python {{ python_min }}           

about:
  home: https://github.com/umr-lops/s1ifr
  summary: python methods to find / move / copy / sort / store / count Sentinel-1 SAR mission files in Ifremer archive
  doc_url: https://s1ifr.readthedocs.io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze

