--- Makefile
+++ Makefile
@@ -16,9 +16,9 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-prefix = /usr
+prefix = $(PREFIX)
 
-CC=gcc
+CC=$(GCC)
 
 VERSION=1.8.0
 TREE_DEST=tree
