diff --git a/Makefile b/Makefile
index 0af8dece..6d9c5e3f 100644
--- a/Makefile
+++ b/Makefile
@@ -34,8 +34,8 @@ CCFLAGS = -D STANDALONE $(ROOTCFLAGS) -g -fPIC -O2 -pthread -pipe -Werror=main -
 LIBS = $(ROOTLIBS) -lgsl -lRooFit -lRooFitCore -lRooStats -lMinuit -lMathMore -lFoam -lHistFactory -lboost_filesystem -lboost_program_options -lboost_system -lvdt
 
 ifeq ($(CONDA), 1)
-CCFLAGS += -I${CONDA_PREFIX}/include/boost -I ${CONDA_PREFIX}/include/vdt -I ${CONDA_PREFIX}/include/gsl -I ${CONDA_PREFIX}/include/eigen3 
-LIBS += -L${CONDA_PREFIX}/lib 
+CCFLAGS += -I${PREFIX}/include/boost -I ${PREFIX}/include/vdt -I ${PREFIX}/include/gsl -I ${PREFIX}/include/eigen3 
+LIBS += -L${PREFIX}/lib 
 else ifeq ($(LCG), 1)
 # for some reason, Eigen headers are nested in LCG
 CCFLAGS += -I ${CPLUS_INCLUDE_PATH}/eigen3
@@ -47,7 +47,6 @@ endif
 
 # Library name -----------------------------------------------------------------
 LIBNAME=HiggsAnalysisCombinedLimit
-SONAME=lib$(LIBNAME).so
 DICTNAME=$(LIBNAME)_xr
 
 # Linker and flags -------------------------------------------------------------
@@ -57,9 +56,11 @@ ROOTLIBDIR = $(shell root-config --libdir)
 # OS x specific linkage
 DARWIN := $(shell uname|grep Darwin)
 ifdef DARWIN
+SONAME=lib$(LIBNAME).dylib
 LDFLAGS       = $(ROOTLDFLAGS) -g -shared -install_name @rpath/$(SONAME) -fPIC
 EXELDFLAGS    = -Wl,-rpath,'@executable_path/../lib' -Wl,-rpath,$(ROOTLIBDIR)
 else
+SONAME=lib$(LIBNAME).so
 LDFLAGS       = $(ROOTLDFLAGS) -shared -Wl,-soname,$(SONAME) -Wl,-E -Wl,-z,defs -fPIC
 EXELDFLAGS    = 
 endif
