--- Makefile	2014-03-27 14:47:15.000000000 -0400
+++ Makefile	2015-11-06 14:14:48.000000000 -0500
@@ -4,7 +4,7 @@
 CC = gcc
 
 # Options for the compiler: A high optimization level is suggested
-CFLAGS = -O2 -W -Wno-unused-result
+CFLAGS = -O2 -W -fPIC
 # CFLAGS = -O -g -W -Wall -Wno-unused-result -ansi -pedantic # -DDEBUG
 
 export CC CFLAGS
