schema_version: 1

context:
  version: "0.1.4"

package:
  name: hoptorch
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/h/hoptorch/hoptorch-${{ version }}.tar.gz
  sha256: 958e22455460342f195c63f989543da6fcc66337b2f8fca1980454209d36d450

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=2.7
    - pyvers >=0.2.2

tests:
  - python:
      imports:
        - hoptorch
      pip_check: true
      python_version: 
        - ${{ python_min }}.*
        - "*"

about:
  summary: Compatibility helpers for PyTorch higher-order operators.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vmoens/hoptorch

extra:
  recipe-maintainers:
    - jan-janssen
