context:
  version: "2.4.2"
  python_min: "3.13"

package:
  name: entangled-cli
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/entangled-cli/entangled_cli-${{ version }}.tar.gz
  sha256: d147d9b7d8ea24ac9a1407819e12ae6a377fa3368bdc955cf08126378c0c56bd

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - entangled = entangled.main:cli
  script: uv pip install --python ${{ PYTHON }} . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv
    - hatchling
  run:
    - python >=${{ python_min }}
    - brei >=0.2.3,<0.3
    - click >=8.3.0
    - copier >=9,<10
    - filelock >=3.12.0,<4
    - msgspec >=0.20.0
    - pyyaml >=6.0.1,<7
    - repl-session >=0.2.0
    - rich >=13,<15
    - rich-argparse >=1.4.0,<2
    - rich-click >=1.9.4
    - tomlkit >=0.12.1,<0.13
    - typeguard >=4.4.4
    - watchfiles >=1.1.1

tests:
  - python:
      imports:
        - entangled
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check
      - entangled --help

about:
  homepage: https://entangled.github.io/
  summary: Literate Programming toolbox
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/entangled/entangled.py

extra:
  recipe-maintainers:
    - tdejager
