context:
  version: "3.1.2"

package:
  name: resummino
  version: ${{ version }}

source:
  url: https://resummino.hepforge.org/downloads/?f=resummino-${{ version }}.zip
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f

build:
  script:
    - CXXFLAGS="${CXXFLAGS}" cmake ${CMAKE_ARGS} -S . -B build
    - cmake build -LH
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cmake --install build
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}  # If you need any compiler, add the C standard library ("stdlib") too
    - libboost
    - gsl
    - lhapdf
  host: []
  run:
    - lhapdf

tests:
  - requirements:
      run: []
    script:
      - resummino input/resummino.in

about:
  homepage: https://resummino.hepforge.org/
  summary: 'Resummino computes predictions for selected Beyond the Standard Model processes at hadron colliders'
  description: |
    Resummino computes predictions for selected Beyond the Standard Model (BSM)
    processes at hadron colliders. In the framework of the Minimal
    Supersymmetric Standard Model (MSSM) predictions at approximate NNLO+NNLL
    are available for slepton-pair and electroweakino-pair production (these
    processes are also available with a collinear improved version of threshold
    resummation for NLO+NLL); predictions at NLO+NLL are available for
    gaugino-gluino and gaugino-squark production.

    In general BSM models with extended gauge sectors, predictions for Z' and
    W' production are available at approximate NNLO+NNLL accuracy. The code is
    able to compute total cross sections as well as invariant-mass and
    transverse-momentum distributions (only for Drell-Yan-like processes).
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE.txt
  # The documentation and repository URLs are optional.
  documentation: https://resummino.hepforge.org/
  repository:

extra:
  recipe-maintainers:
    - kratsg
    - mhance
