schema_version: 1

context:
  version: "2.0"

package:
  name: interfacemethod
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/interfacemethod/interfacemethod-${{ version }}.tar.gz
  sha256: d481775bcb00ffc6bd5041b5a86c6c7b1d51c7e21d617a67b2bc1185744cdaf0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling ==1.32.0
    - hatch-vcs ==0.5.0
    - ase
    - lammpsparser
    - matplotlib-base
    - numpy
    - pandas
    - pyscal3
    - scikit-learn
    - structuretoolkit
    - pip
  run:
    - python >=${{ python_min }}
    - ase >=3.23.0,<=3.29.0
    - lammpsparser >=0.0.1,<=0.0.9
    - matplotlib-base =3.11.1
    - numpy >=2.2.1,<=2.5.3
    - pandas >=2.2.3,<=3.0.5
    - pyscal3 >=3.2.5,<=3.3.2
    - scikit-learn =1.9.0
    - structuretoolkit >=0.0.39,<=0.0.46

tests:
  - python:
      imports:
        - interfacemethod
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: A fully automated approach to determine the melting temperature of crystalline materials.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pyiron_meltingpoint
  documentation: http://pyiron.org/pyiron_meltingpoint/

extra:
  recipe-maintainers:
    - jan-janssen
