schema_version: 1

context:
  version: "1.0.0b260514"
  python_min: "3.10"

package:
  name: agent-framework-azurefunctions
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/agent-framework-azurefunctions/agent_framework_azurefunctions-${{ version }}.tar.gz
  sha256: 5a621ca4a18c195f663d95fad1de4b1b85be2305ee620665a231947b89cb319c

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core <4.0,>=3.11
  run:
    - python >=${{ python_min }}
    - agent-framework-core <2,>=1.4.0
    - agent-framework-durabletask
    - azure-functions <2,>=1.24.0
    - azure-functions-durable <2,>=1.3.1

tests:
  - python:
      imports:
        - agent_framework.azurefunctions
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: |
    Azure Functions integration for Microsoft Agent Framework.
  homepage: https://pypi.org/project/agent-framework-azurefunctions/
  repository: https://github.com/microsoft/agent-framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
    - mgorny
