{% set version = "0.1.29" %}
{% set python_min = "3.11" %}

package:
  name: anemoi-transform
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/anemoi-transform/anemoi_transform-{{ version }}.tar.gz
  sha256: 0df4584cf188ebe9cbd36196e600dde53e0a7e0822e704d99cecf344dd82ee4a

build:
  entry_points:
    - anemoi-transform = anemoi.transform.__main__:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=60
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - anemoi-utils >=0.5.1
    - cfunits
    - earthkit-data >=0.12.4,<1
    - earthkit-geo >=0.3
    - earthkit-meteo >=0.4.1
    - earthkit-regrid >=0.4
    - healpy
    - pandas <3

test:
  imports:
    - anemoi
  commands:
    - anemoi-transform --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ecmwf/anemoi-transform/
  summary: A package to hold various data transformation functions to support training of ML models on ECMWF data.
  doc_url: https://anemoi-transform.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tjtg
    - jasonjunweilyu
    - HCookie
