# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.12.3"

package:
  name: qianfan
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/q/qianfan/qianfan-${{ version }}.tar.gz
  sha256: 1c27dd9a6ff68f69e71a34b350a27624b47bd35d9eac9e0b6e23a4f51c02ef4b

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - requests >=2.24
    - aiohttp >=3.7.0
    - aiolimiter >=1.1.0
    - bce-python-sdk >=0.8.79
    - typing_extensions >=4.0.0
    - pydantic >=1.0
    - python-dotenv >=1.0
    - tenacity >=8.2.3,<9.0.0
    - multiprocess >=0.70.12
    - rich >=13.0.0
    - typer >=0.9.0
    - pyyaml >=6.0.1,<7.0.0
    - prompt-toolkit >=3.0.38
    - diskcache >=5.6.3
    - cachetools >=5.0.0

tests:
  - python:
      imports:
        - qianfan
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://cloud.baidu.com/product/wenxinworkshop
  license: Apache-2.0
  license_file: LICENSE
  summary: 文心千帆大模型平台 Python SDK
  repository: https://github.com/baidubce/bce-qianfan-sdk
  documentation: https://qianfan.readthedocs.io/en/stable/README.html
  description: |
    The Qianfan SDK provides best practices for large model toolchain
    development on the Baidu Qianfan (ERNIE / WenxinWorkshop) platform.
    It supports a wide range of capabilities including large model
    inference, fine-tuning, training, dataset management, plugins,
    and prompt engineering against Baidu's ERNIE family of models.

extra:
  recipe-maintainers:
    - rxm7706
