{% set name = "bw-functional" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bw_functional-{{ version }}.tar.gz
  sha256: a254639c490cbd905500ca2935fdd1c0c5abf65bd6a7e5e51f583d1a7f9ea19b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools >=68.0
  run:
    - python >={{ python_min }}
    - blinker
    - bw2data >=4.0.1
    - bw2io >=0.9.1
    - bw_processing >=0.9.6
    - loguru
    - pandas

test:
  imports:
    - bw_functional
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/LCA-ActivityBrowser/bw-functional
  summary: Code for handling multifunctional activities in Brightway
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/LCA-ActivityBrowser/bw-functional

extra:
  recipe-maintainers:
    - bsteubing
