schema_version: 1

context:
  version: "0.1.0"

package:
  name: bw-functional
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/bw-functional/bw_functional-${{ version }}.tar.gz
  sha256: a254639c490cbd905500ca2935fdd1c0c5abf65bd6a7e5e51f583d1a7f9ea19b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68.0
    - pip
  run:
    - python >=${{ python_min }}
    - blinker
    - bw2data >=4.0.1
    - bw2io >=0.9.1
    - bw_processing >=0.9.6
    - loguru
    - pandas

tests:
  - python:
      imports:
        - bw_functional
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Code for handling multifunctional activities in Brightway
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/LCA-ActivityBrowser/bw-functional
  repository: https://github.com/LCA-ActivityBrowser/bw-functional

extra:
  recipe-maintainers:
    - bsteubing
