{% set name = "pywebview" %}
{% set version = "6.2.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71b7136752e40824655304d938efb62014218d1a90bd8e87e1cbdb1ce9c466af

build:
  noarch: python
  skip: true  # [py<38]
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pythonnet  # [win]
    - pyobjc-core >=9.0  # [darwin]
    - pyobjc-framework-cocoa >=9.0  # [darwin]
    - pyobjc-framework-quartz >=9.0  # [darwin]
    - pyobjc-framework-webkit >=9.0  # [darwin]
    - pyobjc-framework-security >=9.0  # [darwin]
    - pyobjc-framework-uniformtypeidentifiers >=9.0  # [darwin]
    - qtpy  # [openbsd]
    - importlib_resources
    - proxy-tools
    - bottle
    - typing_extensions

test:
  imports:
    - webview
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://{{ name }}.flowrl.com/
  summary: Build GUI for your Python program with JavaScript, HTML, and CSS
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/r0x0r/{{ name }}/

extra:
  recipe-maintainers:
    - jaromieee
