{% set python_min = "3.11" %}
{% set version = "0.1.0" %}

package:
  name: convolinear
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/convolinear/convolinear-{{ version }}.tar.gz
  sha256: aaf32eb0fa77713793c4912d4971e6ee326d5fab6483411ad41c94d6e96ae1c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling >=1.26
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.23.2
    - scipy >=1.8.0

test:
  imports:
    - convolinear
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/sahmed0/convolinear
 # readme
  summary: A fluent time-series and signal processing library for building data pipelines in a single line of Python.
 # readme
  license: MIT
 # readme
  license_file: LICENSE  # readme

extra:
  recipe-maintainers:
    - Sajid Ahmed
