# Quadrants uses Metal 3 APIs introduced in macOS 13.
MACOSX_SDK_VERSION:  # [osx and arm64]
  - "13.3"          # [osx and arm64]
c_stdlib_version:    # [osx and arm64]
  - "13.0"          # [osx and arm64]
