#!/usr/bin/env bash
set -euxo pipefail

cmake -S . -B build -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
  -DBUILD_SHARED_LIBS=ON \
  -DWAMR_BUILD_INTERP=1 \
  -DWAMR_BUILD_FAST_INTERP=1 \
  -DWAMR_BUILD_AOT=0 \
  -DWAMR_BUILD_JIT=0 \
  -DWAMR_BUILD_FAST_JIT=0 \
  -DWAMR_BUILD_LIBC_BUILTIN=1 \
  -DWAMR_BUILD_LIBC_WASI=0 \
  -DWAMR_BUILD_MULTI_MODULE=0 \
  -DWAMR_BUILD_BULK_MEMORY=1 \
  -DWAMR_BUILD_SHARED_MEMORY=0 \
  -DWAMR_BUILD_THREAD_MGR=0 \
  -DWAMR_BUILD_LIB_PTHREAD=0 \
  -DWAMR_BUILD_LIB_WASI_THREADS=0 \
  -DWAMR_BUILD_MINI_LOADER=0 \
  -DWAMR_BUILD_SIMD=1 \
  -DWAMR_BUILD_REF_TYPES=1 \
  -DWAMR_BUILD_MEMORY64=0 \
  -DWAMR_BUILD_MULTI_MEMORY=0 \
  -DWAMR_BUILD_INSTRUCTION_METERING=1

cmake --build build --target install --parallel
