#!/bin/bash

set -eux # Abort on error.

PY_ABIFLAGS=$(python -c "import sys; print('' if sys.version_info.major == 2 else sys.abiflags)")
PY_ABI=${PY_VER}${PY_ABIFLAGS}

if [[ "$OSTYPE" == "darwin"* ]]; then
	export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
fi

CMAKE_ARGS="-DTENSORSTORE_USE_SYSTEM_AOM=ON -DTENSORSTORE_USE_SYSTEM_AVIF=ON -DTENSORSTORE_USE_SYSTEM_BLOSC=ON -DTENSORSTORE_USE_SYSTEM_BROTLI=ON -DTENSORSTORE_USE_SYSTEM_BZIP2=ON -DTENSORSTORE_USE_SYSTEM_CARES=ON -DTENSORSTORE_USE_SYSTEM_CURL=ON -DTENSORSTORE_USE_SYSTEM_DAV1D=ON -DTENSORSTORE_USE_SYSTEM_JPEG=ON -DTENSORSTORE_USE_SYSTEM_LIBLZMA=ON -DTENSORSTORE_USE_SYSTEM_LIBYUV=ON -DTENSORSTORE_USE_SYSTEM_LZ4=ON -DTENSORSTORE_USE_SYSTEM_NGHTTP2=ON -DTENSORSTORE_USE_SYSTEM_NLOHMANN_JSON=ON -DTENSORSTORE_USE_SYSTEM_OPENSSL=ON -DTENSORSTORE_USE_SYSTEM_PNG=ON -DTENSORSTORE_USE_SYSTEM_PROTOBUF=ON -DTENSORSTORE_USE_SYSTEM_SNAPPY=ON -DTENSORSTORE_USE_SYSTEM_TIFF=ON -DTENSORSTORE_USE_SYSTEM_WEBP=ON -DTENSORSTORE_USE_SYSTEM_ZLIB=ON -DTENSORSTORE_USE_SYSTEM_ZSTD=ON -DAVIF_ENABLE_GTEST=OFF -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DINSTALL_GTEST=OFF -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX=$PREFIX" python -m pip install . -vvv