#! /usr/bin/env bash
#
# Install the libtree-sitter runtime library.
#
set -eu -o pipefail

default_version="0.18.0"
prog_name=$(basename "$0")

error() {
  echo "Error: $@" >&2
  exit 1
}

usage() {
  cat <<EOF
Install the tree-sitter runtime library from source.
Usage: $prog_name [OPTIONS]
Options:
  --help
      Show this message and exit.
  --version VERSION
      Install this specific version of tree-sitter. VERSION must be a git tag
      or a branch name in the original tree-sitter repository.
      See valid tags at https://github.com/tree-sitter/tree-sitter/tags
      Current default: $default_version
EOF
}

version="$default_version"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --help)
      usage
      exit 0
      ;;
    --version)
      version="$2"
      shift
      ;;
    *)
      error "Invalid argument passed to '${prog_name}': '$1'"
  esac
  shift
done

echo "Installing tree-sitter library directly from git."
if [[ -d tree-sitter ]]; then
  echo "Removing previous copy of tree-sitter."
  rm -rf tree-sitter
fi
echo "Fetching tree-sitter from git, branch $version."
git clone --depth 1 --branch "$version" \
    https://github.com/tree-sitter/tree-sitter.git

(
  cd tree-sitter
  git clean -dfX
  make

  # When building from source on homebrew sudo is not allowed
  # but also not needed
  if [[ -z "${HOMEBREW_SYSTEM+x}" ]]; then
    make install
  else
    make install
  fi

  # Ensure libtree-sitter is found at linking time.
  # MacOS doesn't have ldconfig. Maybe it works without it?
  if which ldconfig > /dev/null; then
    libdir=$(
      pkg-config --libs-only-L tree-sitter \
      | sed -e 's/^-L//'
    )
    sudo ldconfig "$libdir"
  fi
)
