context:
  version: "2.1.3"
  name: stationxml-seed-converter

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/iris-edu/${{ name }}/archive/refs/tags/${{ name }}-${{ version }}.tar.gz
  sha256: a790d52fba02487ac6c88232f11449ed0af518324b8224beed2dca849863b550

build:
  number: 0
  skip:
    - win
  script:
    - mvn package -DskipTests=true
    - mkdir -p $PREFIX/share/java/${{ name }}
    - cp target/${{ name }}-*-jar-with-dependencies.jar $PREFIX/share/java/${{ name }}/${{ name }}.jar
    - cp LICENSE.md $PREFIX/share/java/${{ name }}/LICENSE.md
    - mkdir -p $PREFIX/bin
    - |
      cat > $PREFIX/bin/${{ name }} << 'EOF'
      #!/bin/sh
      exec java -jar "$CONDA_PREFIX/share/java/stationxml-seed-converter/stationxml-seed-converter.jar" "$@"
      EOF
    - chmod +x $PREFIX/bin/${{ name }}

requirements:
  build:
    - maven
    - openjdk >=11
  run:
    - openjdk >=11

tests:
  - script:
      - stationxml-seed-converter -h

about:
  homepage: https://epic.earthscope.org/content/software-resources
  summary: Convert between StationXML and SEED metadata formats
  description: |
    stationxml-seed-converter is a Java command-line tool for converting
    between FDSN StationXML and dataless SEED station metadata formats.
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  repository: https://github.com/iris-edu/stationxml-seed-converter

extra:
  recipe-maintainers:
    - omid-earthscope
