(
    @echo.# The name of the libraries to be created/linked to
    @echo.XBLASLIB = libxblas.a
    @echo.
    @echo.CC = %CC%
    @echo.CFLAGS = %CFLAGS%
    @echo.LINKER = %CC%
    @echo.LDFLAGS = %LDFLAGS%
    @echo.ARCH = %GCC_AR%
    @echo.ARCHFLAGS = cr
    @echo.RANLIB = %GCC_RANLIB%
    @echo.
    @echo.# Extra libraries needed for xblas test code.
    @echo.EXTRA_LIBS =  -lm
    @echo.
    @echo.# M4 macro preprocessor.  Used to generate C sources.
    @echo.M4 = m4
    @echo.M4_OPTS = -DLAPACK -D no_plain_blas
    @echo.
    @echo.# Indent program.  Used to prettify C source generated by M4.
    @echo.INDENT = indent
    @echo.INDENT_OPTS = -ce -i2 -nfc1 -br -brs -cs -npcs -nprs -npsl
) >make.inc
if errorlevel 1 exit 1

make all
if errorlevel 1 exit 1

mkdir %LIBRARY_PREFIX\lib
copy libxblas.a %LIBRARY_PREFIX\lib
if errorlevel 1 exit 1
