cat > make.inc <<EOF
# The name of the libraries to be created/linked to
XBLASLIB = libxblas.a

CC = $CC
CFLAGS = $CFLAGS
LINKER = $CC
LDFLAGS = $LDFLAGS
ARCH = $GCC_AR
ARCHFLAGS = cr
RANLIB = $GCC_RANLIB

# Extra libraries needed for xblas test code.
EXTRA_LIBS =  -lm

# M4 macro preprocessor.  Used to generate C sources.
M4 = m4
M4_OPTS = -DLAPACK -D no_plain_blas

# Indent program.  Used to prettify C source generated by M4.
INDENT = indent
INDENT_OPTS = -ce -i2 -nfc1 -br -brs -cs -npcs -nprs -npsl

EOF

make all
cp libxblas.a ${PREFIX}/lib/libxblas.a