schema_version: 1

context:
  version: "0.2.1"

package:
  name: jupyter-mcp-manager
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-mcp-manager/jupyter_mcp_manager-${{ version }}.tar.gz
  sha256: 3bc411f334de08b94cf5dcbad2d5ae0364fb4da269e75191aa9becd84c01dd18

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - jupyter-builder >=1.2.0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python >=${{ python_min }}
    - jupyter_server >=2.4.0,<3
    - jupyter_core >=5.0.0
    - jupyterlab_server >=2
    - pydantic >=2.0.0
    - traitlets >=5.0.0

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true
      imports: jupyter_mcp_manager
  - script:
      - jupyter labextension list 2>&1 | rg -ie "jupyter-mcp-manager.*OK"
    requirements:
      run:
        - python ${{ python_min }}.*
        - jupyterlab >=4.5.0,<5
        - ripgrep

about:
  summary: A JupyterLab extension to manage MCP servers.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/jupyter-ai-contrib/jupyter-mcp-manager

extra:
  recipe-maintainers:
    - brichet
    - jtpio
