--- src/Makefile.orig	2019-11-15 08:47:13.221569103 -0500
+++ src/Makefile	2019-11-15 08:46:56.617686678 -0500
@@ -4,9 +4,10 @@
 #
 # Change these if you want to install somewhere else.
 
-INSTALL_PLUGINS_DIR	=	/usr/lib/ladspa/
-INSTALL_INCLUDE_DIR	=	/usr/include/
-INSTALL_BINARY_DIR	=	/usr/bin/
+PREFIX ?= /usr
+INSTALL_PLUGINS_DIR =   $(PREFIX)/lib/ladspa/
+INSTALL_INCLUDE_DIR =   $(PREFIX)/include/
+INSTALL_BINARY_DIR  =   $(PREFIX)/bin/
 
 ###############################################################################
 #
@@ -15,7 +16,7 @@
 
 INCLUDES	=	-I.
 LIBRARIES	=	-ldl -lm
-CFLAGS		=	$(INCLUDES) -Wall -Werror -O2 -fPIC 		\
+CFLAGS	  = $(CFLAGS)  $(INCLUDES) -Wall -Werror -O2 -fPIC		 \
 			-DDEFAULT_LADSPA_PATH=$(INSTALL_PLUGINS_DIR)
 BINFLAGS	=	-fPIE -pie
 CXXFLAGS	=	$(CFLAGS)
@@ -27,8 +28,8 @@
 PROGRAMS	=	../bin/analyseplugin				\
 			../bin/applyplugin 				\
 			../bin/listplugins
-CC		=	cc
-CPP		=	c++
+CC	  ?=   cc
+CPP	 ?=   c++
 
 ###############################################################################
 #
