schema_version: 1

context:
  version: "1.1.0"

package:
  name: pyvims
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyvims/pyvims-${{ version }}.tar.gz
  sha256: 90444bb8604d1579316c020bcfd65f0a1ab7d923f5ad8fc7e62f0d664369508e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pds = pyvims.pds.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.17,<2
    - matplotlib-base >=3.1
    - pillow
    - scipy
    - tqdm
    - requests
    - pvl

tests:
  - python:
      imports:
        - pyvims
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pds --help

about:
  summary: Python package to manipulate the Cassini VIMS data
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://pypi.org/project/pyvims/

extra:
  recipe-maintainers:
    - seignovert
