context:
  version: "0.23.0"

package:
  name: ironclaw
  version: ${{ version }}

source:
  url: https://github.com/nearai/ironclaw/archive/refs/tags/ironclaw-v${{ version }}.tar.gz
  sha256: 0082b11de02407190dfc1db49814af9b35099c5f74cac34896c60ee087c800d6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - ironclaw --version

about:
  homepage: https://github.com/nearai/ironclaw
  summary: IronClaw is OpenClaw inspired implementation in Rust focused on privacy and security
  description: |
    IronClaw is OpenClaw inspired implementation in Rust focused on privacy and security
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://docs.ironclaw.com
  repository: https://github.com/nearai/ironclaw

extra:
  recipe-maintainers:
    - yuikisaito
