schema_version: 1

context:
  version: "0.5.3"
  python_min: "3.12"

package:
  name: amorphouspy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/amorphouspy/amorphouspy-${{ version }}.tar.gz
  sha256: da26728631ecdc8503ca0fddd9b2e5c20e10eaefea5e7bea3c55ae1c874be984

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.21
  run:
    - python >=${{ python_min }}
    - ase
    - numba
    - pandas
    - lammpsparser
    - networkx
    - pydantic
    - pymatgen
    - scikit-image
    - scipy

tests:
  - python:
      imports:
        - amorphouspy
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/glasagent/amorphouspy
  summary: Workflows for atomistic modeling of oxide glasses
  description: |
    A Python package for atomistic simulations of glasses. amorphouspy provides
    capabilities from generating initial structural models through running
    molecular dynamics simulations with LAMMPS, all the way to computing
    material properties and performing detailed structural analysis.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://glasagent.github.io/amorphouspy/
  repository: https://github.com/glasagent/amorphouspy

extra:
  recipe-maintainers:
    - ltalirz
