{% set version = "6.5.2" %}

package:
  name: ogs
  version: {{ version }}

source:
  # url: https://github.com/ufz/ogs/archive/refs/tags/{{ version }}.tar.gz
  # 6.5.2 with patch for conda build:
  url: https://gitlab.opengeosys.org/ogs/ogs/-/archive/15bd1260c78906a35f5e314abcb23f8df679b553/ogs-15bd1260c78906a35f5e314abcb23f8df679b553.tar.gz
  sha256: df3dc384ed68a4df27cf66b001fe4c02701c79a3d4d57e39988884cbca9fc4bf

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  host:
    - eigen
    - exprtk
    - hdf5
    - libboost-python-devel
    - libxml2
    - metis
    - nlohmann_json
    - pybind11
    - range-v3
    - tclap
    - vtk >=9.3.0
    - zlib

  run:
    - _openmp_mutex  # [linux]
    - hdf5
    - libtiff
    - libxml2
    - llvm-openmp  # [osx]
    - python
    - tetgen
    - vtk >=9.3.0

test:
  commands:
    - ogs --version

about:
  home: http://www.opengeosys.org/
  summary: OpenGeoSys (OGS) THMC simulator.
  description: |
    OpenGeoSys (OGS) is a scientific open source project for the development
    of numerical methods for the simulation of thermo-hydro-mechanical-
    chemical (THMC) processes in porous and fractured media. 
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - scripts/cmake/json-cmake/LICENSE
    - build/third_party_licenses.txt
  doc_url: https://www.opengeosys.org/docs
  dev_url: https://gitlab.opengeosys.org/ogs/ogs

extra:
  recipe-maintainers:
    - bilke
