schema_version: 1

context:
  version: "0.1.0"

package:
  name: scibmad
  version: ${{ version }}

source:
  # Not yet on PyPI - soon
  # url: https://pypi.org/packages/source/s/scibmad/scibmad-${{ version }}.tar.gz
  url: https://github.com/bmad-sim/PySciBmad/releases/download/v${{ version }}/scibmad-${{ version }}.tar.gz
  sha256: 69098e4b1b55197da21289c11b1cf9d7edf4a6131b78983af743d1d8a84d07e2

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pyjuliacall >=0.9.20

tests:
  - python:
      imports:
        - scibmad
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/bmad-sim/PySciBmad
  summary: Python interface to the SciBmad.jl accelerator physics simulation ecosystem
  license: LGPL-3.0-or-later
  license_file: LICENSE
  documentation: https://bmad-sim.github.io/SciBmad.jl
  repository: https://github.com/bmad-sim/PySciBmad

extra:
  recipe-maintainers:
    - ken-lauer
