schema_version: 1

context:
  name: flowy
  version: "1.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/flowy-code/flowy/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c2107efbfdf127536073c90d8730127c822396b20deb86752917728633018f21
  patches:
    - 0001-use-system-deps-and-xtensor-headers.patch

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config
    - cmake
  host:
    - fmt
    - hdf5
    - libblas
    - libcblas
    - liblapack
    - libnetcdf
    - pdf_cpplib
    - tomlplusplus
    - tsl_robin_map
    - xtensor
    - xtensor-blas
  run:
    - fmt
    - libnetcdf
    - pdf_cpplib
    - tomlplusplus
    - tsl_robin_map
  run_exports:
    - ${{ pin_subpackage('flowy', upper_bound='x.x') }}

tests:
  - package_contents:
      files:
        - include/flowy/include/simulation.hpp
        - lib/pkgconfig/flowy.pc
  - script:
      - if: unix
        then:
          - test -f "${PREFIX}/include/flowy/include/simulation.hpp"
          - test -f "${PREFIX}/lib/pkgconfig/flowy.pc"
          - test -f "${PREFIX}/lib/libflowy.so" || test -f "${PREFIX}/lib/libflowy.dylib"

about:
  homepage: https://github.com/flowy-code/flowy
  summary: Probabilistic lava emplacement (Mr. Lava Loba reimplementation)
  license: GPL-3.0-only
  license_file: LICENSE
  repository: https://github.com/flowy-code/flowy

extra:
  recipe-maintainers:
    - HaoZeke
