mkdir -p build
cd build
cmake .. ${CMAKE_ARGS} -DCOSTA_WITH_BENCHMARKS:BOOL=OFF -DCOSTA_WITH_APPS:BOOL=OFF -DCOSTA_WITH_TESTS:BOOL=OFF -DCOSTA_WITH_PROFILING:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCOSTA_SCALAPACK:STRING=OFF
make -j${CPU_COUNT} install
