REM prevent vendoring of dependencies
set EVALHYD_PYTHON_VENDOR_XTL=FALSE
set EVALHYD_PYTHON_VENDOR_XTENSOR=FALSE
set EVALHYD_PYTHON_VENDOR_XTENSOR_PYTHON=FALSE
set EVALHYD_PYTHON_VENDOR_EVALHYD_CPP=FALSE

%PYTHON% -m pip install . -vvv
