diff --git a/makefile b/makefile
index b0c4f56..dcbd4f4 100644
--- a/makefile
+++ b/makefile
@@ -15,10 +15,11 @@
 
 SRC = ./
 BIN = ./
+LIB = ./
 
 # CC should be set to the name of your favorite C compiler.
 
-CC = cc
+CC = mpicc -fPIC
 
 # CSWITCHES is a list of all switches passed to the C compiler.  I strongly
 #   recommend using the best level of optimization.  I also strongly
@@ -72,8 +73,8 @@ CC = cc
 # An example CSWITCHES line is:
 #
 #   CSWITCHES = -O -DNO_TIMER -DLINUX -I/usr/X11R6/include -L/usr/X11R6/lib
-
-CSWITCHES = -O -DLINUX -I/usr/X11R6/include -L/usr/X11R6/lib
+#mwf no fpu_control
+CSWITCHES = -O -I/usr/X11R6/include -L/usr/X11R6/lib
 
 # TRILIBDEFS is a list of definitions used to compile an object code version
 #   of Triangle (triangle.o) to be called by another program.  The file
@@ -86,7 +87,7 @@ CSWITCHES = -O -DLINUX -I/usr/X11R6/include -L/usr/X11R6/lib
 #
 #   TRILIBDEFS = -DTRILIBRARY -DREDUCED -DCDT_ONLY
 
-TRILIBDEFS = -DTRILIBRARY
+TRILIBDEFS = -DTRILIBRARY -DMWF_ADDED_FLAGS
 
 # RM should be set to the name of your favorite rm (file deletion program).
 
@@ -97,11 +98,18 @@ RM = /bin/rm
 all: $(BIN)triangle $(BIN)showme
 
 trilibrary: $(BIN)triangle.o $(BIN)tricall
+	ar r $(LIB)libtri.a $(BIN)triangle.o
+	ranlib $(LIB)libtri.a
+
+install: trilibrary $(BIN)triangle $(BIN)showme
+	cp -f $(LIB)libtri.a $(PROTEUS_PREFIX)/lib
+	cp -f $(BIN)triangle $(BIN)showme  $(PROTEUS_PREFIX)/bin
+	cp -f triangle.h $(PROTEUS_PREFIX)/include
 
 $(BIN)triangle: $(SRC)triangle.c
 	$(CC) $(CSWITCHES) -o $(BIN)triangle $(SRC)triangle.c -lm
 
-$(BIN)tricall: $(BIN)tricall.c $(BIN)triangle.o
+$(BIN)tricall: $(SRC)tricall.c $(BIN)triangle.o
 	$(CC) $(CSWITCHES) -o $(BIN)tricall $(SRC)tricall.c \
 		$(BIN)triangle.o -lm
 
@@ -113,4 +121,4 @@ $(BIN)showme: $(SRC)showme.c
 	$(CC) $(CSWITCHES) -o $(BIN)showme $(SRC)showme.c -lX11
 
 distclean:
-	$(RM) $(BIN)triangle $(BIN)triangle.o $(BIN)tricall $(BIN)showme
+	$(RM) $(BIN)triangle $(BIN)triangle.o $(BIN)tricall $(BIN)showme $(LIB)libtri.a
