{% set version = "0.0.1" %}

package:
  name: clickqt-utils
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/clickqt-utils/clickqt_utils-{{ version }}.tar.gz
  sha256: 04fce251fbdf50da45b1a40fd0c2e878dd26fbbb7d458b964208615266f26565

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - click

test:
  imports:
    - clickqt_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/clickqt-utils/
  summary: Some click utilities that are understood by clickqt
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dokempf
