schema_version: 1

context:
  version: "0.5.0"
  python_min: 3.11

package:
  name: cel-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cel-python/cel_python-${{ version }}.tar.gz
  sha256: 3eb0a619e8df0f338d0430cda01427a742e77e3c433a1c7c3ebd409cd804c45a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cel-python = celpy.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - google-re2 >=1.1.20250722
    - jmespath >=1.0.1
    - lark >=1.2.2
    - pendulum >=3.1.0
    - pyyaml >=6.0.2

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - celpy
      pip_check: true
  - requirements:
      run:
        - python
    script:
      - cel-python --help

about:
  summary: Pure Python implementation of Google Common Expression Language
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/cel-python/

extra:
  recipe-maintainers:
    - xhochy
