schema_version: 1

context:
  version: "0.10.0"

package:
  name: shinyswatch
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/shinyswatch/shinyswatch-${{ version }}.tar.gz
  sha256: 8a5320b39210f1d17209c1b850af3ffde8eff17f14f80cb59e618e31c730d59d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - typing_extensions >=3.10.0.0
    - packaging >=20.9
    - htmltools >=0.2.0
    - shiny >=1.2.0

tests:
  - python:
      imports:
        - shinyswatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Bootswatch + Bootstrap 5 themes for Shiny.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rstudio/py-shinyswatch

extra:
  recipe-maintainers:
    - schloerke
