{% set name = "scriptrunner-gui" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scriptrunner-gui-{{ version }}.tar.gz
  sha256: 5bfbc00c3f07672812f002ae6f0ca71fa0b083434e9351bf5234a608d3f49c2c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  entry_points:
    - scriptrunner = scriptrunner.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - scriptrunner
  commands:
    - scriptrunner --help
  requires:
    - python {{ python_min }
    - pip

about:
  home: https://github.com/algotom/scriptrunner
  license: Apache-2.0
  license_file: LICENSE
  summary: GUI software for rendering arguments of CLI Python scripts and scheduling runs

extra:
  recipe-maintainers:
    - nghia-vo


