schema_version: 1

context:
  version: "0.17.3"

package:
  name: libruckig
  version: ${{ version }}

source:
  - url: https://github.com/pantor/ruckig/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 8464bfc7d39b30265a474d74ac8860570089f143b82baa4e28390e8a2bb90919
    target_directory: src

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja
    - if: linux
      then: lcov
  run_exports:
    - ${{ pin_subpackage('libruckig', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - ruckig/ruckig.hpp
      lib:
        - ruckig

about:
  summary: C++ Library Motion Generation for Robots and Machines. Real-time. Jerk-constrained. Time-optimal.
  license: MIT
  license_file: src/LICENSE
  homepage: https://github.com/pantor/ruckig

extra:
  recipe-maintainers:
    - johnwason
    - Levi-Armstrong
    - traversaro

