context:
  version: 3.3.0

package:
  name: libpninexus
  version: ${{ version }}

source:
    url: https://github.com/pni-libraries/libpninexus/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 54b902829ba7a01f889976d72e29c782a07675ae664896da1149c7c9a3f921b0
    patches:
      - add-template-argument-list.patch 
    #  - if: win
    #    then:
    #       - remove-findhdf5.patch

build:
    number: 0
    script:
      - if: win
        then:  set CL=/DH5_BUILT_AS_DYNAMIC_LIB=1 %CL%
      - if: win
        then: cmake -B build -G Ninja  %CMAKE_ARGS%  -DHDF5_FIND_DEBUG=ON  -DHDF5_USE_STATIC_LIBRARIES=OFF -DPNINEXUS_CONAN=DISABLE -DCMAKE_BUILD_TYPE=Release
        else: cmake -B build -G Ninja  ${CMAKE_ARGS}  -DPNINEXUS_CONAN=DISABLE -DCMAKE_BUILD_TYPE=Release
      - cmake --build build  --target all
      # - cmake --build build  --target api_doc
      # - cmake --build build  --target html
      # - cmake --build build  --target check -- -j3  CTEST_OUTPUT_ON_FAILURE=TRUE
      - cmake --build build  --target check

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - doxygen
    - graphviz
    - ghostscript
    - sphinx
    - breathe
    - pygments
    # - latex
    - if: not win
      then: cppunit
  host:
    - hdf5
    - h5cpp
    - boost-cpp
    - zlib

tests:
    - package_contents:
        include:
          - pni/nexus/file.hpp
          - pni/nexus/xml/create.hpp
          - pni/nexus/path/path.hpp
          - pni/parsers/parser.hpp
          - pni/parsers.hpp
        lib:
          - pninexus

about:
  homepage: https://github.com/pni-libraries/libpninexus
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: C++ NeXus library
  description: |
    libpninexus is C++ library to create NeXus files.
    It provides NeXus tree-structure builder basedon XML (NXDL-like) input,
    NeXus path parsers and other algorithms to access NeXus files.
  documentation: https://pni-libraries.github.io/libpninexus
  repository: https://github.com/pni-libraries/libpninexus

extra:
  recipe-maintainers:
    - jkotan
    - yuelongyu
