schema_version: 1

context:
  version: "0.2.0"

package:
  name: coreai-opt
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/coreai-opt/coreai_opt-${{ version }}.tar.gz
  sha256: 2b8829c42c7bb6b88bd056094c3d9dbae23c3bba3bb18773edf9d66582609ebc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - coremltools >=8.3
    - numpy >=2,<2.4
    - pydantic >=2.0.0
    - rich >=13.0.0
    - safetensors >=0.5.3,<=0.7.0
    - pytorch >=2.8.0,<=2.11.0
    - torchao >=0.15.0,<=0.17.0
    - tqdm >=4.65

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - coreai_opt
      pip_check: true

about:
  summary: A library for PyTorch model compression and optimizations for deployment via Core AI on Apple silicon.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/coreai-opt/

extra:
  recipe-maintainers:
    - xhochy
