{% set version = "2.0.2" %}
{% set python_min = "3.9" %}

package:
  name: pytigergraph
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/p/pytigergraph/pytigergraph-{{ version }}.tar.gz
  sha256: b92ab1707b75c3046214f42c38158ed16ad7683cd9687f409f95e621bcd6a53e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - requests
    - aiohttp
    - httpx
    - validators

test:
  imports:
    - pyTigerGraph
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/tigergraph/pyTigerGraph
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for TigerGraph

extra:
  recipe-maintainers:
    - chengbiao-jin
