context:
  version: "2.1.1"

package:
  name: ocaml-cmdliner
  version: ${{ version }}

source:
  url: https://erratique.ch/software/cmdliner/releases/cmdliner-${{ version }}.tbz
  sha256: 05b938d1def4f54c478178f1982822834510431ed98f2ac67cb4d90aa120d6b6

build:
  number: 0
  skip:
    - win
  script:
    # cmdliner bootstraps itself with `ocaml build.ml`; it has no build-system dependency.
    - make all PREFIX="${PREFIX}"
    - make install
        BINDIR="${PREFIX}/bin"
        LIBDIR="${PREFIX}/lib/ocaml/cmdliner"
        SHAREDIR="${PREFIX}/share"
        MANDIR="${PREFIX}/share/man"

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("ocaml") }}
    - make
  host:
    - ocaml >=4.08.0

tests:
  - package_contents:
      strict: true
      bin:
        - cmdliner
      files:
        - lib/ocaml/cmdliner/*
        - share/bash-completion/completions/*
        - share/zsh/site-functions/*
        - share/powershell/*

about:
  homepage: https://erratique.ch/software/cmdliner
  repository: https://github.com/dbuenzli/cmdliner
  documentation: https://erratique.ch/software/cmdliner/doc
  summary: Declarative definition of command line interfaces for OCaml
  license: ISC
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ManuelLerchner
    - MementoRC
