schema_version: 1

context:
  version: "0.0.38"
  python_min: "3.9"

package:
  name: invocation-tree
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/invocation-tree/invocation_tree-${{ version }}.tar.gz
  sha256: 59d878b3adf3dc1dd913eb3c394c2eadabe47a65f5915fd61dbee9e8ea347c21

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - python-graphviz

tests:
  - python:
      imports:
        - invocation_tree
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Generates an invocation tree of functions calls.
  license: BSD-2-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/bterwijn/invocation_tree
  repository: https://github.com/bterwijn/invocation_tree
  
extra:
  recipe-maintainers:
    - bterwijn
