{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stbl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stbl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stbl/stbl_{{ version }}.tar.gz
  sha256: da5cb2d8bf23d04f2a859c1a800e086f359990b0edc1de646da7590475e6a00d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.4.0
    - r-glue
    - r-rlang >=1.0.3
    - r-vctrs
  run:
    - r-base
    - r-cli >=3.4.0
    - r-glue
    - r-rlang >=1.0.3
    - r-vctrs

test:
  commands:
    - $R -e "library('stbl')"           # [not win]
    - "\"%R%\" -e \"library('stbl')\""  # [win]

about:
  home: https://stbl.wrangle.zone/, https://github.com/wranglezone/stbl
  license: MIT
  summary: A set of consistent, opinionated functions to quickly check function arguments, coerce
    them to the desired configuration, or deliver informative error messages when that
    is not possible.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - Mathmath34

# Package: stbl
# Title: Stabilize Function Arguments
# Version: 0.3.0
# Authors@R: person("Jon", "Harmon", , "jonthegeek@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0003-4781-4346"))
# Description: A set of consistent, opinionated functions to quickly check function arguments, coerce them to the desired configuration, or deliver informative error messages when that is not possible.
# License: MIT + file LICENSE
# URL: https://stbl.wrangle.zone/, https://github.com/wranglezone/stbl
# BugReports: https://github.com/wranglezone/stbl/issues
# Depends: R (>= 4.1)
# Imports: cli (>= 3.4.0), glue, rlang (>= 1.0.3), vctrs
# Suggests: astgrepr, knitr, rmarkdown, stringi, stringr, testthat (>= 3.3.0)
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.3.3
# NeedsCompilation: no
# Packaged: 2026-04-04 14:26:49 UTC; jonth
# Author: Jon Harmon [aut, cre, cph] (ORCID: <https://orcid.org/0000-0003-4781-4346>)
# Maintainer: Jon Harmon <jonthegeek@gmail.com>
# Repository: CRAN
# Date/Publication: 2026-04-04 14:40:02 UTC
