{% set version = "0.3.0" %}
{% set name = "sedonadb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/apache/sedona-db/archive/apache-sedona-db-{{ version }}.tar.gz
  sha256: 808a38f955dc1dc1c68793a2a6c707abf6299d5f2371ff7dd7b4a3c267e67333

build:
  number: 0
  script:
    # Windows workaround for upstream geos pkg-config flag'-lstdc++' flag, which breaks MSVC
    # Consider moving this to bld.bat
    - python -c "import os, pathlib; [f.write_text(f.read_text().replace('-lstdc++', '')) for f in pathlib.Path(os.environ['LIBRARY_PREFIX']).joinpath('lib', 'pkgconfig').glob('*.pc')]"  # [win]

    # Configure PyO3 to use the host Python environment
    - export PYO3_PYTHON={{ PYTHON }}  # [not win]
    - set "PYO3_PYTHON={{ PYTHON }}"   # [win]

    # Generate Rust license inventory
    - cd python/sedonadb
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - mv THIRDPARTY.yml ../../         # [not win]
    - move THIRDPARTY.yml ..\..        # [win]

    # Build, skipping auditwheel to rely on shared libs
    - maturin build --release --skip-auditwheel --out dist --interpreter={{ PYTHON }}

    # Install dynamically to avoid issues with path sytax
    - {{ PYTHON }} -m pip install sedonadb --no-index --find-links=dist --no-deps -vv

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.12,<2.0
    - pip
    - geos
  run:
    - python
    - apache-sedona
    - geos

test:
  requires:
    - pip
  imports:
    - sedonadb
  commands:
    - pip check
    - python -c "import sedonadb; print('SedonaDB successfully initialized')"

about:
  home: https://github.com/apache/sedona-db
  summary: A single-node analytical database engine with geospatial as a first-class citizen
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - p-vdp
    - paleolimbot
    - jiayuasu
    
