schema_version: 1

context:
  version: "2.1.0"

package:
  name: fmm3dpy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fmm3dpy/fmm3dpy-${{ version }}.tar.gz
  sha256: b2de0767fd59c8e7d82c7c624699903f6a902a895ef48407fa444068c939e790

build:
  number: 0
  script:
    - if: win
      then: set "AR=lib" && for /d %%d in ("%BUILD_PREFIX%\Library\lib\clang\*") do set "LIB=%%d\lib\x86_64-pc-windows-msvc;%LIB%"
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('fortran') }}
  host:
    - python
    - meson-python
    - numpy >=2.0.0
    - pip
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - fmm3dpy
      pip_check: true
  - script:
      - pytest -s python/test
    files:
      source:
        - python/test/
    requirements:
      run:
        - pip
        - pytest

about:
  homepage: https://github.com/flatironinstitute/FMM3D
  repository: https://github.com/flatironinstitute/FMM3D
  documentation: https://fmm3d.readthedocs.io/en/latest/
  summary: This package contains basic routines for Laplace, Helmholtz, Stokes and Maxwell fast multipole methods in three dimensions
  license: Apache-2.0
  license_file:
    - LICENSE
    - julia/LICENSE

extra:
  recipe-maintainers:
    - srimanachanta
