schema_version: 1

context:
  version: "0.1.1"

package:
  name: servicex-mcp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/servicex_mcp/servicex_mcp-${{ version }}.tar.gz
  sha256: 8ca9f5f24e33688ba6d454194ac319344c5304ef1ab2b1d1916c8b20271b8336

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - servicex-mcp=servicex_mcp.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - mcp >=2.0,<3
    - httpx2 >=2.0.0
    - pydantic >=2.11
    - servicex >=3.3.0
    - starlette >=0.27
    - uvicorn >=0.31.1

tests:
  - python:
      imports:
        - servicex_mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - servicex-mcp --help

about:
  summary: An MCP server that exposes ServiceX operations as tools for LLMs.
  homepage: https://servicex-mcp.readthedocs.io/en/latest/
  repository: https://github.com/maniaclab/servicex-mcp
  documentation: https://maniaclab.uchicago.edu/servicex-mcp/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
