--- Makefile.orig	2020-03-25 11:02:34.874709800 -0500
+++ Makefile	2020-03-25 15:01:00.230571630 -0500
@@ -330,20 +330,20 @@
 	install -m 644 include/mupdf/fitz/*.h $(DESTDIR)$(incdir)/mupdf/fitz
 	install -m 644 include/mupdf/pdf/*.h $(DESTDIR)$(incdir)/mupdf/pdf
 
-	install -d $(DESTDIR)$(libdir)
-	install -m 644 $(INSTALL_LIBS) $(DESTDIR)$(libdir)
+	install --compare --verbose -d $(DESTDIR)$(libdir)
+	install --compare --verbose -m 644 $(INSTALL_LIBS) $(DESTDIR)$(libdir)
 
-	install -d $(DESTDIR)$(bindir)
-	install -m 755 $(TOOL_APPS) $(VIEW_APPS) $(DESTDIR)$(bindir)
+	install --compare --verbose -d $(DESTDIR)$(bindir)
+	install --compare --verbose -m 755 $(TOOL_APPS) $(VIEW_APPS) $(DESTDIR)$(bindir)
 
-	install -d $(DESTDIR)$(mandir)/man1
-	install -m 644 docs/man/*.1 $(DESTDIR)$(mandir)/man1
+	#install -d $(DESTDIR)$(mandir)/man1
+	#install -m 644 docs/man/*.1 $(DESTDIR)$(mandir)/man1
 
-	install -d $(DESTDIR)$(docdir)
-	install -d $(DESTDIR)$(docdir)/examples
-	install -m 644 README COPYING CHANGES $(DESTDIR)$(docdir)
-	install -m 644 docs/*.html docs/*.css docs/*.png $(DESTDIR)$(docdir)
-	install -m 644 docs/examples/* $(DESTDIR)$(docdir)/examples
+	install --compare --verbose -d $(DESTDIR)$(docdir)
+	#install -d $(DESTDIR)$(docdir)/examples
+	install --compare --verbose -m 644 README COPYING CHANGES $(DESTDIR)$(docdir)
+	#install -m 644 docs/*.html docs/*.css docs/*.png $(DESTDIR)$(docdir)
+	#install -m 644 docs/examples/* $(DESTDIR)$(docdir)/examples
 
 tarball:
 	bash scripts/archive.sh
