--- Makefile.orig	2020-03-25 11:02:34.874709800 -0500
+++ Makefile	2020-03-26 15:50:24.164426027 -0500
@@ -340,10 +340,10 @@
 	install -m 644 docs/man/*.1 $(DESTDIR)$(mandir)/man1
 
 	install -d $(DESTDIR)$(docdir)
-	install -d $(DESTDIR)$(docdir)/examples
+	#install -d $(DESTDIR)$(docdir)/examples
 	install -m 644 README COPYING CHANGES $(DESTDIR)$(docdir)
-	install -m 644 docs/*.html docs/*.css docs/*.png $(DESTDIR)$(docdir)
-	install -m 644 docs/examples/* $(DESTDIR)$(docdir)/examples
+	#install -m 644 docs/*.html docs/*.css docs/*.png $(DESTDIR)$(docdir)
+	#install -m 644 docs/examples/* $(DESTDIR)$(docdir)/examples
 
 tarball:
 	bash scripts/archive.sh
