schema_version: 1

context:
  version: "2.23.0"

package:
  name: nxstools
  version: ${{ version }}

source:
  url: https://github.com/nexdatas/nxsconfigserver/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1a845d61f388456216ebf3124d23cd6cb61c13be4606aead87b4e0185653bbfc

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61
    - pip
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - argcomplete
    - lxml
    - pytango
    - mysql-client
    - mysqldb

tests:
  - python:
      imports:
        - nxsconfigserver
        - nxsconfigserver.ComponentParser
        - nxsconfigserver.Errors
        - nxsconfigserver.MYSQLDataBase
        - nxsconfigserver.Merger
        - nxsconfigserver.NXSConfigServer
        - nxsconfigserver.Release
        - nxsconfigserver.StreamSet
        - nxsconfigserver.XMLConfigurator

      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - if: unix
        then:
          - test -x "$PREFIX/bin/NXSConfigServer"
          - NXSConfigServer --help
    requirements:
      run:
        - python ${{ python_min }}.*


about:
  homepage: https://github.com/nexdatas/nxsconfigserver
  repository: https://github.com/nexdatas/nxsconfigserver
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: NeXus Configuration tango server
  description: |
    NeXuS Configuration Server is a Tango Server with its
    implementation based on a MySQL database.
    It allows to store XML configuration datasources and components.
    It also gives possibility to select mandatory components
    and perform the process of component merging.

extra:
  recipe-maintainers:
    - jkotan
