{% set name = "pyreaddbc" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyreaddbc-{{ version }}.tar.gz
  sha256: e3ce8f12b0feec3d6bf2b3722309346f015a22e8279f9789e9eeda869d8b33d1

build:
  number: 0
  skip: True  # [not linux]
  script_env:
   - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - dbfread >=2.0.7

test:
  imports:
    - pyreaddbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyreaddbc/
  summary: pyreaddbc
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - luabida
