{% set version = "6.5" %}

package:
  name: art
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/art/art-{{ version }}.tar.gz
  sha256: a98d77b42c278697ec6cf4b5bdcdfd997f6b2425332da078d4e31e31377d1844

build:
  entry_points:
    - art = art.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - art
  commands:
    - pip check
    - art --help
  requires:
    - pip
    - python

about:
  home: https://github.com/sepandhaghighi/art
  summary: ASCII Art Library For Python
  dev_url: https://github.com/sepandhaghighi/art
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-vdp
