schema_version: 1

context:
  version: "0.23.4"

package:
  name: tree-sitter-cpp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tree_sitter_cpp/tree_sitter_cpp-${{ version }}.tar.gz
  sha256: 6a59c4cebb1ad1dc2e8d586cf8a72b39d21b8108b7b139d089719e81a339e41d

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("c") }}
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
  run:
    - python

tests:
  - python:
      imports:
        - tree_sitter_cpp

about:
  homepage: https://github.com/tree-sitter/tree-sitter-cpp
  summary: C++ grammar for tree-sitter
  license: MIT
  license_file: LICENSE
  repository: https://github.com/tree-sitter/tree-sitter-cpp

extra:
  recipe-maintainers:
    - killua156
    - mgorny
