schema_version: 1

context:
  version: "1.9"

package:
  name: macher
  version: ${{ version }}

source:
  url: https://github.com/culler/macher/archive/refs/tags/v${{ version }}.tar.gz 
  sha256: 3988b6066524561a982cf8aa79604dbced2c01286bddb872c8340c4825cc64a0

build:
  number: 0
  skip: not osx
  script:
    - make macher
    - install -m0755 macher ${PREFIX}/bin/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make

tests:
  - script:
      - make example/hello
      - "[[ $(example/hello) == 'hello world' ]]"

about:
  homepage: https://github.com/culler/macher
  summary: A tool for dealing with mach-O object files
  description: |
    Macher is a command line tool for inspecting and modifying Mach-O
    binary files as produced by Apple's clang C compiler.

    Macher provides some functions which are similar to those provided
    by Apple's install_name_tool and otool programs, as well as some
    functions which are not available with those programs.
  license: BSD-2-Clause
  license_file: License.txt
  repository: https://github.com/culler/macher

extra:
  recipe-maintainers:
    - mgorny
