context:
  version: "0.1.0"

package:
  name: urdf-usd-converter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/u/urdf-usd-converter/urdf_usd_converter-${{ version }}.tar.gz
  sha256: a1732cb9812c5acaa75121c108477032ad4ca37b53c4b8272bf2a3b0fe4f67c1

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - urdf_usd_converter = urdf_usd_converter.__main__:run

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - requests
  run:
    - python >=${{ python_min }}
    - usd-exchange >=2.2.2
    - newton-usd-schemas >=0.1.0
    - numpy-stl >=3.2
    - pycollada >=0.9.2
    - tinyobjloader-python >=2.0.0rc13

tests:
  - python:
      imports:
        - urdf_usd_converter
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - urdf_usd_converter --help

about:
  homepage: https://github.com/newton-physics/urdf-usd-converter
  repository: https://github.com/newton-physics/urdf-usd-converter
  documentation: https://github.com/newton-physics/urdf-usd-converter#readme
  summary: A URDF to OpenUSD data converter
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - traversaro
