{% set name = "tomlplus" %}
{% set version = "1.0.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tomlplus-{{ version }}.tar.gz
  sha256: 7d0935ebc19cc634e29458c7ca320ed2799326c2dbf6d1c678f5b0bafc82e64d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - tomlplus
  commands:
    - tomlplus --help

about:
  home: https://github.com/CarsonKopec/tomlplus
  license: MIT
  license_file: LICENSE
  summary: TOML+ configuration format with dictionaries, annotations, and variables
  doc_url: https://github.com/CarsonKopec/tomlplus
  dev_url: https://github.com/CarsonKopec/tomlplus

extra:
  recipe-maintainers:
    - CarsonKopec
