schema_version: 1

context:
  version: "0.1.0"

package:
  name: jupyverse-kernels
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupyverse-kernels/jupyverse_kernels-${{ version }}.tar.gz
    sha256: 2d12495203af104c7d8ad37a4d965b4b3b270bb114c5b4f3cac95515fb395bb8

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - fastapi-core
    - jupyverse-api >=0.15.0,<0.16.0
    - jupyverse-auth >=0.2.0,<0.3.0
    - jupyverse-kernel >=0.1.0,<0.2.0
    - pydantic

tests:
  - python:
      imports: jupyverse_kernels
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/api/kernels
  summary: The API for Jupyverse's kernels.

extra:
  recipe-maintainers:
    - davidbrochart
