context:
  version: "2.1.0"

package:
  name: pygensuggestions
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pygensuggestions/pygensuggestions-${{ version }}.tar.gz
  sha256: 575573a498f65041dcfaf93caeb89becf83854502bce3f3c597328efd3191cc2

build:
  script:
    - uv pip install --python ${{ PYTHON }} --no-deps -vv .
  number: 0
  noarch: python
  python:
    entry_points:
      - pygensuggestions = pygensuggestions.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - uv
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - pygensuggestions
      pip_check: true
  - script:
      - pygensuggestions -v
      - pygensuggestions spammy hammy eggs

about:
  homepage: https://github.com/jonathandung/pygensuggestions
  summary: Generate suggestions deterministically based on mistyped input and possible targets.
  description: A self-contained string suggester derived from the CPython source that operates on strings and bytestrings alike.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/jonathandung/pygensuggestions

extra:
  recipe-maintainers:
    - jonathandung
