context:
  version: "0.1.0"

package:
  name: uuid7
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/u/uuid7/uuid7-${{ version }}.tar.gz
  sha256: 8c57aa32ee7456d3cc68c95c4530bc571646defac01895cfc73545449894a63c

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - uuid_extensions
      pip_check: true

about:
  homepage: https://github.com/stevesimmons/uuid7
  summary: UUID version 7, generating time-sorted UUIDs with 200ns time resolution and 48 bits of randomness
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MertErtugrulQC
