#!/usr/bin/env bash

unset ROOTSYS

unset CMSSW_RELEASE_BASE
unset CMSSW_BASE
export DYLD_FALLBACK_LIBRARY_PATH=$OLD_DYLD_FALLBACK_LIBRARY_PATH
unset OLD_DYLD_FALLBACK_LIBRARY_PATH
unset LIBRARY_PATH
unset ROOT_INCLUDE_PATH
unset CMSSW_SEARCH_PATH
