{% set name = "pyobjc-framework-uniformtypeidentifiers" %}
{% set version = "12.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fb89d13aa3c2df8e6d6536f6df3493fe5a6caefd2a5adebf17c5af3b29ed4a2

build:
  skip: true # not [osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.10
    - pyobjc-core >=12.2.1
    - pyobjc-framework-cocoa >=12.2.1

test:
  imports:
    - UniformTypeIdentifiers
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the framework UniformTypeIdentifiers on macOS
  doc_url: https://pyobjc.readthedocs.io/en/latest/
  license: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - jaromieee
