# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.0.0rc4"
  python_min: "3.13"

package:
  name: eopf
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/eopf/eopf-${{ version }}.tar.gz
  sha256: 3855237849102c9cc82cc49bf37daa2a6805f96e52c8a4745b828a4487da2f02
  patches: [no-eccodeslib.patch, no-aiokafka.patch]
 
build:
  # noarch: python
  script: python -m pip install . -vv
  number: 0
  skip:
    - not match(python, "<3.13.*")

requirements:
  build:
  host:
    - python ${{ python_min }}.*
    - pip >=25.3
    - flit-core >=3.12
  run:
    - python
    # - python >=${{ python_min }}
    - starlette >=1.3.0
    - setuptools >=78.1.1
    - python-dotenv
    - pydantic >=2, <3
    - Jinja2 >=3
    - beautifulsoup4 >=4
    - cloudpickle >=3
    - future >=1.0.0
    - dacite >=1
    - xarray >=2026.2
    - netcdf4 >1.7.3
    - numpy >=2
    - zarr >=2.12.8,<4.0
    - python-blosc2
    - obstore
    - fsspec >=2024
    - lxml >=6
    - cfgrib >=0.9.15.1
    - python-eccodes >=2.43.0
    - rioxarray >=0.22
    - rasterio >=1.4.3
    - h5py >=3
    - s3fs >=2025.10.0
    - click >=8
    - fastapi >=0.136
    - uvicorn >=0.30
    - requests >=2
    - aiokafka >=0
    - pytz >=2024
    - rio-cogeo >=5
    - toml >=0
    - deepdiff >=8.6.1
    - jsonschema >=4
    - shapely >=2
    - geopandas >=1
    - overrides >=7
    - xmlschema >=4
    - json5
    - pandas >2.2
    - pyarrow
    - pyyaml >=6

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
      - eopf
      pip_check: true
  # - requirements:
  #     run:
  #       - pytest
  #       - pytest-asyncio
  #       - hypothesis >=6
  #       - pytest-error-for-skips >=2
  #       - kerchunk >=0
  #       - scipy
  #       - defusedxml
  #   files:
  #     source:
  #       - tests/
  #   script:
  #     - pytest tests/

about:
  homepage: https://gitlab.eopf.copernicus.eu/cpm/eopf-cpm
  summary: 'EOPF Core Python Modules'
  description: |
    The EOPF Core Python Modules (EOPF-CPM) is python package gathering the
    best-in-class open-source python modules in a harmonized framework
    intended for the development of image processors. Particularly the
    re-engineering of the operational Level-0, Level-1 and Level-2 processors
    for the instruments on-board of the Copernicus Sentinel-1, Sentinel-2,
    Sentinel-3 (Land) missions.
    It is providing features such as:
    * A generic product representation EOProduct compatible with the UNIDATA
      CDM model with utilities library allowing:
      - Writing an EOProduct to different external representations,
        formats and file systems.
      - Reading an EOProduct from different external representations
        including the legacy file format (mostly SAFE).
    * Distributed and parallel computing based on Dask.
    * Logging and tracing tools.
    * Processors triggering and workflows definition.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://cpm.pages.eopf.copernicus.eu/eopf-cpm/main/index.html
  repository: https://gitlab.eopf.copernicus.eu/cpm/eopf-cpm

extra:
  recipe-maintainers:
    - avalentino
