{% set name = "amzn-sagemaker-ray-jupyterlab-extension" %}
{% set version = "0.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amzn_sagemaker_ray_jupyterlab_extension-{{ version }}.tar.gz
  sha256: d4464e7c0ecf52b3dc23846e50753046130efc37482b6c84a12c0960411576de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - amzn_sagemaker_ray_jupyterlab_extension
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/amzn-sagemaker-ray-jupyterlab-extension/
  summary: SageMaker JupyterLab Ray extension for HyperPod Ray cluster discovery and connection
  description: |
    SageMaker JupyterLab Ray extension for HyperPod Ray cluster discovery and
    connection.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HariniNarayanan
