context:
  version: "2.3.1"

package:
  name: chronos-forecasting
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/chronos-forecasting/chronos_forecasting-${{ version }}.tar.gz
  sha256: 785116f3f10aaac44a315700c5e4de71a5fe6385c9c771722d688f402fe75083

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - pytorch >=2.2,<3
    - transformers >=4.41,<6
    - accelerate >=1.1.0,<2
    - numpy >=1.21,<3
    - einops >=0.7.0,<1
    - pandas >=2.0,<4

tests:
  - python:
      imports:
        - chronos
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/amazon-science/chronos-forecasting
  summary: "Chronos: Pretrained models for time series forecasting"
  description: |
    Chronos is a family of pretrained time series forecasting models based on
    language model architectures. A time series is transformed into a sequence
    of tokens via scaling and quantization, and a model is trained on these
    tokens. Chronos models can generate probabilistic forecasts in a zero-shot
    fashion and include the Chronos, Chronos-Bolt, and Chronos-2 model families.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://github.com/amazon-science/chronos-forecasting
  repository: https://github.com/amazon-science/chronos-forecasting

extra:
  recipe-maintainers:
    - shchur
    - abdulfatir
