{% set name = "mritk" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: bababceb46adab0b84a8b8d4e5122a66122ad1f188b8fffbf63f6b5344e23739

build:
  number: 0
  noarch: python
  entry_points:
    - "mritk=mritk.cli:main"
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tqdm
    - numpy
    - rich-argparse
    - nibabel
    - pandas
    - scipy
    - scikit-image
    - pydicom
    - dcm2niix
test:
  requires:
    - python {{ python_min }}

  imports:
    - mritk

  commands:
    - mritk --help


about:
  home: https://github.com/scientificcomputing/mri-toolkit
  summary: MRI-toolkit provides a set of features dedicated to human MRI data post-processing
  license: MIT
  license_file: LICENSE
  doc_url: https://scientificcomputing.github.io/mri-toolkit/
  dev_url: https://github.com/scientificcomputing/mri-toolkit

extra:
  recipe-maintainers:
    - finsberg
    - cdaversin
