#!/bin/bash

EXTRA_CMAKE_ARGS=""
if [[ `uname` == 'Darwin' ]];
then
    EXTRA_CMAKE_ARGS="-DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}"
else
    export CXXFLAGS="-pthread ${CXXFLAGS}"
fi
export EXTRA_CMAKE_ARGS

export AD3_CXX_FLAGS="${CXXFLAGS}"
#export AD3_CXX_FLAGS="${CXXFLAGS} -std=c++11"


export AD3_LDFLAGS="${CXX_LDFLAGS} -Wl,-rpath,${PREFIX}/lib -L${PREFIX}/lib"






cmake  \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    -DCMAKE_PREFIX_PATH=${PREFIX} \
    \
    -DCMAKE_CXX_LINK_FLAGS="${AD3_LDFLAGS}" \
    -DCMAKE_EXE_LINKER_FLAGS="${AD3_LDFLAGS}" \
    -DCMAKE_CXX_FLAGS="${AD3_CXX_FLAGS}" \
    -DCMAKE_CXX_FLAGS_RELEASE="${AD3_CXX_FLAGS_RELEASE}" \
    -DCMAKE_CXX_FLAGS_DEBUG="${AD3_CXX_FLAGS}" \

make -j${CPU_COUNT}

make install
