{% set version = "0.2.1" %}

package:
  name: pymatgen-io-aims
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatgen_io_aims-{{ version }}.tar.gz
  sha256: fea6acfb5159c6e9c4cd899333217005397b2bffaa31f1338eb84ce59ab9aed3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - pymatgen >=2022.0.3
    - pyfhiaims >=1.1.0

test:
  imports:
    - build
    - dist
    - pymatgen
  commands:
    - pip check
  requires:
    - pip

about:
  summary: pymatgen-io-aims is a pymatgen addon that bridges the gap between FHI-aims and the pymatgen ecosystem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ansobolev
    - tpurcell90
