@echo off
set "SWIFT="
set "SWIFTC="
set "SWIFT_EXEC="
set "CONDA_SWIFT_COMPILER="
set "CONDA_SWIFT_BIN="
if defined CONDA_SWIFT_SDKROOT_SET call set "SDKROOT=%%CONDA_SWIFT_SDKROOT_BACKUP%%"
set "CONDA_SWIFT_SDKROOT_BACKUP="
set "CONDA_SWIFT_SDKROOT_SET="
