context:
  version: "1.1"

package:
  name: ocaml-gen
  version: ${{ version }}

source:
  url: https://github.com/c-cube/gen/archive/v${{ version }}.tar.gz
  sha256: 6893bf156bbaa4254ec5ec2ea5fe539030f2395bc5cd83ccb8fe3930cff89cb0

build:
  number: 0
  skip:
    - win
  script:
    - dune build --profile=release -p gen @install
    - dune install --prefix="${PREFIX}" --libdir="${PREFIX}/lib/ocaml" gen

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("ocaml") }}
    - ocaml-dune >=1.1
  host:
    - ocaml >=4.03.0
    - ocaml-seq
  run:
    # gen's META declares `requires = "seq"`, so consumers need it too.
    - ocaml-seq

tests:
  - package_contents:
      strict: true
      files:
        - lib/ocaml/gen/*
        - doc/gen/*

about:
  homepage: https://github.com/c-cube/gen
  repository: https://github.com/c-cube/gen
  summary: Iterators for OCaml, both restartable and consumable
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ManuelLerchner
    - MementoRC
