schema_version: 1

context:
  python_min: "3.11"
  version: "3.0.0"

package:
  name: lume-torch
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lume-torch/lume_torch-${{ version }}.tar.gz
  sha256: 276e90b7bd7ff4b7bba1d67a2ad40eebf3015a8dbe1e2683fbcd21745545a676

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=75.0
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic
    - numpy
    - pyyaml
    - lume-base
    - pytorch >=2.4
    - botorch >=0.15

tests:
  - if: not win
    then:
      python:
        imports:
          - lume_torch
        pip_check: true
        python_version: ${{ python_min }}.*

about:
  summary: LUME compatible wrapper for Torch based surrogate models.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/lume-science/lume-torch
  documentation: https://lume-science.github.io/lume-torch/

extra:
  recipe-maintainers:
    - pluflou
