schema_version: 1

context:
  version: "0.0.1"

package:
  name: voms-lsc
  version: ${{ version }}

source:
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/desy-voms-all-1.0.0-1.noarch.rpm
    sha256: d615fb5c3c3a71d87475a449ac72d837073e5d9b9114c85b6ec267ce30350073
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-alice-3.0.0-1.el9.noarch.rpm
    sha256: ef477cdcd785be1d248cb22d627185dbd1ccf00aeb6bf471c035733cfd8fb5e8
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-atlas-3.0.0-1.el9.noarch.rpm
    sha256: 1be1a43d46134492cf0f7a79c9ada672c8d22f76ceb3bc5715d156842092585c
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-cms-3.0.0-1.el9.noarch.rpm
    sha256: ed467bd1ad20f1dcba4a3af5012d3e2facd901abd921103fad57298a08c4d731
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-dteam-1.0.0-1.el9.noarch.rpm
    sha256: ffbd8b2d37df1ef97b021cc091e550d90e2ae15d30d5b6932fd3ae911096f1b0
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-ilc-1.0.0-1.noarch.rpm
    sha256: 1c404ceb80ddb5d38173a43a5012fadcfcab09d312d82c38afde6b9c8d7f54ef
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-juno-1.0.0-1.el9.noarch.rpm
    sha256: 0f60aad8890058ecd3ba9762e27ffd90592a356e877aaf347ebdaaedca7ceb7b
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-lhcb-3.0.0-1.el9.noarch.rpm
    sha256: 55b132393c09c03210718ca22659e08616c61754f8c3fa771298e92bf7f2454c
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-lsc-ops-2.0.0-1.el9.noarch.rpm
    sha256: d350588f27a02792c53956187137bc00624f2ee32f6684dc2f17837ea7398e49
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-vomses-alice-3.0.0-1.el9.noarch.rpm
    sha256: 5dd591db52f533664e263cfc223ca7c2af52910b2fb638ebade8a6f4fd0d2ddf
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-vomses-atlas-3.0.0-1.el9.noarch.rpm
    sha256: cac0eee3843d4159abaa8dd8d5bd65f28aa60b910bc64a6c8b6e67c34b93286e
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-vomses-cms-3.0.0-1.el9.noarch.rpm
    sha256: 0d1593926aee93d2ab503f43e850cc3b371fa370a3a284c3f0ba34530f821968
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-vomses-dteam-1.0.0-1.el9.noarch.rpm
    sha256: 03a1c0f9001a28aae40b1d1f5b6f03a76fed2ef02d9e2b4423e3063281cdea47
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-vomses-ilc-1.0.0-1.noarch.rpm
    sha256: 9cbbf23dab22b125d5f899985bcca2f2930648911d1276fae5f148972460a08c
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-vomses-lhcb-3.0.0-1.el9.noarch.rpm
    sha256: dfa5f553bf5d0ece74a1fa6a5e9499a01263718c385dccf6e68bc89ea130c3f4
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-iam-vomses-ops-2.0.0-1.el9.noarch.rpm
    sha256: 388f9c777e87f214f247551b34020b675b1341842d1aa8ab5efa1023b3c5df27
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-lsc-belle-1.0.0-1.el9.noarch.rpm
    sha256: 25e62f10c82e8092554792519702c0745711033d6f1165e6269d852d44757a8b
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-lsc-dune-1.0.0-1.el9.noarch.rpm
    sha256: 5c5af191792b983f5e937a9afeed507ba35bf3ac91371be50fa50202be1d962a
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-voms-alice-2.0.0-1.el9.noarch.rpm
    sha256: d9b911c8473743b3adea389418dcde2bc387beb7a5f8df5c0d7bcaa466633de6
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-voms-atlas-2.0.0-1.el9.noarch.rpm
    sha256: 9df0dfbf14c7e418462b3757c62085fc8033465979eb6126405f22934b4c0c04
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-voms-cms-2.0.0-1.el9.noarch.rpm
    sha256: 38477999c966c69fd89d336300f20469092f922c7a3b5c9f6629ce5e1a9653da
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-voms-dteam-1.0.0-1.el9.noarch.rpm
    sha256: 68aec7a4696e7d9e7df9f28a215fd07bfde03186043405e68311e369861a853e
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-voms-lhcb-2.0.0-1.el9.noarch.rpm
    sha256: 1212ad79c04ee114e74b976ab110b918fd056ba41705dcbfb23c5e869c0035f4
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-voms-ops-2.0.1-1.el9.noarch.rpm
    sha256: 6f85ab3955bd1fb820e0f77fb64803eba6aba721a4e5238229dfd622b7ce8617
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-vomses-belle-1.0.0-1.el9.noarch.rpm
    sha256: dfbac5b083391962acf7d3e46eebb8ee0590749648b34d59ed8c6b0509ab8566
    target_directory: rpms
  - url: https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-vomses-dune-1.0.0-1.el9.noarch.rpm
    sha256: bb83841acf8686c35fd4809a338c2456f949d685b5d9e67ac5329be007c4c99c
    target_directory: rpms
  - path: vomsdir/ams02.cern.ch/voms-02.pd.infn.it.lsc
    target_directory: etc/grid-security/vomsdir/ams02.cern.ch
  - path: vomsdir/ams02.cern.ch/voms-ams.cloud.cnaf.infn.it.lsc
    target_directory: etc/grid-security/vomsdir/ams02.cern.ch
  - path: vomsdir/dream/voms.hpcc.ttu.edu.lsc
    target_directory: etc/grid-security/vomsdir/dream
  - path: vomsdir/escape/voms-escape.cloud.cnaf.infn.it.lsc
    target_directory: etc/grid-security/vomsdir/escape
  - path: vomsdir/na62.vo.gridpp.ac.uk/voms.gridpp.ac.uk.lsc
    target_directory: etc/grid-security/vomsdir/na62.vo.gridpp.ac.uk
  - path: vomsdir/na62.vo.gridpp.ac.uk/voms02.gridpp.ac.uk.lsc
    target_directory: etc/grid-security/vomsdir/na62.vo.gridpp.ac.uk
  - path: vomsdir/na62.vo.gridpp.ac.uk/voms03.gridpp.ac.uk.lsc
    target_directory: etc/grid-security/vomsdir/na62.vo.gridpp.ac.uk
  - path: vomsdir/vo.compass.cern.ch/voms-compass-auth.cern.ch.lsc
    target_directory: etc/grid-security/vomsdir/vo.compass.cern.ch
  - path: vomses/ams02.cern.ch-voms-02.pd.infn.it
    target_directory: etc/vomses
  - path: vomses/ams02.cern.ch-voms-ams.cloud.cnaf.infn.it
    target_directory: etc/vomses
  - path: vomses/dream-voms.hpcc.ttu.edu
    target_directory: etc/vomses
  - path: vomses/escape-voms-escape.cloud.cnaf.infn.it
    target_directory: etc/vomses
  - path: vomses/na62.vo.gridpp.ac.uk-voms.gridpp.ac.uk
    target_directory: etc/vomses
  - path: vomses/na62.vo.gridpp.ac.uk-voms02.gridpp.ac.uk
    target_directory: etc/vomses
  - path: vomses/na62.vo.gridpp.ac.uk-voms03.gridpp.ac.uk
    target_directory: etc/vomses
  - path: vomses/vo.compass.cern.ch-voms-compass-auth.cern.ch
    target_directory: etc/vomses

build:
  number: 0
  noarch: generic
  script: build.py

requirements:
  build:
    - rpm-tools
    - python

tests:
  - script:
      interpreter: python
      content: |
        import os
        os.environ["X509_VOMS_DIR"]
        os.environ["VOMS_USERCONF"]

  - package_contents:
      strict: true
      files:
        # -- Env Vars --
        - etc/conda/env_vars.d/voms-lsc.json
        # -- desy-voms-all --
        - etc/grid-security/vomsdir/belle/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/calice/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/desy/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/ghep/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/hermes/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/hone/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/icecube/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/ilc/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/ildg/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/olympus/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/xfel.eu/grid-voms.desy.de.lsc
        - etc/grid-security/vomsdir/zeus/grid-voms.desy.de.lsc
        - etc/vomses/belle-grid-voms.desy.de
        - etc/vomses/calice-grid-voms.desy.de
        - etc/vomses/desy-grid-voms.desy.de
        - etc/vomses/ghep-grid-voms.desy.de
        - etc/vomses/hermes-grid-voms.desy.de
        - etc/vomses/hone-grid-voms.desy.de
        - etc/vomses/icecube-grid-voms.desy.de
        - etc/vomses/ilc-grid-voms.desy.de
        - etc/vomses/ildg-grid-voms.desy.de
        - etc/vomses/olympus-grid-voms.desy.de
        - etc/vomses/xfel.eu-grid-voms.desy.de
        - etc/vomses/zeus-grid-voms.desy.de
        # -- wlcg-iam-lsc-alice --
        - etc/grid-security/vomsdir/alice/voms-alice-auth.cern.ch.lsc
        # -- wlcg-iam-lsc-atlas --
        - etc/grid-security/vomsdir/atlas/voms-atlas-auth.cern.ch.lsc
        # -- wlcg-iam-lsc-cms --
        - etc/grid-security/vomsdir/cms/voms-cms-auth.cern.ch.lsc
        # -- wlcg-iam-lsc-dteam --
        - etc/grid-security/vomsdir/dteam/voms-dteam-auth.cern.ch.lsc
        # -- wlcg-iam-lsc-ilc --
        - etc/grid-security/vomsdir/ilc/voms-ilc-auth.cern.ch.lsc
        # -- wlcg-iam-lsc-juno --
        - etc/grid-security/vomsdir/juno/voms-juno.cloud.cnaf.infn.it.lsc
        # -- wlcg-iam-lsc-lhcb --
        - etc/grid-security/vomsdir/lhcb/voms-lhcb-auth.cern.ch.lsc
        # -- wlcg-iam-lsc-ops --
        - etc/grid-security/vomsdir/ops/voms-ops-auth.cern.ch.lsc
        # -- wlcg-iam-vomses-alice --
        - etc/vomses/alice-voms-alice-auth.cern.ch
        # -- wlcg-iam-vomses-atlas --
        - etc/vomses/atlas-voms-atlas-auth.cern.ch
        # -- wlcg-iam-vomses-cms --
        - etc/vomses/cms-voms-cms-auth.cern.ch
        # -- wlcg-iam-vomses-dteam --
        - etc/vomses/voms-dteam-auth.cern.ch.vomses
        # -- wlcg-iam-vomses-ilc --
        - etc/vomses/ilc-voms-ilc-auth.cern.ch
        # -- wlcg-iam-vomses-lhcb --
        - etc/vomses/lhcb-voms-lhcb-auth.cern.ch
        # -- wlcg-iam-vomses-ops --
        - etc/vomses/ops-voms-ops-auth.cern.ch
        # -- wlcg-lsc-belle --
        - etc/grid-security/vomsdir/belle/belle-auth.cc.kek.jp.lsc
        - etc/grid-security/vomsdir/belle/voms.cc.kek.jp.lsc
        # -- wlcg-lsc-dune --
        - etc/grid-security/vomsdir/dune/voms1.fnal.gov.lsc
        - etc/grid-security/vomsdir/dune/voms2.fnal.gov.lsc
        # -- wlcg-voms-alice --
        - etc/grid-security/vomsdir/alice/lcg-voms2.cern.ch.lsc
        - etc/grid-security/vomsdir/alice/voms2.cern.ch.lsc
        # -- wlcg-voms-atlas --
        - etc/grid-security/vomsdir/atlas/lcg-voms2.cern.ch.lsc
        - etc/grid-security/vomsdir/atlas/voms2.cern.ch.lsc
        # -- wlcg-voms-cms --
        - etc/grid-security/vomsdir/cms/lcg-voms2.cern.ch.lsc
        - etc/grid-security/vomsdir/cms/voms2.cern.ch.lsc
        # -- wlcg-voms-dteam --
        - etc/grid-security/vomsdir/dteam/voms2.hellasgrid.gr.lsc
        - etc/vomses/dteam-voms2.hellasgrid.gr
        # -- wlcg-voms-lhcb --
        - etc/grid-security/vomsdir/lhcb/lcg-voms2.cern.ch.lsc
        - etc/grid-security/vomsdir/lhcb/voms2.cern.ch.lsc
        # -- wlcg-voms-ops --
        - etc/grid-security/vomsdir/ops/lcg-voms2.cern.ch.lsc
        - etc/grid-security/vomsdir/ops/voms2.cern.ch.lsc
        - etc/vomses/ops-lcg-voms2.cern.ch
        - etc/vomses/ops-voms2.cern.ch
        # -- wlcg-vomses-belle --
        - etc/vomses/belle-belle-auth.cc.kek.jp
        - etc/vomses/belle-voms.cc.kek.jp
        # -- wlcg-vomses-dune --
        - etc/vomses/dune-voms1.fnal.gov
        - etc/vomses/dune-voms2.fnal.gov
        # -- local (no authoritative RPM) --
        - etc/grid-security/vomsdir/ams02.cern.ch/voms-02.pd.infn.it.lsc
        - etc/grid-security/vomsdir/ams02.cern.ch/voms-ams.cloud.cnaf.infn.it.lsc
        - etc/grid-security/vomsdir/dream/voms.hpcc.ttu.edu.lsc
        - etc/grid-security/vomsdir/escape/voms-escape.cloud.cnaf.infn.it.lsc
        - etc/grid-security/vomsdir/na62.vo.gridpp.ac.uk/voms.gridpp.ac.uk.lsc
        - etc/grid-security/vomsdir/na62.vo.gridpp.ac.uk/voms02.gridpp.ac.uk.lsc
        - etc/grid-security/vomsdir/na62.vo.gridpp.ac.uk/voms03.gridpp.ac.uk.lsc
        - etc/grid-security/vomsdir/vo.compass.cern.ch/voms-compass-auth.cern.ch.lsc
        - etc/vomses/ams02.cern.ch-voms-02.pd.infn.it
        - etc/vomses/ams02.cern.ch-voms-ams.cloud.cnaf.infn.it
        - etc/vomses/dream-voms.hpcc.ttu.edu
        - etc/vomses/escape-voms-escape.cloud.cnaf.infn.it
        - etc/vomses/na62.vo.gridpp.ac.uk-voms.gridpp.ac.uk
        - etc/vomses/na62.vo.gridpp.ac.uk-voms02.gridpp.ac.uk
        - etc/vomses/na62.vo.gridpp.ac.uk-voms03.gridpp.ac.uk
        - etc/vomses/vo.compass.cern.ch-voms-compass-auth.cern.ch

about:
  summary: VOMS LSC and vomses configuration files for WLCG VOs
  homepage: https://twiki.cern.ch/twiki/bin/view/LCG/VOMSLSCfileConfiguration
  documentation: https://twiki.cern.ch/twiki/bin/view/LCG/VOMSLSCfileConfiguration
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
