{% set name = "watertap-solvers" %}
{% set version = "24.12.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/watertap-solvers/watertap_solvers-{{ version }}.tar.gz
  sha256: ddefb8e2d0ed627a310f53c24eb3c5dece5242d2ca11519a231f84e794d4680a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - pyomo
    - idaes-pse
    - cyipopt

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - ipython
    - cyipopt
    - idaes-pse
  imports:
    - watertap_solvers
  commands:
    - pip check
  
about:
  home: "https://github.com/watertap-org/watertap-solvers"
  license_family: BSD
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - COPYRIGHT.md
  summary: "WaterTAP Solvers"
  dev_url: "https://github.com/watertap-org/watertap-solvers"

extra:
  recipe-maintainers:
    - sufikaur
    - lbianchi-lbl
