{% set version = "0.7.1" %}

package:
  name: doclang
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/doclang/doclang-{{ version }}.tar.gz
  sha256: aa2391b08751e311033b614b11dbeb3cd236f71772fe3db5722f4871361bd11d

build:
  entry_points:
    - doclang = doclang.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=80
    - pip
  run:
    - python >=3.10
    - lxml >=6.0.2
    - typer >=0.15.1

test:
  imports:
    - doclang
  commands:
    - pip check
    - doclang --help
  requires:
    - pip
    - python

about:
  home: https://www.doclang.ai/
  summary: DocLang reference toolkit
  doc_url: https://github.com/doclang-project/doclang/blob/main/README.md
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
