context:
  version: "0.0.4"

package:
  name: jupyter-ai-chat-commands
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-ai-chat-commands/jupyter_ai_chat_commands-${{ version }}.tar.gz
  sha256: 0c9722d139376e1bff87a730fbb6cc14019b010282fbce9d62001223d3d3c6b0

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
  run:
    - python >=${{ python_min }}
    - jupyter-ai-persona-manager >=0.0.3
    - jupyter-ai-router >=0.0.2
    - jupyter_server >=2.4.0,<3
    - jupyterlab-chat >=0.17.0

tests:
  - python:
      imports:
        - jupyter_ai_chat_commands
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-ai-chat-commands
  summary: "Default set of chat commands in Jupyter AI"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-ai-chat-commands

extra:
  recipe-maintainers:
    - dlqqq
    - andrii-i
