diff --git libraries/liblmdb/Makefile libraries/liblmdb/Makefile
index 0940c49..2550f1d 100644
--- libraries/liblmdb/Makefile
+++ libraries/liblmdb/Makefile
@@ -26,7 +26,7 @@ OPT = -O2 -g
 CFLAGS	= $(THREADS) $(OPT) $(W) $(XCFLAGS)
 LDLIBS	=
 SOLIBS	=
-prefix	= /usr/local
+prefix	=
 exec_prefix = $(prefix)
 bindir = $(exec_prefix)/bin
 libdir = $(exec_prefix)/lib
