{% set name = "fabdem" %}
{% set version = "0.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fabdem-{{ version }}.tar.gz
  sha256: af3704620e68871122d9663d8ec0f67f1aed5dd93b57c0bed84d98b87c6ed705

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.25
    - geopandas >=0.14
    - shapely >=2.0
    - rasterio >=1.3
    - pyproj >=3.0

test:
  imports:
    - fabdem
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jantomec/fabdem
  dev_url: https://github.com/jantomec/fabdem
  summary: 'Download FABDEM data: a DEM with forests and buildings removed using ML.'
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jantomec
