context:
  name: ffjet
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ffjet-${{ version }}.tar.gz
  sha256: 36dce69bc6d7099010ba2f60431defe1503502d69ec3addb10c50d28a9c590da

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy >=1.21
    - scipy >=1.10
    - astropy >=5.3
    - matplotlib-base >=3.6
    - numba >=0.57

tests:
  - python:
      imports:
        - jetfuncs
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
    script:
      - pytest tests -q

about:
  homepage: https://github.com/dpesce/ffjet
  repository: https://github.com/dpesce/ffjet
  summary: Semi-analytic force-free jet model for images and spectral energy distributions of relativistic jets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dpesce
