--- make/makefile.orig	2020-02-13 13:08:39.812176248 -0500
+++ make/makefile	2020-02-13 13:06:07.021291279 -0500
@@ -42,15 +42,15 @@
 .SUFFIXES: .c .cpp .f .f90 .F90 .fpp .o
 
 # Define the Fortran compile flags
-FC = gfortran
-FFLAGS = -O2 -fbacktrace
+#FC = gfortran
+#FFLAGS = -O2 -fbacktrace
 
 # Define the C compile flags
-CC = gcc
-CFLAGS = -O2 -D_UF
+#CC = gcc
+#CFLAGS = -O2 -D_UF
 
 # Define the libraries
-SYSLIBS =
+#SYSLIBS =
 
 OBJECTS = \
 $(OBJDIR)/kind.o \
