{% set version = "0.1.0" %}

package:
  name: collasso
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/collasso/collasso-{{ version }}.tar.gz
  sha256: 864762b8116bb6de93e65fe5c8201a1514fb96aa4f51c0e1d9a83ed6b3ce95d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10
    - numpy >=1.24
    - scipy >=1.10
    - scikit-learn >=1.2
    - docrep >=0.3

test:
  imports:
    - collasso
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://rauschenberger.github.io/collasso/
  summary: Sparse Linear Multi-Task Regression
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rauschenberger
