#!/usr/bin/env bash

export LD_LIBRARY_PATH=`thepeg-config --libdir`

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="$(dirname "${HERE}")"
exec "${HERE}/Herwig.orig" \
    --repo="${PREFIX}/share/Herwig/HerwigDefaults.rpo" \
    "$@"
