context:
  version: "7.2.0"

package:
  name: herwig
  version: ${{ version }}

source:
  url: https://herwig.hepforge.org/downloads/Herwig-${{ version }}.tar.bz2
  sha256: 5933545ddff7fde2bea86fa61943fba5d4be50ba993c336e9a372529a2f2b164

build:
  script:
    - FCFLAGS="-fallow-argument-mismatch" FFLAGS="-fallow-argument-mismatch" ./configure ${CONFIGURE_COMMON_FLAGS} --prefix=${PREFIX} --with-thepeg=${PREFIX} --with-fastjet=${PREFIX} --with-gsl=${PREFIX} --with-boost=${PREFIX}
    - make -j${CPU_COUNT} CXX=$CXX && make install
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler("fortran") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - make
  host:
    - boost
    - fastjet
    - gsl
    - thepeg

about:
  homepage: https://herwig.hepforge.org/
  summary: 'Multi-purpose particle physics event generator'
  description: |
    Herwig provides significantly improved and extended physics capabilities when compared to both its predecessors,
    HERWIG 6 and Herwig++ 2, while keeping the key model motivations such as coherent parton showers (including
    angular-ordered and dipole-based evolution), the cluster hadronization model, an eikonal multiple-interaction model,
    highly flexible BSM capabilities and improved perturbative input using next-to-leading order QCD.
  license: GPL-3.0-or-later
  license_file: COPYING
  documentation: https://herwig.hepforge.org/doxygen/
  repository: https://repo.hepforge.org/source/herwighg/

extra:
  recipe-maintainers:
    - utk4r-sh
    - GiacomoXT
    - vvsagar
    - AlexanderHeidelbach
