# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/pwwang/github/conda-recipes/r-ggradar, last modified Fri Jan  9 19:53:17 2026
# ------------------------------------------------

package:
  name: r-ggradar
  version: 0.2.0
source:
  git_rev: 568537ab057b333f628c1087d1a8b268eb490de8
  git_url: https://github.com/ricardo-bion/ggradar
build:
  number: '0'
  rpaths:
    - lib/
    - lib/R/lib/
  string: r44_568538
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _r-mutex 1.0.1 anacondar_1
    - binutils_impl_linux-64 2.45 default_hfdba357_105
    - bwidget 1.10.1 ha770c72_1
    - bzip2 1.0.8 hda65f42_8
    - c-ares 1.34.6 hb03c661_0
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cairo 1.18.4 h3394656_0
    - curl 8.18.0 h4e3cde8_0
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 h77eed37_3
    - fontconfig 2.15.0 h7e30c49_1
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 hc364b38_1
    - freetype 2.14.1 ha770c72_0
    - fribidi 1.0.16 hb03c661_0
    - gcc_impl_linux-64 15.2.0 hc5723f1_16
    - gfortran_impl_linux-64 15.2.0 h281d09f_16
    - graphite2 1.3.14 hecca717_2
    - gsl 2.7 he838d99_0
    - gxx_impl_linux-64 15.2.0 hda75c37_16
    - harfbuzz 12.2.0 h15599e2_0
    - icu 75.1 he02047a_0
    - kernel-headers_linux-64 6.12.0 he073ed8_5
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.45 default_hbd61a6d_105
    - lerc 4.0.0 h0aef613_1
    - libblas 3.11.0 5_h4a7cf45_openblas
    - libcblas 3.11.0 5_h0358290_openblas
    - libcurl 8.18.0 h4e3cde8_0
    - libdeflate 1.25 h17f619e_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.3 hecca717_0
    - libffi 3.5.2 h9ec8514_0
    - libfreetype 2.14.1 ha770c72_0
    - libfreetype6 2.14.1 h73754d4_0
    - libgcc 15.2.0 he0feb66_16
    - libgcc-devel_linux-64 15.2.0 hcc6f6b0_116
    - libgcc-ng 15.2.0 h69a702a_16
    - libgfortran 15.2.0 h69a702a_16
    - libgfortran-ng 15.2.0 h69a702a_16
    - libgfortran5 15.2.0 h68bc16d_16
    - libglib 2.86.3 h6548e54_0
    - libgomp 15.2.0 he0feb66_16
    - libiconv 1.18 h3b78370_2
    - libjpeg-turbo 3.1.2 hb03c661_0
    - liblapack 3.11.0 5_h47877c9_openblas
    - liblzma 5.8.1 hb9d3cd8_2
    - libnghttp2 1.67.0 had1ee68_0
    - libopenblas 0.3.30 pthreads_h94d23a6_4
    - libpng 1.6.54 h421ea60_0
    - libsanitizer 15.2.0 h90f66d4_16
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.2.0 h934c35e_16
    - libstdcxx-devel_linux-64 15.2.0 hd446a21_116
    - libstdcxx-ng 15.2.0 hdf11a46_16
    - libtiff 4.7.1 h9d88235_1
    - libuuid 2.41.3 h5347b49_0
    - libwebp-base 1.6.0 hd42ef1d_0
    - libxcb 1.17.0 h8a09558_0
    - libzlib 1.3.1 hb9d3cd8_2
    - make 4.4.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.6.0 h26f9b46_0
    - pango 1.56.4 hadf4263_0
    - pcre2 10.47 haa7fec5_0
    - pixman 0.46.4 h54a6638_1
    - pthread-stubs 0.4 hb9d3cd8_1002
    - r-base 4.4.3 h835929b_7
    - r-cli 3.6.5 r44h3697838_1
    - r-colorspace 2.1_2 r44h54b55ab_0
    - r-cpp11 0.5.2 r44h785f33e_2
    - r-farver 2.1.2 r44h3697838_2
    - r-ggplot2 4.0.1 r44h785f33e_0
    - r-glue 1.8.0 r44h54b55ab_1
    - r-gtable 0.3.6 r44hc72bb7e_1
    - r-isoband 0.3.0 r44h3697838_0
    - r-labeling 0.4.3 r44hc72bb7e_2
    - r-lifecycle 1.0.5 r44hc72bb7e_0
    - r-munsell 0.5.1 r44hc72bb7e_2
    - r-r6 2.6.1 r44hc72bb7e_1
    - r-rcolorbrewer 1.1_3 r44h785f33e_4
    - r-rlang 1.1.7 r44h3697838_0
    - r-s7 0.2.1 r44h54b55ab_0
    - r-scales 1.4.0 r44hc72bb7e_1
    - r-vctrs 0.6.5 r44h3697838_2
    - r-viridislite 0.4.2 r44hc72bb7e_3
    - r-withr 3.0.2 r44hc72bb7e_1
    - readline 8.3 h853b02a_0
    - sed 4.9 h6688a6e_0
    - sysroot_linux-64 2.39 hc4b9eeb_5
    - tk 8.6.13 noxft_ha0e22de_103
    - tktable 2.10 h8d826fa_7
    - tzdata 2025c hc9c84f9_1
    - xorg-libice 1.1.2 hb9d3cd8_0
    - xorg-libsm 1.2.6 he73a12e_0
    - xorg-libx11 1.8.12 h4f16b4b_0
    - xorg-libxau 1.0.12 hb03c661_1
    - xorg-libxdmcp 1.1.5 hb03c661_1
    - xorg-libxext 1.3.6 hb9d3cd8_0
    - xorg-libxrender 0.9.12 hb9d3cd8_0
    - xorg-libxt 1.3.1 hb9d3cd8_0
    - zstd 1.5.7 hb78ec9c_6
  run:
    - r-base >=4.4,<4.5.0a0
    - r-base >=4.4,<4.5.0a0
    - r-ggplot2
test:
  commands:
    - $R -e "library('ggradar')"
about:
  home: https://github.com/ricardo-bion/ggradar
  license: GPL-2
  license_family: GPL
  license_file:
    - /home/pwwang/miniconda3/conda-bld/r-ggradar_1768632871585/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/share/licenses/GPL-2
    - DESCRIPTION
  summary: This package exports the functionality of ggplot2 to create radar charts.
extra:
  copy_test_source_files: true
  final: true
