{% set name = "mcflow-py" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/I-AlKhurayyif/mcflow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b7f1c245b597d58af729ea9606ad0709bfc86873de5c37c270910d46d38b1ac1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.10
    - numpy
    - scipy
    - matplotlib-base
    - tqdm

test:
  imports:
    - mcflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/I-AlKhurayyif/mcflow
  summary: "A Python library for Monte Carlo methods, MCMC, and Bayesian Monte Carlo."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - I-AlKhurayyif
    