schema_version: 1

context:
  name: inspect-swe
  version: "0.2.68"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/inspect_swe-${{ version }}.tar.gz
  sha256: 91f8141acadd7d749835a6dab3d426ccd29f20d2cab4a3cf7549d1be44885667

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling <1.30
    - hatch-vcs
    - inspect-ai
    - pip
  run:
    - python >=${{ python_min }}
    - httpx
    - inspect-ai >=0.3.251
    - nest-asyncio
    - platformdirs
    - pydantic >=2.13.0
    - pyyaml
    - sniffio
    - anyio
    - typing_extensions >=4.9.0
    - agent-client-protocol >=0.11.0

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - inspect_swe
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Software engineering agents for Inspect AI.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/meridianlabs-ai/inspect_swe
  repository: https://github.com/meridianlabs-ai/inspect_swe

extra:
  recipe-maintainers:
    - tdsmith
