{% set name = "itkwasm-downsample-emscripten" %}
{% set version = "1.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/itkwasm-downsample-emscripten/itkwasm_downsample_emscripten-{{ version }}.tar.gz
  sha256: 905f39d4ae9ccb58e8ccfc5de7313c5d59c10073258e63aab6fa667e6403672e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - itkwasm
test:
  imports:
    - itkwasm_downsample_emscripten
  requires:
    - python

about:
  home: https://pypi.org/project/itkwasm-downsample-emscripten/
  summary: Pipelines for downsampling images.
  dev_url: https://github.com/InsightSoftwareConsortium/ITK-Wasm
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - khaled196
    - thewtex
