schema_version: 1

context:
  version: "0.1.5"
  python_min: "3.9"

package:
  name: ansible-sign
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ansible-sign/ansible_sign-${{ version }}.tar.gz
  sha256: d1c9b5ef4329501615b18fe2bf035f63a429f7c05e653d32ac59fc01892eaf74

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ansible-sign = ansible_sign.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=65.3.0
    - setuptools_scm >=7.0.5
  run:
    - python >=${{ python_min }}
    - distlib >=0.4.0
    - python-gnupg >=0.5.2

tests:
  - python:
      imports:
        - ansible_sign
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: |
    Ansible content validation library and CLI
  homepage: https://pypi.org/project/ansible-sign/
  repository: https://pypi.org/project/ansible-sign/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - killua156
    - mgorny
