context:
  version: "4.2.1"

package:
  name: font-monocraft
  version: ${{ version }}

source:
  - url: https://github.com/IdreesInc/Monocraft/releases/download/v${{ version }}/Monocraft-otf.zip
    sha256: e623b72f1021062ad0156cc41f54b108e70bd35e2b295127475bb572d8ade61d
    target_directory: otf
  - url: https://github.com/IdreesInc/Monocraft/releases/download/v${{ version }}/Monocraft-ttf.zip
    sha256: 897faffbef8cc27fadd0d5aa51872ab5f908e22a89bb8fa5b191366025d503e0
    target_directory: ttf
  - url: https://raw.githubusercontent.com/IdreesInc/Monocraft/v${{ version }}/LICENSE
    sha256: f69c147003e052dbc9d96c40a9f73647e72766cfda95a597b94ed827fe25acb1
    file_name: LICENSE

build:
  noarch: generic
  number: 0
  script:
    - mkdir -p $PREFIX/fonts
    - cp otf/Monocraft.otf $PREFIX/fonts
    - cp otf/weights/* $PREFIX/fonts
    - cp ttf/Monocraft.ttf $PREFIX/fonts
    - cp ttf/weights/* $PREFIX/fonts

tests:
  - package_contents:
      files:
        - fonts/Monocraft.otf
        - fonts/Monocraft-Black.otf
        - fonts/Monocraft-Black-Italic.otf
        - fonts/Monocraft-Bold.otf
        - fonts/Monocraft-Bold-Italic.otf
        - fonts/Monocraft-ExtraLight.otf
        - fonts/Monocraft-ExtraLight-Italic.otf
        - fonts/Monocraft-Italic.otf
        - fonts/Monocraft-Light.otf
        - fonts/Monocraft-Light-Italic.otf
        - fonts/Monocraft-SemiBold.otf
        - fonts/Monocraft-SemiBold-Italic.otf
        - fonts/Monocraft.ttf
        - fonts/Monocraft-Black.ttf
        - fonts/Monocraft-Black-Italic.ttf
        - fonts/Monocraft-Bold.ttf
        - fonts/Monocraft-Bold-Italic.ttf
        - fonts/Monocraft-ExtraLight.ttf
        - fonts/Monocraft-ExtraLight-Italic.ttf
        - fonts/Monocraft-Italic.ttf
        - fonts/Monocraft-Light.ttf
        - fonts/Monocraft-Light-Italic.ttf
        - fonts/Monocraft-SemiBold.ttf
        - fonts/Monocraft-SemiBold-Italic.ttf
      strict: true

about:
  homepage: https://github.com/IdreesInc/Monocraft
  summary: A monospaced programming font inspired by the Minecraft typeface
  license: OFL-1.1
  license_file: LICENSE
  repository: https://github.com/IdreesInc/Monocraft

extra:
  recipe-maintainers:
    - pavelzw
