{% set name = "py2opsin" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e1fb22cc7ecaf9622dd770811ccaaced0348a011d6cb6e847dc3c82fd346147

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - openjdk >=8

test:
  imports:
    - py2opsin
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - python -m pip check
    - java -version
    - python -c "from py2opsin import py2opsin; assert py2opsin('ethane') == 'CC'"

about:
  home: https://github.com/JacksonBurns/py2opsin
  summary: Simple Python interface to OPSIN, the Open Parser for Systematic IUPAC nomenclature
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - r-fedorov
