{% set version = "1.0.1" %}

package:
  name: spt3g
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spt3g/spt3g-{{ version }}.tar.gz
  sha256: 6a1bbb92e3883d751d677129f82d11a73512c0d7a9bac811494793ef748c2ab7

build:
  number: 0
  skip: true  # [win]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - pip
    - pybind11
    - setuptools
    - setuptools-scm
    - numpy
    - libflac
    - libogg
    - libnetcdf
    - zlib
    - bzip2
    - liblzma
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - python
    - numpy
    - scipy
    - astropy-base
    - healpy

test:
  requires:
    - pytest
  commands:
    - ctest --test-dir build --output-on-failure  # [build_platform == target_platform]
    - pytest gcp/tests  # [build_platform == target_platform]
    - pytest dfmux/tests  # [build_platform == target_platform]
    - pytest core/tests  # [build_platform == target_platform]
    - pytest maps/tests  # [build_platform == target_platform]

about:
  home: https://github.com/CMB-S4/spt3g_software
  summary: Public Subset of Analysis Software Developed by the SPT-3G Collaboration
  description: |
    This repository contains the public portions of the analysis software developed by the SPT-3G collaboration. It includes the IO libraries, data acquisition code for McGill's DfMux readout boards, pipeline glue code, a binned map-maker, and a sky mock-observer, as well as defining all the APIs used by the project.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://cmb-s4.github.io/spt3g_software/
  dev_url: https://github.com/CMB-S4/spt3g_software

extra:
  recipe-maintainers:
    - tskisner
    #- iparask
    #- arahlin
