schema_version: 1

context:
  python_min: "3.11"
  version: "0.0.3"

package:
  name: ramp-batman
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/ramp-batman/ramp_batman-${{ version }}.tar.gz
  sha256: 848e25f9ffca169884e84e5c94e360b8fdf1cf2e9bc1201876bb206291a4d924

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core
    - matplotlib-base
    - more-itertools
    - multipledispatch
    - networkx
    - numpy
    - ramp-coremaker
    - ramp-endf
    - ramp-isotopes
    - ramp-reactions
    - scipy
    - toolz

tests:
  - python:
      imports:
        - batman
      pip_check: true
      python_version: 
        - ${{ python_min }}.*
        - "*"

about:
  summary: Package for solving reactions and decays by Bateman's equation
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/ramp-batman/

extra:
  recipe-maintainers:
    - esheder
