schema_version: 1

context:
  version: "1.1.3"

package:
  name: valijson
  version: ${{ version }}

source:
  url: https://github.com/tristanpenman/valijson/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 887b53b1a924f6fe0b35fa3bbc9bbbe5ae8c72097b7f0f7c17b45f4cfa646029

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja

tests:
  - package_contents:
      include:
        - valijson/schema.hpp
        - valijson/schema_parser.hpp
        - valijson/validator.hpp
      files:
        - if: win
          then: Library/lib/cmake/valijson/valijsonConfig.cmake
          else: lib/cmake/valijson/valijsonConfig.cmake

about:
  homepage: https://github.com/tristanpenman/valijson
  repository: https://github.com/tristanpenman/valijson
  summary: Header-only JSON Schema validation library for C++
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
