{% set name = "scinumtools3" %}
{% set version = "0.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/vrtulka23/scinumtools3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7e0e0d0d5c8328a4686362b489b4e70ac757b635cb783b474dce71aaaf937ac0

build:
  number: 0
  script: 
    - export CMAKE_BUILD_PARALLEL_LEVEL=1
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.24
    - ninja

  host:
    - python
    - pip
    - scikit-build-core
    - pybind11
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - scinumtools3

  commands:
    - python -c "import scinumtools3"

about:
  home: https://github.com/vrtulka23/scinumtools3
  summary: Python bindings for the SciNumTools3 C++ numerical library.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vrtulka23
