{% set name = "scinumtools3" %}
{% set version = "0.5.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/vrtulka23/scinumtools3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04c9f98e6cd5d2331bf795c2df713460c592a64601daf046b685557fa27a1a79

build:
  number: 0
  script: 
    - export CMAKE_BUILD_PARALLEL_LEVEL=1  # [unix]
    - export CMAKE_GENERATOR=Ninja         # [unix]
    - {{ PYTHON }} -m pip install . --no-deps -vv --config-settings=cmake.define.ENABLE_UNIT_TESTS=ON --config-settings=cmake.define.RUN_UNIT_TESTS=ON 

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.24
    - ninja
  host:
    - python
    - pip
    - pytest
    - scikit-build-core
    - pybind11
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - scinumtools3
  commands:
    - python -c "import scinumtools3"
    
about:
  home: https://github.com/vrtulka23/scinumtools3
  summary: Python bindings for the SciNumTools3 C++ numerical library.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vrtulka23
