context:
  version: "0.1.2"

package:
  name: snapshot
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/snapshot/snapshot-${{ version }}.tar.gz
  sha256: 6d0809a8b488eee00def7edc7775b1cb9dd84bfbadef38aa6890934535731a2e

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - snapshot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/gemerden/snapshot
  summary: Extract named tuples from classes with a simple descriptor
  description: |
    snapshot lets you extract named tuples from classes using a simple
    descriptor, providing a convenient way to create lightweight, immutable
    snapshots of object state.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/gemerden/snapshot

extra:
  recipe-maintainers:
    - m0nonoke
