{% set version = '1.7.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-icellr
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/iCellR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/iCellR/iCellR_{{ version }}.tar.gz
  sha256: 0e220d2ecf3b5f0e53a83b9cb947c9134fb17dda9f2229414727ec3734976bdb

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-hmisc
    - r-matrix
    - r-nbclust
    - r-rann
    - r-rcolorbrewer
    - r-rcpp
    - r-rtsne
    - r-ape
    - r-data.table
    - r-ggdendro
    - r-ggplot2
    - r-ggpubr
    - r-ggrepel
    - r-gridextra
    - r-hdf5r
    - r-htmlwidgets
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-pheatmap
    - r-plotly
    - r-plyr
    - r-png
    - r-progress
    - r-reshape
    - r-scatterplot3d
    - r-shiny
    - r-uwot
  run:
    - r-base
    - r-hmisc
    - r-matrix
    - r-nbclust
    - r-rann
    - r-rcolorbrewer
    - r-rcpp
    - r-rtsne
    - r-ape
    - r-data.table
    - r-ggdendro
    - r-ggplot2
    - r-ggpubr
    - r-ggrepel
    - r-gridextra
    - r-hdf5r
    - r-htmlwidgets
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-pheatmap
    - r-plotly
    - r-plyr
    - r-png
    - r-progress
    - r-reshape
    - r-scatterplot3d
    - r-shiny
    - r-uwot

test:
  commands:
    - $R -e "library('iCellR')"           # [not win]
    - "\"%R%\" -e \"library('iCellR')\""  # [win]

about:
  home: https://github.com/rezakj/iCellR
  license: GPL-2.0-only
  summary: A toolkit that allows scientists to work with data from single cell sequencing technologies
    such as scRNA-seq, scVDJ-seq, scATAC-seq, CITE-Seq and Spatial Transcriptomics (ST).
    Single (i) Cell R package ('iCellR') provides unprecedented flexibility at every
    step of the analysis pipeline, including normalization, clustering, dimensionality
    reduction, imputation, visualization, and so on. Users can design both unsupervised
    and supervised models to best suit their research. In addition, the toolkit provides
    2D and 3D interactive visualizations, differential expression analysis, filters
    based on cells, genes and clusters, data merging, normalizing for dropouts, data
    imputation methods, correcting for batch differences, pathway analysis, tools to
    find marker genes for clusters and conditions, predict cell types and pseudotime
    analysis. See Khodadadi-Jamayran, et al (2020) <doi:10.1101/2020.05.05.078550>  and
    Khodadadi-Jamayran, et al (2020) <doi:10.1101/2020.03.31.019109> for more details.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: iCellR
# Type: Package
# Title: Analyzing High-Throughput Single Cell Sequencing Data
# Version: 1.7.0
# Authors@R: c( person(given = 'Alireza', family = 'Khodadadi-Jamayran',role = c('aut','cre'), email = 'alireza.khodadadi.j@gmail.com', comment = c(ORCID = '0000-0003-2495-7504')), person(given = 'Joseph', family = 'Pucella',role = c('aut','ctb'), comment = c(ORCID = '0000-0003-0875-8046')), person(given = 'Hua', family = 'Zhou',role = c('aut','ctb'), comment = c(ORCID = '0000-0003-1822-1306')), person(given = 'Nicole', family = 'Doudican',role = c('aut','ctb'), comment = c(ORCID = '0000-0003-3827-9644')), person(given = 'John', family = 'Carucci',role = c('aut','ctb'), comment = c(ORCID = '0000-0001-6817-9439')), person(given = 'Adriana', family = 'Heguy',role = c('aut','ctb')), person(given = 'Boris', family = 'Reizis',role = c('aut','ctb'), comment = c(ORCID = '0000-0003-1140-7853')), person(given = "Aristotelis", family = "Tsirigos",role = c('aut','ctb'), comment = c(ORCID = '0000-0002-7512-8477')) )
# Maintainer: Alireza Khodadadi-Jamayran <alireza.khodadadi.j@gmail.com>
# Description: A toolkit that allows scientists to work with data from single cell sequencing technologies such as scRNA-seq, scVDJ-seq, scATAC-seq, CITE-Seq and Spatial Transcriptomics (ST). Single (i) Cell R package ('iCellR') provides unprecedented flexibility at every step of the analysis pipeline, including normalization, clustering, dimensionality reduction, imputation, visualization, and so on. Users can design both unsupervised and supervised models to best suit their research. In addition, the toolkit provides 2D and 3D interactive visualizations, differential expression analysis, filters based on cells, genes and clusters, data merging, normalizing for dropouts, data imputation methods, correcting for batch differences, pathway analysis, tools to find marker genes for clusters and conditions, predict cell types and pseudotime analysis. See Khodadadi-Jamayran, et al (2020) <doi:10.1101/2020.05.05.078550>  and Khodadadi-Jamayran, et al (2020) <doi:10.1101/2020.03.31.019109> for more details.
# Depends: R (>= 3.3.0), ggplot2, plotly
# Imports: Matrix, Rtsne, gridExtra, ggrepel, ggpubr, scatterplot3d, RColorBrewer, knitr, NbClust, shiny, pheatmap, ape, ggdendro, plyr, reshape, Hmisc, htmlwidgets, methods, uwot, progress, igraph, data.table, Rcpp, hdf5r, RANN, jsonlite, png
# License: GPL-2
# LinkingTo: Rcpp
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.2
# BugReports: https://github.com/rezakj/iCellR/issues
# URL: https://github.com/rezakj/iCellR
# NeedsCompilation: yes
# Packaged: 2025-10-28 14:48:40 UTC; khodaa01
# Author: Alireza Khodadadi-Jamayran [aut, cre] (ORCID: <https://orcid.org/0000-0003-2495-7504>), Joseph Pucella [aut, ctb] (ORCID: <https://orcid.org/0000-0003-0875-8046>), Hua Zhou [aut, ctb] (ORCID: <https://orcid.org/0000-0003-1822-1306>), Nicole Doudican [aut, ctb] (ORCID: <https://orcid.org/0000-0003-3827-9644>), John Carucci [aut, ctb] (ORCID: <https://orcid.org/0000-0001-6817-9439>), Adriana Heguy [aut, ctb], Boris Reizis [aut, ctb] (ORCID: <https://orcid.org/0000-0003-1140-7853>), Aristotelis Tsirigos [aut, ctb] (ORCID: <https://orcid.org/0000-0002-7512-8477>)
# Repository: CRAN
# Date/Publication: 2025-10-28 15:30:02 UTC
