--- tests/slow/Makefile.am	2017-05-27 07:31:00.000000000 +0200
+++ tests/slow/Makefile.am	2017-09-25 19:37:59.313348260 +0200
@@ -56,6 +56,7 @@
 check_PROGRAMS = $(ctests) cipher-test cipher-override mac-override cipher-override2 hash-large
 TESTS = $(ctests) test-ciphers.sh override-ciphers test-hash-large.sh
 
+if ENABLE_OPENSSL
 if HAVE_LIBCRYPTO
 cipher_openssl_compat_LDFLAGS = $(LDADD) $(LIBCRYPTO)
 
@@ -63,6 +64,7 @@
 check_PROGRAMS += cipher-openssl-compat
 TESTS += test-ciphers-openssl.sh
 endif
+endif
 
 EXTRA_DIST = README gnutls-asan.supp
 
