schema_version: 1

context:
  version: "4.8.3"

package:
  name: cedarpy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cedarpy/cedarpy-${{ version }}.tar.gz
  sha256: 472774410c9562b14191faf7665bb821404340a0f952624c2ffe261b6d3d5f5e

build:
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.8,<2
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
  host:
    - python
    - maturin >=1.8,<2
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - cedarpy
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/cedarpy/
  repository: https://github.com/k9securityio/cedar-py
  summary: Python bindings for the Cedar Policy project.

extra:
  recipe-maintainers:
    - xhochy
    - swenger
