# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.1.39"

package:
  name: cleanlab-tlm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cleanlab-tlm/cleanlab_tlm-${{ version }}.tar.gz
  sha256: 1f6352750a93632a36d8f19503f977ee5089ec9776be0c784835fdf3e03e69d2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - aiohttp >=3.8.1
    - nest-asyncio >=1.5.0
    - pandas >=2,<3
    - requests >=2.27.1
    - tqdm >=4.64.0
    - semver >=2.13.0,<3.0.0
    - typing_extensions >=4.2.0

tests:
  - python:
      imports:
        - cleanlab_tlm
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pypi.org/project/cleanlab-tlm/
  license: MIT
  license_file: LICENSE
  summary: Python client library for Cleanlab Trustworthy Language Model
  repository: https://github.com/cleanlab/cleanlab-tlm
  documentation: https://github.com/cleanlab/cleanlab-tlm#readme
  description: |
    In one line of code, Cleanlab TLM adds real-time evaluation of every
    response in LLM, RAG, and Agent systems. It provides trustworthiness
    scoring for language model outputs via state-of-the-art uncertainty
    estimation, helping catch unreliable responses in data extraction,
    tagging, Q&A systems, and agent workflows.

extra:
  recipe-maintainers:
    - rxm7706
