context:
  name: pvview
  version: "1.1.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: "${{ PYTHON }} -m pip install . --no-deps -vv"
  python:
    entry_points:
      - pvview = pvview.pvview:main

requirements:
  host:
    - python >=${{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=${{ python_min }}
    - pydm
    - pyqt =5

tests:
  - python:
      imports:
      - pvview
      pip_check: true
      python_version: ${{ python_min }}
  - script:
      - pvview --help
      - pvview --version

about:
  homepage: https://github.com/BCDA-APS/pvview
  license: LicenseRef-ANL-Open-Source-License
  # license_family: OTHER
  license_file: LICENSE
  summary: "Display one or more EPICS PVs in a PyDM GUI window as a table."

extra:
  recipe-maintainers:
    - prjemian
