{% set version = "1.2.1" %}

package:
  name: quaccatoo
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/q/quaccatoo/quaccatoo-{{ version }}.tar.gz
  sha256: 7d39527e2b7eae8a149df8ee1bec6a8545876bd0c8f7e4c8e7a82b772760a86a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - lmfit
    - matplotlib-base
    - numpy
    - qutip >=5
    - scipy
    - dill

test:
  imports:
    - quaccatoo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/QISS-HZB/QuaCCAToo
  summary: Quantum Color Centers Analysis Toolbox
  doc_url: https://qiss-hzb.github.io/QuaCCAToo/
  dev_url: https://github.com/QISS-HZB/QuaCCAToo
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucas-tsunaki
