{% set version = "0.9.8" %}

package:
  name: huira
  version: {{ version }}

source:
  url: https://github.com/huira-render/huira/archive/v{{ version }}.tar.gz
  sha256: 7631132c0ba2877f6ecc0677368eee4233b51a5bcac8eb6cc082754187b72967

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - python
    - pybind11
    - pybind11-abi
    - assimp
    - cfitsio
    - cspice
    - embree
    - fftw
    - gdal
    - glm
    - indicators
    - libcurl
    - libtiff
    - libpng
    - libjpeg-turbo
    - tbb-devel
  run:
    - python
    - {{ pin_compatible('cspice', max_pin='x') }}
    - glm
    - tbb-devel

test:
  imports:
    - huira
  commands:
    - python -c "from huira.rgb import Scene; print('Python bindings OK')"
    - huira --help
    - huira fetch-tycho2 --help
    - huira process-tycho2 --help
    - test -f $PREFIX/include/huira/huira.hpp                                    # [unix]
    - if not exist %LIBRARY_INC%\\huira\\huira.hpp exit 1                        # [win]
    - test -f $PREFIX/lib/cmake/huira/huiraConfig.cmake                          # [unix]
    - test -f $PREFIX/lib/cmake/huira/huiraTargets.cmake                         # [unix]
    - if not exist %LIBRARY_LIB%\\cmake\\huira\\huiraConfig.cmake exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\huira\\huiraTargets.cmake exit 1        # [win]
    - test -f $PREFIX/share/huira/data/kernels/lsk/naif0012.tls                  # [unix]
    - if not exist %LIBRARY_PREFIX%\\share\\huira\\data\\kernels\\lsk\\naif0012.tls exit 1  # [win]

about:
  home: https://huira.space
  license: MIT
  license_file: LICENSE
  summary: A library for space rendering, LiDAR simulation, and solar radiation pressure modeling.
  doc_url: https://docs.huira.space
  dev_url: https://github.com/huira-render/huira

extra:
  recipe-maintainers:
    - crgnam
