#! /bin/bash

set -e
set -x

export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"

# SURELOG_USE_HOST_UHDM=ON turns on capnp automatically
# and conflicts with SURELOG_USE_HOST_CAPNP=ON

mkdir build
cd build

cmake ${CMAKE_ARGS} \
    -DCMAKE_CXX_STANDARD=17 \
    -DBUILD_SHARED_LIBS=ON \
    -DSURELOG_BUILD_TESTS=OFF \
    -DSURELOG_USE_HOST_ALL=ON \
    -DSURELOG_USE_HOST_ANTLR=ON \
    -DSURELOG_USE_HOST_GTEST=ON \
    -DSURELOG_USE_HOST_JSON=ON \
    -DSURELOG_USE_HOST_UHDM=ON \
    -DSURELOG_USE_HOST_CAPNP=OFF \
    -DSURELOG_WITH_TCMALLOC=OFF \
    -DSURELOG_WITH_ZLIB=ON \
    -DCMAKE_INSTALL_RPATH=$PREFIX/lib \
    -DPython3_EXECUTABLE="$PYTHON" \
    -DSURELOG_WITH_PYTHON=ON \
    -DANTLR_JAR_LOCATION="$PREFIX/lib/antlr4.jar" \
    ..

make -j${CPU_COUNT}
make install
