#!/usr/bin/env bash

# env vars expected by cmsShow
export CMSSW_RELEASE_BASE=""
export CMSSW_BASE="${CONDA_PREFIX}"
export CMSSW_SEARCH_PATH=${CONDA_PREFIX}/data
export CMSSW_DATA_PATH=${CONDA_PREFIX}/data
export CMSSW_VERSION=CMSSW_XX_YY_ZZ

if [[ "$(uname)" == "Darwin" ]]; then
    export DYLD_FALLBACK_LIBRARY_PATH=${CONDA_PREFIX}/lib${DYLD_FALLBACK_LIBRARY_PATH:+:$DYLD_FALLBACK_LIBRARY_PATH}
else
    export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
fi
export ROOT_INCLUDE_PATH=${CONDA_PREFIX}/src${ROOT_INCLUDE_PATH:+:$ROOT_INCLUDE_PATH}
