schema_version: 1

context:
  python_min: "3.9"
  version: "2.0"

package:
  name: colorzero
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/colorzero/colorzero-${{ version }}.tar.gz
  sha256: e7d5a5c26cd0dc37b164ebefc609f388de24f8593b659191e12d85f8f9d5eb58

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools

tests:
  - python:
      imports:
        - colorzero
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Yet another Python color library
  description: |
    colorzero is a color manipulation library which aims to be reasonably
    simple to use and "pythonic" in nature. Colors can be constructed from
    and converted to many representations (RGB, HSV, HSL, YUV, CSS names,
    HTML strings, and more) and manipulated through arithmetic operations
    and chainable attribute adjustments such as hue, lightness, and
    saturation.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/colorzero/
  repository: https://github.com/waveform80/colorzero
  documentation: https://colorzero.readthedocs.io/

extra:
  recipe-maintainers:
    - ruben-arts
