context:
  gem_name: "ed25519"
  version: "1.4.0"

package:
  name: rb-${{ gem_name }}
  version: ${{ version }}

source:
  url: https://rubygems.org/downloads/${{ gem_name }}-${{ version }}.gem
  sha256: 16e97f5198689a154247169f3453ef4cfd3f7a47481fde0ae33206cdfdcac506

build:
  number: 0
  script: build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - ruby
  run:
    - ruby

tests:
  - script:
      - ruby -r ed25519 -e "exit 0"

about:
  homepage: https://rubygems.org/gems/${{ gem_name }}
  summary: Library for the Ed25519 public-key signature system.
  license: MIT
  license_file: ${{ gem_name }}-${{ version }}/LICENSE
  repository: https://github.com/RubyCrypto/ed25519

extra:
  recipe-maintainers:
    - aktech
