schema_version: 1

context:
  version: "1.0.0rc1"
  python_min: "3.10"

package:
  name: agent-framework-ag-ui
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/agent-framework-ag-ui/agent_framework_ag_ui-${{ version }}.tar.gz
  sha256: 5689f9e82c1d7eab6edef682d8684f56f256f00e287720770c21965ef66cf156

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - agent-framework-core <2,>=1.4.0
    - ag-ui-protocol <0.2,>=0.1.16
    - fastapi <0.133.1,>=0.115.0
    - uvicorn <0.42.0,>=0.30.0

tests:
  - python:
      imports:
        - agent_framework.ag_ui
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: |
    AG-UI protocol integration for Agent Framework
  homepage: https://pypi.org/project/agent-framework-ag-ui/
  repository: https://github.com/microsoft/agent-framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
    - mgorny
