cmake -GNinja -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib ${CMAKE_ARGS} -DCMAKE_CUDA_ARCHITECTURES=all -DSKIP_DOCS=TRUE -DSKIP_OPENMP_LIB=TRUE ${SRC_DIR}
cmake --build . --target install --verbose
ctest -VV
