{% set version = "3.1.1" %}

package:
  name: gplite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gplite/gplite-{{ version }}.tar.gz
  sha256: 121fd4321e82f04f67de40928698f666763f5b624914745506c9509c81264922

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.2.6
    - scipy >=1.15.3

test:
  imports:
    - gplite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gplite/
  summary: Lightweight Gaussian Process regression library
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - soconnor16
