context:
  version: "0.0.21"

package:
  name: openinterpreter
  version: ${{ version }}

source:
  url: https://github.com/openinterpreter/openinterpreter/archive/refs/tags/rust-v${{ version }}.tar.gz
  sha256: dc5159bc3f30b0d3b3710dc0d0044d51b5927bc2c691e9b4a8d6fa0371490245

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - pkg-config
    - openssl
  host:
    - ${{ 'libcap' if linux }}
    - ${{ 'openssl' if unix }}

tests:
  - package_contents:
      bin:
        - i
        - interpreter
      files:
        - etc/pixi/i/global-ignore-conda-prefix
        - etc/pixi/interpreter/global-ignore-conda-prefix
      strict: true
  - script:
      - i --version
      - interpreter --help

about:
  homepage: http://openinterpreter.com
  documentation: https://www.openinterpreter.com/docs/terminal
  repository: https://github.com/openinterpreter/openinterpreter
  summary: A lightweight coding agent for open models like Deepseek, Kimi, and Qwen
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    **Open Interpreter** lets LLMs run code (Python, Javascript, Shell, and more) locally.
    You can chat with Open Interpreter through a ChatGPT-like interface in your terminal by running `$ interpreter` after installing.

    This provides a natural-language interface to your computer's general-purpose capabilities:

    - Create and edit photos, videos, PDFs, etc.
    - Control a Chrome browser to perform research
    - Plot, clean, and analyze large datasets
    - ...etc.

extra:
  recipe-maintainers:
    - eunos-1128
