schema_version: 1

context:
  python_min: "3.11"
  version: "1.0.1"

package:
  name: napari-resources
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/napari-resources/napari_resources-${{ version }}.tar.gz
  sha256: 78985f16dee0732ecf344430aa594eb77fe778e1ea63e7c24b33b016b5e6e858

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - lxml

tests:
  - python:
      imports:
        - napari_resources
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Resources for the napari project.
  description: |
    napari-resources generates, collects and exposes napari core resources
    such as logos and icons for use in napari itself, websites and other places.
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/napari/napari-resources
  homepage: https://github.com/napari/napari-resources
  documentation: https://github.com/napari/napari-resources#README.md

extra:
  recipe-maintainers:
    - conda-forge/napari
