schema_version: 1

context:
  version: 1.8.5

package:
  name: libblake3
  version: ${{ version }}

source:
  url: https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/${{ version }}.tar.gz
  sha256: 220bd81286e2a0585beac66d41ac3f4c2c33ae8a4e339fc88cf22d5e00514fe9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

tests:
  - package_contents:
      lib:
        - blake3
      include:
        - blake3.h

about:
  license: Apache-2.0 OR CC0-1.0
  license_file:
    - LICENSE_A2
    - LICENSE_CC0
  summary: BLAKE3 cryptographic hash function C library
  description: |
    BLAKE3 is a cryptographic hash function that is much faster than MD5,
    SHA-1, SHA-2, SHA-3, and BLAKE2; secure against length extension;
    highly parallelizable across any number of threads and SIMD lanes;
    capable of verified streaming and incremental updates; and serves as
    a PRF, MAC, KDF, and XOF as well as a regular hash.
  homepage: https://github.com/BLAKE3-team/BLAKE3
  repository: https://github.com/BLAKE3-team/BLAKE3

extra:
  recipe-maintainers:
    - phreed
