{% set version = "0.1.0" %}

package:
  name: lume-bmad
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lume-bmad/lume_bmad-{{ version }}.tar.gz
  sha256: 92c998d60584e89f7e8bb8ebcd1b5e1979e834140b162dc27a68cedabac5005d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.11
    - lume-base
    - openpmd-beamphysics

test:
  imports:
    - lume_bmad
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/lume-science/lume-bmad
  summary: Tools for using Bmad in LUME
  doc_url: https://github.com/lume-science/lume-bmad
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pluflou
