schema_version: 1

context:
  version: "1.7.0"

package:
  name: idutils
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/idutils/idutils-${{ version }}.tar.gz
  sha256: 848702d9b953a34ba597ac9fd04823fa2ace9dafda3924e91bcf349223cd7442

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - isbnlib2 >=3.11.7

tests:
  - python:
      imports:
        - idutils
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Small library for persistent identifiers used in scholarly communication.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://idutils.readthedocs.io/
  documentation: https://idutils.readthedocs.io/
  repository: https://github.com/inveniosoftware/idutils

extra:
  recipe-maintainers:
    - tovrstra
