{% set version = '0.12.6' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tikzdevice
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tikzDevice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tikzDevice/tikzDevice_{{ version }}.tar.gz
  sha256: 04db2163ca9acb640161fb84dfc492f16abc6f5acc0c64782c197457e15004ac

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-filehash >=2.3
    - r-png
  run:
    - r-base
    - r-filehash >=2.3
    - r-png

test:
  commands:
    - $R -e "library('tikzDevice')"           # [not win]
    - "\"%R%\" -e \"library('tikzDevice')\""  # [win]

about:
  home: https://github.com/daqana/tikzDevice
  license: GPL-2.0-only
  summary: Provides a graphics output device for R that records plots in a LaTeX-friendly format.
    The device transforms plotting commands issued by R functions into LaTeX code blocks.
    When included in a LaTeX document, these blocks are interpreted with the help of
    'TikZ'---a graphics package for TeX and friends written by Till Tantau. Using the
    'tikzDevice', the text of R plots can contain LaTeX commands such as mathematical
    formula. The device also allows arbitrary LaTeX code to be inserted into the output
    stream.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
# Encoding: UTF-8

extra:
  recipe-maintainers:
    - conda-forge/r
    - GiulioCentorame

# Package: tikzDevice
# Type: Package
# Title: R Graphics Output in LaTeX Format
# Version: 0.12.6
# Authors@R: c( person("Charlie", "Sharpsteen", role = "aut"), person("Cameron", "Bracken", role = "aut"), person("Kirill", "Muller", role = c("ctb"), email = "krlmlr+r@mailbox.org"), person("Yihui", "Xie", role = "ctb"), person("Ralf", "Stubner", email = "ralf.stubner@gmail.com", role = "cre"), person("Nico", "Bellack", email = "nico.belack@daqana.com", role = "ctb") )
# URL: https://github.com/daqana/tikzDevice
# BugReports: https://github.com/daqana/tikzDevice/issues
# Description: Provides a graphics output device for R that records plots in a LaTeX-friendly format. The device transforms plotting commands issued by R functions into LaTeX code blocks. When included in a LaTeX document, these blocks are interpreted with the help of 'TikZ'---a graphics package for TeX and friends written by Till Tantau. Using the 'tikzDevice', the text of R plots can contain LaTeX commands such as mathematical formula. The device also allows arbitrary LaTeX code to be inserted into the output stream.
# License: GPL (>= 2)
# Depends: R (>= 2.14.0)
# Imports: filehash (>= 2.3), png
# Suggests: evaluate, formatR, ggplot2, knitr, lattice, maps, scales, stringr, testthat (>= 0.8.1), withr, covr
# SystemRequirements: pgf (>= 2.00)
# LazyLoad: yes
# VignetteBuilder: knitr
# RoxygenNote: 7.2.3
# NeedsCompilation: yes
# Packaged: 2023-11-29 21:06:07 UTC; ralf
# Author: Charlie Sharpsteen [aut], Cameron Bracken [aut], Kirill Muller [ctb], Yihui Xie [ctb], Ralf Stubner [cre], Nico Bellack [ctb]
# Maintainer: Ralf Stubner <ralf.stubner@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-11-29 21:40:02 UTC
