context:
  version: "1.0.0"

package:
  name: coverplot
  version: ${{ version }}

source:
  url: https://gitlab.com/earthscope/public/epic/passoft/coverplot/-/archive/v${{ version }}/coverplot-v${{ version }}.tar.gz
  sha256: 4845af85a02e71c059d1e425898df38cdb66f558c747a31af5b9b4b8a888ec30

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  python:
    entry_points:
      - coverplot = coverplot.coverplot:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pyside6
    - pillow
    - obspy

tests:
  - python:
      imports:
        - coverplot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - coverplot --help

about:
  homepage: https://epic.earthscope.org/content/software-resources
  summary: Plot time coverage of a dataless
  description: |
    Plot the time coverage of a dataless SEED file.
  license: GPL-3.0-or-later
  license_file: LICENSE
  repository: https://gitlab.com/earthscope/public/epic/passoft/coverplot

extra:
  recipe-maintainers:
    - omid-earthscope
