{% set python_min = "3.9" %}
{% set version = "1.0.0b0" %}

package:
  name: jupyterlab-plugin-playground
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-plugin-playground/jupyterlab_plugin_playground-{{ version }}.tar.gz
  sha256: 9e89f0ed00d846285baf0137b53eb7afabc7b83edc7675f6a46bf5f95a4a541a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.4.0
    - jupyterlab >=4.0,<5.dev0
    - pip
  run:
    - python >={{ python_min }}
    - jupyterlab >=4.0,<5.dev0

test:
  imports:
    - jupyterlab_plugin_playground
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/plugin-playground.*OK"
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/jupyterlab/plugin-playground
  summary: A JupyterLab Plugin Playground.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MUFFANUJ
    - krassowski
