schema_version: 1

context:
  python_min: "3.12"
  version: 0.0.1a1

package:
  name: airbornegeo
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/airbornegeo/airbornegeo-${{ version }}.tar.gz
  sha256: b4cb4205538e8d174c6f2412a5af81d75606ae1f03ca6103e4f7993be58c1ff3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.26
    - hatch-vcs
    - setuptools >=61
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.0.0
    - scipy >=1.13.0
    - matplotlib-base >=3.9.0
    - pandas >=2.3.0
    - scikit-learn >=1.5.0
    - ipython >=8.23.0
    - harmonica
    - xrft >=1.0.0
    - geopandas
    - pygmt
    - shapely
    - tqdm
    - verde
    - ipykernel
    - plotly
    - seaborn
    - boule
    - pyproj
    - geographiclib
    - scooby

tests:
  - python:
      imports:
        - airbornegeo
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Tools for processing airborne geophysical survey data
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/airbornegeo/airbornegeo
  documentation: https://airbornegeo.github.io/airbornegeo/

extra:
  recipe-maintainers:
    - mdtanker
