diff --git a/Makefile b/Makefile
index 6e8d822..af9cedc 100644
--- a/Makefile
+++ b/Makefile
@@ -60,7 +60,7 @@ COMPILER = gfortran
 F90C     = gfortran
 SFFLAGS =  -shared -fPIC

-FFLAGS =  -O3 -fopenmp -ffast-math -fmax-errors=4
+FFLAGS =  -O3 -fopenmp -fmax-errors=4 ${EXTRA_FFLAGS}
 DEBUGFLAGS = -cpp -g -fbounds-check -fbacktrace -ffree-line-length-none -fmax-errors=4 -ffpe-trap=invalid,overflow,zero
 MODOUT =  -J$(OUTPUT_DIR)
 SMODOUT = -J$(DLL_DIR)
