--- Makefile.old	2017-03-02 22:19:15.115267456 +0530
+++ Makefile	2017-03-02 22:32:50.947846231 +0530
@@ -5,12 +5,12 @@
 
 all clean:
 	for dir in $(DIRS); do \
-		(cd $${dir} && make $@)\
+		($(MAKE) -C $${dir} $@)\
 	done
 
 distclean: clean
 	for dir in $(DIRS); do \
-		(cd $${dir} && make distclean)\
+		$(MAKE) -C $${dir} distclean;\
 	done
 
 install: all

--- dik/makefile.old	2017-03-02 23:22:17.141204589 +0530
+++ dik/makefile	2017-03-02 23:22:21.589256857 +0530
@@ -1,5 +1,3 @@
-CFLAGS = -O -DLARGE_MEM -DVERBOSE
-
 OBJS =	cube.o \
 	phase1.o \
 	phase2.o \
@@ -9,40 +7,40 @@
 	globals.o
 
 cube:	$(OBJS)
-	$(CC) $(CFLAGS) -o dikcube $(OBJS)
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -DLARGE_MEM -DVERBOSE -o dikcube $(OBJS)
 	size dikcube
 
 size222:	size222.o
-	$(CC) $(CFLAGS) -o size222 size222.o
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -o size222 size222.o
 	size size222
 
 size333c.o:	size333c.c
-	$(CC) $(CFLAGS) -DCTWIST -c size333c.c
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -DCTWIST -c size333c.c
 
 size333c:	size333c.o
-	$(CC) $(CFLAGS) -o size333c size333c.o
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -o size333c size333c.o
 	size size333c
 
 sizesquare:	sizesquare.o
-	$(CC) $(CFLAGS) -o sizesquare sizesquare.o
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -o sizesquare sizesquare.o
 	size sizesquare
 
 sizedom.o:	sizedom.c
-	$(CC) $(CFLAGS) -DCCPERM -DIPERM -c sizedom.c
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -DCCPERM -DIPERM -c sizedom.c
 
 sizedom:	sizedom.o
-	$(CC) $(CFLAGS) -o sizedom sizedom.o
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -o sizedom sizedom.o
 	size sizedom
 
 sizekoc1:	sizekoc1.o
-	$(CC) $(CFLAGS) -o sizekoc1 sizekoc1.o
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -o sizekoc1 sizekoc1.o
 	size sizekoc1
 
 sizekoc2.o:	sizekoc2.c
-	$(CC) $(CFLAGS) -DCCPERM -DIPERM -c sizekoc2.c
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -DCCPERM -DIPERM -c sizekoc2.c
 
 sizekoc2:	sizekoc2.o
-	$(CC) $(CFLAGS) -o sizekoc2 sizekoc2.o
+	$(CC) -O $(CFLAGS) -DLARGE_MEM -DVERBOSE -o sizekoc2 sizekoc2.o
 	size sizekoc2
 
 all:	cube size222 size333c sizesquare sizedom sizekoc1 sizekoc2
