context:
  version: "0.2.1"
  python_min: "3.12"

package:
  name: pint-cf
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pint-cf/pint_cf-${{ version }}.tar.gz
  sha256: ac17b5a3bae01e88e7420fab9de7d59d12aa154497fc04739b7db4a2a9deee57

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pint >=0.25.2
    - lark

tests:
  - python:
      imports:
        - pint_cf
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  homepage: https://github.com/pgamez/pint-cf
  documentation: https://pgamez.github.io/pint-cf/
  repository: https://github.com/pgamez/pint-cf
  summary: CF-compliant unit registry and formatter for Pint
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pgamez
