@echo off
REM Dune deactivation script - restore original OCAMLPATH and OCAMLFIND_DESTDIR

if defined _CONDA_DUNE_OCAMLPATH_BACKUP (
    set "OCAMLPATH=%_CONDA_DUNE_OCAMLPATH_BACKUP%"
) else (
    set "OCAMLPATH="
)
set "_CONDA_DUNE_OCAMLPATH_BACKUP="

if defined _CONDA_DUNE_DESTDIR_BACKUP (
    set "OCAMLFIND_DESTDIR=%_CONDA_DUNE_DESTDIR_BACKUP%"
) else (
    set "OCAMLFIND_DESTDIR="
)
set "_CONDA_DUNE_DESTDIR_BACKUP="
