export _OLD_FC=$FC
export _OLD_FFLAGS=$FFLAGS
export _OLD_FORTRANFLAGS=$FORTRANFLAGS

export FORTRANFLAGS="$FORTRANFLAGS --sysroot=$CONDA_BUILD_SYSROOT"

export FC="flang-new"
export FFLAGS=$FORTRANFLAGS
