#!/bin/bash

set -exo pipefail

export CMAKE_ARGS="\
    -DBUILD_WITH_CUDA=OFF \
    -DBUILD_TEST=OFF \
    -DUSE_SYSTEM_ASSIMP=ON \
    -DUSE_SYSTEM_OPENEXR=ON \
    -DUSE_SYSTEM_EIGEN=ON \
    -DEIGEN3_INCLUDE_DIR=${PREFIX}/include/eigen3 \
    -DUSE_SYSTEM_GLFW=ON \
    -DUSE_SYSTEM_MAGNUM=ON \
    -DUSE_SYSTEM_PYBIND11=ON \
    -DUSE_SYSTEM_RAPIDJSON=ON \
    -DUSE_SYSTEM_BULLET=ON \
    -DUSE_SYSTEM_ZSTD=ON \
    -DMAGNUMBINDINGS_INCLUDE_DIR=${PREFIX}/include \
    -DLIB_SUFFIX=''"
export CMAKE_BUILD_PARALLEL_LEVEL="${CMAKE_BUILD_PARALLEL_LEVEL:-1}"

"${PYTHON}" -m pip install . -vv
