{% set name = "pymatgen-core" %}
{% set version = "2026.2.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatgen_core-{{ version }}.tar.gz
  sha256: c5b15dc3409ea0a9d9adc9805376c07341e6df7a9770159b431f12ab639d9ddb

build:
  skip: true  # [py<=310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.23
    - numpy >=2.1.0
    - setuptools >=65.0.0
    - pip
  run:
    - python
    - matplotlib-base >=3.8
    - monty >=2026.2.18
    - networkx >=2.7
    - orjson >=3.10,<4
    - palettable >=3.3.3
    - pandas >=2
    - scipy >=1.13.0
    - scipy >=1.14.1  # [win]
    - spglib >=2.5
    - sympy >=1.3
    - uncertainties >=3.1
    - plotly >=6.0
    - joblib >=1.3.2
    - bibtexparser
    - tabulate >=0.9.0
    - tqdm >=4.67.3
    - requests >=2.32.5
    - numpy

test:
  imports:
    - pymatgen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pymatgen.org
  summary: Python Materials Genomics is a robust materials analysis code that defines core object representations for structures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
