:: PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
:: will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
:: changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
:: benefit from the improvement.

:: INPUTS (required environment variables)
:: CONDA_BLD_PATH: path for the conda-build workspace
:: CI: azure, or unset
:: MINIFORGE_HOME: where to install the base conda environment

setlocal enableextensions enabledelayedexpansion

call :start_group "Provisioning build tools"
if "%MINIFORGE_HOME%"=="" (
    set "MINIFORGE_HOME=%REPO_ROOT%\.pixi\envs\default"
) else (
    set "PIXI_CACHE_DIR=%MINIFORGE_HOME%"
)
:: Remove trailing backslash, if present
if "%MINIFORGE_HOME:~-1%"=="\" set "MINIFORGE_HOME=%MINIFORGE_HOME:~0,-1%"

call :start_group "Provisioning base env with pixi"
echo Installing pixi

setlocal

set "PS_SCRIPT=%TEMP%\install-pixi.ps1"

(
echo param (
echo     [string] $PixiVersion = 'latest',
echo     [string] $PixiHome = "$Env:USERPROFILE.pixi",
echo     [switch] $NoPathUpdate,
echo     [string] $PixiRepourl = 'https://github.com/prefix-dev/pixi'
echo )
echo.
echo Set-StrictMode -Version Latest
echo.
echo function Mask-Credentials {
echo     param(
echo         [string] $Url
echo     )
echo     return $Url -replace '://[^:@/]+:[^@/]+@', '://***:***@'
echo }
echo.
echo function Publish-Env {
echo     if (-not ("Win32.NativeMethods" -as [Type])) {
echo         Add-Type -Namespace Win32 -Name NativeMethods -MemberDefinition @"
echo [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
echo public static extern IntPtr SendMessageTimeout(
echo     IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam,
echo     uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
echo "@
echo     }
echo.
echo     $HWND_BROADCAST = [IntPtr] 0xffff
echo     $WM_SETTINGCHANGE = 0x1a
echo     $result = [UIntPtr]::Zero
echo.
echo     [Win32.Nativemethods]::SendMessageTimeout($HWND_BROADCAST,
echo         $WM_SETTINGCHANGE,
echo         [UIntPtr]::Zero,
echo         "Environment",
echo         2,
echo         5000,
echo         [ref] $result
echo     ) ^| Out-Null
echo }
echo.
echo function Write-Env {
echo     param(
echo         [String] $name,
echo         [String] $val,
echo         [Switch] $global
echo     )
echo.
echo     $RegisterKey = if ($global) {
echo         Get-Item -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager'
echo     } else {
echo         Get-Item -Path 'HKCU:'
echo     }
echo.
echo     $EnvRegisterKey = $RegisterKey.OpenSubKey('Environment', $true)
echo     if ($null -eq $val) {
echo         $EnvRegisterKey.DeleteValue($name)
echo     } else {
echo         $RegistryValueKind = if ($val.Contains('%%')) {
echo             [Microsoft.Win32.RegistryValueKind]::ExpandString
echo         } elseif ($EnvRegisterKey.GetValue($name)) {
echo             $EnvRegisterKey.GetValueKind($name)
echo         } else {
echo             [Microsoft.Win32.RegistryValueKind]::String
echo         }
echo         $EnvRegisterKey.SetValue($name, $val, $RegistryValueKind)
echo     }
echo     Publish-Env
echo }
echo.
echo function Get-Env {
echo     param(
echo         [String] $name,
echo         [Switch] $global
echo     )
echo.
echo     $RegisterKey = if ($global) {
echo         Get-Item -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager'
echo     } else {
echo         Get-Item -Path 'HKCU:'
echo     }
echo.
echo     $EnvRegisterKey = $RegisterKey.OpenSubKey('Environment')
echo     $RegistryValueOption = [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames
echo     $EnvRegisterKey.GetValue($name, $null, $RegistryValueOption)
echo }
echo.
echo function Get-TargetTriple() {
echo   try {
echo     $a = [System.Reflection.Assembly]::LoadWithPartialName("System.Runtime.InteropServices.RuntimeInformation")
echo     $t = $a.GetType("System.Runtime.InteropServices.RuntimeInformation")
echo     $p = $t.GetProperty("OSArchitecture")
echo     switch ($p.GetValue($null).ToString())
echo     {
echo       "X86" { return "i686-pc-windows-msvc" }
echo       "X64" { return "x86_64-pc-windows-msvc" }
echo       "Arm" { return "thumbv7a-pc-windows-msvc" }
echo       "Arm64" { return "aarch64-pc-windows-msvc" }
echo     }
echo   } catch {
echo     Write-Verbose "Get-TargetTriple: Exception when trying to determine OS architecture."
echo     Write-Verbose $_
echo   }
echo.
echo   Write-Verbose("Get-TargetTriple: falling back to Is64BitOperatingSystem.")
echo   if ([System.Environment]::Is64BitOperatingSystem) {
echo     return "x86_64-pc-windows-msvc"
echo   } else {
echo     return "i686-pc-windows-msvc"
echo   }
echo }
echo.
echo if ($Env:PIXI_VERSION) {
echo     $PixiVersion = $Env:PIXI_VERSION
echo }
echo.
echo if ($Env:PIXI_HOME) {
echo     $PixiHome = $Env:PIXI_HOME
echo }
echo.
echo if ($Env:PIXI_NO_PATH_UPDATE) {
echo     $NoPathUpdate = $true
echo }
echo.
echo if ($Env:PIXI_REPOURL) {
echo     $PixiRepourl = $Env:PIXI_REPOURL -replace '/$', ''
echo }
echo.
echo $ARCH = Get-TargetTriple
echo.
echo if (-not @("x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc") -contains $ARCH) {
echo     throw "ERROR: could not find binaries for this platform ($ARCH)."
echo }
echo.
echo $BINARY = "pixi-$ARCH"
echo.
echo if ($Env:PIXI_DOWNLOAD_URL) {
echo     $DOWNLOAD_URL = $Env:PIXI_DOWNLOAD_URL
echo } elseif ($PixiVersion -eq 'latest') {
echo     $DOWNLOAD_URL = "$PixiRepourl/releases/latest/download/$BINARY.zip"
echo } else {
echo     $PixiVersion = "v" + ($PixiVersion -replace '^v', '')
echo     $DOWNLOAD_URL = "$PixiRepourl/releases/download/$PixiVersion/$BINARY.zip"
echo }
echo.
echo $BinDir = Join-Path $PixiHome 'bin'
echo.
echo Write-Host "This script will automatically download and install Pixi ($PixiVersion) for you."
echo Write-Host "Getting it from this url: $(Mask-Credentials $DOWNLOAD_URL)"
echo Write-Host "The binary will be installed into '$BinDir'"
echo.
echo $TEMP_FILE = [System.IO.Path]::GetTempFileName()
echo.
echo try {
echo     Write-Host "Invoking web request"
echo     Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile $TEMP_FILE
echo.
echo     if (!(Test-Path -Path $BinDir)) {
echo         Write-Host "Creating install dir"
echo         New-Item -ItemType Directory -Path $BinDir ^| Out-Null
echo     }
echo.
echo     $ZIP_FILE = $TEMP_FILE + ".zip"
echo     Write-Host "Renaming to zip file"
echo     Rename-Item -Path $TEMP_FILE -NewName $ZIP_FILE
echo.
echo     Write-Host "Expanding zip archive to '$BinDir'"
echo     Expand-Archive -Path $ZIP_FILE -DestinationPath $BinDir -Force
echo } catch {
echo     Write-Host "Error: '$(Mask-Credentials $DOWNLOAD_URL)' is not available or failed to download"
echo     exit 1
echo } finally {
echo     Write-Host "Removing zip file"
echo     Remove-Item -Path $ZIP_FILE
echo }
echo.
echo if (!$NoPathUpdate) {
echo     $PATH = Get-Env 'PATH'
echo     if ($PATH -notlike "*$BinDir*") {
echo         Write-Output "Adding $BinDir to PATH"
echo         Write-Env -name 'PATH' -val "$BinDir;$PATH"
echo         $Env:PATH = "$BinDir;$PATH"
echo         Write-Output "You may need to restart your shell"
echo     } else {
echo         Write-Output "$BinDir is already in PATH"
echo     }
echo } else {
echo     Write-Output "You may need to update your PATH manually to use pixi"
echo }
) > "%PS_SCRIPT%"

powershell -NoProfile -ExecutionPolicy Bypass -File "%PS_SCRIPT%"

endlocal


if !errorlevel! neq 0 exit /b !errorlevel!
set "PATH=%USERPROFILE%\.pixi\bin;%PATH%"
echo Installing environment
if "%PIXI_CACHE_DIR%"=="%MINIFORGE_HOME%" (
    mkdir "%MINIFORGE_HOME%"
    copy /Y pixi.toml "%MINIFORGE_HOME%"
    copy /Y LICENSE.txt "%MINIFORGE_HOME%"
    pushd "%MINIFORGE_HOME%"
) else (
    pushd "%REPO_ROOT%"
)
:: Git on Windows needs to run post link scripts to properly set up SSL certificates
pixi config set --global run-post-link-scripts insecure
if !errorlevel! neq 0 exit /b !errorlevel!
pixi install --environment win-64
if !errorlevel! neq 0 exit /b !errorlevel!
pixi list --environment win-64
if !errorlevel! neq 0 exit /b !errorlevel!
set "ACTIVATE_PIXI=%TMP%\pixi-activate-%RANDOM%.bat"
pixi shell-hook --environment win-64 > "%ACTIVATE_PIXI%"
if !errorlevel! neq 0 exit /b !errorlevel!
call "%ACTIVATE_PIXI%"
if !errorlevel! neq 0 exit /b !errorlevel!
popd
call :end_group

call :start_group "Configuring conda"

if "%CONDA_BLD_PATH%" == "" (
    set "CONDA_BLD_PATH=C:\bld"
)

:: Activate the base conda environment
echo Activating "%MINIFORGE_HOME%"
call "%MINIFORGE_HOME%\Scripts\activate"

:: Set basic configuration
echo Setting up configuration
conda.exe config --env --set always_yes yes
if !errorlevel! neq 0 exit /b !errorlevel!
conda.exe config --env --set channel_priority strict
if !errorlevel! neq 0 exit /b !errorlevel!
conda.exe config --env --set solver libmamba
if !errorlevel! neq 0 exit /b !errorlevel!

setup_conda_rc .\ ".\recipes" .\.ci_support\%CONFIG%.yaml
if !errorlevel! neq 0 exit /b !errorlevel!

echo Run conda_forge_build_setup
call run_conda_forge_build_setup
if !errorlevel! neq 0 exit /b !errorlevel!

if not "%CI%" == "" (
    echo Force fetch origin/main
    git fetch --force origin main:main
    if !errorlevel! neq 0 exit /b !errorlevel!
)
echo Removing recipes also present in main
cd recipes
for /f "tokens=*" %%a in ('git ls-tree --name-only main -- .') do rmdir /s /q %%a && echo Removing recipe: %%a
cd ..

:: make sure there is a package directory so that artifact publishing works
if not exist "%CONDA_BLD_PATH%\win-64\" mkdir "%CONDA_BLD_PATH%\win-64\"
if not exist "%CONDA_BLD_PATH%\win-arm64\" mkdir "%CONDA_BLD_PATH%\win-arm64\"
if not exist "%CONDA_BLD_PATH%\noarch\" mkdir "%CONDA_BLD_PATH%\noarch\"

echo Index %CONDA_BLD_PATH%
conda.exe index "%CONDA_BLD_PATH%"
if !errorlevel! neq 0 exit /b !errorlevel!

call :end_group

echo Building all recipes
python .ci_support\build_all.py
if !errorlevel! neq 0 exit /b !errorlevel!

call :start_group "Inspecting artifacts"

:: inspect_artifacts was only added in conda-forge-ci-setup 4.6.0; --all-packages in 4.9.3
WHERE inspect_artifacts >nul 2>nul && inspect_artifacts --all-packages || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.3"

call :end_group

exit

:: Logging subroutines

:start_group
if /i "%CI%" == "github_actions" (
    echo ::group::%~1
    exit /b
)
if /i "%CI%" == "azure" (
    echo ##[group]%~1
    exit /b
)
echo %~1
exit /b

:end_group
if /i "%CI%" == "github_actions" (
    echo ::endgroup::
    exit /b
)
if /i "%CI%" == "azure" (
    echo ##[endgroup]
    exit /b
)
exit /b
