schema_version: 1

context:
  version: "0.1.0"

package:
  name: cc-plugin-sgrid
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cc-plugin-sgrid/cc_plugin_sgrid-${{ version }}.tar.gz
  sha256: 671db0a832877a4bda7debbb9858368e268935f1d1fb21bfb8c708cc6df0d95e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - compliance-checker >=2.0.0
    - netcdf4 >=1.2.0

tests:
  - python:
      imports:
        - cc_plugin_sgrid
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: SGRID plugin for the IOOS Compliance Checker Plugin
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/cc-plugin-sgrid/

extra:
  recipe-maintainers:
    - ocefpaf
