# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "1.0.2"

package:
  name: copilot-cli
  version: ${{ version }}

source:
  - if: linux-64
    then:
      url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-linux-x64.tar.gz
      sha256: 521f87d04f073356c65ad973db7124b32ff3a23fd3257f0cd3fcf4c5d4649047

  - url: https://raw.githubusercontent.com/github/copilot-cli/refs/tags/v${{ version }}/LICENSE.md
    sha256: 1fbd0dcc55c66738b1b591632132c927de20c8443dff1d55b4851e378883e402


build:
  skip:
    - not linux-64
  number: 0
  script: |
    ls -la
    chmod +x ./copilot
    mkdir -p "${PREFIX}/bin"
    cp ./copilot "${PREFIX}/bin/copilot"


tests:
  - requirements:
      run:
        - ripgrep
    script:
      content: |
        set -euxo pipefail
        copilot --version | rg '${{ version }}'


about:
  homepage: https://github.com/github/copilot-cli
  summary: 'GitHub Copilot CLI brings the power of Copilot coding agent directly to your terminal.'
  license: LicenseRef-GitHub-Copilot-CLI
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dhirschfeld
