--- Makefile.old	2018-12-12 16:05:31.477045109 -0500
+++ Makefile	2018-12-12 16:08:31.052109762 -0500
@@ -2,12 +2,13 @@
 
 CC      ?= gcc
 CFLAGS  += -Wall -Wextra -D_REENTRANT -fpic
+PREFIX  ?= /usr
 
 ifeq (,$(INSTALL_PROGRAM))
     INSTALL_PROGRAM := "install"
 endif
 
-prefix	= /usr
+prefix  = $(PREFIX)
 libdir 	= $(prefix)/lib
 ifneq (,$(libarch))
 # The `*-*' pattern matches to both hurd-i386 and e.g. i386-linux-gnu
