--- Makefile.old	2018-12-12 16:05:31.477045109 -0500
+++ Makefile	2018-12-12 16:27:42.867447542 -0500
@@ -2,12 +2,13 @@
 
 CC      ?= gcc
 CFLAGS  += -Wall -Wextra -D_REENTRANT -fpic
+PREFIX  ?= /usr
 
 ifeq (,$(INSTALL_PROGRAM))
     INSTALL_PROGRAM := "install"
 endif
 
-prefix	= /usr
+prefix  = $(PREFIX)
 libdir 	= $(prefix)/lib
 ifneq (,$(libarch))
 # The `*-*' pattern matches to both hurd-i386 and e.g. i386-linux-gnu
@@ -19,12 +20,21 @@
 all compile: datefudge datefudge.so datefudge.1
 
 install: datefudge datefudge.so datefudge.1
-	install -d $(DESTDIR)$(libdir)/$(libarch)/datefudge
-	$(INSTALL_PROGRAM) -o root -g root -m 644 datefudge.so $(DESTDIR)$(libdir)/$(libarch)/datefudge/datefudge.so
-	install -d $(DESTDIR)$(bindir)
-	$(INSTALL_PROGRAM) -o root -g root -m 755 datefudge $(DESTDIR)$(bindir)
-	install -d $(DESTDIR)$(mandir)/man1
-	install -o root -g root -m 644 datefudge.1 $(DESTDIR)$(mandir)/man1
+
+	# copy the shared object
+	mkdir -p $(libdir)/datefudge
+	cp datefudge$(SHLIB_EXT) $(libdir)/datefudge/datefudge$(SHLIB_EXT)
+	chmod 644 $(libdir)/datefudge/datefudge$(SHLIB_EXT)
+
+	# copy the shell script
+	mkdir -p $(bindir)
+	cp datefudge $(bindir)/datefudge
+	chmod 755 $(bindir)/datefudge
+
+	# copy the man file
+	mkdir $(mandir)/man1
+	cp datefudge.1 $(mandir)/man1/datefudge.1
+	chmod 644 $(mandir)/man1/datefudge.1
 
 datefudge: datefudge.sh
 datefudge.1: datefudge.man
