{% set version = "1.0.1" %}
{% set python_min = "3.12" %}

package:
  name: ctao-datamodel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/ctao-datamodel/ctao_datamodel-{{ version }}.tar.gz
  sha256: a3df5449ab371caf79ba3dc959127dec5f83f7cc7a2d079c6890e913079c7ada

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pydantic
    - email-validator
    - pyyaml
    - astropy-base >=7.1
    - astropydantic

test:
  imports:
    - ctao_datamodel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ctao-datamodel/
  summary: CTAO Data Model in pydantic and utilities for exporting it to latex and plantuml.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kosack
    - maxnoe
