@echo off
set "CONDA_BACKUP_CGO_ENABLED=%CGO_ENABLED%"
set "CGO_ENABLED=1"

rem set "CONDA_BACKUP_CGO_CFLAGS=%CGO_CFLAGS%"
rem set "CGO_CFLAGS=%CFLAGS%"

rem set "CONDA_BACKUP_CGO_CPPFLAGS=%CGO_CPPFLAGS%"
rem set "CGO_CPPFLAGS=%CPPFLAGS%"

rem set "CONDA_BACKUP_CGO_CXXFLAGS=%CGO_CXXFLAGS%"
rem set "CGO_CXXFLAGS=%CXXFLAGS%"

rem set "CONDA_BACKUP_CGO_FFLAGS=%CGO_FFLAGS%"
rem set "CGO_FFLAGS=%FFLAGS%"

rem set "CONDA_BACKUP_CGO_LDFLAGS=%CGO_LDFLAGS%"
rem set "CGO_LDFLAGS=%LDFLAGS%"
