@echo off
set "CGO_ENABLED=%CONDA_BACKUP_CGO_ENABLED%"
set "CONDA_BACKUP_CGO_ENABLED="

rem set "CGO_CFLAGS=%CONDA_BACKUP_CGO_CFLAGS%"
rem set "CONDA_BACKUP_CGO_CFLAGS="

rem set "CGO_CPPFLAGS=%CONDA_BACKUP_CGO_CPPFLAGS%"
rem set "CONDA_BACKUP_CGO_CPPFLAGS="

rem set "CGO_CXXFLAGS=%CONDA_BACKUP_CGO_CXXFLAGS%"
rem set "CONDA_BACKUP_CGO_CXXFLAGS="

rem set "CGO_FFLAGS=%CONDA_BACKUP_CGO_FFLAGS%"
rem set "CONDA_BACKUP_CGO_FFLAGS="

rem set "CGO_LDFLAGS=%CONDA_BACKUP_CGO_LDFLAGS%"
rem set "CONDA_BACKUP_CGO_LDFLAGS="

