context:
  name: perl-par-packer
  version: "1.064"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RS/RSCHUPP/PAR-Packer-${{ version }}.tar.gz
  sha256: 0fc063e448e34f7cb5c69c6be5b2258f7150187b33140dedabd53a2c34ca3cba

build:
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - perl
    - perl-archive-zip
    - perl-par
    - perl-par-dist
    - perl-module-scandeps
    - perl-getopt-argvfile
  run:
    - perl
    - perl-archive-zip
    - perl-par
    - perl-par-dist
    - perl-module-scandeps
    - perl-getopt-argvfile

tests:
  - script:
      - pp --version
      - perl -e "use PAR::Packer; print qq(ok\n)"

about:
  homepage: https://metacpan.org/dist/PAR-Packer
  summary: PAR Packager - generate stand-alone executables from Perl programs
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file: LICENSE
  repository: https://github.com/rschupp/PAR-Packer

extra:
  recipe-maintainers:
    - baszalmstra
