{% set version = "0.7.0" %}

package:
  name: tomosipo
  version: {{ version }}

source:
  url: https://github.com/cicwi/tomosipo/archive/v{{ version }}.tar.gz
  sha256: e2a1fb97ad00ccf6cca1d20da76a468db22015de8e66fd71290755cfd36b80bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-index -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - astra-toolbox >=2.0
    - numpy >=1.21
    - __cuda

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cicwi/tomosipo
  summary: 'A library for painless tomographic reconstruction based on ASTRA Toolbox.'
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - askorikov
