{% set version = '0.4.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rextendr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rextendr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rextendr/rextendr_{{ version }}.tar.gz
  sha256: 3bd1f33d88d394618f4be42c5118cfac20aa6fe984a7c800d279600915fe81f6

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-brio
    - r-callr
    - r-cli
    - r-desc
    - r-dplyr
    - r-glue >=1.7.0
    - r-jsonlite
    - r-pkgbuild >=1.4.0
    - r-processx
    - r-rlang >=1.0.5
    - r-rprojroot
    - r-stringi
    - r-vctrs
    - r-withr
  run:
    - r-base
    - r-brio
    - r-callr
    - r-cli
    - r-desc
    - r-dplyr
    - r-glue >=1.7.0
    - r-jsonlite
    - r-pkgbuild >=1.4.0
    - r-processx
    - r-rlang >=1.0.5
    - r-rprojroot
    - r-stringi
    - r-vctrs
    - r-withr

test:
  commands:
    - $R -e "library('rextendr')"           # [not win]
    - "\"%R%\" -e \"library('rextendr')\""  # [win]

about:
  home: https://extendr.rs/rextendr/, https://github.com/extendr/rextendr
  license: MIT
  summary: Provides functions to compile and load Rust code from R, similar to how 'Rcpp' or
    'cpp11' allow easy interfacing with C++ code. Also provides helper functions to
    create R packages that use Rust code. Under the hood, the Rust crate 'extendr' is
    used to do all the heavy lifting.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - sgsokol

# Package: rextendr
# Title: Call Rust Code from R using the 'extendr' Crate
# Version: 0.4.2
# Authors@R: c(person(given = "Claus O.", family = "Wilke", role = "aut", email = "wilke@austin.utexas.edu", comment = c(ORCID = "0000-0002-7470-9261")), person(given = "Andy", family = "Thomason", role = "aut", email = "andy@andythomason.com"), person(given = "Mossa M.", family = "Reimert", role = "aut", email = "mossa@sund.ku.dk"), person(given = "Ilia", family = "Kosenkov", role = c("aut", "cre"), email = "ilia.kosenkov@outlook.com", comment = c(ORCID = "0000-0001-5563-7840")), person(given = "Malcolm", family = "Barrett", role = "aut", email = "malcolmbarrett@gmail.com", comment = c(ORCID = "0000-0003-0299-5825")), person(given = "Josiah", family = "Parry", role = "ctb", email = "josiah.parry@gmail.con", comment = c(ORCID = "0000-0001-9910-865X")), person(given = "Kenneth", family = "Vernon", role = "ctb", email = "kenneth.b.vernon@gmail.com", comment = c(ORCID = "0000-0003-0098-5092")), person(given = "Alberson", family = "Miranda", role = "ctb", email = "albersonmiranda@hotmail.com", comment = c(ORCID = "0000-0001-9252-4175")))
# Description: Provides functions to compile and load Rust code from R, similar to how 'Rcpp' or 'cpp11' allow easy interfacing with C++ code. Also provides helper functions to create R packages that use Rust code. Under the hood, the Rust crate 'extendr' is used to do all the heavy lifting.
# License: MIT + file LICENSE
# URL: https://extendr.rs/rextendr/, https://github.com/extendr/rextendr
# BugReports: https://github.com/extendr/rextendr/issues
# Depends: R (>= 4.1)
# Imports: brio, callr, cli, desc, dplyr, glue (>= 1.7.0), jsonlite, pkgbuild (>= 1.4.0), processx, rlang (>= 1.0.5), rprojroot, stringi, vctrs, withr
# Suggests: devtools, rcmdcheck, knitr, lintr, rmarkdown, testthat (>= 3.1.7), usethis
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# SystemRequirements: Rust 'cargo'; the crate 'libR-sys' must compile without error
# NeedsCompilation: no
# Packaged: 2025-08-26 13:21:13 UTC; iliak
# Author: Claus O. Wilke [aut] (ORCID: <https://orcid.org/0000-0002-7470-9261>), Andy Thomason [aut], Mossa M. Reimert [aut], Ilia Kosenkov [aut, cre] (ORCID: <https://orcid.org/0000-0001-5563-7840>), Malcolm Barrett [aut] (ORCID: <https://orcid.org/0000-0003-0299-5825>), Josiah Parry [ctb] (ORCID: <https://orcid.org/0000-0001-9910-865X>), Kenneth Vernon [ctb] (ORCID: <https://orcid.org/0000-0003-0098-5092>), Alberson Miranda [ctb] (ORCID: <https://orcid.org/0000-0001-9252-4175>)
# Maintainer: Ilia Kosenkov <ilia.kosenkov@outlook.com>
# Repository: CRAN
# Date/Publication: 2025-08-26 14:00:02 UTC
