{% set version = "1.2.0" %}

package:
  name: geoparquet-io
  version: {{ version }}

source:
  url: https://github.com/geoparquet/geoparquet-io/releases/download/v{{ version }}/geoparquet_io-{{ version }}.tar.gz
  sha256: 12691cd24caa2daac0a27163746a4d2eaeb9d01e8fe54224c57a7ae20d9a64d4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-build
    - python
    - pip
    - setuptools
    - duckdb
    - geoarrow-pyarrow
    - pyarrow
    - pyproj
    - mercantile
    - click-plugins
    - rich
    - fsspec
    - obstore
    - jsonschema
    - pystac
    - pandas
    - psutil
    - s3fs
    - httpx
    - owslib
    - requests
    - idna
    - urllib3
    - lxml
    - shapely
    - uv
  run:
    - python


test:
  imports:
    - geoparquet_io

  requires:
    - hatch-build
    - python
    - pip
    - duckdb
    - geoarrow-pyarrow
    - pyarrow
    - pyproj
    - mercantile
    - click-plugins
    - rich
    - fsspec
    - obstore
    - jsonschema
    - pystac
    - pandas
    - psutil
    - s3fs
    - httpx
    - owslib
    - requests
    - idna
    - urllib3
    - lxml
    - shapely
    - uv


about:
  home: https://github.com/geoparquet/geoparquet-io
  summary: 'A collection of tools for GeoParquet, built on DuckDB, GDAL & Obstore '
  description: |
    Fast I/O and transformation tools for GeoParquet files, powered
    by DuckDB and PyArrow.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://geoparquet.io/
  dev_url: https://github.com/geoparquet/geoparquet-io

extra:
  recipe-maintainers:
    - hobu
