{% set version = "2.2.2" %}
{% set python_min = "3.11" %}
{% set py = py | default(python_min) %}


package:
  name: astro-gdt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/astro-gdt/astro_gdt-{{ version }}.tar.gz
  sha256: 43e2c28cd740e4817faa8869cbfb9e2b3bbb23d1e3430e8fc7c6a83864848fba

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]
  skip: true  # [py<311]


requirements:
  host:
    - python 
    - setuptools >=61.0
    - pip
  run:
    - python
    - pyproj >=1.9.6
    - numpy >=2.2.3
    - scipy ==1.15.2
    - astropy-base >=7.0.0
    - matplotlib-base >=3.10.0,<3.11.dev0
    - healpy >=1.18.0,<1.19.dev0
    - cartopy >=0.21.1
    - rich >=13.3.3

test:
  imports:
    - gdt
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/astro-gdt/
  summary: 'Gamma-ray Data Tools: Core Components'
  doc_url: https://astro-gdt.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file:
    - NOTICE
    - license.txt

extra:
  recipe-maintainers:
    - zoghbi-a
