{% set name = "asciidoctor-diagram" %}
{% set version = "3.2.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: f6e56f65d220549bfaadf2b247a0431c294d3ee118fdc869a73b118bed4d18d7
  - path: asciidoctor-diagram.bat

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - cp -v asciidoctor-diagram.bat $PREFIX/bin/asciidoctor-diagram.bat

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - asciidoctor >=1.5.7,<3
    - rb-rexml >=0


test:
  commands:
    - asciidoctor-diagram -v

about:
  home: https://rubygems.org/gems/asciidoctor-diagram
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Asciidoctor diagramming extension

  doc_url: https://www.rubydoc.info/gems/asciidoctor-diagram

extra:
  recipe-maintainers:
    - jdmarques