# Recipe for asciidoctor-diagram Ruby gem
# A family of Asciidoctor extensions that generate images from a broad range of embedded plain text diagram descriptions
schema_version: 1

context:
  version: "3.0.1"

package:
  name: rb-asciidoctor-diagram
  version: ${{ version }}

source:
  url: https://rubygems.org/downloads/asciidoctor-diagram-${{ version }}.gem
  sha256: a91bde8ef01b0c1c114ca5404b9c3b95ae930980167ffd477d49150cf610f4a4

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies asciidoctor-diagram-${{ version }}.gem
    - gem unpack asciidoctor-diagram-${{ version }}.gem
    - cp asciidoctor-diagram-${{ version }}/LICENSE.txt .

requirements:
  host:
    - ruby ${{ ruby_min }}.*
  run:
    - ruby >=${{ ruby_min }}
    - asciidoctor >=1.5.7,<3.0
    - rb-rexml >=3.2.5

tests:
  - script:
      - ruby -r 'asciidoctor-diagram'

about:
  homepage: https://github.com/asciidoctor/asciidoctor-diagram
  license: MIT
  license_file: LICENSE.txt
  summary: Asciidoctor diagramming extension
  description: |
    A family of Asciidoctor extensions that generate images from a broad range of
    embedded plain text diagram descriptions, including PlantUML, ditaa, Kroki,
    and many others. The extension supports AsciiToSVG, BlockDiag (BlockDiag,
    SeqDiag, ActDiag, NwDiag), Ditaa, Erd, GraphViz, Mermaid, Msc, PlantUML,
    Shaape, SvgBob, Syntrax, UMLet, Vega, Vega-Lite and WaveDrom.
  documentation: https://docs.asciidoctor.org/diagram-extension/latest/
  repository: https://github.com/asciidoctor/asciidoctor-diagram

extra:
  recipe-maintainers:
    - phreed
    - jdmarques
