--- Makefile.orig	2020-03-17 15:40:06.426202274 -0500
+++ Makefile	2020-03-17 16:45:43.924829577 -0500
@@ -27,7 +27,8 @@
 #LDFLAGS += -Zexe -Dstrncasecmp=strnicmp

 # OS X
-#whois_LDADD += -liconv
+ON_OSX = 1
+whois_LDADD += -liconv

 ifdef CONFIG_FILE
 DEFS += -DCONFIG_FILE=\"$(CONFIG_FILE)\"
@@ -65,6 +66,8 @@
 # owl and openSUSE have crypt_gensalt(3) in libowcrypt
 DEFS += -DHAVE_CRYPT_H -DHAVE_LINUX_CRYPT_GENSALT -D_OW_SOURCE
 mkpasswd_LDADD += -lcrypt -lowcrypt
+else ifdef ON_OSX
+# nothing to do
 else
 mkpasswd_LDADD += -lcrypt
 endif
