--- Makefile.orig	2020-03-17 15:40:06.426202274 -0500
+++ Makefile	2020-03-17 15:40:20.202144175 -0500
@@ -27,7 +27,7 @@
 #LDFLAGS += -Zexe -Dstrncasecmp=strnicmp
 
 # OS X
-#whois_LDADD += -liconv
+whois_LDADD += -liconv
 
 ifdef CONFIG_FILE
 DEFS += -DCONFIG_FILE=\"$(CONFIG_FILE)\"
