context:
  version: "0.1.0"

package:
  name: pymc-bilby
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pymc-bilby/pymc_bilby-${{ version }}.tar.gz
  sha256: e291cf9cae7057c27b1b56e1a8da432e5a05502214edcca1d777d99257a9dccd

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - python >=${{ python_min }}
    - bilby >=2.3.0
    - pymc >=5.9

tests:
  - python:
      imports:
        - pymc_bilby
      # MKL-variant solves can make pip_check fail spuriously via mkl-service.
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/bilby-dev/pymc-bilby
  repository: https://github.com/bilby-dev/pymc-bilby
  summary: Plugin for using pymc with bilby.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
    - mj-will
