{% set name = "binmod1d" %}
{% set version = "1.0.9" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 13d0ac4f7d96e6b27677f2b0f4f5e56b0ce7858e12287ab67d9422a3291a4768
  - url: https://raw.githubusercontent.com/NOAA-National-Severe-Storms-Laboratory/BinMod1D-PARS/main/LICENSE
    fn: LICENSE
    sha256: 92ce9e384e0109a0e525ecbd4079149e9a094405997bfbb2ba0d1fe7b2adfb57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - mpmath >=1.3.0
    - scipy >=1.15.0
    - numba >=0.61.0
    - matplotlib-base >=3.9.0
    - netcdf4 >=1.7.0
    - tqdm >=4.66.0
    - cloudpickle >=3.0.0

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - python -c "import binmod1d; print('Import successful')"

about:
  home: https://github.com/NOAA-National-Severe-Storms-Laboratory/BinMod1D-PARS
  summary: A 1D Column bin microphysics model that performs collision-coalescence and breakup.
  license: CC-BY-NC-SA-4.0
  license_family: OTHER
  license_file: LICENSE

extra:
  recipe-maintainers:
    - EdwinDunnavan
