context:
  version: "0.3.1"

package:
  name: ocaml-seq
  version: ${{ version }}

source:
  url: https://github.com/c-cube/seq/archive/v${{ version }}.tar.gz
  sha256: 6bc8beb15f0a678dbd6f8b4f75a2cc45fa2d9e4cf545eafe9fb057c97c9914cf

build:
  number: 0
  skip:
    - win
  script:
    - dune build --profile=release -p seq @install
    - dune install --prefix="${PREFIX}" --libdir="${PREFIX}/lib/ocaml" seq

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("ocaml") }}
    - ocaml-dune >=2.5
  host:
    - ocaml

tests:
  - package_contents:
      strict: true
      files:
        - lib/ocaml/seq/*
        - doc/seq/*

about:
  homepage: https://github.com/c-cube/seq
  repository: https://github.com/c-cube/seq
  summary: Compatibility package for OCaml's standard iterator type since 4.07
  license: LGPL-2.1-or-later WITH OCaml-LGPL-linking-exception
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ManuelLerchner
    - MementoRC
