{% set name = "versitygw" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/versity/versitygw/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bdbe036f282aba67ff179795f4eba2115106237d88a9453bea1ed3353f5ffb5d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - test -x "${PREFIX}/bin/versitygw"  # [unix]
    - versitygw --version
    - versitygw --help

about:
  home: https://github.com/versity/versitygw
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - library_licenses/
  summary: High-performance S3-compatible gateway that translates S3 API calls to filesystem and other storage backends
  description: |
    The Versity S3 Gateway (versitygw) is an open-source, stateless server that
    presents an AWS S3-compatible API in front of existing storage systems,
    including POSIX filesystems, Versity ScoutFS, Azure Blob Storage, and other
    S3 servers. It is written in Go and licensed under Apache 2.0.
  doc_url: https://github.com/versity/versitygw/wiki
  dev_url: https://github.com/versity/versitygw

extra:
  recipe-maintainers:
    - tropicrainforest
