if [ -z "${CONDA_MACOSX_SDK_BACKUP_MACOSX_SDK_VERSION}" ]; then
    export MACOSX_SDK_VERSION="${CONDA_MACOSX_SDK_BACKUP_MACOSX_SDK_VERSION}"
    unset CONDA_MACOSX_SDK_BACKUP_MACOSX_SDK_VERSION
else
    unset MACOSX_SDK_VERSION
fi

if [ -z "${CONDA_MACOSX_SDK_BACKUP_MACOSX_SDK_CACHE_DIR}" ]; then
    # we didn't override this so no need to reset
    # backup var is here to indicate to not unset
    unset CONDA_MACOSX_SDK_BACKUP_MACOSX_SDK_CACHE_DIR
else
    unset MACOSX_SDK_CACHE_DIR
fi

if [ -z "${CONDA_MACOSX_SDK_BACKUP_CONDA_BUILD_SYSROOT}" ]; then
    export CONDA_BUILD_SYSROOT="${CONDA_MACOSX_SDK_BACKUP_CONDA_BUILD_SYSROOT}"
    unset CONDA_MACOSX_SDK_BACKUP_CONDA_BUILD_SYSROOT
else
    unset CONDA_BUILD_SYSROOT
fi

if [ -z "${CONDA_MACOSX_SDK_BACKUP_SDKROOT}" ]; then
    export SDKROOT="${CONDA_MACOSX_SDK_BACKUP_SDKROOT}"
    unset CONDA_MACOSX_SDK_BACKUP_SDKROOT
else
    unset SDKROOT
fi

if [ -z "${CONDA_MACOSX_SDK_BACKUP_CMAKE_ARGS}" ]; then
    export CMAKE_ARGS="${CONDA_MACOSX_SDK_BACKUP_CMAKE_ARGS}"
    unset CONDA_MACOSX_SDK_BACKUP_CMAKE_ARGS
else
    unset CMAKE_ARGS
fi
