if [ -z "${CONDA_BACKUP_MACOSX_DEPLOYMENT_TARGET}" ]; then
    export MACOSX_DEPLOYMENT_TARGET="${CONDA_BACKUP_MACOSX_DEPLOYMENT_TARGET}"
    unset CONDA_BACKUP_MACOSX_DEPLOYMENT_TARGET
else
    unset MACOSX_DEPLOYMENT_TARGET
fi
