# generated by datamodel-codegen:
#   filename:  well_known_types.yaml

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class String(BaseModel):
    type: str
    description: str


class BinaryData(BaseModel):
    type: str
    description: str
    pattern: str


class Date(BaseModel):
    type: str
    pattern: str
    description: str


class TimestampWithTimezone(BaseModel):
    type: str
    pattern: str
    description: str


class TimestampWithoutTimezone(BaseModel):
    type: str
    pattern: str
    description: str


class TimeWithTimezone(BaseModel):
    type: str
    pattern: str
    description: str


class TimeWithoutTimezone(BaseModel):
    type: str
    pattern: str
    description: str


class OneOfItem(BaseModel):
    pattern: Optional[str] = None
    enum: Optional[List[str]] = None


class Number(BaseModel):
    type: str
    oneOf: List[OneOfItem]
    description: str


class Integer(BaseModel):
    type: str
    oneOf: List[OneOfItem]


class Boolean(BaseModel):
    type: str
    description: str


class Definitions(BaseModel):
    String: String
    BinaryData: BinaryData
    Date: Date
    TimestampWithTimezone: TimestampWithTimezone
    TimestampWithoutTimezone: TimestampWithoutTimezone
    TimeWithTimezone: TimeWithTimezone
    TimeWithoutTimezone: TimeWithoutTimezone
    Number: Number
    Integer: Integer
    Boolean: Boolean


class Model(BaseModel):
    definitions: Definitions
