context:
  version: "1.5.2"

package:
  name: ocaml-csexp
  version: ${{ version }}

source:
  url: https://github.com/ocaml-dune/csexp/releases/download/${{ version }}/csexp-${{ version }}.tbz
  sha256: 1a14dd04bb4379a41990248550628c77913a9c07f3c35c1370b6960e697787ff

build:
  number: 0
  skip:
    - win
  script:
    - dune build --profile=release -p csexp @install
    - dune install --prefix="${PREFIX}" --libdir="${PREFIX}/lib/ocaml" csexp

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("ocaml") }}
    - ocaml-dune >=3.4
  host:
    - ocaml >=4.03.0

tests:
  - package_contents:
      strict: true
      files:
        - lib/ocaml/csexp/*
        - doc/csexp/*

about:
  homepage: https://github.com/ocaml-dune/csexp
  repository: https://github.com/ocaml-dune/csexp
  summary: Parsing and printing of S-expressions in canonical form
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ManuelLerchner
    - MementoRC
