schema_version: 1

context:
  version: "1.1.6"

package:
  name: show-in-file-manager
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/show-in-file-manager/show_in_file_manager-${{ version }}.tar.gz
  sha256: 559b596e3e563800cf69d734cd236824279a9d820d1d841640c5f13e0058f9b6

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  python:
    entry_points:
      - showinfilemanager = showinfm.showinfm:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-argparse-manpage
    - pip
  run:
    - python >=${{ python_min }}
    - if: unix
      then:
        - __unix
        - pyxdg >=0.25
    - packaging
    - if: win
      then:
      - __win
      - pywin32-on-windows >=301

tests:
  - python:
      imports:
        - show_in_file_manager
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - ${{ python_min }}.*
    script:
      - showinfilemanager --help

about:
  summary: Open the system file manager and select files in it
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/damonlynch/showinfilemanager

extra:
  recipe-maintainers:
    - thewchan
