schema_version: 1

context:
  python_min: "3.12"
  version: "0.8.0"

package:
  name: fixbikenet
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fixbikenet/fixbikenet-${{ version }}.tar.gz
  sha256: 1cf2659d6ec37760bf03815c09efe783263839ce38d1dee78155d0fa360a2eea

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}
    - geopandas >=1
    - matplotlib-base
    - osmnx >=2
    - geojson
    - tqdm

tests:
  - python:
      imports:
        - fixbikenet
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: BikeNetKit Python package to detect gaps in developed bicycle networks
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://bikenetkit.org/
  documentation: https://docs.bikenetkit.org/FixBikeNet/

extra:
  recipe-maintainers:
    - mszell
