package:
  name: gpjax
  version: 0.12.0

source:
  url: https://pypi.org/packages/source/g/gpjax/gpjax-0.12.0.tar.gz
  sha256: f59a19f71f488a06182cbb4cf6bf51fcb8d97aef011f77fb6d1507c808269532

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10,<3.14
    - hatchling
    - pip
  run:
    - python >=3.10,<3.14
    - jax >=0.4.0
    - optax >=0.2.1
    - numpyro
    - jaxtyping >=0.2.10
    - tqdm >=4.66.2
    - beartype >=0.16.1
    - flax >=0.10.0
    - numpy >=2.0.0

test:
  - imports:
      - gpjax
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  homepage: https://github.com/JaxGaussianProcesses/GPJax
  summary: Gaussian processes in JAX.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thomaspinder
