schema_version: 1

context:
  version: "3.1.1"

package:
  name: graphrag-cache
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/graphrag-cache/graphrag_cache-${{ version }}.tar.gz
  sha256: 8e011af30069520b27b65ee70f781892aeac6ed9e51f9b311f5b30db0606d979

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.27.0,<2.0.0
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - graphrag-common ==3.1.1
    - graphrag-storage ==3.1.1

tests:
  - python:
      imports:
        - graphrag_cache
      pip_check: true
      python_version: 
        - ${{ python_min }}.*
        - "*"

about:
  summary: GraphRAG cache package.
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/graphrag-cache/
  repository: https://github.com/microsoft/graphrag

extra:
  recipe-maintainers:
    - jan-janssen
