context:
  version: "0.2.60"

package:
  name: cargo-show-asm
  version: ${{ version }}

source:
  url: https://github.com/pacak/cargo-show-asm/archive/refs/tags/${{ version }}.tar.gz
  sha256: 7758624e0364d34f86827a8fd076f370f0dd0611d8762c88701ec396c69fd840

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - cargo-asm --help
  - package_contents:
      bin:
        - cargo-asm
      strict: true

about:
  homepage: https://github.com/pacak/cargo-show-asm
  repository: https://github.com/pacak/cargo-show-asm
  documentation: https://github.com/pacak/cargo-show-asm
  summary: Display the Assembly, LLVM-IR, MIR and WASM generated for Rust code
  description: |
    A cargo subcommand that displays the Assembly, LLVM-IR, MIR and WASM
    generated for Rust source code.
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apcamargo
