import os

os.environ['MD_AUTH_TOKEN']="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2ODAyMTQ2NzcsImV4cCI6MTcxMTc1MDY3NywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQifQ.zYCHB04KaVtd6ex2TASsAoqttF2Ufgqi4_f_abYLrdo"

import morningstar_data as md