{% set version = '0.3.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mantar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mantar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mantar/mantar_{{ version }}.tar.gz
  sha256: 4610d367325d7839954f2be22016ef91ee7ce927e37bb84ad3a07595fcf7e57b

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rdpack
    - r-glassofast
    - r-mathjaxr
  run:
    - r-base
    - r-matrix
    - r-rdpack
    - r-glassofast
    - r-mathjaxr

test:
  commands:
    - $R -e "library('mantar')"           # [not win]
    - "\"%R%\" -e \"library('mantar')\""  # [win]

about:
  home: https://github.com/kai-nehler/mantar
  license: GPL-3.0-only
  summary: Provides functionality for estimating cross-sectional network structures representing
    partial correlations while accounting for missing data. Networks are estimated via
    neighborhood selection or regularization, with model selection guided by information
    criteria. Missing data can be handled primarily via multiple imputation or a maximum
    likelihood-based approach, as demonstrated by Nehler and Schultze (2025) <doi:10.1080/00273171.2025.2503833>
    and Nehler and Schultze (2026) <doi:10.1037/met0000828>. Deletion-based approaches
    are also available but play a secondary role.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mantar
# Title: Missingness Alleviation for Network Analysis
# Version: 0.3.1
# Authors@R: person("Kai Jannik", "Nehler", , "nehler@psych.uni-frankfurt.de", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-3764-761X"))
# Description: Provides functionality for estimating cross-sectional network structures representing partial correlations while accounting for missing data. Networks are estimated via neighborhood selection or regularization, with model selection guided by information criteria. Missing data can be handled primarily via multiple imputation or a maximum likelihood-based approach, as demonstrated by Nehler and Schultze (2025) <doi:10.1080/00273171.2025.2503833> and Nehler and Schultze (2026) <doi:10.1037/met0000828>. Deletion-based approaches are also available but play a secondary role.
# License: GPL (>= 3)
# Depends: R (>= 4.1.0)
# Imports: Rdpack, mathjaxr, stats, Matrix, glassoFast
# Suggests: numDeriv, mice, lavaan, qgraph, testthat (>= 3.0.0), knitr, rmarkdown
# LazyData: true
# Encoding: UTF-8
# RdMacros: Rdpack, mathjaxr
# Config/testthat/edition: 3
# URL: https://github.com/kai-nehler/mantar
# BugReports: https://github.com/kai-nehler/mantar/issues
# VignetteBuilder: knitr
# Config/roxygen2/version: 8.0.0
# NeedsCompilation: no
# Packaged: 2026-07-08 12:52:08 UTC; nehler
# Author: Kai Jannik Nehler [aut, cre] (ORCID: <https://orcid.org/0000-0003-3764-761X>)
# Maintainer: Kai Jannik Nehler <nehler@psych.uni-frankfurt.de>
# Repository: CRAN
# Date/Publication: 2026-07-08 13:40:09 UTC
