schema_version: 1

context:
  version: "1.4.357.0"

package:
  name: vulkan-profiles
  version: ${{ version }}

source:
  url: https://github.com/KhronosGroup/Vulkan-Profiles/archive/refs/tags/vulkan-sdk-${{ version }}.tar.gz
  sha256: 08494e824457659d0399075263deff22226ef2c0c1067f551b7ec84a1b11df53
  patches:
    # conda-forge provides the shared jsoncpp target.
    - use-shared-jsoncpp.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - python
  host:
    - jsoncpp
    - libvulkan-headers =${{ version }}
    - valijson
    - vulkan-utility-libraries =${{ version }}
  run_constraints:
    - libvulkan-headers =${{ version }}
  run_exports:
    - ${{ pin_subpackage("vulkan-profiles", upper_bound="x.x.x") }}

tests:
  - package_contents:
      include:
        - vulkan/vulkan_profiles.hpp
      files:
        - if: win
          then:
            - Library/bin/VkLayer_khronos_profiles.dll
            - Library/bin/VkLayer_khronos_profiles.json
          else:
            - lib/libVkLayer_khronos_profiles.*
            - share/vulkan/explicit_layer.d/VkLayer_khronos_profiles.json
        - if: win
          then: Library/share/vulkan/registry/profiles-0.8-latest.json
          else: share/vulkan/registry/profiles-0.8-latest.json

about:
  homepage: https://github.com/KhronosGroup/Vulkan-Profiles
  repository: https://github.com/KhronosGroup/Vulkan-Profiles
  summary: Tools and libraries for Vulkan profile development
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - LICENSES/Apache-2.0.txt

extra:
  recipe-maintainers:
    - wolfv
