# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2025.2.0

package:
  name: jsonschema-markdown
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jsonschema-markdown/jsonschema_markdown-${{ version }}.tar.gz
    sha256: 187e11c02e1c56c0448bff022b01c099e09d66b6c525b5c77f6fda1c6c78db6d
    target_directory: dist
  - url: https://github.com/elisiariocouto/jsonschema-markdown/archive/refs/tags/${{ version }}.tar.gz
    sha256: 52a67e1d109cae7a9555cafac0f3a72e445e864bd07b12a957a7e974ee2efdeb
    target_directory: src
    patches:
      # TODO: remove after https://github.com/elisiariocouto/jsonschema-markdown/pull/25
      - 0000-test-float.patch

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jsonschema-markdown = jsonschema_markdown.main:cli

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - click >=8.1.7,<9
    - jsonref >=1.1.0,<2
    - loguru >=0.7.2,<0.8
    - python >=${{ python_min }}
    - pyyaml >=6.0.2,<7

tests:
  - python:
      imports: jsonschema_markdown
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - pydantic
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - jsonschema-markdown --help
      - curl https://pixi.sh/v0.36.0/schema/manifest/schema.json | jsonschema-markdown - > /tmp/pixi.schema.md
      - cd src
      - coverage run --source=jsonschema_markdown --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=82

about:
  summary: Export a JSON Schema document to Markdown documentation.
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
