{% set version = "2.0.0" %}

package:
  name: sfcgal
  version: {{ version }}

source:
  url: https://gitlab.com/sfcgal/SFCGAL/-/archive/v{{ version }}/SFCGAL-v{{ version }}.tar.gz
  sha256: 11843953f49e7e4432c42fd27d54e1ff7ca55d0cc72507725c2a5d840c2c6535

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cgal-cpp
    - cmake
    - ninja
  host:
    - gmp
    - mpfr
    - libboost-devel

test:
  commands:
    - sfcgal-config --version

about:
  home: https://gitlab.com/sfcgal/SFCGAL
  summary: "A wrapper around CGAL that intents to implement 2D and 3D operations on OGC standards models."
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  dev_url: https://gitlab.com/sfcgal/SFCGAL

extra:
  recipe-maintainers:
    - lbartoletti
