load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "any_invocable",
)

cc_library(
    name = "bind_front",
)

cc_library(
    name = "function_ref",
)

cc_library(
    name = "overload",
)
