{% set version = "0.1.4" %}

package:
  name: muondecay
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/muondecay/muondecay-{{ version }}.tar.gz
  sha256: cd7ac47b77438b724fddf54e1f005d8efad16d67fd4fefbac9233874508ecec0

build:
  entry_points:
    - muon_detect = muondecay.detect:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy
    - scipy
    - pyserial
    - lmfit
    - matplotlib-base
    - tk

test:
  imports:
    - muondecay
  commands:
    - pip check
    - muon_detect --help
  requires:
    - pip

about:
  home: https://github.com/sprague252/muondecay/
  summary: Read and analyze data from TeachSpin's muon detector.
  dev_url: https://github.com/sprague252/muondecay/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sprague252
