#!/bin/bash
set -euxo pipefail

# The default target also runs the upstream test suite; NO_INTERNET=1 skips
# the tests that need name resolution. VERSION is normally generated by the
# upstream packaging scripts and has to be provided when building from the
# GitHub tarball.
make -C src install \
  -j"${CPU_COUNT}" \
  PREFIX="${PREFIX}" \
  VERSION="${PKG_VERSION}" \
  NO_INTERNET=1

# Extract the license of the statically linked QuickJS-ng from its header
sed -n '/QuickJS Javascript Engine/,/^ \*\//p' src/quickjs/quickjs.h \
  > "${SRC_DIR}/LICENSE.quickjs"
