schema_version: 1

context:
  version: "0.1.3"

package:
  name: scrollstats
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/scrollstats/scrollstats-${{ version }}.tar.gz
  sha256: 4053ed6029e0857887e067f376faf892e1664ba359a60311cfeb0654c36c6c3f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - geopandas
    - matplotlib-base
    - scipy
    - rasterio
    - numba
    - tqdm
    - nptyping
    - lazy-loader

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
      - scrollstats
      pip_check: true

about:
  homepage: https://pypi.org/project/scrollstats/
  summary: An open-source python library to calculate and extract morphometrics from scroll bar floodplains
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tamu-edu/scrollstats

extra:
  recipe-maintainers:
    - a-vanderheiden
