schema_version: 1

context:
  version: "0.5.3"

package:
  name: topo-tools
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/topo-tools/topo_tools-${{ version }}.tar.gz
  sha256: 989f95a7fc276d725085f58fe91f9dc5912b368511066744c3c090aed18a9d7a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - topo-tools = topo_tools.cli.main:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - click
    - python-duckdb >=1.5.5
    - psutil
    - pyyaml >=6.0.3

tests:
  - python:
      imports:
        - topo_tools
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - topo-tools --help

about:
  summary: DuckDB-powered geospatial topology utilities (edge-matching, topology cleaning, more)
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/OCHA-DAP/topo-tools-py
  repository: https://github.com/OCHA-DAP/topo-tools-py
  documentation: https://github.com/OCHA-DAP/topo-tools-py#readme

extra:
  recipe-maintainers:
    - maxmalynowsky
