schema_version: 1

context:
  version: "2.6.1"
  python_min: "3.9"

package:
  name: agno
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/agno/agno-${{ version }}.tar.gz
  sha256: 87b49a2c8c1849a5504a2b70f33ccd6e1a2b0c8b279be824040ffbb203f34d06

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - docstring_parser
    - gitpython
    - h11 >=0.16.0
    - httpx
    - h2
    - packaging
    - pydantic
    - pydantic-settings
    - python-dotenv
    - python-multipart
    - pyyaml
    - rich
    - typer
    - typing_extensions

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - agno
        - agno.agent
        - agno.models
        - agno.tools

about:
  homepage: https://agno.com
  repository: https://github.com/agno-agi/agno
  documentation: https://docs.agno.com
  summary: The programming language for agentic software.
  description: |
    Agno is a lightweight framework for building multi-modal Agents.
    It supports any model provider, native multi-modal I/O, multi-agent
    teams, memory management, knowledge stores, structured outputs, and
    real-time monitoring.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - killua156
    - mgorny
