#!/bin/bash

mkdir -p ./build
cd build
cmake -D CMAKE_INSTALL_PREFIX=${PREFIX} -DBUILD_SERVER=OFF -DBUILD_CVMFS=ON -DBUILD_UNITTESTS=OFF -DBUILD_UNITTESTS_DEBUG=OFF -DBUILD_PRELOADER=OFF -DBUILD_LIBCVMFS=OFF -DLEVELDB_BUILTIN=OFF -DSQLITE3_BUILTIN=OFF -DLIBCURL_BUILTIN=OFF -DZLIB_BUILTIN=OFF -DSPARSEHASH_BUILTIN=OFF ..


make
make install
