schema_version: 1

context:
  version: "0.3.0"

package:
  name: tabalyst
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tabalyst/tabalyst-${{ version }}.tar.gz
  sha256: a69ee772b0fbf966f9f7c2f174c623468ba876aa59ef1948c06e54c914ca81af

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - tabalyst = tabalyst.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - pip
  run:
    - python >=${{ python_min }}
    - jinja2 >=3.1
    - pandas >=2.2
    - pydantic >=2.10
    - typer >=0.12

tests:
  - python:
      imports:
        - tabalyst
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python
    script:
      - tabalyst --help

about:
  summary: Open-source data profiling engine for structured JSON and customizable HTML reports.
  license: MIT
  license_file: LICENSE
  homepage: https://tabalyst.com/
  repository: https://github.com/loribel-labs/tabalyst
  documentation: https://docs.tabalyst.com/

extra:
  recipe-maintainers:
    - HeavyTony2
