{% set python_min = "3.9" %}
{% set version = "1.0.4" %}

package:
  name: checkpoint-schedules
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/checkpoint-schedules/checkpoint_schedules-{{ version }}.tar.gz
  sha256: aaa9191a6da910fd1b1e0526df2ca7ecea04823fe5106360e3e23d2413dcfeeb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - checkpoint_schedules
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://www.firedrakeproject.org/checkpoint_schedules/
  summary: Schedules for incremental checkpointing of adjoint simulations.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - finsberg
    - jorgensd
