{% set name = "pyreml" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55f274b1351568f7e298c41540bb40b41be43d80e3fa730f80ded69a31f22d60 

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.10
    - pytorch
    - numpy
    - scipy
    - pandas
    - patsy

test:
  imports:
    - pyreml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ai-for-genome-interpretation-lab/pyreml
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "General-purpose linear mixed model solver (REML, BLUP, LMM)."
  description: |
    pyreml is a general-purpose linear mixed model solver. It fits linear
    mixed models for a wide range of applications: quantitative genetics,
    spatial statistics, health sciences, among others. Models are fitted by
    direct differentiation of the Restricted Maximum Likelihood (REML),
    using PyTorch for variance parameter estimation. It benefits from PyTorch
    parallelization and GPU acceleration.
  doc_url: https://ai-for-genome-interpretation-lab.github.io/pyreml/
  dev_url: https://github.com/ai-for-genome-interpretation-lab/pyreml

extra:
  recipe-maintainers:
    - almarch
    - eddiewrc