#!/bin/bash
set -euxo pipefail

MODULE_NAME=asyn
INSTALL_LOCATION="${PREFIX}/epics/modules/${MODULE_NAME}"

# Comment out every line naming a test*App or iocBoot so the demo IOCs are not
# built or installed. Keep asyn/asynPortDriver/unittest: it alone defines
# TESTS/TESTPROD, and is what `make runtests` runs.
#
# EPICS_LIBCOM_ONLY=YES would drop the demo IOCs as well, but it also drops
# devEpics, asynRecord and devGpib, which this module needs.
#
# We edit upstream's Makefile instead of keeping our own, to stay in sync with
# upstream release changes.
sed -E '/unittest/! s/^(.*(test|iocBoot).*)$/#\1/' Makefile > Makefile.standalone

# DRV_FTDI, LINUX_GPIB and gsIP488 stay off (upstream defaults / need IPAC).
cat > configure/CONFIG_SITE.local <<EOF
DRV_USBTMC=YES
DRV_VXI11=YES
INSTALL_LOCATION=${INSTALL_LOCATION}
EOF

if [[ ${target_platform} == linux-* ]]; then
  # glibc 2.26 dropped its built-in SunRPC, so vxi11 needs libtirpc. Upstream
  # leaves TIRPC unset, so without this the library compiles against libtirpc
  # headers but resolves the symbols from glibc's obsolete copy. The include
  # path has to come from us either way, since upstream hardcodes
  # the libtirpc include path and under conda the headers are in the host
  # prefix.
  #
  # The link flag is for the test executables: they pull in libasyn, libusb and
  # then conda's libudev, which references glibc symbols newer than the
  # compiler sysroot's glibc. ld resolves transitively needed symbols by
  # default and fails on them. conda's own LDFLAGS carry this flag for exactly
  # that reason, but EPICS constructs its own link line and never sees them.
  cat >> configure/CONFIG_SITE.local <<EOF
TIRPC=YES
USR_INCLUDES_Linux += -I${PREFIX}/include/tirpc
USR_LDFLAGS += -Wl,--allow-shlib-undefined
EOF
fi

cat > configure/RELEASE <<EOF
# Generated by the asyn conda build.
EPICS_BASE=${EPICS_BASE}
EOF

make -f Makefile.standalone -j"${CPU_COUNT:-2}" build
make -f Makefile.standalone runtests
make -f Makefile.standalone install

# Shared library only; static archives are not part of the conda-forge
# distribution (CFEP-18).
find "${INSTALL_LOCATION}/lib" -name '*.a' -delete

if [[ ${target_platform} == linux-* ]]; then
  # A build that lost TIRPC=YES would still compile, link and run, so check the
  # linkage directly.
  # READELF comes from the compiler activation; a bare readelf would find the
  # image's system binutils, which is the wrong arch when cross-compiling.
  "${READELF}" -d "${INSTALL_LOCATION}/lib/${EPICS_HOST_ARCH}/libasyn.so" \
    | grep -q 'NEEDED.*libtirpc'
fi
