schema_version: 1

context:
  version: "0.7.0"

  lib: ${{ "lib/python*" if unix else "Lib" }}
  so: ${{ "abi3.so" if unix else "pyd" }}

package:
  name: mqtt5
  version: ${{ version }}
  
source:
  url: https://pypi.org/packages/source/m/mqtt5/mqtt5-${{ version }}.tar.gz
  sha256: b210ce32ce98731b42589a0ae655a10511fb61052a4b9e0afbfc70937b9cbd16

build:
  number: 0
  skip: match(python, "<=3.11")
  script:
    env:
      PYTHONIOENCODING: utf-8
    content:
      - ${{ PYTHON }} -m pip install -v --use-pep517 --no-deps --no-build-isolation .
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - maturin >=1.13.1
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - maturin <2.0
    - python
    - pip
  run:
    - python

tests:
  - package_contents:
      strict: true
      files:
        - ${{ lib }}/site-packages/mqtt5/__init__.py
        - ${{ lib }}/site-packages/mqtt5/__pycache__/*
        - ${{ lib }}/site-packages/mqtt5/mqtt5.${{ so }}
        - ${{ lib }}/site-packages/mqtt5/mqtt5.pyi
        - ${{ lib }}/site-packages/mqtt5/py.typed
        - ${{ lib }}/site-packages/mqtt5-${{ version }}.dist-info/*
  - python:
      imports:
        - mqtt5
      pip_check: true

about:
  homepage: https://github.com/empicano/mqtt5
  summary: 'The MQTTv5 protocol for Python written in Rust'
  description: |
    A sans-I/O implementation of the MQTTv5 protocol for Python,
    written in Rust. Serialization is ~5x faster and deserialization
    ~20x faster than comparable Python code
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/empicano/mqtt5

extra:
  recipe-maintainers:
    - MementoRC
