CUSTOM_CMAKE_ARGS="-DFORCE_OWN_FLTK=OFF"
CUSTOM_CMAKE_ARGS+=" -DFORCE_OWN_FFTW=OFF"
CUSTOM_CMAKE_ARGS+=" -DBUILD_SHARED_LIBS=OFF"

cmake ${CMAKE_ARGS} ${CUSTOM_CMAKE_ARGS} "$SRC_DIR"
make -j $CPU_COUNT
